
/* ===================== TESTE 80/20: BOMBEIRO E DIREITO =====================
   Mesmo formato do banco original: 5 alternativas, índice da correta e explicação. */
Object.assign(TESTE80,{
'ps-aval':{qs:[
 {q:'Na avaliação primária do traumatizado pelo protocolo XABCDE, a primeira prioridade é:',o:['Abrir as vias aéreas com controle cervical.','Conter hemorragia externa grave (exsanguinante).','Avaliar o nível de consciência pela escala de Glasgow.','Verificar a frequência respiratória.','Expor a vítima e prevenir hipotermia.'],r:1,x:'O "X" veio antes do "A" porque hemorragia exsanguinante mata em poucos minutos. Só depois vem a via aérea com proteção cervical.'},
 {q:'Na escala AVDI, a vítima que só reage quando o socorrista aplica um estímulo doloroso é classificada como:',o:['A','V','D','I','Glasgow 15'],r:2,x:'A = alerta; V = responde à voz; D = responde à dor; I = inconsciente (não responde a nada).'},
 {q:'Antes de iniciar qualquer atendimento, o socorrista deve primeiro:',o:['Checar o pulso carotídeo.','Posicionar a vítima em decúbito lateral.','Avaliar a segurança da cena.','Iniciar compressões torácicas.','Colher o histórico SAMPLA.'],r:2,x:'Socorrista ferido vira mais uma vítima. Cena segura e biossegurança vêm antes de tudo.'},
 {q:'No histórico SAMPLA, a letra "M" corresponde a:',o:['Mecanismo do trauma.','Medicamentos em uso.','Membros afetados.','Motricidade.','Monitoramento dos sinais vitais.'],r:1,x:'SAMPLA: Sinais e sintomas, Alergias, Medicamentos, Passado médico, Líquidos e alimentos ingeridos, Ambiente/eventos.'},
 {q:'Na escala de Coma de Glasgow, a menor pontuação possível é:',o:['0','1','3','5','8'],r:2,x:'A escala vai de 3 (sem resposta ocular, verbal e motora) a 15. Pontuação de 8 ou menos indica coma e via aérea em risco.'}]},
'ps-rcp':{qs:[
 {q:'Na RCP de adulto realizada por socorrista, a frequência das compressões torácicas recomendada é de:',o:['60 a 80 por minuto.','80 a 100 por minuto.','100 a 120 por minuto.','120 a 140 por minuto.','Mais de 150 por minuto.'],r:2,x:'100 a 120 compressões por minuto, com profundidade de 5 a 6 cm e retorno total do tórax.'},
 {q:'Sem via aérea avançada, a relação compressão-ventilação na RCP de adulto é:',o:['15:1','15:2','30:1','30:2','5:1'],r:3,x:'30 compressões para 2 ventilações, com 1 ou 2 socorristas. Em criança com 2 socorristas, 15:2.'},
 {q:'Durante a RCP, o desfibrilador externo automático (DEA) deve ser usado:',o:['Só depois de 10 minutos de compressões.','Assim que estiver disponível.','Apenas por médicos.','Só se a vítima tiver pulso.','Apenas em crianças.'],r:1,x:'Quanto antes o choque em ritmo chocável, maior a sobrevida. Liga, cola as pás, afasta todos e volta às compressões logo após.'},
 {q:'Em adulto consciente com obstrução total das vias aéreas por corpo estranho, a conduta indicada é:',o:['Dar água para ajudar a engolir.','Fazer compressões abdominais (manobra de Heimlich).','Iniciar ventilações boca a boca.','Deitar a vítima e aguardar.','Tentar retirar o objeto às cegas com os dedos.'],r:1,x:'Compressões abdominais até desobstruir ou a vítima ficar inconsciente, quando se inicia a RCP. Em gestante ou obeso, compressões torácicas.'},
 {q:'A profundidade das compressões torácicas no adulto deve ser de:',o:['1 a 2 cm.','2 a 3 cm.','3 a 4 cm.','5 a 6 cm.','8 a 10 cm.'],r:3,x:'Pelo menos 5 cm e no máximo 6 cm, com as mãos na metade inferior do esterno.'}]},
'ps-quei':{qs:[
 {q:'Queimadura que atinge epiderme e parte da derme, com formação de bolhas e dor intensa, é classificada como de:',o:['1º grau.','2º grau.','3º grau.','4º grau.','Grau leve, sem classificação.'],r:1,x:'Bolha (flictena) é a marca do 2º grau. O 1º grau só avermelha; o 3º destrói toda a derme e pode doer pouco.'},
 {q:'Pela regra dos nove, no adulto, um membro inferior inteiro corresponde a aproximadamente:',o:['9% da superfície corporal.','18% da superfície corporal.','27% da superfície corporal.','36% da superfície corporal.','1% da superfície corporal.'],r:1,x:'Cabeça 9%, cada membro superior 9%, tronco anterior 18%, posterior 18%, cada membro inferior 18%, genitais 1%.'},
 {q:'Diante de uma queimadura térmica recente e pequena, a conduta correta é:',o:['Aplicar gelo diretamente sobre a pele.','Passar pasta de dente ou manteiga.','Resfriar com água corrente em temperatura ambiente.','Furar as bolhas para aliviar a pressão.','Cobrir com algodão diretamente sobre a lesão.'],r:2,x:'Água corrente em temperatura ambiente interrompe o dano. Gelo, pomadas caseiras e furar bolhas pioram a lesão ou aumentam a infecção.'},
 {q:'Na queimadura de 3º grau, a pouca dor no centro da lesão se explica por:',o:['Menor profundidade da lesão.','Destruição das terminações nervosas.','Efeito do resfriamento.','Formação de bolhas.','Liberação de adrenalina.'],r:1,x:'O 3º grau destrói toda a derme, inclusive os receptores de dor. As bordas, geralmente de 2º grau, continuam doendo.'},
 {q:'Em vítima de queimadura, é sinal de alerta para lesão de vias aéreas:',o:['Queimadura na palma da mão.','Pelos nasais chamuscados e rouquidão.','Bolhas no antebraço.','Vermelhidão nas costas.','Dor no local da queimadura.'],r:1,x:'Queimadura em face, fuligem na boca, pelos nasais chamuscados e rouquidão indicam possível lesão inalatória, que pode obstruir a via aérea.'}]},
'comb-cla':{qs:[
 {q:'Incêndio em equipamento elétrico energizado é classificado como de classe:',o:['A','B','C','D','K'],r:2,x:'Classe C: equipamento energizado. Nunca use água. Desligada a energia, o incêndio passa a ser tratado conforme o material que queima.'},
 {q:'Os incêndios de classe A caracterizam-se por:',o:['Queimar só na superfície, sem deixar resíduos.','Envolver metais pirofóricos.','Queimar em superfície e em profundidade, deixando resíduos.','Envolver óleo de cozinha.','Envolver gases inflamáveis.'],r:2,x:'Classe A: sólidos comuns (madeira, papel, tecido), que queimam em superfície e profundidade e deixam brasas e cinzas.'},
 {q:'O método de extinção que age retirando o calor do material em combustão é o:',o:['Abafamento.','Isolamento.','Resfriamento.','Extinção química.','Diluição do combustível.'],r:2,x:'Resfriamento ataca o calor (água é o agente clássico). Abafamento ataca o oxigênio; isolamento, o combustível; extinção química, a reação em cadeia.'},
 {q:'Óleos e gorduras em cozinhas industriais pertencem à classe:',o:['A','B','C','D','K'],r:4,x:'Classe K (cozinha). Exige agente específico; água pode provocar projeção violenta do óleo em chamas.'},
 {q:'O pó químico age principalmente por:',o:['Resfriamento.','Isolamento.','Quebra da reação em cadeia e abafamento.','Diluição do oxigênio pela água.','Remoção do combustível.'],r:2,x:'O pó interrompe a reação em cadeia (extinção química) e forma uma camada que abafa.'}]},
'comb-ext':{qs:[
 {q:'O extintor de gás carbônico (CO₂) é indicado para as classes:',o:['A e B.','A, B e C.','B e C.','Somente A.','D e K.'],r:2,x:'CO₂ age por abafamento e não conduz eletricidade: indicado para B e C. Tem pouca eficiência em classe A, que reacende.'},
 {q:'O extintor de água pressurizada é indicado para incêndios de classe:',o:['A.','B.','C.','D.','K.'],r:0,x:'Água resfria sólidos comuns (classe A). Em C conduz eletricidade; em B e K espalha o fogo; em D pode reagir.'},
 {q:'Ao operar um extintor portátil, o jato deve ser dirigido:',o:['Ao topo das chamas.','À fumaça.','À base das chamas, com movimento de varredura.','Ao ponto mais distante do fogo.','Para cima, formando uma nuvem.'],r:2,x:'O combustível está na base: é ali que o agente age. A varredura cobre toda a área.'},
 {q:'O extintor de pó químico ABC tem como vantagem:',o:['Não deixar resíduo.','Servir para as classes A, B e C.','Ser o único indicado para metais.','Ser indicado para cozinhas industriais.','Agir apenas por resfriamento.'],r:1,x:'O pó ABC (fosfato monoamônico) cobre as três classes mais comuns, mas deixa resíduo.'},
 {q:'Um risco do uso do extintor de CO₂ em ambiente pequeno e fechado é:',o:['Choque elétrico.','Asfixia pela redução do oxigênio.','Explosão do agente.','Contaminação por pó.','Aumento da temperatura.'],r:1,x:'O CO₂ desloca o oxigênio. Além disso, o difusor fica muito frio e pode queimar a mão por congelamento.'}]},
'comb-fases':{qs:[
 {q:'A inflamação generalizada e quase simultânea de todos os materiais combustíveis de um ambiente é chamada de:',o:['Backdraft.','Flashover.','Rollover.','Ignição.','BLEVE.'],r:1,x:'Flashover é a transição para o incêndio totalmente desenvolvido. O rollover (chamas na camada de fumaça) costuma ser o aviso.'},
 {q:'O fenômeno em que a entrada súbita de ar em ambiente fechado, pobre em oxigênio e cheio de gases quentes, provoca uma explosão é o:',o:['Flashover.','Backdraft.','Rollover.','Boil over.','Fulgor.'],r:1,x:'Backdraft: sinais como fumaça amarelada pulsando, portas quentes, vidros escurecidos e ar sendo "sugado" para dentro.'},
 {q:'A transmissão de calor por massas de ar ou gases aquecidos em movimento é a:',o:['Condução.','Convecção.','Irradiação.','Reflexão.','Ionização.'],r:1,x:'Convecção leva o calor para cima e por corredores e escadas, espalhando o incêndio para outros andares.'},
 {q:'Um produto típico da combustão incompleta é:',o:['Oxigênio.','Nitrogênio.','Monóxido de carbono.','Vapor de água puro.','Gás hélio.'],r:2,x:'Com pouco oxigênio, a queima gera CO (tóxico e inodoro) e fuligem.'},
 {q:'A transmissão de calor que ocorre por ondas eletromagnéticas, sem precisar de meio material, é a:',o:['Condução.','Convecção.','Irradiação.','Combustão.','Oxidação.'],r:2,x:'A irradiação aquece edificações vizinhas mesmo sem contato com as chamas.'}]},
'dadm-princ':{qs:[
 {q:'São princípios expressos da Administração Pública no caput do art. 37 da Constituição Federal:',o:['Legalidade, impessoalidade, moralidade, publicidade e eficiência.','Legalidade, razoabilidade, moralidade, publicidade e eficiência.','Supremacia do interesse público, legalidade, moralidade, publicidade e eficiência.','Legalidade, impessoalidade, moralidade, proporcionalidade e eficiência.','Legalidade, impessoalidade, motivação, publicidade e eficiência.'],r:0,x:'LIMPE. Razoabilidade, proporcionalidade, motivação e supremacia do interesse público são princípios implícitos (ou de outras leis).'},
 {q:'O princípio da eficiência foi incluído expressamente na Constituição pela:',o:['Redação original de 1988.','Emenda Constitucional 19/1998.','Emenda Constitucional 45/2004.','Lei 8.112/1990.','Lei 9.784/1999.'],r:1,x:'A EC 19/1998 (reforma administrativa) acrescentou a eficiência ao art. 37.'},
 {q:'Para a Administração Pública, o princípio da legalidade significa que ela:',o:['Pode fazer tudo o que a lei não proíbe.','Só pode fazer o que a lei autoriza.','Pode agir livremente em nome do interesse público.','Está dispensada de seguir a lei em emergências.','Pode criar obrigações por ato administrativo sem base legal.'],r:1,x:'O particular pode tudo o que a lei não proíbe; a Administração, só o que a lei permite.'},
 {q:'A vedação de nomes, símbolos ou imagens que caracterizem promoção pessoal de autoridades na publicidade oficial decorre diretamente do princípio da:',o:['Eficiência.','Impessoalidade.','Publicidade.','Legalidade.','Continuidade.'],r:1,x:'A publicidade oficial deve ser educativa, informativa ou de orientação social, sem promoção pessoal (art. 37, §1º): impessoalidade.'},
 {q:'Segundo a Súmula 473 do STF, a Administração pode anular seus próprios atos quando ilegais e revogá-los por conveniência e oportunidade. Esse poder expressa o princípio da:',o:['Autotutela.','Tutela.','Hierarquia.','Continuidade.','Especialidade.'],r:0,x:'Autotutela é o controle da Administração sobre os próprios atos. Tutela é o controle sobre as entidades da indireta.'}]},
'dadm-atos':{qs:[
 {q:'A revogação do ato administrativo ocorre por:',o:['Ilegalidade, com efeitos retroativos.','Conveniência e oportunidade, com efeitos para o futuro.','Ilegalidade, com efeitos para o futuro.','Decisão judicial, com efeitos retroativos.','Descumprimento de condição pelo beneficiário.'],r:1,x:'Revogação: mérito (conveniência e oportunidade), só pela Administração, efeitos ex nunc. Anulação: ilegalidade, efeitos ex tunc.'},
 {q:'São elementos sempre vinculados do ato administrativo:',o:['Motivo e objeto.','Competência, finalidade e forma.','Competência, motivo e objeto.','Forma, motivo e finalidade.','Apenas a finalidade.'],r:1,x:'Competência, finalidade e forma são vinculados; motivo e objeto formam o mérito nos atos discricionários.'},
 {q:'O atributo que permite à Administração executar suas decisões sem precisar de autorização judicial prévia é a:',o:['Presunção de legitimidade.','Tipicidade.','Autoexecutoriedade.','Imperatividade.','Motivação.'],r:2,x:'Autoexecutoriedade: a Administração executa diretamente (por exemplo, a interdição de um estabelecimento irregular).'},
 {q:'O Poder Judiciário, ao controlar um ato administrativo discricionário, pode:',o:['Revogá-lo por inconveniência.','Anulá-lo se for ilegal.','Substituir o mérito administrativo pelo seu.','Rever a oportunidade do ato.','Aplicar sanção disciplinar ao servidor.'],r:1,x:'O Judiciário controla a legalidade (anula), não o mérito. Revogar é exclusivo da própria Administração.'},
 {q:'Os vícios de competência (quando não exclusiva) e de forma (quando não essencial) podem ser corrigidos por meio da:',o:['Revogação.','Cassação.','Convalidação.','Caducidade.','Contraposição.'],r:2,x:'Convalidação corrige vícios sanáveis, preservando os efeitos já produzidos.'}]},
'dcon-dir':{qs:[
 {q:'Segundo a Constituição, a casa é asilo inviolável do indivíduo, mas é possível nela penetrar sem consentimento do morador, a qualquer hora, em caso de:',o:['Ordem judicial.','Flagrante delito, desastre ou para prestar socorro.','Fiscalização tributária.','Investigação policial em curso.','Requisição do Ministério Público.'],r:1,x:'Flagrante, desastre e socorro autorizam a entrada a qualquer hora. Por ordem judicial, só durante o dia.'},
 {q:'O remédio constitucional cabível para proteger a liberdade de locomoção é o:',o:['Mandado de segurança.','Habeas data.','Habeas corpus.','Mandado de injunção.','Ação popular.'],r:2,x:'Habeas corpus protege o direito de ir, vir e permanecer. É gratuito e não exige advogado.'},
 {q:'O mandado de injunção é cabível quando:',o:['Houver ameaça à liberdade de locomoção.','Faltar norma regulamentadora que torne inviável o exercício de direito constitucional.','For negado acesso a informações pessoais em banco de dados público.','Houver ato lesivo ao patrimônio público.','Houver lesão a direito líquido e certo não amparado por habeas corpus.'],r:1,x:'Mandado de injunção combate a omissão legislativa que impede o exercício de um direito.'},
 {q:'Tem legitimidade para propor ação popular:',o:['Qualquer pessoa, inclusive estrangeiro não residente.','Qualquer cidadão.','Apenas o Ministério Público.','Apenas partidos políticos.','Apenas associações constituídas há mais de um ano.'],r:1,x:'Ação popular: qualquer cidadão (eleitor), contra ato lesivo ao patrimônio público, à moralidade, ao meio ambiente e ao patrimônio histórico e cultural.'},
 {q:'Os tratados internacionais sobre direitos humanos aprovados em cada Casa do Congresso, em dois turnos, por três quintos dos votos, serão equivalentes a:',o:['Leis ordinárias.','Leis complementares.','Emendas constitucionais.','Decretos legislativos.','Normas supralegais.'],r:2,x:'É o §3º do art. 5º (EC 45/2004). Tratados de direitos humanos sem esse rito têm status supralegal.'}]}
});
