
/* ===================== ARENA: LÍNGUA PORTUGUESA =====================
   Bancos combinatórios: cada frase é montada na hora a partir de moldes e listas,
   e o mesmo item aparece em formatos diferentes (lacuna, toque no erro, certo/errado,
   alternativa incorreta entre cinco). */
const SI=a=>({s:a[0],c:a[1],w:a[2].split('|'),x:a[3]||''});
const siP=list=>()=>SI(rP(list));

/* ---------- CONCORDÂNCIA ---------- */
const PL_N=['muitos acidentes','várias ocorrências','três incêndios','problemas sérios','reclamações dos moradores','dúvidas sobre o edital','casos parecidos','falhas no equipamento','vítimas no local','denúncias anônimas','vagas remanescentes','erros na escala'];
const PL_C=['no plantão de ontem','na rodovia','durante a vistoria','no último concurso','naquele bairro','nesta semana','no relatório','na operação'];
const PL_S=['os novos equipamentos','as viaturas reformadas','os resultados da prova','as ordens do comandante','três candidatos atrasados','os documentos do concurso','as mangueiras novas','os reforços da capital'];
const X_HAVER='"Haver" no sentido de existir ou acontecer é impessoal: fica sempre no singular, e o auxiliar que o acompanha também.';
const cGen={
  haver(){ const t=rP([['Houve','Houveram'],['Havia','Haviam'],['Haverá','Haverão'],['Há','Hão']]); return {s:'{} '+rP(PL_N)+' '+rP(PL_C)+'.',c:t[0],w:[t[1]],x:X_HAVER}; },
  fazer(){ const n=rI(2,15), u=rP(['anos','meses','semanas','dias']), t=rP([['Faz','Fazem'],['Fazia','Faziam'],['Fará','Farão']]); return {s:'{} '+n+' '+u+' que '+rP(['ele entrou na corporação','o edital foi publicado','a obra começou','não chove na região','a equipe treina junta']),c:t[0],w:[t[1]],x:'"Fazer" indicando tempo decorrido é impessoal: fica no singular.'}; },
  basico(){ const s=rP([['Os bombeiros','chegaram','chegou'],['As equipes','trabalharam','trabalhou'],['Os candidatos','estavam','estava'],['Nós','saímos','saiu'],['A guarnição','partiu','partiram'],['O comandante e o tenente','saíram','saiu'],['Tu e ele','ficareis','ficará']]); return {s:s[0]+' {} '+rP(['cedo.','logo após o alarme.','antes do previsto.']),c:s[1],w:[s[2]],x:'O verbo concorda com o núcleo do sujeito em número e pessoa.'}; },
  posposto(){ const sub=rP(PL_S), v=rP([['Chegaram','Chegou'],['Faltam','Falta'],['Sobraram','Sobrou'],['Restam','Resta'],['Surgiram','Surgiu'],['Bastam','Basta']]); return {s:'{} '+rP(['ontem','ainda','no quartel','hoje'])+' '+sub+'.',c:v[0],w:[v[1]],x:'Com o sujeito depois do verbo, a concordância continua obrigatória: "'+sub+'" é plural.'}; },
  existir(){ const t=rP([['Existem','Existe'],['Existiam','Existia'],['Existirão','Existirá']]); return {s:'{} '+rP(PL_N)+' '+rP(PL_C)+'.',c:t[0],w:[t[1]],x:'"Existir" é verbo pessoal: concorda com o sujeito (diferente de "haver", que é impessoal).'}; },
  locHaver(){ const t=rP([['Deve haver','Devem haver'],['Vai haver','Vão haver'],['Pode haver','Podem haver'],['Costuma haver','Costumam haver']]); return {s:'{} '+rP(PL_N)+' '+rP(PL_C)+'.',c:t[0],w:[t[1]],x:X_HAVER}; },
  passiva(){ const v=rP([['Vendem-se','Vende-se','casas'],['Alugam-se','Aluga-se','salas comerciais'],['Consertam-se','Conserta-se','extintores'],['Contratam-se','Contrata-se','motoristas'],['Fazem-se','Faz-se','vistorias'],['Analisaram-se','Analisou-se','os recursos'],['Publicaram-se','Publicou-se','os resultados'],['Revisaram-se','Revisou-se','as escalas']]); return {s:'{} '+v[2]+'.',c:v[0],w:[v[1]],x:'Voz passiva sintética: o verbo transitivo direto + "se" concorda com o sujeito paciente ("'+v[2]+' são …").'}; },
  indet(){ const v=rP([['Precisa-se','Precisam-se','de voluntários'],['Trata-se','Tratam-se','de casos graves'],['Confia-se','Confiam-se','em bons profissionais'],['Obedece-se','Obedecem-se','às normas'],['Necessita-se','Necessitam-se','de novos equipamentos'],['Assistiu-se','Assistiram-se','a cenas lamentáveis']]); return {s:'{} '+v[2]+'.',c:v[0],w:[v[1]],x:'Verbo com preposição + "se" = índice de indeterminação do sujeito: o verbo fica no singular.'}; },
  nominal(){ return SI(rP([
    ['Seguem {} as cópias dos documentos.','anexas','anexo|anexa','"Anexo" é adjetivo e concorda com o substantivo ("cópias anexas"). "Em anexo" seria invariável.'],
    ['Seguem {} os comprovantes.','inclusos','incluso','"Incluso" é adjetivo: concorda com "comprovantes".'],
    ['A cadete agradeceu: "Muito {}".','obrigada','obrigado','"Obrigado" concorda com quem fala: mulher diz "obrigada".'],
    ['Elas {} organizaram a formatura.','mesmas','mesmo','"Mesmo" no sentido de "próprio" concorda: "elas mesmas".'],
    ['Estamos {} com a tesouraria.','quites','quite','"Quite" é adjetivo e concorda: "estamos quites".'],
    ['A soldado ficou {} cansada após o treino.','meio','meia','"Meio" antes de adjetivo é advérbio (= um pouco): invariável.'],
    ['Comeu {} marmita no intervalo.','meia','meio','Antes de substantivo, "meio" é numeral e concorda: "meia marmita".'],
    ['Era meio-dia e {} quando o alarme tocou.','meia','meio','"Meio-dia e meia (hora)": concorda com "hora", subentendido.'],
    ['Havia {} candidatos na sala.','bastantes','bastante','Antes de substantivo, "bastante" tem valor de adjetivo/pronome e vai ao plural.'],
    ['Os cadetes estudaram {} para a prova.','bastante','bastantes','Modificando verbo, "bastante" é advérbio: invariável.'],
    ['{} entrada de pessoas estranhas.','É proibido','É proibida','Sem artigo, a expressão fica invariável: "é proibido entrada". Com artigo: "é proibida a entrada".'],
    ['{} a entrada de pessoas estranhas.','É proibida','É proibido','Com artigo, o adjetivo concorda: "é proibida a entrada".'],
    ['{} paciência nos treinos.','É necessário','É necessária','Sem determinante, "é necessário" fica invariável.'],
    ['Havia {} pessoas na fila do que ontem.','menos','menas','"Menos" é sempre invariável; "menas" não existe na norma-padrão.'],
    ['As duas voluntárias ficaram {} no alojamento.','sós','só','"Só" com sentido de "sozinhas" é adjetivo e concorda: "ficaram sós".'],
    ['{} as oficiais participaram da reunião.','Só','Sós','"Só" com sentido de "somente" é advérbio: invariável.'],
    ['As provas eram {} difíceis.','meio','meias','"Meio" modificando adjetivo é advérbio: não varia.']])); },
  especial(){ return SI(rP([
    ['Mais de um candidato {} a prova.','perdeu','perderam','"Mais de um" leva o verbo ao singular (sem ideia de reciprocidade).'],
    ['{} duas horas quando o alarme tocou.','Eram','Era','Horas: o verbo "ser" concorda com o numeral ("eram duas horas").'],
    ['{} uma hora da tarde.','Era','Eram','"Uma hora": singular.'],
    ['{} aos oficiais fiscalizar as obras.','Cabe','Cabem','O sujeito é a oração "fiscalizar as obras": sujeito oracional leva o verbo ao singular.'],
    ['{} resolver os problemas da escala.','Falta','Faltam','Sujeito oracional ("resolver os problemas"): verbo no singular.'],
    ['Fui eu que {} o relatório.','fiz','fez','Com o relativo "que", o verbo concorda com o antecedente ("eu fiz").'],
    ['Fomos nós que {} a vistoria.','fizemos','fizeram|fez','"Que" retoma "nós": o verbo concorda com o antecedente.'],
    ['Os Estados Unidos {} o acordo.','assinaram','assinou','Nome próprio plural com artigo: verbo no plural.'],
    ['Cada um dos candidatos {} a sua prova.','recebeu','receberam','"Cada um" pede o verbo no singular.'],
    ['Nenhum dos soldados {} atrasado.','chegou','chegaram','"Nenhum de" + plural: verbo no singular, concordando com "nenhum".'],
    ['Deve fazer dez anos que ele {} a corporação.','deixou','deixaram','O sujeito de "deixou" é "ele"; "deve fazer" fica no singular por ser impessoal.'],
    ['Os dados que o relatório {} estavam corretos.','trazia','traziam','O sujeito de "trazia" é "o relatório"; "que" é objeto.'],
    ['{} de haver novas vagas no próximo edital.','Deixou','Deixaram','"Deixar de haver": o auxiliar de "haver" impessoal fica no singular.']])); }
};
const cAll=()=>cGen[rP(Object.keys(cGen))]();
arGame({id:'ar-port-conc',s:'port',t:'port-conc',nome:'Concordância sem erro',ic:'Nº',desc:'Verbo e nome concordando, das regras gerais às pegadinhas de prova.',lv:[
  {d:'"Haver" e "fazer" impessoais, sujeito simples e composto.',g:[()=>siCloze(rP([cGen.haver,cGen.fazer,cGen.basico])()),()=>siTF(rP([cGen.haver,cGen.fazer,cGen.basico])())]},
  {d:'Sujeito depois do verbo, "existir" × "haver", locuções com "haver".',g:[()=>siAny(rP([cGen.posposto,cGen.existir,cGen.locHaver])()),()=>siSpot(rP([cGen.posposto,cGen.existir,cGen.locHaver,cGen.haver])())]},
  {d:'Voz passiva sintética × índice de indeterminação do sujeito.',g:[()=>siAny(rP([cGen.passiva,cGen.indet])()),()=>arSort('Classifique o "se":',['Pronome apassivador (verbo concorda)','Índice de indeterminação (singular)'],rN([['Vendem-se casas.',0],['Alugam-se salas.',0],['Consertam-se extintores.',0],['Fazem-se vistorias.',0],['Publicaram-se os editais.',0],['Precisa-se de voluntários.',1],['Trata-se de casos graves.',1],['Confia-se em bons profissionais.',1],['Necessita-se de reforços.',1],['Obedece-se às normas.',1]],5),{x:'Verbo transitivo direto + se: passiva (concorda). Verbo com preposição + se: indeterminação (singular).'})]},
  {d:'Concordância nominal: anexo, meio, bastante, é proibido, só.',g:[()=>siAny(cGen.nominal()),()=>siSpot(cGen.nominal(),0.25)]},
  {d:'Casos especiais e questões de "assinale o erro".',g:[()=>siAny(cGen.especial()),()=>siOdd([cAll(),cAll(),cAll(),cAll(),cGen.especial()],rC(.5),'concordância')||siCloze(cGen.especial())]}]});

/* ---------- REGÊNCIA E CRASE ---------- */
const CR_FEM=['farmácia','escola','prefeitura','sede do batalhão','delegacia','praia','biblioteca','secretaria','reunião','Bahia','Europa','França','Argentina','Itália'];
const CR_SEM=['Curitiba','Londrina','Paranaguá','Portugal','Roma','Brasília','Maringá','Lisboa','Ponta Grossa'];
const CR_MOV=['Fui','Vou','Chegamos','Voltei','A equipe foi','O cadete retornou','Dirigiu-se'];
const crGen={
  lugar(){ if(rC(.55)){ const p=rP(CR_FEM); return {s:rP(CR_MOV)+' {} '+p+'.',c:'à',w:['a'],x:'Teste do "volto": volto DA '+p.split(' ')[0]+' → há artigo → crase.'}; }
    const p=rP(CR_SEM); return {s:rP(CR_MOV)+' {} '+p+'.',c:'a',w:['à'],x:'Teste do "volto": volto DE '+p+' → sem artigo → sem crase. "Vou a, volto da, crase há; vou a, volto de, crase pra quê?"'}; },
  proibida(){ return SI(rP([
    ['Começou {} chover forte.','a','à','Antes de verbo nunca há crase.'],['O efetivo voltou {} treinar.','a','à','Antes de verbo nunca há crase.'],['Estava disposto {} ajudar.','a','à','Antes de verbo nunca há crase.'],
    ['Andou {} cavalo pela serra.','a','à','Palavra masculina não admite artigo feminino.'],['Comprou o equipamento {} prazo.','a','à','"Prazo" é masculino.'],['Fez o trajeto {} pé.','a','à','"Pé" é masculino.'],
    ['Refiro-me {} ela.','a','à','Pronome pessoal não admite artigo.'],['Entreguei o documento {} você.','a','à','Pronome de tratamento "você" não admite artigo.'],['Encaminho o ofício {} Vossa Senhoria.','a','à','Pronomes de tratamento (exceto senhora, senhorita e dona) não admitem artigo.'],
    ['Não fale disso {} ninguém.','a','à','Pronome indefinido não admite artigo.'],['Ficaram frente {} frente.','a','à','Entre palavras repetidas não há crase.'],['Ficamos cara {} cara com o perigo.','a','à','Palavras repetidas: sem crase.'],
    ['O remédio foi dado gota {} gota.','a','à','Palavras repetidas: sem crase.'],['Referiu-se {} questões antigas.','a','à','"A" no singular antes de palavra no plural é só preposição.'],['Assisti {} uma palestra sobre prevenção.','a','à','Antes de artigo indefinido "uma" não há crase.'],
    ['Daqui {} duas horas, a equipe parte.','a','à|às','"Daqui a" indica tempo futuro, não horário: sem artigo.'],['Os marinheiros voltaram {} terra.','a','à','"Terra" no sentido de terra firme não leva artigo.'],['Voltei {} casa cedo.','a','à','"Casa" (o próprio lar) sem determinante não leva artigo.']])); },
  obrig(){ return SI(rP([
    ['A reunião começa {} 8h.','às','as|a','Hora determinada: a + as = às.'],['O plantão termina {} uma hora.','à','a','Indicação de hora: à uma hora.'],['Chegou {} noite.','à','a','Locução adverbial feminina: à noite.'],['Ficou {} espera do resgate.','à','a','Locução "à espera de".'],
    ['Saíram {} pressas.','às','as','Locução feminina: às pressas.'],['{} medida que o fogo avançava, a equipe recuava.','À','A','Locução conjuntiva: à medida que.'],['Pagou {} vista.','à','a','Locução feminina: à vista.'],['Estava {} procura de abrigo.','à','a','Locução "à procura de".'],
    ['Entreguei o relatório {} senhora do balcão.','à','a','"Senhora" admite artigo: a + a = à.'],['Obedeça {} normas de segurança.','às','as','Obedecer a + as normas = às normas.'],['Fez referência {} Lei 19.449.','à','a','Referência a + a Lei = à Lei.'],['Refiro-me {} aquele caso.','àquele','aquele|a aquele','a + aquele = àquele.'],
    ['Fui {} aquela reunião.','àquela','aquela','a + aquela = àquela.'],['Voltei {} casa dos meus pais.','à','a','Com determinante ("dos meus pais"), "casa" leva artigo.'],['Fui {} Curitiba dos pinheirais.','à','a','Cidade com determinante passa a ter artigo: à Curitiba dos pinheirais.'],['Sapato {} Luís XV.','à','a','Subentende-se "à moda de": crase mesmo antes de masculino.'],
    ['O foco estava {} distância de 20 metros.','à','a','Distância determinada: crase.'],['O plantão vai das 8h {} 17h.','às','as|a','Paralelismo: "das… às".']])); },
  facult(){ return rP([['Dirigiu-se a sua sala.',2],['Entreguei a carta a Maria.',2],['Fui até a porta.',2],['Fui à farmácia.',0],['Obedeça às normas.',0],['Começou a chover.',1],['Andou a cavalo.',1],['Refiro-me a ela.',1],['Chegou à noite.',0],['Pediu ajuda a sua mãe.',2],['Vou a Curitiba.',1],['Vou à Bahia.',0],['Atendemos de segunda a sexta.',1],['Assisti à palestra.',0]]); },
  regV(){ return SI(rP([
    ['Assisti {} jogo pela televisão.','ao','o','"Assistir" no sentido de ver pede a preposição "a".'],['Aspiro {} cargo de oficial.','ao','o','"Aspirar" no sentido de desejar pede "a".'],['O bombeiro aspirou {} fumaça.','a','à','"Aspirar" no sentido de inspirar é transitivo direto.'],
    ['Obedeça {} regulamento.','ao','o','"Obedecer" pede "a".'],['Prefiro estudar {} descansar.','a','do que','"Preferir" pede "a", nunca "do que" nem "mais".'],['Chegamos {} quartel antes das 7h.','ao','no','Na norma-padrão, quem chega, chega A algum lugar.'],
    ['A mudança {} novos custos.','implica','implica em','"Implicar" (acarretar) é transitivo direto.'],['Esqueci-me {} horário.','do','o','Pronominal, "esquecer-se" pede "de".'],['Esqueci {} horário.','o','do','Sem pronome, "esquecer" é transitivo direto.'],
    ['Lembrou-se {} prova.','da','a','Pronominal, "lembrar-se" pede "de".'],['Paguei {} funcionário.','ao','o','"Pagar" a pessoa: objeto indireto.'],['Perdoou {} irmão.','ao','o','"Perdoar" a pessoa: objeto indireto.'],
    ['O juiz procedeu {} leitura da sentença.','à','a','"Proceder" (dar início) pede "a".'],['O resultado agradou {} comandante.','ao','o','"Agradar" (satisfazer) pede "a".'],['Respondeu {} ofício no prazo.','ao','o','"Responder" pede "a".'],
    ['O cadete {} a recruta há dois anos.','namora','namora com','"Namorar" é transitivo direto.'],['Ele {} o novo instrutor.','simpatizou com','simpatizou-se com','"Simpatizar" não é pronominal.'],['{} entender a matéria.','Custou-me','Custei a','"Custar" (ser difícil): o sujeito é a coisa difícil.'],
    ['Reside {} Rua XV de Novembro.','na','à','"Residir" pede "em".'],['Fui {} cinema no sábado.','ao','no','"Ir" pede "a".']])); },
  rel(){ return SI(rP([
    ['Este é o cargo {} aspiro.','a que','que','Aspirar a → "a que".'],['Esta é a lei {} me referi.','a que','que','Referir-se a → "a que".'],['O equipamento {} precisamos chegou.','de que','que','Precisar de → "de que".'],
    ['O instrutor {} confio foi promovido.','em quem','que','Confiar em → "em quem".'],['O filme {} assisti era longo.','a que','que','Assistir a → "a que".'],['A cidade {} moro é fria.','em que','que','Morar em → "em que".'],
    ['Os livros {} gosto estão na estante.','de que','que','Gostar de → "de que".'],['A cidade {} vou fica no litoral.','aonde','onde','"Aonde" com verbos de movimento (ir a).'],['A cidade {} moro fica no planalto.','onde','aonde','"Onde" indica lugar fixo (morar em).'],
    ['A reunião {} qual assisti foi produtiva.','à','a','Assistir a + a qual = à qual.'],['São normas {} todos devem obedecer.','a que','que','Obedecer a → "a que".'],['A pessoa {} me referi chegou.','a quem','quem','Referir-se a → "a quem".']])); }
};
arGame({id:'ar-port-reg',s:'port',t:'port-reg',nome:'Regência e crase',ic:'à',desc:'Quando o "a" leva acento grave e qual preposição cada verbo pede.',lv:[
  {d:'Crase antes de feminino × masculino, verbo e pronome.',g:[()=>siCloze(rC(.5)?crGen.lugar():crGen.proibida()),()=>siTF(crGen.proibida())]},
  {d:'Lugares (teste do "volto"), horas e locuções femininas.',g:[()=>siAny(rC(.5)?crGen.lugar():crGen.obrig()),()=>siSpot(crGen.obrig(),0.2)]},
  {d:'Obrigatória, proibida ou facultativa.',g:[()=>{ const it=rN(Array.from({length:14},crGen.facult).filter((x,i,a)=>a.findIndex(y=>y[0]===x[0])===i),5); return arSort('Classifique a crase em cada frase:',['Obrigatória','Proibida','Facultativa'],it,{x:'Facultativa: antes de possessivo feminino, nome próprio feminino de pessoa e depois de "até".'}); },()=>siAny(rC(.5)?crGen.obrig():crGen.proibida())]},
  {d:'Regência verbal dos verbos que mais caem.',g:[()=>siAny(crGen.regV()),()=>siSpot(crGen.regV(),0.2)]},
  {d:'Pronome relativo com preposição, onde × aonde, questões de alternativa.',g:[()=>siAny(crGen.rel()),()=>siOdd([crGen.rel(),crGen.regV(),crGen.obrig(),crGen.proibida(),crGen.regV()],rC(.5),'regência ou crase')||siCloze(crGen.rel())]}]});

/* ---------- COLOCAÇÃO PRONOMINAL ---------- */
const COL_V=[['me','disseram','tudo'],['lhe','entregaram','o relatório'],['nos','chamaram','para a reunião'],['se','levantou','cedo'],['me','pediram','ajuda'],['lhe','deram','a notícia'],['te','avisaram','do horário'],['se','feriu','no treino'],['nos','convocaram','às pressas'],['me','informaram','o resultado']];
const COL_AT=[['Não','negativa'],['Nunca','negativa'],['Ninguém','pronome indefinido'],['Tudo','pronome indefinido'],['Alguém','pronome indefinido'],['Sempre','advérbio'],['Já','advérbio'],['Talvez','advérbio'],['Quem','pronome interrogativo']];
const colGen={
  inicio(){ const v=rP(COL_V); const cap=w=>w[0].toUpperCase()+w.slice(1); return {s:'{} '+v[2]+'.',c:cap(v[1])+'-'+v[0],w:[cap(v[0])+' '+v[1]],x:'A norma-padrão não inicia oração com pronome oblíquo átono: ênclise.'}; },
  atr(){ const v=rP(COL_V), a=rP(COL_AT); const s=a[0]==='Quem'?'Quem {} '+v[2]+'?':a[0]+' {} '+v[2]+'.'; return {s,c:v[0]+' '+v[1],w:[v[1]+'-'+v[0]],x:'Palavra atrativa ('+a[1]+': "'+a[0].toLowerCase()+'") exige próclise.'}; },
  sub(){ const v=rP(COL_V), c=rP([['Espero que','conjunção integrante'],['Quando','conjunção subordinativa'],['Embora','conjunção concessiva'],['O oficial que','pronome relativo'],['Se','conjunção condicional']]); return {s:c[0]+' {} '+v[2]+(c[0]==='O oficial que'?' saiu cedo.':', tudo bem.'),c:v[0]+' '+v[1],w:[v[1]+'-'+v[0]],x:'Conjunções subordinativas e pronomes relativos atraem o pronome ('+c[1]+'): próclise.'}; },
  meso(){ return SI(rP([
    ['{} a vistoria amanhã.','Far-se-á','Fará-se|Se fará','Futuro do presente no início, sem palavra atrativa: mesóclise.'],['{} o relatório na segunda.','Entregar-lhe-ei','Entregarei-lhe|Lhe entregarei','Futuro sem atrativo: mesóclise.'],['{} a verdade, se pudesse.','Dir-te-ia','Diria-te|Te diria','Futuro do pretérito sem atrativo: mesóclise.'],
    ['{} o concurso em maio.','Realizar-se-á','Realizará-se|Se realizará','Futuro sem atrativo: mesóclise.'],['Não {} a vistoria amanhã.','se fará','far-se-á|fará-se','Com palavra atrativa ("não"), a próclise prevalece sobre a mesóclise.'],['Ninguém {} o resultado.','lhe dirá','dir-lhe-á|dirá-lhe','Pronome indefinido atrai: próclise.']])); },
  loc(){ return SI(rP([
    ['Ele tinha {} a verdade.','me dito','dito-me','Nunca há ênclise ao particípio.'],['Os documentos haviam {} antes.','se perdido','perdido-se','Particípio não admite ênclise.'],['{} de fraude, a denúncia foi apurada.','Em se tratando','Em tratando-se','"Em" + gerúndio atrai o pronome: próclise.'],
    ['Vou {} amanhã.','ajudá-lo','ajudar-lo|ajudar ele','Infinitivo terminado em r + o: cai o r e o pronome vira "lo" (ajudá-lo).'],['Precisamos {} logo.','encontrá-los','encontrar-los|encontrar eles','r + os = -los: encontrá-los.'],['Os bombeiros {} rapidamente.','resgataram-no','resgataram-o|resgataram-lo','Verbo terminado em som nasal (m) + o = -no.']])); },
  lo(){ const v=rP([['fazer','fazê-lo'],['vender','vendê-la'],['entregar','entregá-lo'],['resolver','resolvê-lo'],['partir','parti-lo'],['construir','construí-lo'],['atrair','atraí-la'],['compor','compô-lo'],['dizer','dizê-lo'],['conseguir','consegui-la']]);
    const base=v[1].split('-')[0].replace(/[áêíôí]$/,'').replace(/[áéíóúâêô]/g,m=>({'á':'a','é':'e','í':'i','ó':'o','ú':'u','â':'a','ê':'e','ô':'o'}[m]));
    return {s:'Não sei se vou conseguir {} a tempo.',c:v[1],w:[v[0]+'-'+v[1].split('-')[1],v[0]+' '+(v[1].endsWith('la')?'ela':'ele')].filter(x=>x!==v[1]),x:'Infinitivo + o/a: some o "r" e o pronome vira lo/la ('+v[0]+' → '+v[1]+'). "'+v[0]+' ele" é coloquial.'}; }
};
arGame({id:'ar-port-col',s:'port',t:'port-col',nome:'Pronome no lugar',ic:'-se',desc:'Próclise, ênclise e mesóclise: onde o pronome oblíquo fica.',lv:[
  {d:'Início de frase (ênclise) × palavra negativa (próclise).',g:[()=>siCloze(rC(.5)?colGen.inicio():colGen.atr()),()=>siTF(rC(.5)?colGen.inicio():colGen.atr())]},
  {d:'Todas as palavras atrativas: indefinidos, advérbios, conjunções, relativos.',g:[()=>siAny(rP([colGen.atr,colGen.sub])()),()=>arSort('A frase exige próclise ou ênclise?',['Próclise','Ênclise'],rS([['Não ___ disseram nada.',0],['Disseram-___ tudo.',1],['Quem ___ contou?',0],['Levantou-___ cedo.',1],['Espero que ___ ligue.',0],['Tudo ___ resolveu.',0],['Entregaram-___ o prêmio.',1]]).slice(0,5),{x:'Sem palavra atrativa e no início: ênclise. Com atrativo: próclise.'})]},
  {d:'Mesóclise nos futuros e quando a próclise vence.',g:[()=>siAny(colGen.meso()),()=>siSpot(colGen.meso(),0.2)]},
  {d:'Locuções verbais, particípio, gerúndio com "em".',g:[()=>siAny(colGen.loc()),()=>siSpot(colGen.loc(),0.2)]},
  {d:'Formas lo/la/no/na e questões de alternativa.',g:[()=>siAny(colGen.lo()),()=>siOdd([colGen.inicio(),colGen.atr(),colGen.meso(),colGen.loc(),colGen.sub()],rC(.5),'colocação pronominal')||siCloze(colGen.loc())]}]});

/* ---------- ORTOGRAFIA E ACENTUAÇÃO ---------- */
const ORT=('exceção:excessão,esceção|paralisar:paralizar|análise:análize|pesquisar:pesquizar|empecilho:impecilho|privilégio:previlégio|beneficente:beneficiente|ascensão:ascenção,acensão|enxergar:enchergar|mexer:mecher|enxurrada:enchurrada|xícara:chícara|chuchu:xuxu|'+
 'baliza:balisa|certeza:certesa|francesa:franceza|portuguesa:portugueza|princesa:princeza|freguesia:freguezia|deslizar:deslisar|realizar:realisar|utilizar:utilisar|batizar:batisar|analisar:analizar|vizinho:visinho|obsessão:obseção,obcessão|'+
 'excesso:exceço,escesso|exceto:esceto|descer:decer|nascer:naser|consciência:conciência|discussão:discução|sucessão:sucesão|admissão:admição|permissão:permição|compreensão:compreenção|extensão:extenção|pretensão:pretenção|suspensão:suspenção|expansão:expanção|'+
 'cansaço:cançaço|maciço:massiço|assessor:acessor|enxaqueca:enchaqueca|bexiga:bechiga|xingar:chingar|faxina:fachina|puxar:puchar|cochichar:coxixar|salsicha:salsixa|mochila:moxila|pechincha:pexincha|bochecha:boxecha|caxumba:cachumba|abacaxi:abacachi|'+
 'gorjeta:gorgeta|laje:lage|majestade:magestade|gengiva:jengiva|jiló:giló|berinjela:beringela|ferrugem:ferrujem|sarjeta:sargeta|tigela:tijela|jeito:geito|canjica:cangica|herege:hereje|agiota:ajiota|estrangeiro:estranjeiro|'+
 'cadeado:cadiado|periquito:pirequito|disenteria:desinteria|possui:possue|quase:quasi|meritíssimo:meretíssimo|requisito:requesito|bueiro:boeiro|goela:guela|mágoa:mágua|camundongo:camondongo|tossir:tussir|engolir:engulir|bússola:bússula|entupir:entopir|'+
 'hesitar:esitar|habilidade:abilidade|desumano:deshumano|inábil:inhábil|mortadela:mortandela|cabeleireiro:cabelereiro|reivindicar:reinvindicar|prazeroso:prazeiroso|asterisco:asterístico|bandeja:bandeija|caranguejo:carangueijo|frustrado:frustado|'+
 'meteorologia:metereologia|companhia:compania|lagartixa:largatixa|mendigo:mendingo|sobrancelha:sombrancelha|ansioso:ancioso|ansiedade:anciedade|pretensioso:pretencioso|obcecado:obsecado|concessão:conceção|espontâneo:expontâneo|extravagante:estravagante|'+
 'esplêndido:explêndido|estender:extender|misto:mixto|cinquenta:cincoenta|êxito:ézito|hipótese:hipótese_|beneficência:beneficiência|advogado:adivogado|problema:poblema|próprio:própio').split('|').map(p=>{ const [c,w]=p.split(':'); return [c,w.split(',').filter(x=>x.indexOf('_')<0)]; }).filter(p=>p[1].length);
const ACENTO=[
 ['proparoxítona (todas são acentuadas)','lâmpada|médico|público|número|sílaba|fôlego|pêssego|árvore|cálculo|trânsito|máquina|técnico|âmbito|ônibus'],
 ['paroxítona terminada em l, n, r, x ou ps','útil|fácil|amável|túnel|hífen|pólen|caráter|açúcar|revólver|tórax|látex|bíceps'],
 ['paroxítona terminada em ã(s), ão(s), i(s), us, um/uns','ímã|órfã|órgão|bênção|táxi|júri|lápis|tênis|vírus|bônus|álbum|fórum'],
 ['paroxítona terminada em ditongo','história|série|água|régua|mágoa|jóquei|vôlei|pônei|glória|rádio'],
 ['oxítona terminada em a(s), e(s), o(s), em, ens','sofá|café|cipó|também|parabéns|você|após|Paraná|português|jacaré|armazém'],
 ['monossílabo tônico terminado em a(s), e(s), o(s)','pá|pé|nó|já|pó|mês|três|pés|nós'],
 ['ditongo aberto éi, ói, éu em oxítona ou monossílabo','papéis|herói|chapéu|anéis|céu|dói|fiéis|troféu|heróis|réu'],
 ['hiato: i ou u tônico sozinho na sílaba','saída|saúde|baú|país|egoísmo|raízes|juízes|faísca|ciúme|viúva']].map(([r,w])=>({r,w:w.split('|')}));
const SEM_ACENTO=['ideia','assembleia','heroico','jiboia','plateia','estreia','paranoia','boia','voo','enjoo','creem','leem','veem','deem','feiura','para','pelo','polo','pera','linguiça','tranquilo','frequente'];
const HIFEN=[['micro-ondas','microondas','Prefixo terminado na mesma vogal que inicia a palavra: hífen.'],['anti-inflamatório','antiinflamatório','Vogais iguais: hífen.'],['autoescola','auto-escola','Vogais diferentes: sem hífen.'],['antissocial','anti-social','Prefixo em vogal + palavra com s: dobra o s, sem hífen.'],['contrarregra','contra-regra','Prefixo em vogal + palavra com r: dobra o r.'],['ultrassom','ultra-som','Dobra o s.'],['infraestrutura','infra-estrutura','Vogais diferentes: junta.'],['extraoficial','extra-oficial','Vogais diferentes: junta.'],['coautor','co-autor','"Co" se junta ao segundo elemento.'],['pré-escola','préescola','Pré, pós e pró tônicos pedem hífen.'],['pós-graduação','posgraduação','Pós tônico: hífen.'],['ex-aluno','exaluno','"Ex" (anterior) sempre com hífen.'],['vice-diretor','vicediretor','"Vice" sempre com hífen.'],['super-homem','superomem','Prefixo + palavra com h: hífen.'],['inter-regional','interregional','Prefixo terminado em r + palavra com r: hífen.'],['bem-vindo','benvindo','"Bem" com hífen nesse composto.'],['mal-humorado','malhumorado','"Mal" + palavra com h: hífen.'],['recém-nascido','recémnascido','"Recém" sempre com hífen.'],['autoestima','auto-estima','Vogais diferentes: junta.'],['semiárido','semi-árido','Vogais diferentes: junta.'],['arqui-inimigo','arquiinimigo','Vogais iguais: hífen.']];
const ortUso=()=>SI(rP([
  ['{} você faltou ao treino?','Por que','Porque|Por quê|Porquê','Pergunta no início: "por que" (separado, sem acento).'],['Faltei {} estava doente.','porque','por que|por quê|porquê','Explicação/causa: "porque" (junto).'],['Você faltou {}?','por quê','porque|por que|porquê','No fim da frase: "por quê" (separado, com acento).'],
  ['Não sei o {} da ausência.','porquê','porque|por que|por quê','Substantivo (com artigo): "o porquê".'],['Este é o caminho {} passamos.','por que','porque|por quê','"Por que" = pelo qual.'],['Ele é um {} motorista.','mau','mal','"Mau" é adjetivo (oposto de "bom").'],
  ['Ele dirige {}.','mal','mau','"Mal" é advérbio (oposto de "bem").'],['{} chegou, já saiu de novo.','Mal','Mau','"Mal" como conjunção (= assim que).'],['Moro aqui {} dez anos.','há','a|à','Tempo passado: "há" (verbo haver).'],
  ['Daqui {} dez dias sai o resultado.','a','há|à','Tempo futuro: "a" (preposição).'],['Estamos {} dois quilômetros do foco.','a','há|à','Distância: "a".'],['Ele {} o documento amanhã.','traz','trás|tras','"Traz" é do verbo trazer.'],
  ['Ficou para {} na corrida.','trás','traz','"Trás" = atrás.'],['Estude, {} será reprovado.','senão','se não','"Senão" = caso contrário.'],['{} chover, faremos o treino.','Se não','Senão','"Se não" = caso não.'],
  ['Estudou muito {} passar.','a fim de','afim de','"A fim de" = para, com a finalidade de.'],['Física e Química são matérias {}.','afins','a fins|a fim','"Afins" = que têm afinidade.'],['O instrutor falou {} do edital.','acerca','a cerca|há cerca','"Acerca de" = sobre, a respeito de.'],
  ['{} de dez anos o quartel foi reformado.','Há cerca','Acerca|A cerca','"Há cerca de" = faz aproximadamente.'],['A {} do tribunal durou horas.','sessão','seção|cessão','Sessão = reunião, tempo de duração.'],['Procure a {} de pessoal.','seção','sessão|cessão','Seção (secção) = divisão, departamento.'],['A {} do terreno foi aprovada.','cessão','sessão|seção','Cessão = ato de ceder.']]));
const ortPal=n=>{ const p=rP(ORT); return arCh('Qual é a grafia correta?',p[0],rS(p[1]).slice(0,n-1).concat(n>2?ORT.filter(x=>x!==p).map(()=>null).slice(0,0):[]),{x:'Grafia correta: **'+p[0]+'**.'}); };
function ortCtx(){ const p=rP(ORT); const frase=rP(['A palavra “{}” apareceu no texto da prova.','O instrutor escreveu “{}” no quadro.','No relatório, constava a palavra “{}”.']); return siAny({s:frase,c:p[0],w:p[1],x:'Grafia correta: '+p[0]+'.'},['cloze','tf']); }
function ortAcento(){ const g=rP(ACENTO), w=rP(g.w); return arCh('Por que a palavra **'+w+'** é acentuada?',g.r,ACENTO.filter(x=>x!==g).map(x=>x.r),{x:'"'+w+'": '+g.r+'.'}); }
function ortAcentoPar(){ const g=rP(ACENTO), [a,b]=rN(g.w,2), right=a+' e '+b, ws=[]; let t=0;
  while(ws.length<4&&t<40){ t++; const [g1,g2]=rN(ACENTO,2); const s=rP(g1.w)+' e '+rP(g2.w); if(ws.indexOf(s)<0) ws.push(s); }
  return arCh('Assinale a alternativa em que as duas palavras são acentuadas **pela mesma regra**.',right,ws,{x:'"'+a+'" e "'+b+'": '+g.r+'.'}); }
function ortAcordo(){ if(rC(.5)){ const w=rP(SEM_ACENTO); return arTF('Depois do Acordo Ortográfico, a palavra “'+w+'” se escreve sem acento (ou sem trema).',true,{x:'Correto: "'+w+'". Perderam o acento os ditongos abertos ei/oi em paroxítonas (ideia, heroico), os hiatos ee/oo (creem, voo), o i/u tônico após ditongo em paroxítona (feiura), vários diferenciais (para, pelo, polo, pera) e o trema (linguiça).'}); }
  const h=rP(HIFEN); return arCh('Qual forma segue o Acordo Ortográfico?',h[0],[h[1]],{x:h[2]}); }
function ortTodas(){ const good=()=>rN(ORT,3).map(p=>p[0]); const bad=()=>{ const ws=rN(ORT,3), k=rI(0,2); return ws.map((p,i)=>i===k?rP(p[1]):p[0]); };
  const R=good().join(', '), W=[bad().join(', '),bad().join(', '),bad().join(', '),bad().join(', ')];
  return arCh('Assinale a alternativa em que **todas** as palavras estão escritas corretamente.',R,W,{x:'Correta: '+R+'.'}); }
arGame({id:'ar-port-ort',s:'port',t:'port-ort',nome:'Ortografia relâmpago',ic:'ç',desc:'Mais de 150 palavras que derrubam candidatos, acentuação, hífen e os porquês.',lv:[
  {d:'Grafia certa entre duas opções.',g:[()=>{ const p=rP(ORT); return arCh('Qual é a grafia correta?',p[0],[rP(p[1])],{x:'Grafia correta: **'+p[0]+'**.'}); },()=>ortCtx()]},
  {d:'Grafia em contexto e com mais distratores; regras de acentuação básicas.',g:[()=>{ const p=rP(ORT); return arCh('Complete com a grafia correta:\n“O candidato escreveu _____ na redação.”',p[0],p[1],{x:'Grafia correta: **'+p[0]+'**.'}); },()=>ortAcento()]},
  {d:'Por que a palavra é acentuada: todas as regras.',g:[()=>ortAcento(),()=>ortAcentoPar()]},
  {d:'Acordo Ortográfico, hífen e os usos: porquês, mal/mau, há/a, senão.',g:[()=>ortAcordo(),()=>siAny(ortUso())]},
  {d:'"Todas as palavras corretas", regra comum de acentuação, usos em contexto.',g:[()=>ortTodas(),()=>ortAcentoPar(),()=>siSpot(ortUso(),0.2)]}]});

/* ---------- SEMÂNTICA ---------- */
const PARON=[
 [['iminente','eminente'],['prestes a acontecer','ilustre, elevado'],[['O risco de desabamento era {}.',0],['O {} professor recebeu uma homenagem.',1]]],
 [['retificar','ratificar'],['corrigir','confirmar'],[['Foi preciso {} o erro no relatório.',0],['O comandante resolveu {} a ordem dada.',1]]],
 [['infringir','infligir'],['violar (uma lei)','aplicar (pena, castigo)'],[['O motorista acabou por {} a lei de trânsito.',0],['O juiz vai {} a pena ao réu.',1]]],
 [['discrição','descrição'],['reserva, prudência','ato de descrever'],[['O caso foi tratado com {}.',0],['Faça uma {} detalhada do local.',1]]],
 [['tráfego','tráfico'],['trânsito','comércio ilegal'],[['O {} na BR estava lento.',0],['A polícia combate o {} de drogas.',1]]],
 [['cumprimento','comprimento'],['saudação; execução','extensão'],[['O {} da ordem foi imediato.',0],['A mangueira tem 30 metros de {}.',1]]],
 [['flagrante','fragrante'],['evidente, no ato','perfumado'],[['O suspeito foi preso em {}.',0],['O jardim estava {} de flores.',1]]],
 [['emergir','imergir'],['vir à tona','mergulhar'],[['O mergulhador começou a {} lentamente.',0],['É preciso {} a peça na água fria.',1]]],
 [['emigrar','imigrar'],['sair do país','entrar em outro país'],[['Muitos italianos decidiram {} da Itália no século XIX.',0],['Eles vieram {} para o Paraná.',1]]],
 [['deferir','diferir'],['atender, conceder','ser diferente; adiar'],[['O diretor vai {} o requerimento.',0],['As duas versões costumam {} em detalhes.',1]]],
 [['mandato','mandado'],['período de representação','ordem judicial'],[['O {} do prefeito termina em dezembro.',0],['O juiz expediu um {} de busca.',1]]],
 [['acender','ascender'],['pôr fogo, ligar','subir, elevar-se'],[['É proibido {} fogueiras no parque.',0],['Ele quer {} ao posto de capitão.',1]]],
 [['concerto','conserto'],['apresentação musical','reparo'],[['A banda da corporação fez um {}.',0],['A viatura foi para o {}.',1]]],
 [['censo','senso'],['recenseamento','juízo, discernimento'],[['O IBGE realiza o {} a cada dez anos.',0],['Falta {} de responsabilidade a ele.',1]]],
 [['cela','sela'],['pequeno quarto de prisão','arreio de montaria'],[['O preso voltou para a {}.',0],['Ajustou a {} do cavalo.',1]]],
 [['cessão','sessão'],['ato de ceder','reunião'],[['A {} do terreno foi aprovada.',0],['A {} da Câmara começou às 9h.',1]]],
 [['incipiente','insipiente'],['que está no início','ignorante, sem saber'],[['O projeto ainda está em fase {}.',0],['Aquele argumento é {} e confuso.',1]]],
 [['espiar','expiar'],['observar às escondidas','pagar por culpa'],[['Ficou na janela para {} a rua.',0],['Queria {} seus erros do passado.',1]]],
 [['cassar','caçar'],['anular (direito, mandato)','perseguir animais'],[['O tribunal decidiu {} o mandato.',0],['É proibido {} animais silvestres.',1]]],
 [['descriminar','discriminar'],['deixar de considerar crime','distinguir; tratar com preconceito'],[['O projeto pretende {} a conduta.',0],['É crime {} alguém pela cor da pele.',1]]],
 [['despercebido','desapercebido'],['que não foi notado','desprovido, desprevenido'],[['O erro passou {} na revisão.',0],['Estava {} de recursos para a viagem.',1]]],
 [['vultoso','vultuoso'],['volumoso, de grande valor','inchado (o rosto)'],[['O contrato envolvia uma quantia {}.',0],['O paciente apresentava o rosto {}.',1]]],
 [['estrato','extrato'],['camada','resumo; o que se extrai'],[['Cada {} de rocha revela uma época.',0],['Tirou o {} bancário.',1]]],
 [['tachar','taxar'],['atribuir defeito, rotular','fixar taxa, tributar'],[['Não é justo {} o colega de preguiçoso.',0],['O governo vai {} os produtos importados.',1]]]];
const SINON=[['A medida foi **ratificada** pelo comando.','confirmada','corrigida|anulada|adiada|questionada'],['O bombeiro agiu com **destreza**.','habilidade','lentidão|imprudência|timidez|raiva'],['O relatório era **sucinto**.','breve','extenso|confuso|minucioso|tendencioso'],
 ['A situação da estrutura era **precária**.','instável','segura|próspera|urgente|recente'],['O comandante foi **enfático** na ordem.','firme, incisivo','hesitante|breve|gentil|irônico'],['A equipe mostrou-se **apática** diante do problema.','indiferente','agitada|preocupada|furiosa|eficiente'],
 ['O depoimento foi **ambíguo**.','de duplo sentido','claro|falso|longo|decisivo'],['Houve um **exíguo** prazo para a entrega.','pequeno, escasso','amplo|justo|flexível|extra'],['A atitude **leviana** causou problemas.','imprudente','corajosa|lenta|honesta|sensata'],
 ['O perito fez uma análise **minuciosa**.','detalhada','rápida|superficial|parcial|breve'],['Ele é **perspicaz** nas investigações.','sagaz, observador','distraído|lento|ingênuo|teimoso'],['A decisão foi **unânime**.','de todos','da maioria|polêmica|provisória|secreta'],
 ['O impacto do vento era **iminente**.','prestes a ocorrer','ilustre|passado|improvável|fraco'],['A **anuência** do diretor foi necessária.','concordância','ausência|recusa|assinatura|presença'],['Foi um ato **ilícito**.','proibido por lei','permitido|legal|inocente|público'],
 ['O aluno **inerte** não reagiu.','parado, sem ação','agitado|atento|irritado|curioso'],['Seu argumento é **plausível**.','aceitável, razoável','absurdo|ofensivo|antigo|obscuro'],['A chuva **incessante** alagou o bairro.','contínua','fraca|repentina|rara|leve'],
 ['O discurso foi **prolixo**.','longo e cansativo','curto|objetivo|emocionante|claro'],['O fogo foi **debelado** em minutos.','controlado, vencido','ateado|espalhado|investigado|avistado'],['Ele **ratifica** o que disse ontem.','confirma','corrige|nega|esquece|repete'],
 ['O efeito foi **efêmero**.','passageiro','duradouro|intenso|grave|imediato'],['O plano era **exequível**.','realizável','impossível|caro|secreto|antigo'],['A **índole** do rapaz era boa.','caráter, temperamento','aparência|saúde|condição financeira|família']];
const ANTON=[['efêmero','duradouro'],['prolixo','conciso'],['ativo','inerte'],['lícito','ilícito'],['escasso','abundante'],['sucinto','extenso'],['ambíguo','claro'],['precário','estável'],['otimista','pessimista'],['ascender','descender'],['emergir','submergir'],['cauteloso','imprudente'],['generoso','mesquinho'],['explícito','implícito'],['convergir','divergir']];
const DENOT=[['O bombeiro tem um coração de ouro.',1],['O ouro foi extraído no litoral paranaense.',0],['Ele é uma fera na matemática.',1],['A fera escapou da jaula do zoológico.',0],['A notícia caiu como uma bomba no quartel.',1],['A bomba foi desarmada pelo esquadrão.',0],['Ela tem nervos de aço.',1],['A estrutura de aço resistiu ao fogo.',0],['O preço da gasolina subiu às nuvens.',1],['As nuvens encobriram a serra.',0],['Aquele sargento é uma pedra no sapato.',1],['Havia uma pedra no sapato do atleta.',0]];
const FIG=[['O quartel é uma segunda família.','Metáfora'],['Forte como um touro, ele carregou a vítima.','Comparação'],['Ele leu Machado de Assis nas férias.','Metonímia'],['Bebeu dois copos de água depois do treino.','Metonímia'],['Já te falei isso um milhão de vezes!','Hipérbole'],['Chorei rios de lágrimas.','Hipérbole'],
 ['Ele partiu desta para melhor.','Eufemismo'],['Que belo serviço: quebrou todo o equipamento!','Ironia'],['O vento sussurrava entre as araucárias.','Prosopopeia'],['A cidade dormia em silêncio.','Prosopopeia'],['Nasce o sol e não dura mais que um dia.','Antítese'],['É dor que desatina sem doer.','Paradoxo'],
 ['Estou morrendo de fome.','Hipérbole'],['O pé da mesa quebrou.','Catacrese'],['Ouvi uma voz doce e aveludada.','Sinestesia'],['Tic-tac, o relógio não parava.','Onomatopeia'],['Todos os dias, todas as horas, todos os minutos, ele treinava.','Anáfora'],['Vi com meus próprios olhos.','Pleonasmo']];
function semParon(){ const p=rP(PARON), [s,k]=rP(p[2]); return {s,c:p[0][k],w:[p[0][1-k]],x:'"'+p[0][0]+'" = '+p[1][0]+'; "'+p[0][1]+'" = '+p[1][1]+'.'}; }
function semSign(){ const p=rP(PARON), k=rI(0,1); return arCh('Qual o significado de **'+p[0][k]+'**?',p[1][k],[p[1][1-k]].concat(rN(PARON.filter(x=>x!==p),3).map(x=>x[1][rI(0,1)])),{x:'"'+p[0][0]+'" = '+p[1][0]+'; "'+p[0][1]+'" = '+p[1][1]+'.'}); }
arGame({id:'ar-port-sem',s:'port',t:'port-sem',nome:'Sentido exato',ic:'≈',desc:'Sinônimos, parônimos, homônimos, conotação e figuras de linguagem.',lv:[
  {d:'Sinônimo em contexto.',g:[()=>{ const s=rP(SINON); return arCh(s[0]+'\nA palavra destacada pode ser substituída, sem alterar o sentido, por:',s[1],s[2].split('|'),{x:'Sentido no contexto: '+s[1]+'.'}); }]},
  {d:'Antônimos e significado de parônimos.',g:[()=>{ const a=rP(ANTON), k=rI(0,1); return arCh('Qual é o antônimo de **'+a[k]+'**?',a[1-k],rN(ANTON.filter(x=>x!==a),4).map(x=>x[rI(0,1)]),{x:'"'+a[0]+'" × "'+a[1]+'".'}); },()=>semSign()]},
  {d:'Parônimos e homônimos na frase.',g:[()=>siAny(semParon(),['cloze','spot','tf'])]},
  {d:'Sentido denotativo × conotativo.',g:[()=>{ const it=rN(DENOT,5); return arSort('Classifique o sentido das palavras em cada frase:',['Denotativo (literal)','Conotativo (figurado)'],it,{x:'Denotativo: sentido literal, de dicionário. Conotativo: sentido figurado, que depende do contexto.'}); },()=>{ const d=rP(DENOT); return arCh('Em “'+d[0]+'”, a linguagem é:',d[1]?'Conotativa (sentido figurado)':'Denotativa (sentido literal)',[d[1]?'Denotativa (sentido literal)':'Conotativa (sentido figurado)'],{x:'Literal = denotativa; figurada = conotativa.'}); }]},
  {d:'Figuras de linguagem e trocas que alteram o sentido.',g:[()=>{ const f=rP(FIG); return arCh('Qual figura de linguagem aparece em: “'+f[0]+'”?',f[1],[...new Set(FIG.map(x=>x[1]))].filter(x=>x!==f[1]),{x:'“'+f[0]+'”: '+f[1]+'.'}); },()=>siOdd([semParon(),semParon(),semParon(),semParon(),semParon()],rC(.6),'emprego de palavras')||siCloze(semParon())]}]});

/* ---------- CLASSES DE PALAVRAS ---------- */
const CL_NOME={sub:'Substantivo',adj:'Adjetivo',art:'Artigo',num:'Numeral',pron:'Pronome',verb:'Verbo',adv:'Advérbio',prep:'Preposição',conj:'Conjunção',interj:'Interjeição'};
const CL_FR=['Os[art] bombeiros[sub] chegaram[verb] rapidamente[adv] ao local.','A[art] viatura[sub] nova[adj] saiu[verb] cedo[adv].','Ela[pron] estudou[verb] muito[adv] para[prep] a prova.','Três[num] soldados[sub] resgataram[verb] a vítima.','Nossa[pron] equipe[sub] trabalhou[verb] mas[conj] não venceu.',
 'Nossa![interj] Que[adv] incêndio[sub] enorme[adj]!','O[art] correr[sub] diário[adj] melhora[verb] o fôlego.','Ele[pron] falou[verb] alto[adv] durante[prep] a reunião.','O cadete[sub] atento[adj] percebeu[verb] o erro.','Saímos[verb] porque[conj] chovia[verb] muito.',
 'Aquele[pron] prédio[sub] alto[adj] foi[verb] evacuado.','Ontem[adv] recebemos[verb] duas[num] denúncias[sub].','Com[prep] calma[sub], tudo[pron] se resolve[verb].','Ai![interj] O fogo[sub] queimou[verb] minha[pron] mão.','Embora[conj] cansados[adj], eles[pron] continuaram[verb].',
 'O[art] primeiro[num] colocado[sub] recebeu[verb] a medalha.','Alguém[pron] deixou[verb] a porta[sub] aberta[adj].','Talvez[adv] chova[verb] amanhã[adv].','A coragem[sub] é[verb] essencial[adj].','Os alunos[sub] estudam[verb] e[conj] treinam[verb].'];
const QUE_SE=[['O livro **que** li era ótimo.','Pronome relativo'],['Espero **que** você passe.','Conjunção integrante'],['Estudou tanto **que** passou.','Conjunção consecutiva'],['Ele é mais forte **que** o irmão.','Conjunção comparativa'],['**Que** bonito foi o desfile!','Advérbio de intensidade'],['**Que** horas são?','Pronome interrogativo'],['Tenho **que** sair cedo.','Preposição'],['Eu é **que** sei o caminho.','Palavra expletiva (de realce)'],
 ['Vendem-**se** casas.','Pronome apassivador'],['Precisa-**se** de ajudantes.','Índice de indeterminação do sujeito'],['Ele **se** feriu no treino.','Pronome reflexivo'],['**Se** chover, não vou.','Conjunção condicional'],['Não sei **se** ele vem.','Conjunção integrante'],['Ele **se** queixou do barulho.','Parte integrante do verbo'],['Os dois **se** abraçaram.','Pronome recíproco']];
const MUDA=[['O **correr** faz bem à saúde.','Substantivo'],['Ele deu um **não** como resposta.','Substantivo'],['Ele fala **alto**.','Advérbio'],['O prédio **alto** foi evacuado.','Adjetivo'],['Havia **bastante** trabalho.','Pronome indefinido (adjetivo)'],['Estudou **bastante**.','Advérbio'],['Ela ficou **meio** tonta.','Advérbio'],['Comprou **meio** litro.','Numeral'],['**Só** ele chegou.','Advérbio (palavra denotativa)'],['Ele ficou **só**.','Adjetivo'],
 ['Encontrei-**a** no quartel.','Pronome oblíquo'],['Vou **a** Curitiba.','Preposição'],['**A** equipe chegou.','Artigo'],['Fiz **como** mandaram.','Conjunção conformativa'],['Corre **como** um atleta.','Conjunção comparativa'],['**Como** estava cansado, dormiu.','Conjunção causal'],['**Como** você chegou aqui?','Advérbio interrogativo']];
function clParse(fr){ const toks=fr.split(' '), parts=[], tags=[]; toks.forEach(t=>{ const m=t.match(/^(.*?)\[(\w+)\](.*)$/); if(m){ parts.push(m[1]+m[3]); tags.push(m[2]); } else { parts.push(t); tags.push(null); } }); return {parts,tags}; }
function clPick(basic){ let g=0; while(g++<30){ const {parts,tags}=clParse(rP(CL_FR)); const avail=[...new Set(tags.filter(Boolean))].filter(t=>!basic||['sub','adj','verb','adv'].indexOf(t)>=0); const want=rP(avail); const idx=tags.map((t,i)=>t===want?i:-1).filter(i=>i>=0); if(idx.length!==1) continue;
  return arPick('Toque no **'+CL_NOME[want].toLowerCase()+'**.',parts,idx[0],{x:'"'+parts[idx[0]].replace(/[.,!?]/g,'')+'" é '+CL_NOME[want].toLowerCase()+'.'}); } return clQual(); }
function clQual(){ const {parts,tags}=clParse(rP(CL_FR)); const idxs=tags.map((t,i)=>t?i:-1).filter(i=>i>=0), i=rP(idxs); const w=parts[i].replace(/[.,!?]/g,'');
  return arCh('Em “'+parts.join(' ')+'”, a palavra **'+w+'** é:',CL_NOME[tags[i]],Object.keys(CL_NOME).filter(k=>k!==tags[i]).map(k=>CL_NOME[k]),{x:'"'+w+'": '+CL_NOME[tags[i]].toLowerCase()+'.'}); }
const clBank=(bank,q)=>()=>{ const it=rP(bank); return arCh(it[0]+'\n'+q,it[1],[...new Set(bank.map(x=>x[1]))].filter(x=>x!==it[1]),{x:it[0].replace(/\*\*/g,'')+' → '+it[1]+'.'}); };
arGame({id:'ar-port-cla',s:'port',t:'port-cla',nome:'Classificador de palavras',ic:'Aa',desc:'As dez classes, o "que" e o "se" e as palavras que mudam de classe.',lv:[
  {d:'Substantivo, adjetivo, verbo e advérbio.',g:[()=>clPick(true)]},
  {d:'Todas as dez classes.',g:[()=>clQual(),()=>clPick(false)]},
  {d:'As funções do "que" e do "se".',g:[clBank(QUE_SE,'Classifique a palavra destacada:')]},
  {d:'Palavras que mudam de classe conforme o contexto.',g:[clBank(MUDA,'A palavra destacada é:')]},
  {d:'Mistura de prova: "que", "se", "a", "como".',g:[clBank(QUE_SE.concat(MUDA),'A palavra destacada é classificada como:'),()=>arSort('Classifique o "se":',['Apassivador','Indeterminação do sujeito','Reflexivo/recíproco','Conjunção'],rS([['Vendem-se casas.',0],['Alugam-se salas.',0],['Precisa-se de ajudantes.',1],['Trata-se de um caso grave.',1],['Ele se feriu.',2],['Os dois se abraçaram.',2],['Se chover, não vou.',3],['Não sei se ele vem.',3]]).slice(0,5),{x:'VTD + se = apassivador; com preposição = indeterminação; ação sobre si = reflexivo; ligando orações = conjunção.'})]}]});

/* ---------- SINTAXE ---------- */
const SUJ=[['Os bombeiros chegaram cedo.','Simples'],['O comandante e o tenente saíram.','Composto'],['Chegamos cedo ao quartel.','Oculto (desinencial)'],['Estudei a noite toda.','Oculto (desinencial)'],['Roubaram a viatura ontem.','Indeterminado'],['Precisa-se de voluntários.','Indeterminado'],['Houve muitos feridos.','Oração sem sujeito'],['Choveu muito em Curitiba.','Oração sem sujeito'],['Faz dez anos que ele entrou.','Oração sem sujeito'],['São oito horas.','Oração sem sujeito'],['Falaram mal de você.','Indeterminado'],['A tropa e os civis ajudaram.','Composto'],['Vive-se bem no interior.','Indeterminado'],['Amanheceu nublado.','Oração sem sujeito'],['Os documentos foram entregues.','Simples']];
const TRANS=[['A vítima **morreu**.','Intransitivo'],['O bombeiro **resgatou** a criança.','Transitivo direto'],['Ele **precisa** de ajuda.','Transitivo indireto'],['Ele **entregou** o relatório ao chefe.','Transitivo direto e indireto'],['A equipe **estava** cansada.','De ligação'],['O prédio **parece** seguro.','De ligação'],['Todos **obedeceram** às ordens.','Transitivo indireto'],['A viatura **chegou**.','Intransitivo'],['O cadete **informou** o fato ao sargento.','Transitivo direto e indireto'],['Os alunos **continuam** atentos.','De ligação'],['O fogo **destruiu** o galpão.','Transitivo direto'],['Eu **gosto** de Física.','Transitivo indireto']];
const PRED=[['O fogo destruiu o galpão.','Verbal'],['A equipe estava cansada.','Nominal'],['Os bombeiros voltaram exaustos.','Verbo-nominal'],['O dia amanheceu frio.','Verbo-nominal'],['O prédio parece seguro.','Nominal'],['A equipe resgatou a vítima.','Verbal'],['Consideraram o cadete apto.','Verbo-nominal'],['O comandante permaneceu calado.','Nominal']];
const TERMOS=[
 ['O comandante|entregou|os certificados|aos cadetes|.',['suj','v','OD','OI']],['Os bombeiros|resgataram|a vítima|durante a madrugada|.',['suj','v','OD','AADV']],['A vítima|foi resgatada|pelos bombeiros|.',['suj','v','AP']],
 ['Curitiba|,|capital do Paraná|,|fica no planalto|.',['suj',null,'AP2',null,'pred']],['Soldado|,|venha|até aqui|.',['VOC',null,'v','AADV']],['A equipe|considerou|a missão|perigosa|.',['suj','v','OD','PO']],
 ['O cadete|estava|cansado|.',['suj','v','PS']],['Tenho|medo|de altura|.',['v','OD','CN']],['A casa|de madeira|pegou fogo|.',['suj','AADN','pred']],
 ['Os alunos|precisam|de mais tempo|.',['suj','v','OI']],['A resposta|ao ofício|chegou|ontem|.',['suj','CN','v','AADV']],['Os soldados|voltaram|exaustos|.',['suj','v','PS']]];
const TERMO_NOME={suj:'Sujeito',v:'Verbo',OD:'Objeto direto',OI:'Objeto indireto',AADV:'Adjunto adverbial',AP:'Agente da passiva',AP2:'Aposto',VOC:'Vocativo',PO:'Predicativo do objeto',PS:'Predicativo do sujeito',CN:'Complemento nominal',AADN:'Adjunto adnominal'};
const ORAC=[['Treinou muito, **porém se lesionou**.','Coordenada adversativa'],['Vá devagar, **que a pista está molhada**.','Coordenada explicativa'],['Estudou o edital; **portanto, sabe o conteúdo**.','Coordenada conclusiva'],['Não só treina, **mas também estuda**.','Coordenada aditiva'],['**Ora chove**, ora faz sol.','Coordenada alternativa'],['A equipe chegou **e isolou a área**.','Coordenada aditiva'],['O fogo cedeu, **contudo ainda havia fumaça**.','Coordenada adversativa'],['Os bombeiros **que atenderam a ocorrência** foram elogiados.','Subordinada adjetiva restritiva'],['O comandante, **que chegou cedo**, abriu a reunião.','Subordinada adjetiva explicativa'],['A viatura **em que viemos** quebrou.','Subordinada adjetiva restritiva'],['O Paraná, **cuja capital é Curitiba**, fica no Sul.','Subordinada adjetiva explicativa'],['Este é o edital **de que falei**.','Subordinada adjetiva restritiva'],['Estudou muito, **mas não passou**.','Coordenada adversativa'],['Estude, **pois a prova é amanhã**.','Coordenada explicativa'],['Choveu muito; **logo, o treino foi cancelado**.','Coordenada conclusiva'],['Ele treina **e estuda**.','Coordenada aditiva'],['**Ou você estuda**, ou não passa.','Coordenada alternativa'],
 ['Os candidatos **que estudaram** passaram.','Subordinada adjetiva restritiva'],['Curitiba, **que é a capital**, fica no planalto.','Subordinada adjetiva explicativa'],['É importante **que você estude**.','Subordinada substantiva subjetiva'],['Espero **que você passe**.','Subordinada substantiva objetiva direta'],['Tenho certeza **de que ele virá**.','Subordinada substantiva completiva nominal'],
 ['A verdade é **que ninguém sabia**.','Subordinada substantiva predicativa'],['Lembrou-se **de que havia prova**.','Subordinada substantiva objetiva indireta'],['**Quando o alarme tocou**, todos saíram.','Subordinada adverbial temporal'],['**Embora estivesse cansado**, estudou.','Subordinada adverbial concessiva'],['**Se estudar**, passará.','Subordinada adverbial condicional'],
 ['Estudou tanto **que passou**.','Subordinada adverbial consecutiva'],['Saiu cedo **porque estava atrasado**.','Subordinada adverbial causal'],['Estudou **para que fosse aprovado**.','Subordinada adverbial final'],['**Conforme o edital determina**, a prova terá 70 questões.','Subordinada adverbial conformativa'],['**À medida que o fogo avançava**, a equipe recuava.','Subordinada adverbial proporcional'],['Ele corre **como um atleta corre**.','Subordinada adverbial comparativa']];
function sxTermo(pickMode){ let g=0; while(g++<30){ const T=rP(TERMOS), parts=T[0].split('|'), tags=T[1]; const avail=tags.filter(t=>t&&t!=='v'&&t!=='pred'); const want=rP(avail); if(tags.filter(t=>t===want).length!==1) continue; const idx=tags.indexOf(want);
  const shown=parts.filter(p=>p!=='.'&&p!==','), fr=T[0].replace(/\|/g,' ').replace(/ ([.,])/g,'$1');
  if(pickMode) return arPick('Toque no termo que exerce a função de **'+TERMO_NOME[want].toLowerCase()+'**.',parts.slice(0,tags.length),idx,{x:'"'+parts[idx]+'" = '+TERMO_NOME[want].toLowerCase()+'.'});
  return arCh('Em “'+fr+'”, o termo **'+parts[idx]+'** é:',TERMO_NOME[want],Object.values(TERMO_NOME).filter(n=>n!==TERMO_NOME[want]&&n!=='Verbo'),{x:'"'+parts[idx]+'" = '+TERMO_NOME[want].toLowerCase()+'.'}); } }
arGame({id:'ar-port-sint',s:'port',t:'port-sint',nome:'Análise sintática',ic:'S+P',desc:'Sujeito, predicado, termos da oração e período composto.',lv:[
  {d:'Tipos de sujeito.',g:[clBank(SUJ,'Classifique o sujeito:')]},
  {d:'Transitividade verbal e tipos de predicado.',g:[clBank(TRANS,'O verbo destacado é:'),clBank(PRED,'O predicado é:')]},
  {d:'Termos da oração: objeto, adjunto, predicativo, aposto, vocativo.',g:[()=>sxTermo(true),()=>sxTermo(false)]},
  {d:'Orações coordenadas e adjetivas.',g:[clBank(ORAC.slice(0,19),'A oração destacada é:')]},
  {d:'Subordinadas substantivas e adverbiais.',g:[clBank(ORAC.slice(19),'A oração destacada é:'),()=>sxTermo(rC(.5))]}]});

/* ---------- PONTUAÇÃO ----------
   moldes: trechos separados por marcadores de vírgula: "/" obrigatória, "|" proibida, "~" facultativa */
const PONT=[
 ['Soldado / venha até aqui','Vocativo se isola por vírgula.'],['Venha até aqui / soldado','Vocativo se isola por vírgula.'],['Curitiba / capital do Paraná / fica no Primeiro Planalto','Aposto explicativo vem entre vírgulas.'],
 ['Zacarias de Góis / primeiro presidente da província / tomou posse em 1853','Aposto entre vírgulas.'],['Curitiba / que é a capital do estado / fica no planalto','Oração adjetiva explicativa: entre vírgulas.'],['Os candidatos | que estudaram | foram aprovados','Oração adjetiva restritiva: sem vírgula.'],
 ['Estudou muito / mas não passou na prova','Antes de conjunção adversativa: vírgula.'],['A equipe / porém / manteve o ritmo','Conjunção deslocada (intercalada): entre vírgulas.'],['Os candidatos / portanto / devem chegar cedo','"Portanto" intercalado: entre vírgulas.'],
 ['Levou mangueira / capacete / luvas | e lanterna','Enumeração: vírgula entre os itens; antes do "e" final, não.'],['Os candidatos aprovados na primeira fase do concurso | deverão apresentar os documentos','Sujeito (mesmo longo) não se separa do verbo.'],['Os bombeiros / durante a madrugada / controlaram o incêndio','Adjunto adverbial intercalado entre sujeito e verbo: entre vírgulas.'],
 ['Quando o alarme tocou / todos saíram','Oração adverbial anteposta: separa-se por vírgula.'],['Chegando ao local / a equipe isolou a área','Oração reduzida de gerúndio anteposta: vírgula.'],['Sim / o relatório foi entregue','"Sim" e "não" no início: vírgula.'],
 ['O oficial / isto é / o responsável pela operação / assinou o relatório','Expressão explicativa ("isto é"): entre vírgulas.'],['Eu prefiro Física / ele / Química','A vírgula marca a omissão do verbo (zeugma).'],['Chegaram | os novos equipamentos','Verbo e sujeito posposto: sem vírgula.'],
 ['O comandante | entregou | ao cadete | o certificado','Verbo e complementos: sem vírgula.'],['Durante o plantão ~ os bombeiros | atenderam três ocorrências','Adjunto adverbial curto anteposto: vírgula facultativa; sujeito e verbo, nunca.'],['Se chover / o treino será cancelado','Oração condicional anteposta: vírgula.'],
 ['A viatura | que estava na garagem | foi vistoriada','Adjetiva restritiva: sem vírgulas.'],['Paranaguá / 29 de julho de 1648','Local e data: vírgula.'],['Os alunos | precisam | de mais tempo','Verbo e objeto indireto: sem vírgula.']];
function pontParse(t){ const toks=t.split(/ ([\/|~]) /), ch=[], sl=[]; toks.forEach((x,i)=>{ if(i%2===0) ch.push(x); else sl.push(x==='/'?'must':x==='|'?'no':'opt'); }); ch[ch.length-1]+='.'; return {ch,sl}; }
function pontCommas(){ const T=rP(PONT), {ch,sl}=pontParse(T[0]); return arCommas('Toque nos espaços onde a vírgula é **obrigatória**. Deixe os outros vazios.',ch,sl,{x:T[1]+' Correto: “'+arCommaText(ch,sl.map(s=>s==='must'))+'”'}); }
function pontVer(ok){ const T=rP(PONT), {ch,sl}=pontParse(T[0]); let pat=sl.map(s=>s==='must');
  if(!ok){ const cand=sl.map((s,i)=>s!=='opt'?i:-1).filter(i=>i>=0); if(!cand.length) return pontVer(true); const i=rP(cand); pat=pat.slice(); pat[i]=!pat[i]; }
  return {text:arCommaText(ch,pat),ok,x:T[1]+(ok?'':' Correto: “'+arCommaText(ch,sl.map(s=>s==='must'))+'”')}; }
const PONT_TF=[['O ponto e vírgula pode separar orações coordenadas longas que já tenham vírgulas internas.',true],['Os dois-pontos podem introduzir uma enumeração, uma citação ou um esclarecimento.',true],['O travessão pode isolar uma explicação intercalada, como as vírgulas.',true],['As aspas servem para marcar citações diretas e palavras em sentido especial.',true],['Nunca se usa vírgula antes de "e".',false],['A oração adjetiva restritiva deve vir entre vírgulas.',false],['O vocativo pode ficar sem vírgula quando está no início da frase.',false],['A vírgula pode separar o sujeito do verbo quando o sujeito é longo.',false],['O ponto de exclamação pode encerrar frases imperativas enfáticas.',true],['Reticências indicam interrupção do pensamento ou suspensão da fala.',true]];
arGame({id:'ar-port-pont',s:'port',t:'port-pont',nome:'Vírgula certa',ic:',',desc:'Você mesmo coloca as vírgulas: vocativo, aposto, orações e as proibições.',lv:[
  {d:'A pontuação da frase está certa?',g:[()=>{ const v=pontVer(rC(.5)); return arTF('A pontuação está correta?\n“'+v.text+'”',v.ok,{x:v.x}); }]},
  {d:'Onde está a vírgula errada (ou faltando)?',g:[()=>{ const good=pontVer(true), bads=[pontVer(false),pontVer(false),pontVer(false),pontVer(false)]; return arCh('Assinale a frase com a pontuação **correta**.',good.text,bads.map(b=>b.text),{x:good.x}); }]},
  {d:'Coloque as vírgulas: casos básicos.',g:[()=>pontCommas()]},
  {d:'Alternativa com erro de pontuação.',g:[()=>{ const bad=pontVer(false), goods=[pontVer(true),pontVer(true),pontVer(true),pontVer(true)]; return arCh('Assinale a alternativa em que há **erro** de pontuação.',bad.text,goods.map(b=>b.text),{x:bad.x}); },()=>pontCommas()]},
  {d:'Vírgulas nos períodos longos e outros sinais.',g:[()=>pontCommas(),()=>{ const t=rP(PONT_TF); return arTF(t[0],t[1],{x:t[1]?'Correto.':'Incorreto.'}); }]}]});

/* ---------- COESÃO E CONECTIVOS ---------- */
const CON={
 'Adição':['e','além disso','também','ademais'],'Oposição (adversidade)':['mas','porém','contudo','todavia','entretanto','no entanto'],'Concessão':['embora','ainda que','mesmo que','conquanto','se bem que'],
 'Causa':['porque','visto que','já que','uma vez que','porquanto'],'Conclusão':['logo','portanto','por isso','por conseguinte','assim'],'Condição':['caso','desde que','contanto que'],'Finalidade':['para que','a fim de que'],
 'Tempo':['quando','assim que','logo que','mal'],'Conformidade':['conforme','segundo','consoante'],'Proporção':['à medida que','à proporção que'],'Consequência':['de modo que','de forma que','tanto que']};
const CON_FR={
 'Oposição (adversidade)':['A prova era difícil, {} ele estava preparado.','O fogo era intenso, {} a equipe não recuou.','Choveu a manhã inteira, {} o treino foi mantido.'],
 'Concessão':['{} a prova fosse difícil, ele estava preparado.','{} o fogo fosse intenso, a equipe não recuou.','{} chovesse muito, o treino foi mantido.'],
 'Causa':['O treino foi cancelado {} choveu muito.','A equipe recuou {} a estrutura estava comprometida.','Ele foi promovido {} se destacou na operação.'],
 'Conclusão':['Choveu muito; {}, o treino foi cancelado.','A estrutura estava comprometida; {}, a equipe recuou.','Ele estudou todos os dias; {}, foi aprovado.'],
 'Condição':['{} chova, o treino será cancelado.','{} a estrutura resista, a equipe entrará no prédio.','O candidato será aprovado {} atinja a nota mínima.'],
 'Finalidade':['Treinamos todos os dias {} a equipe esteja pronta.','Isolaram a área {} ninguém se ferisse.'],
 'Tempo':['{} o alarme tocou, todos saíram.','{} a viatura chegou, o fogo já estava controlado.'],
 'Conformidade':['{} determina o edital, a prova terá 70 questões.','{} informou o comando, a operação foi um sucesso.'],
 'Proporção':['{} o fogo avançava, a equipe recuava.','{} a água subia, os moradores deixavam as casas.']};
const REFER=[['Os bombeiros chegaram ao prédio. **Eles** isolaram a área em minutos.','os bombeiros','o prédio|a área|os moradores'],['A viatura quebrou na serra, o que atrasou o resgate. **Isso** preocupou o comando.','o atraso causado pela quebra da viatura','a serra|o comando|o resgate'],
 ['O edital e a portaria foram publicados. **Esta** trata do calendário.','a portaria','o edital|o calendário|a publicação'],['O edital e a portaria foram publicados. **Aquele** trata das vagas.','o edital','a portaria|as vagas|a publicação'],
 ['Zacarias chegou a Curitiba em 1853. **Ali**, instalou o governo da nova província.','Curitiba','a província|1853|o governo'],['A araucária produz o pinhão. **Sua** semente alimenta a gralha-azul.','da araucária','do pinhão|da gralha-azul|da floresta'],
 ['O sargento orientou o soldado para que **ele** revisasse o equipamento.','o soldado','o sargento|o equipamento|ambígua sem contexto'],['Choveu forte na madrugada. **O temporal** derrubou árvores.','a chuva forte da madrugada','as árvores|a madrugada|o vento']];
const conRel=()=>rP(Object.keys(CON_FR));
function conFill(){ const r=conRel(), fr=rP(CON_FR[r]), c=rP(CON[r]); const cap=fr.startsWith('{}'); const f=w=>cap?w[0].toUpperCase()+w.slice(1):w;
  const wr=Object.keys(CON_FR).filter(k=>k!==r).map(k=>f(rP(CON[k]))); return arCh('Complete com o conectivo que dá sentido à frase:\n'+fr.replace('{}','_____'),f(c),wr,{x:'A relação é de '+r.toLowerCase()+': "'+c+'".'}); }
function conSubst(alter){ const r=conRel(), fr=rP(CON_FR[r]), [a,b]=rN(CON[r],2); if(!b) return conFill(); const cap=fr.startsWith('{}'); const f=w=>cap?w[0].toUpperCase()+w.slice(1):w; const shown=fr.replace('{}','**'+f(a)+'**');
  const others=Object.keys(CON).filter(k=>k!==r&&k!=='Adição').map(k=>rP(CON[k]));
  if(!alter) return arCh(shown+'\nSem alterar o sentido, o conectivo destacado pode ser substituído por:',b,others,{x:'"'+a+'" e "'+b+'" expressam '+r.toLowerCase()+'.'});
  const same=CON[r].filter(x=>x!==a); if(same.length<3) return conSubst(false); return arCh(shown+'\nQual substituição **altera** o sentido da frase?',rP(others),rN(same,4),{x:'Os demais expressam '+r.toLowerCase()+', como "'+a+'".'}); }
arGame({id:'ar-port-coe',s:'port',t:'port-coe',nome:'Conectivos em ação',ic:'∴',desc:'A relação lógica de cada conectivo, substituições e retomadas.',lv:[
  {d:'Que relação o conectivo expressa?',g:[()=>{ const r=rP(Object.keys(CON)), c=rP(CON[r]); return arCh('Qual relação o conectivo **'+c+'** expressa?',r,Object.keys(CON).filter(k=>k!==r),{x:'"'+c+'": '+r.toLowerCase()+'.'}); }]},
  {d:'A relação na frase.',g:[()=>{ const r=conRel(), fr=rP(CON_FR[r]), c=rP(CON[r]); const cap=fr.startsWith('{}'); return arCh(fr.replace('{}','**'+(cap?c[0].toUpperCase()+c.slice(1):c)+'**')+'\nO conectivo destacado expressa:',r,Object.keys(CON).filter(k=>k!==r),{x:r+'.'}); },()=>arMatch('Ligue cada conectivo à relação que expressa.',rN(Object.keys(CON),4).map(r=>[rP(CON[r]),r]),{x:'Cada conectivo tem uma relação lógica própria.'})]},
  {d:'Substituição sem alterar o sentido.',g:[()=>conSubst(false)]},
  {d:'Complete com o conectivo adequado; retomada (coesão referencial).',g:[()=>conFill(),()=>{ const r=rP(REFER); return arCh(r[0]+'\nO termo destacado retoma:',r[1],r[2].split('|'),{x:'Retoma "'+r[1]+'".'}); }]},
  {d:'Qual troca altera o sentido; misto de prova.',g:[()=>conSubst(true),()=>conFill()]}]});

/* ---------- TIPOLOGIA E GÊNEROS ---------- */
const TIPOS=[
 ['Quando a equipe chegou, o fogo já havia tomado o segundo andar. O sargento subiu primeiro, encontrou a família no corredor e a conduziu até a escada.','Narrativo'],['Ele abriu a porta devagar, ouviu um estalo e recuou. Segundos depois, o teto desabou.','Narrativo'],['Em 1853, o Paraná separou-se de São Paulo. Meses depois, Zacarias chegou a Curitiba para assumir a província.','Narrativo'],
 ['O quartel é um prédio antigo, de paredes amarelas e janelas altas. No pátio, duas viaturas vermelhas brilham sob o sol da manhã.','Descritivo'],['A vítima era um homem alto, magro, de cabelos grisalhos e voz rouca.','Descritivo'],['A serra é íngreme, coberta por mata densa e cortada por riachos de água gelada.','Descritivo'],
 ['A prevenção é mais barata do que o combate. Por isso, investir em vistorias e educação deveria ser prioridade de todo município.','Dissertativo-argumentativo'],['Não basta aumentar o efetivo: sem treinamento contínuo, mais bombeiros não significam mais vidas salvas.','Dissertativo-argumentativo'],['É inaceitável que prédios públicos funcionem sem alvará; afinal, o poder público deveria dar o exemplo.','Dissertativo-argumentativo'],
 ['O tetraedro do fogo é formado por combustível, comburente, calor e reação em cadeia. Retirando-se um desses elementos, o fogo se extingue.','Expositivo'],['A araucária pode ultrapassar 30 metros de altura e produz o pinhão, semente rica em amido.','Expositivo'],['A hipotermia ocorre quando a temperatura do corpo cai abaixo de 35 °C.','Expositivo'],
 ['Retire o pino de segurança, aponte o bico para a base das chamas e aperte o gatilho.','Injuntivo'],['Em caso de incêndio, não use o elevador. Desça pelas escadas e mantenha-se abaixado.','Injuntivo'],['Misture a farinha com o açúcar e leve ao forno por 40 minutos.','Injuntivo']];
const TIPO_DEF=[['Usa verbos de ação no pretérito e marcadores de tempo (depois, naquela noite).','Narrativo'],['Predominam adjetivos e verbos de estado (ser, estar, parecer).','Descritivo'],['Tem tese, argumentos e conclusão.','Dissertativo-argumentativo'],['Usa conectivos de causa e conclusão para sustentar uma opinião.','Dissertativo-argumentativo'],['Define conceitos e apresenta dados de forma objetiva.','Expositivo'],['Aparece em manuais, receitas e regulamentos.','Injuntivo'],['Organiza-se em etapas numeradas ou em sequência de ordens.','Injuntivo'],['Tem enredo, clímax e desfecho.','Narrativo'],['Funciona como um retrato, parado no tempo.','Descritivo'],['Aparece em verbetes e textos didáticos.','Expositivo'],['Relata fatos em sequência, com personagens, tempo e espaço.','Narrativo'],['Retrata características de um ser, objeto ou lugar.','Descritivo'],['Defende um ponto de vista com argumentos.','Dissertativo-argumentativo'],['Apresenta informações e conceitos sem defender opinião.','Expositivo'],['Orienta o leitor a fazer algo, com verbos no imperativo.','Injuntivo']];
const GENEROS=[
 ['Um incêndio atingiu um galpão na Cidade Industrial de Curitiba na madrugada desta terça-feira. Segundo o Corpo de Bombeiros, não houve feridos.','Notícia'],['Querida mãe, cheguei bem ao curso de formação. A rotina é puxada, mas estou feliz. Com saudade, Pedro.','Carta pessoal'],
 ['Ofício nº 15/2025. Ao Senhor Comandante. Assunto: solicitação de viaturas. Senhor Comandante, solicito a Vossa Senhoria…','Ofício'],['João da Silva, cadete, vem respeitosamente requerer a revisão de sua nota. Nestes termos, pede deferimento.','Requerimento'],
 ['Ingredientes: 2 xícaras de farinha e 3 ovos. Modo de preparo: bata os ovos e acrescente a farinha aos poucos.','Receita'],['Posologia: 1 comprimido a cada 8 horas. Contraindicações: pacientes com hipersensibilidade ao princípio ativo.','Bula'],
 ['Em "O Cortiço", Aluísio Azevedo retrata a vida numa habitação coletiva. A obra, embora densa, prende o leitor. Leitura recomendada.','Resenha'],['Toda segunda-feira é igual: o café esfria antes de ser bebido, a caneta some e a gente jura que a semana vai ser diferente. Não é.','Crônica'],
 ['Chegou o novo capacete X-Pro: mais leve, mais seguro. Proteja quem protege você!','Anúncio publicitário'],['Vende-se casa, 3 quartos, garagem, próximo ao centro. Tratar pelo telefone.','Classificado'],
 ['Às 14h20, a guarnição foi acionada para atender colisão na BR-277. Foram atendidas duas vítimas, conduzidas ao hospital.','Relatório'],['Aos cinco dias do mês de maio, reuniram-se os membros da comissão… Nada mais havendo a tratar, lavrou-se a presente ata.','Ata'],
 ['Bombeiro (s.m.): profissional encarregado de combater incêndios e realizar salvamentos.','Verbete'],['Conta a lenda que a gralha-azul enterrava pinhões e, assim, espalhou as araucárias pelo Paraná.','Lenda'],
 ['A cigarra cantou o verão inteiro enquanto a formiga trabalhava. Quando o inverno chegou, faltou-lhe comida. Moral: previna-se.','Fábula'],['— Como começou sua carreira? — Entrei no Corpo de Bombeiros em 2005, como soldado.','Entrevista'],
 ['Na minha avaliação, a cidade precisa urgentemente de mais hidrantes. Defendo que cada bairro tenha ao menos um.','Artigo de opinião'],['Zacarias de Góis e Vasconcelos nasceu na Bahia, em 1815, e foi o primeiro presidente da Província do Paraná.','Biografia']];
const FUNC=[['O Paraná tem 399 municípios.','Referencial'],['A água ferve a 100 °C ao nível do mar.','Referencial'],['Que alegria imensa eu senti ao ver meu nome na lista!','Emotiva'],['Estou exausto, mas muito feliz.','Emotiva'],['Não deixe para amanhã: faça sua inscrição hoje!','Conativa (apelativa)'],['Você, motorista, respeite a faixa de pedestres.','Conativa (apelativa)'],
 ['Alô? Está me ouvindo? Câmbio.','Fática'],['— Oi, tudo bem? — Tudo, e você?','Fática'],['Substantivo é a palavra que nomeia seres e objetos.','Metalinguística'],['Neste poema, falo de como é difícil escrever um poema.','Metalinguística'],['O fogo dança, lambe a noite e devora o silêncio.','Poética'],['Pinheiro, sentinela do planalto, guarda no alto a coroa verde.','Poética']];
const genQ=(bank,q)=>()=>{ const it=rP(bank); return arCh('“'+it[0]+'”\n'+q,it[1],[...new Set(bank.map(x=>x[1]))].filter(x=>x!==it[1]),{x:'Trata-se de: '+it[1].toLowerCase()+'.'}); };
arGame({id:'ar-port-gen',s:'port',t:'port-gen',nome:'Detetive de gêneros',ic:'¶',desc:'Tipos textuais, gêneros e funções da linguagem a partir de trechos reais.',lv:[
  {d:'Os cinco tipos textuais pela definição.',g:[()=>{ const d=rP(TIPO_DEF); return arCh(d[0]+'\nEssa é a característica do tipo:',d[1],TIPO_DEF.filter(x=>x!==d).map(x=>x[1]),{x:d[1]+'.'}); }]},
  {d:'Qual tipo predomina no trecho?',g:[genQ(TIPOS,'O tipo textual predominante é:')]},
  {d:'Qual é o gênero do texto?',g:[genQ(GENEROS,'O trecho pertence ao gênero:')]},
  {d:'Funções da linguagem.',g:[genQ(FUNC,'A função da linguagem predominante é:')]},
  {d:'Misto: tipo, gênero e função, com classificação em lote.',g:[genQ(GENEROS,'O gênero é:'),genQ(FUNC,'A função predominante é:'),()=>arSort('Classifique o tipo predominante de cada trecho:',['Narrativo','Descritivo','Dissertativo-argumentativo','Expositivo','Injuntivo'],rN(TIPOS,4).map(t=>[t[0].slice(0,70)+'…',['Narrativo','Descritivo','Dissertativo-argumentativo','Expositivo','Injuntivo'].indexOf(t[1])]),{x:'Narrar: fatos em sequência. Descrever: características. Argumentar: opinião com argumentos. Expor: informar. Injunção: instruir.'})]}]});

/* ---------- INTERPRETAÇÃO DE TEXTO ----------
   Cada texto traz: o que está escrito (af), o que se pode inferir (inf) e o que não se pode afirmar (no). */
const TEXTOS=[
 {tx:'A maior parte dos incêndios residenciais começa na cozinha, e o óleo quente é o principal vilão. Jogar água numa panela em chamas provoca uma explosão de vapor que espalha o fogo. O correto é desligar o fogo e abafar a panela com uma tampa. Bombeiros alertam que, nesses casos, segundos de calma valem mais do que qualquer extintor.',
  af:['Jogar água em óleo quente em chamas espalha o fogo.','O correto é desligar o fogo e tampar a panela.','A cozinha é onde começa a maior parte dos incêndios residenciais.'],inf:['Conhecer o procedimento correto pode evitar que um pequeno fogo se torne um incêndio.','Muitas pessoas reagem de forma errada diante de uma panela em chamas.'],
  no:['Os extintores são inúteis em incêndios de cozinha.','A maioria dos incêndios é causada por curto-circuito.','Óleo quente nunca deve ser usado para cozinhar.'],tema:'A forma correta de agir diante do fogo em óleo de cozinha',temaW:['A proibição do uso de óleo nas cozinhas','A importância dos extintores em residências','A estatística dos incêndios no Brasil'],voc:['vilão','causador principal do problema','herói da história|ingrediente mais caro|personagem de ficção']},
 {tx:'A araucária, símbolo do Paraná, já cobriu cerca de um terço do território do estado. A exploração intensa da madeira no século XX reduziu drasticamente essas florestas. Hoje, a espécie está ameaçada de extinção, e seu corte é proibido por lei. A gralha-azul, ao enterrar pinhões para comer depois, ajuda a espalhar novas árvores.',
  af:['A araucária está ameaçada de extinção.','O corte da araucária é proibido por lei.','A gralha-azul enterra pinhões.'],inf:['A exploração econômica da madeira teve impacto ambiental duradouro.','Parte dos pinhões enterrados pela gralha-azul não é consumida e germina.'],
  no:['A gralha-azul é a única responsável pelo plantio de araucárias.','A araucária é encontrada apenas no Paraná.','A exploração da madeira ainda é a principal atividade econômica do estado.'],tema:'A redução das florestas de araucária e a importância da sua preservação',temaW:['A alimentação da gralha-azul','A economia paranaense no século XX','A legislação ambiental brasileira'],voc:['drasticamente','de forma intensa, severa','de modo lento|de forma leve|de maneira ilegal']},
 {tx:'Dormir pouco na véspera da prova é um erro comum. Durante o sono, o cérebro consolida o que foi estudado ao longo do dia, transformando informações recentes em memórias duradouras. Quem troca a noite de sono por mais algumas horas de revisão costuma lembrar menos, e não mais. O descanso, portanto, faz parte do estudo.',
  af:['O cérebro consolida memórias durante o sono.','Dormir pouco na véspera da prova é um erro comum.'],inf:['Estudar a noite toda antes da prova tende a prejudicar o desempenho.','O autor recomenda organizar os estudos para não sacrificar o sono.'],
  no:['Quem dorme mais de dez horas tira notas melhores.','Revisar o conteúdo é inútil.','Todos os candidatos dormem mal antes da prova.'],tema:'A importância do sono para a memória e para o estudo',temaW:['Técnicas de revisão rápida','Os distúrbios do sono','A ansiedade antes das provas'],voc:['consolida','fortalece, torna estável','apaga|esquece|mistura']},
 {tx:'Em 1853, o Paraná deixou de ser a 5ª Comarca de São Paulo e tornou-se província. A emancipação atendia a antigas reivindicações das elites locais, mas também interessava ao Império, que queria controlar melhor a região sul e o caminho das tropas. Curitiba foi escolhida como capital, e Zacarias de Góis e Vasconcelos, o primeiro presidente.',
  af:['Curitiba foi escolhida como capital da nova província.','Antes de 1853, o Paraná era a 5ª Comarca de São Paulo.','Zacarias de Góis e Vasconcelos foi o primeiro presidente da província.'],inf:['A emancipação também tinha motivações estratégicas para o governo imperial.','Havia grupos locais interessados na separação antes de 1853.'],
  no:['A emancipação foi obtida por meio de uma revolução armada.','Paranaguá foi a primeira capital da província.','O Império se opôs à criação da nova província.'],tema:'A emancipação política do Paraná e seus interesses',temaW:['A vida de Zacarias de Góis','O tropeirismo nos Campos Gerais','A fundação de Curitiba'],voc:['reivindicações','pedidos, exigências','protestos armados|leis aprovadas|festas populares']},
 {tx:'O trote telefônico para o 193 não é uma brincadeira inofensiva. Cada chamada falsa ocupa a linha e pode deslocar uma viatura para um endereço sem ocorrência, enquanto alguém realmente precisa de socorro. Além disso, a prática pode ser enquadrada como crime. Educar crianças e adolescentes sobre o uso correto do número é a melhor forma de prevenção.',
  af:['Chamadas falsas podem deslocar viaturas sem necessidade.','O trote pode ser considerado crime.','Educar jovens é apontado como a melhor forma de prevenção.'],inf:['Os trotes podem atrasar o atendimento de emergências reais.','Parte dos trotes é feita por crianças e adolescentes.'],
  no:['Todos os trotes são feitos por adolescentes.','O número 193 deixará de funcionar por causa dos trotes.','As viaturas só são enviadas após confirmação presencial.'],tema:'Os prejuízos causados pelos trotes ao número de emergência',temaW:['A história do número 193','A punição de adolescentes','A tecnologia das centrais telefônicas'],voc:['inofensiva','que não causa dano','perigosa|engraçada|proibida']},
 {tx:'As enchentes urbanas não dependem apenas da quantidade de chuva. Quando o solo é impermeabilizado por asfalto e concreto, a água não infiltra e escoa rapidamente para as partes baixas. Lixo nos bueiros agrava o problema. Por isso, áreas verdes e drenagem adequada são tão importantes quanto obras de contenção.',
  af:['Solo impermeabilizado dificulta a infiltração da água.','Lixo nos bueiros agrava as enchentes.'],inf:['Cidades muito pavimentadas tendem a sofrer mais com alagamentos.','A ação dos moradores também influencia a ocorrência de enchentes.'],
  no:['Obras de contenção são desnecessárias.','Só há enchentes em cidades grandes.','A quantidade de chuva não influencia as enchentes.'],tema:'Os fatores urbanos que contribuem para as enchentes',temaW:['A previsão do tempo','A coleta seletiva de lixo','O asfaltamento das rodovias'],voc:['agrava','piora','resolve|explica|causa sozinho']},
 {tx:'O primeiro atendimento a uma vítima de parada cardíaca é decisivo. A cada minuto sem massagem cardíaca, as chances de sobrevivência caem. Leigos treinados podem iniciar as compressões até a chegada do socorro especializado. Por isso, cursos de primeiros socorros para a população salvam vidas que as ambulâncias, sozinhas, não alcançariam a tempo.',
  af:['Leigos treinados podem iniciar as compressões.','As chances de sobrevivência caem a cada minuto sem massagem cardíaca.'],inf:['O tempo de chegada das ambulâncias pode ser longo demais em alguns casos.','Treinar a população amplia a rede de socorro.'],
  no:['Leigos podem substituir completamente o socorro especializado.','Toda parada cardíaca é fatal.','As ambulâncias são desnecessárias.'],tema:'A importância do atendimento imediato e do treinamento da população',temaW:['O funcionamento das ambulâncias','As causas da parada cardíaca','A formação dos médicos'],voc:['decisivo','determinante','opcional|lento|posterior']},
 {tx:'O café transformou o norte do Paraná a partir dos anos 1920. Companhias colonizadoras dividiram a terra em pequenos lotes, e cidades como Londrina e Maringá surgiram em poucas décadas. A geada de 1975, porém, destruiu grande parte dos cafezais, e muitos produtores migraram para outras culturas, como a soja.',
  af:['A geada de 1975 destruiu grande parte dos cafezais.','Londrina e Maringá surgiram no contexto da expansão cafeeira.'],inf:['A geada acelerou mudanças na agricultura do norte do Paraná.','A venda de pequenos lotes atraiu muitos migrantes para a região.'],
  no:['O café deixou de ser plantado no Paraná após 1975.','A soja foi introduzida no Brasil pelo Paraná.','Londrina e Maringá foram fundadas pelo governo federal.'],tema:'A ascensão e a crise do café no norte do Paraná',temaW:['A história da soja','A fundação de Curitiba','O clima do Paraná'],voc:['colonizadoras','que promoviam o povoamento','exportadoras|agrícolas|estatais']}];
function itTxt(t){ return '**Texto:**\n'+t.tx; }
arGame({id:'ar-port-int',s:'port',t:'port-int',nome:'Leitor de elite',ic:'“ ”',desc:'Informação explícita, inferência, extrapolação e tema, como a banca cobra.',lv:[
  {d:'Segundo o texto: a informação está escrita.',g:[()=>{ const t=rP(TEXTOS); return arCh(itTxt(t)+'\n\nSegundo o texto, é correto afirmar que:',rP(t.af),t.no,{x:'Está escrito no texto. As demais extrapolam ou contradizem o texto.'}); },()=>{ const t=rP(TEXTOS), ok=rC(.5); return arTF(itTxt(t)+'\n\nO texto afirma: “'+(ok?rP(t.af):rP(t.no))+'”',ok,{x:ok?'Está no texto.':'O texto não diz isso.'}); }]},
  {d:'Vocabulário no contexto e tema central.',g:[()=>{ const t=rP(TEXTOS); return arCh(itTxt(t)+'\n\nNo texto, a palavra **'+t.voc[0]+'** significa:',t.voc[1],t.voc[2].split('|'),{x:'No contexto: '+t.voc[1]+'.'}); },()=>{ const t=rP(TEXTOS); return arCh(itTxt(t)+'\n\nO tema central do texto é:',t.tema,t.temaW,{x:t.tema+'.'}); }]},
  {d:'Inferência: o que se conclui, sem estar escrito.',g:[()=>{ const t=rP(TEXTOS); return arCh(itTxt(t)+'\n\nPode-se **inferir** do texto que:',rP(t.inf),t.no,{x:'É uma conclusão apoiada no texto. As outras extrapolam.'}); }]},
  {d:'Assinale a INCORRETA; o que não se pode afirmar.',g:[()=>{ const t=rP(TEXTOS); return arCh(itTxt(t)+'\n\nDe acordo com o texto, é **incorreto** afirmar que:',rP(t.no),t.af.concat(t.inf),{x:'Essa afirmação não se sustenta no texto.'}); }]},
  {d:'Classifique: escrito, inferível ou extrapolação.',g:[()=>{ const t=rP(TEXTOS); const it=rN(t.af,2).map(s=>[s,0]).concat(rN(t.inf,1).map(s=>[s,1]),rN(t.no,2).map(s=>[s,2])); return arSort(itTxt(t)+'\n\nClassifique cada afirmação:',['Está no texto','Pode-se inferir','Não se pode afirmar'],rS(it),{x:'Explícito: está escrito. Inferência: conclusão apoiada no texto. Extrapolação: vai além do que o texto permite.'}); }]}]});
