
/* ===================== ARENA: MATEMÁTICA =====================
   Tudo gerado: números novos a cada rodada, com os erros típicos como alternativas
   e a resolução passo a passo. Nos níveis altos, parte das rodadas pede a resposta digitada. */
const M={};
const mg=(id,t,nome,ic,desc,lv)=>arGame({id,s:'mat',t,nome,ic,desc,lv});

/* ---------- operações: frações, potências, raízes ---------- */
M.ops=[
 ()=>{ const d=rP([2,3,4,5,8,10]), n=rI(1,d-1), tot=d*rI(2,12), a=tot*n/d; return arNum('Quanto é '+n+'/'+d+' de '+tot+'?',a,{d:0,c:[tot/d,tot*n,a+tot/d],steps:[tot+' ÷ '+d+' = '+(tot/d),(tot/d)+' × '+n+' = '+a]}); },
 ()=>{ const d=rI(3,12), a=rI(1,d-1), b=rI(1,d-1); return arCh('Calcule '+a+'/'+d+' + '+b+'/'+d+'.',fFr(a+b,d),[fFr(a+b,2*d),fFr(a*b,d),a+b+'/'+(2*d),fFr(a+b+1,d)],{x:'Mesmo denominador: some os numeradores e conserve o denominador.'}); },
 ()=>{ const b=rP([2,3,5,10]), x=rI(1,4), y=rI(1,3); return arNum('Calcule '+b+sq(x)+' × '+b+sq(y)+'.',Math.pow(b,x+y),{d:0,c:[Math.pow(b,x*y),b*(x+y),Math.pow(b,x)+Math.pow(b,y)],steps:['Mesma base: some os expoentes → '+b+sq(x+y),'= '+Math.pow(b,x+y)]}); }];
M.ops2=[
 ()=>{ const [d1,d2]=rN([2,3,4,5,6,8,10,12],2), a=rI(1,d1-1)||1, b=rI(1,d2-1)||1, D=lcm(d1,d2), N=a*D/d1+b*D/d2; return arCh('Calcule '+a+'/'+d1+' + '+b+'/'+d2+'.',fFr(N,D),[fFr(a+b,d1+d2),fFr(a*b,d1*d2),fFr(N+1,D),fFr(a*d2+b*d1+d1,d1*d2)],{x:'MMC('+d1+', '+d2+') = '+D+'. '+a+'/'+d1+' = '+(a*D/d1)+'/'+D+' e '+b+'/'+d2+' = '+(b*D/d2)+'/'+D+'. Soma: '+N+'/'+D+(gcd(N,D)>1?' = '+fFr(N,D):'')+'.'}); },
 ()=>{ const [a,b]=[rI(2,9)*rP([2,3,4,6]),rI(2,9)*rP([2,3,5])]; return arNum('Qual é o MMC de '+a+' e '+b+'?',lcm(a,b),{d:0,c:[a*b,gcd(a,b),lcm(a,b)*2],steps:['Fatore os dois números e multiplique os fatores com os maiores expoentes.','MMC = '+lcm(a,b)]}); },
 ()=>{ const g=rP([2,3,4,5,6,8,12]), a=g*rI(2,9), b=g*rI(2,9); if(gcd(a,b)!==g&&rC(.5)) return M.ops2[1](); return arNum('Qual é o MDC de '+a+' e '+b+'?',gcd(a,b),{d:0,c:[lcm(a,b),Math.min(a,b),g*2],steps:['Maior divisor comum aos dois números.','MDC = '+gcd(a,b)]}); },
 ()=>{ const a=rI(2,9), b=rI(2,9), c=rI(2,9); return arCh('Calcule '+a+'/'+b+' ÷ '+c+'/'+b+'.',fFr(a,c),[fFr(a*c,b*b),fFr(a*b,c),fFr(c,a)],{x:'Divisão de frações: conserve a primeira e multiplique pelo inverso da segunda: '+a+'/'+b+' × '+b+'/'+c+' = '+fFr(a,c)+'.'}); }];
M.ops3=[
 ()=>{ const b=rP([2,3,5,10]), e=rI(1,3); return arCh('Quanto vale '+b+sq('-'+e)+'?','1/'+Math.pow(b,e),['−'+Math.pow(b,e),String(-b*e),'1/'+(b*e),String(Math.pow(b,e))],{x:'Expoente negativo: inverta a base. '+b+sq('-'+e)+' = 1/'+b+sq(e)+' = 1/'+Math.pow(b,e)+'.'}); },
 ()=>{ const k=rP([2,3,4,5,6,7,10]), m=rP([2,3,5,6,7]), n=k*k*m; return arCh('Simplifique √'+n+'.',k+'√'+m,[(k*k)+'√'+m,m+'√'+k,k+'√'+(m*2),'√'+(k+m)],{x:n+' = '+(k*k)+' × '+m+'. √'+(k*k)+' = '+k+', então √'+n+' = '+k+'√'+m+'.'}); },
 ()=>{ const b=rP([4,8,9,16,25,27,32,64]); const r={4:[2,'1/2'],8:[2,'1/3'],9:[3,'1/2'],16:[2,'1/4'],25:[5,'1/2'],27:[3,'1/3'],32:[2,'1/5'],64:[4,'1/3']}[b]; return arNum('Calcule '+b+'^('+r[1]+').',r[0],{d:0,c:[b/2,b/3,r[0]*2],steps:['Expoente fracionário 1/n = raiz de índice n.','Raiz de '+b+' com índice '+r[1].split('/')[1]+' = '+r[0]]}); },
 ()=>{ const x=rI(2,5), y=rI(2,5), b=rP([2,3]); return arNum('Calcule ('+b+sq(x)+')'+sq(y)+' ÷ '+b+sq(x*y-1)+'.',b,{d:0,c:[Math.pow(b,2),1,b*x*y],steps:['Potência de potência: multiplique os expoentes → '+b+sq(x*y),'Divisão de mesma base: subtraia → '+b+sq(1)+' = '+b]}); }];
M.ops4=[
 ()=>{ const a=rI(2,9), b=rI(2,9), c=rI(2,6), d=rI(1,9); const v=a+b*c-d; return arNum('Calcule '+a+' + '+b+' × '+c+' − '+d+'.',v,{d:0,neg:true,c:[(a+b)*c-d,a+b*(c-d),v+d*2],steps:['Primeiro a multiplicação: '+b+' × '+c+' = '+(b*c),'Depois, da esquerda para a direita: '+a+' + '+(b*c)+' − '+d+' = '+v]}); },
 ()=>{ const a=rI(2,6), b=rI(2,6), c=rI(1,5), e=rI(2,3); const v=Math.pow(a,e)-(b+c)*2; return arNum('Calcule '+a+sq(e)+' − ('+b+' + '+c+') × 2.',v,{d:0,neg:true,c:[Math.pow(a,e)-b+c*2,(Math.pow(a,e)-b-c)*2,a*e-(b+c)*2],steps:['Potência: '+a+sq(e)+' = '+Math.pow(a,e),'Parênteses: '+(b+c)+'; vezes 2 = '+((b+c)*2),'Resultado: '+v]}); },
 ()=>{ const m=rI(11,99)/10, e=rP([-5,-4,-3,3,4,5,6]); const val=Number((m*Math.pow(10,e)).toPrecision(2)); const dec=val.toLocaleString('pt-BR',{maximumFractionDigits:10}); const f=(a,b)=>fN(a,1)+' × 10'+sq(b); return arCh('Escreva '+dec+' em notação científica.',f(m,e),[f(m,e+1),f(m,e-1),f(m*10,e-1),f(m,-e)],{x:'Um número entre 1 e 10 vezes uma potência de 10: '+f(m,e)+'.'}); }];
M.ops5=[
 ()=>{ const tot=rP([60,120,180,240,360,480,600]), f1=rP([[1,3],[1,4],[1,2],[2,5]]), f2=rP([[1,2],[1,3],[1,4]]); const g1=tot*f1[0]/f1[1], rest=tot-g1, g2=rest*f2[0]/f2[1], sobra=rest-g2; if(sobra%1||g2%1) return M.ops5[1]();
   return arNum('Um tanque tinha '+tot+' L. Gastou-se '+f1[0]+'/'+f1[1]+' dele e, depois, '+f2[0]+'/'+f2[1]+' do que restou. Quantos litros sobraram?',sobra,{d:0,u:'L',c:[tot-g1-tot*f2[0]/f2[1],g2,rest],steps:[f1[0]+'/'+f1[1]+' de '+tot+' = '+g1+' → restam '+rest,f2[0]+'/'+f2[1]+' de '+rest+' = '+g2+' → sobram '+sobra+' L']}); },
 ()=>{ const r=rP([2,3,5,6,7]), k=rP([2,3,4,5]); return arCh('Racionalize '+k+'/√'+r+'.',(k%r===0?(k/r)+'√'+r:k+'√'+r+'/'+r),[k+'/'+r,k+'√'+r,'√'+r+'/'+k,(k*r)+'/√'+r],{x:'Multiplique numerador e denominador por √'+r+': '+k+'√'+r+'/'+r+'.'}); },
 ()=>{ const a=rI(2,5)*1e3, b=rP([2,4,5])*1e-3; return arCh('Calcule ('+fN(a,0)+') × ('+fN(b,3)+') em notação científica.',fN(a*b/Math.pow(10,Math.floor(Math.log10(a*b))),2)+' × 10'+sq(Math.floor(Math.log10(a*b))),[fN(a*b,2)+' × 10'+sq(3),fN(a*b/Math.pow(10,Math.floor(Math.log10(a*b))),2)+' × 10'+sq(Math.floor(Math.log10(a*b))+1),fN(a*b/Math.pow(10,Math.floor(Math.log10(a*b))),2)+' × 10'+sq(-3)],{x:'Resultado: '+fN(a*b,3)+'.'}); }];
mg('ar-mat-ops','mat-ops','Cálculo de quartel','√','Frações, MMC/MDC, potências, raízes, expressões e notação científica.',[
 {d:'Fração de quantidade, soma de frações simples, potências de mesma base.',g:M.ops},{d:'MMC, MDC, frações com denominadores diferentes, divisão de frações.',g:M.ops2},{d:'Expoente negativo e fracionário, simplificação de raízes.',g:M.ops3},{d:'Expressões numéricas e notação científica.',g:M.ops4},{d:'Problemas com frações do restante, racionalização.',g:M.ops5}]);

/* ---------- razão, proporção, regra de três ---------- */
mg('ar-mat-prop','mat-prop','Regra de três tática','∝','Razão, escala, regra de três simples, inversa, composta e divisão proporcional.',[
 {d:'Razão e escala.',g:[()=>{ const e=rP([100,200,500,1000,5000]), c=rI(2,15); return arNum('Num mapa na escala 1:'+fN(e,0)+', uma distância de '+c+' cm corresponde a quantos metros reais?',c*e/100,{d:1,u:'m',c:[c*e,c*e/10,c*e/1000],steps:['1 cm no mapa = '+fN(e,0)+' cm reais','×'+c+' = '+fN(c*e,0)+' cm = '+fN(c*e/100,1)+' m']}); },()=>{ const a=rI(2,9)*rP([2,3]), b=rI(2,9)*rP([2,3]); return arCh('Qual a razão entre '+a+' e '+b+', na forma simplificada?',fFr(a,b).replace('/',' : '),[fFr(b,a).replace('/',' : '),a+' : '+(a+b),fFr(a+1,b).replace('/',' : ')],{x:a+'/'+b+' = '+fFr(a,b)+'.'}); }]},
 {d:'Regra de três simples direta.',g:[()=>{ const k=rI(2,12), a=rI(2,8), b=a+rI(1,7); return arNum(a+' metros de mangueira custam R$ '+(k*a)+'. Quanto custam '+b+' metros?',k*b,{d:0,u:'reais',c:[k*a*a/b,k*a+b,k*b+k],steps:['Direta: mais metros, mais caro.','1 m = '+k+' reais','× '+b+' = '+(k*b)]}); },()=>{ const lpm=rP([200,300,400,500,600]), t=rI(2,9); return arNum('Uma bomba lança '+lpm+' litros em 1 minuto. Quantos litros lança em '+t+' minutos?',lpm*t,{d:0,u:'L',c:[lpm/t,lpm+t,lpm*(t+1)],steps:[lpm+' × '+t+' = '+(lpm*t)]}); }]},
 {d:'Regra de três inversa.',g:[()=>{ const [n1,h1,n2,h2]=rP([[2,6,3,4],[3,8,4,6],[4,6,6,4],[6,4,8,3],[5,12,6,10],[4,9,6,6],[3,10,5,6],[2,9,6,3],[4,15,6,10],[8,3,6,4]]); return arNum(n1+' bombeiros fazem um rescaldo em '+h1+' h. Em quanto tempo '+n2+' bombeiros fariam o mesmo serviço, no mesmo ritmo?',h2,{d:0,u:'h',c:[h1*n2/n1,h1+n2-n1,h1-1],steps:['Inversa: mais gente, menos tempo.',n1+' × '+h1+' = '+(n1*h1)+' bombeiro-horas',(n1*h1)+' ÷ '+n2+' = '+h2+' h']}); },()=>{ const v1=rP([40,50,60,80]), t1=rP([3,4,6]), v2=rP([60,80,100,120]); const t2=v1*t1/v2; if(t2%0.5) return M.inv(); return arNum('Uma viatura a '+v1+' km/h leva '+t1+' h num trajeto. A '+v2+' km/h, quanto tempo levaria?',t2,{d:1,u:'h',c:[t1*v2/v1,t1+1,t2*2]}); }]},
 {d:'Regra de três composta.',g:[()=>M.comp(),()=>{ for(let t=0;t<80;t++){ const m1=rI(2,6), k1=rI(2,9)*100, m2=rI(2,8), dd=rP([2,3,4,5]); const k2=k1*m2*dd/(m1*2); if(k2%1||m1===m2) continue; return arNum(m1+' mangueiras lançam '+k1+' L em 2 min. Quantos litros '+m2+' mangueiras iguais lançam em '+dd+' min?',k2,{d:0,u:'L',c:[k1*m2/m1,k1*dd/2,k1*m1*dd/(m2*2)],steps:['Mais mangueiras e mais tempo → mais litros (as duas diretas).',k1+' × ('+m2+'/'+m1+') × ('+dd+'/2) = '+k2]}); } return M.comp(); },()=>{ const [a,d1,h1,b,d2]=rP([[4,6,8,6,4],[3,10,6,5,4],[5,8,6,4,6],[6,5,8,4,6],[2,12,5,4,5]]); const h2=h1*a*d1/(b*d2); if(h2%1) return M.comp(); return arNum(a+' bombeiros, trabalhando '+d1+' h por dia, fazem uma vistoria em '+h1+' dias. Quantos dias '+b+' bombeiros, trabalhando '+d2+' h por dia, levariam?',h2,{d:0,u:'dias',c:[h1*b*d2/(a*d1),h1*a/b,h1*d1/d2],steps:['Mais bombeiros → menos dias (inversa); mais horas/dia → menos dias (inversa).','Dias = '+h1+' × ('+a+'/'+b+') × ('+d1+'/'+d2+') = '+h2]}); }]},
 {d:'Divisão proporcional direta e inversa.',g:[()=>{ const [p,q,r]=rP([[2,3,5],[1,2,3],[3,4,5],[2,5,3]]), k=rP([100,200,300,500,1000]); const tot=(p+q+r)*k; return arNum('R$ '+fN(tot,0)+' serão divididos em partes diretamente proporcionais a '+p+', '+q+' e '+r+'. Quanto recebe a maior parte?',Math.max(p,q,r)*k,{d:0,u:'reais',c:[tot/3,Math.min(p,q,r)*k,tot/Math.max(p,q,r)],steps:['Soma das partes: '+(p+q+r),'Constante: '+fN(tot,0)+' ÷ '+(p+q+r)+' = '+k,'Maior: '+Math.max(p,q,r)+' × '+k]}); },()=>{ const tot=rP([90,180,360,540]); return arNum(fN(tot,0)+' horas de plantão serão divididas em partes inversamente proporcionais a 2, 3 e 6. Qual a maior parte?',tot/2,{d:0,u:'h',c:[tot/6,tot/3,tot*6/11],steps:['Inversamente a 2, 3 e 6 = diretamente a 1/2, 1/3 e 1/6 = 3, 2 e 1 (×6).','Soma 6 → constante '+(tot/6),'Maior: 3 × '+(tot/6)+' = '+(tot/2)]}); }]}]);
M.inv=()=>AR_BY['ar-mat-prop'].lv[2].g[0]();
M.comp=()=>{ for(let t=0;t<80;t++){ const a=rI(2,8), b=rI(2,8), d1=rP([4,5,6,8]), d2=rP([4,5,6,8,10]), h1=rI(3,15); const h2=h1*a*d1/(b*d2); if(a===b&&d1===d2) continue; if(h2%1===0&&h2>0) return arNum(a+' bombeiros, trabalhando '+d1+' h por dia, fazem uma vistoria em '+h1+' dias. Quantos dias '+b+' bombeiros, trabalhando '+d2+' h por dia, levariam?',h2,{d:0,u:'dias',c:[h1*b*d2/(a*d1),h1*a/b,h1*d1/d2],steps:['Mais gente e mais horas por dia → menos dias (as duas inversas).','Dias = '+h1+' × ('+a+'/'+b+') × ('+d1+'/'+d2+') = '+h2]}); } return arNum('4 bombeiros, 6 h por dia, 9 dias. E 6 bombeiros, 4 h por dia?',9,{d:0,u:'dias',c:[6,13.5,4]}); };

/* ---------- porcentagem e juros ---------- */
mg('ar-mat-porc','mat-porc','Porcentagem e juros','%','Porcentagem, aumentos, descontos, variação, juros simples e compostos.',[
 {d:'x% de um valor.',g:[()=>{ const p=rP([5,10,12,15,20,25,30,40,75]), v=rP([80,120,160,200,240,300,400,500,600,800]); return arNum('Quanto é '+p+'% de '+v+'?',v*p/100,{d:1,c:[v/p,v*p/10,v*p/1000],steps:[v+' × '+p+'/100 = '+fN(v*p/100,1)]}); },()=>{ const t=rP([20,25,40,50,80]), p=rP([10,20,25,50,75]); return arNum('Numa turma de '+t+' cadetes, '+p+'% são mulheres. Quantas mulheres há?',t*p/100,{d:0,c:[p,t-t*p/100,t*p/10]}); }]},
 {d:'Aumento e desconto.',g:[()=>{ const p=rP([10,15,20,25,30]), v=rP([100,200,250,400,500,800,1000]), up=rC(.5), a=v*(1+(up?1:-1)*p/100); return arNum('Um equipamento custava R$ '+fN(v,0)+' e teve '+(up?'aumento':'desconto')+' de '+p+'%. Qual o novo preço?',a,{d:2,u:'reais',c:[v*p/100,v*(1+(up?-1:1)*p/100),v+(up?p:-p)],steps:['Multiplique por '+fN(1+(up?1:-1)*p/100,2),fN(v,0)+' × '+fN(1+(up?1:-1)*p/100,2)+' = '+fN(a,2)]}); }]},
 {d:'Aumentos sucessivos e variação percentual.',g:[()=>{ const a=rP([10,20,25,50]), b=rP([10,20,25,50]); const tot=((1+a/100)*(1+b/100)-1)*100; return arNum('Um preço sobe '+a+'% e depois mais '+b+'%. Qual o aumento total?',tot,{d:1,u:'%',c:[a+b,a*b/100,tot+1],steps:['Fatores: '+fN(1+a/100,2)+' × '+fN(1+b/100,2)+' = '+fN(1+tot/100,4),'Aumento: '+fN(tot,1)+'%']}); },()=>{ const v1=rP([40,50,80,100,200]), p=rP([10,20,25,50,75]); const v2=v1*(1+p/100); return arNum('Um valor passou de '+v1+' para '+fN(v2,1)+'. Qual foi o aumento percentual?',p,{d:0,u:'%',c:[v2-v1,(v2-v1)/v2*100,p/2]}); },()=>{ const p=rP([10,20,25,50]); return arNum('Um produto subiu '+p+'% e depois caiu '+p+'%. Qual a variação total (negativo = queda)?',((1+p/100)*(1-p/100)-1)*100,{d:2,u:'%',neg:true,c:[0,-p,p*p/100]}); }]},
 {d:'Juros simples; valor antes do desconto.',g:[()=>{ const C=rP([500,1000,2000,5000]), i=rP([1,2,3,5]), t=rI(2,12), J=C*i*t/100; return arNum('Qual o juro simples de R$ '+fN(C,0)+' a '+i+'% ao mês durante '+t+' meses?',J,{d:0,u:'reais',c:[C*i/100,J+C,C*i*t/10],steps:['J = C · i · t',fN(C,0)+' × '+i+'/100 × '+t+' = '+fN(J,0)]}); },()=>{ const p=rP([10,20,25,40]), v=rP([100,200,300,400,500,600]); const pago=v*(1-p/100); return arNum('Após desconto de '+p+'%, um item saiu por R$ '+fN(pago,2)+'. Qual era o preço original?',v,{d:2,u:'reais',c:[pago*(1+p/100),pago+p,pago/(p/100)],steps:['Preço × '+fN(1-p/100,2)+' = '+fN(pago,2),'Preço = '+fN(pago,2)+' ÷ '+fN(1-p/100,2)+' = '+fN(v,2)]}); }]},
 {d:'Juros compostos e comparação com simples.',g:[()=>{ const C=rP([1000,2000,5000,10000]), i=rP([10,20]), t=rP([2,3]); const M2=C*Math.pow(1+i/100,t); return arNum('R$ '+fN(C,0)+' aplicados a juros compostos de '+i+'% ao ano. Qual o montante após '+t+' anos?',M2,{d:2,u:'reais',c:[C*(1+i*t/100),C*Math.pow(1+i/100,t-1),M2-C],steps:['M = C · (1 + i)ᵗ',fN(C,0)+' × '+fN(1+i/100,1)+sq(t)+' = '+fN(M2,2)]}); },()=>{ const C=rP([1000,2000,4000]), i=10, t=2; return arNum('Qual a diferença entre o montante a juros compostos e a juros simples, para R$ '+fN(C,0)+' a 10% ao mês por 2 meses?',C*1.21-C*1.2,{d:2,u:'reais',c:[C*0.21,C*0.2,0],steps:['Compostos: '+fN(C*1.21,2),'Simples: '+fN(C*1.2,2),'Diferença: '+fN(C*0.01,2)]}); }]}]);

/* ---------- equações ---------- */
mg('ar-mat-eq','mat-eq','Equações em chamas','x=','Equações do 1º e 2º grau, sistemas, inequações e problemas.',[
 {d:'Equação do 1º grau direta.',g:[()=>{ const x=rI(-6,12), a=rP([2,3,4,5,6,7]), b=rNZ(-15,20), c=a*x+b; return arNum('Resolva: '+fPoly([a,b],'x')+' = '+fI(c),x,{d:0,neg:true,c:[(c+b)/a,c-b,-x],steps:['Passe o '+fI(b)+' trocando o sinal: '+a+'x = '+fI(c-b),'x = '+fI(c-b)+' ÷ '+a+' = '+fI(x)]}); }]},
 {d:'Parênteses, frações e problemas.',g:[()=>{ const x=rI(-5,10), a=rI(2,5), b=rNZ(-6,6), c=rI(1,4); const R=a*(x+b)-c*x; return arNum('Resolva: '+a+'(x '+(b<0?'− '+(-b):'+ '+b)+') − '+c+'x = '+fI(R),x,{d:0,neg:true,c:[x+1,-x,R/a]}); },()=>{ const x=rP([6,12,18,24,30,36,42,48]); return arNum('A metade de um número mais a sua terça parte dá '+fI(x/2+x/3)+'. Que número é esse?',x,{d:0,c:[x/2,x*2,x+6]}); },()=>{ const x=rI(5,30), y=rI(2,10); return arNum('A soma de dois números é '+(2*x+y)+' e um deles é '+y+' unidades maior que o outro. Qual é o menor?',x,{d:0,c:[x+y,(2*x+y)/2,y]}); }]},
 {d:'Sistemas 2×2.',g:[()=>{ const x=rI(-4,9), y=rI(-4,9), a=rI(1,4), b=rI(1,4); return arNum('Resolva o sistema: x + y = '+fI(x+y)+' e '+a+'x − '+b+'y = '+fI(a*x-b*y)+'. Quanto vale x?',x,{d:0,neg:true,c:[y,x+y,-x]}); },()=>{ const c=rI(10,40), m=rI(3,20), p1=2, p2=4; const car=m, moto=c-m; return arNum('Num estacionamento há motos e carros, '+c+' veículos e '+(moto*2+car*4)+' rodas. Quantos carros há?',car,{d:0,c:[moto,c/2,car+2]}); }]},
 {d:'Equação do 2º grau: raízes, soma, produto, Δ.',g:[()=>{ let r1=rI(-5,7), r2=rI(-5,7); if(r1===r2) r2++; const S=r1+r2, P=r1*r2, k=rI(0,2), eq=fPoly([1,-S,P],'x')+' = 0';
   if(k===0) return arNum('Qual a soma das raízes de '+eq+'?',S,{d:0,neg:true,c:[-S,P]}); if(k===1) return arNum('Qual o produto das raízes de '+eq+'?',P,{d:0,neg:true,c:[-P,S]}); return arNum('Qual a maior raiz de '+eq+'?',Math.max(r1,r2),{d:0,neg:true,c:[Math.min(r1,r2),S,-Math.max(r1,r2)]}); },
   ()=>{ const a=rI(1,3), b=rNZ(-8,8), c=rNZ(-9,9), D=b*b-4*a*c; return arCh('Quantas raízes reais tem '+fPoly([a,b,c],'x')+' = 0?',D>0?'Duas raízes reais distintas':D===0?'Duas raízes reais iguais':'Nenhuma raiz real',['Duas raízes reais distintas','Duas raízes reais iguais','Nenhuma raiz real','Infinitas raízes'],{x:'Δ = b² − 4ac = '+fI(b*b)+' − '+fI(4*a*c)+' = '+fI(D)+'. Δ>0: duas; Δ=0: uma dupla; Δ<0: nenhuma real.'}); }]},
 {d:'Inequações e problemas do 2º grau.',g:[()=>{ const a=rP([2,3,4,5]), x=rI(-4,8), b=rNZ(-10,10); return arCh('Resolva '+fPoly([a,b],'x')+' > '+fI(a*x+b)+'.','x > '+fI(x),['x < '+fI(x),'x > '+fI(-x),'x ≥ '+fI(x),'x > '+fI(x+1)],{x:a+'x > '+fI(a*x)+' → x > '+fI(x)+'.'}); },()=>{ const r1=rI(1,4), r2=r1+rI(2,5); return arCh('Qual o conjunto solução de '+fPoly([1,-(r1+r2),r1*r2],'x')+' < 0?',r1+' < x < '+r2,['x < '+r1+' ou x > '+r2,'x > '+r2,'x < '+r1,'−'+r2+' < x < −'+r1],{x:'Parábola com concavidade para cima: negativa entre as raízes '+r1+' e '+r2+'.'}); },()=>{ const x=rI(4,12); return arNum('Um terreno retangular tem área '+(x*(x+3))+' m² e o comprimento é 3 m maior que a largura. Qual a largura?',x,{d:0,u:'m',c:[x+3,Math.round(Math.sqrt(x*(x+3))),x-3]}); }]}]);

/* ---------- funções ---------- */
function linFig(a,b){ return fgPlot({xr:[-5,5],yr:[-6,6],sx:1,sy:2,fns:[{f:x=>a*x+b}],label:'Gráfico de uma função afim'}); }
mg('ar-mat-fun','mat-fun','Leitura de funções','f(x)','Funções afim e quadrática: valores, gráficos, raízes, vértice e sinal.',[
 {d:'Valor numérico da função.',g:[()=>{ const a=rNZ(-4,5), b=rI(-8,8), k=rI(-4,6); return arNum('Se f(x) = '+fPoly([a,b],'x')+', quanto vale f('+fI(k)+')?',a*k+b,{d:0,neg:true,c:[a*k-b,a+k+b,-(a*k+b)],steps:['Troque x por '+fI(k)+': '+a+' · ('+fI(k)+') '+(b<0?'− '+(-b):'+ '+b)+' = '+fI(a*k+b)]}); }]},
 {d:'Raiz e coeficiente angular.',g:[()=>{ const r=rI(-5,6), a=rNZ(-4,4); const b=-a*r; return arNum('Qual a raiz (zero) de f(x) = '+fPoly([a,b],'x')+'?',r,{d:0,neg:true,c:[-r,b,a]}); },()=>{ const x1=rI(-3,2), x2=x1+rI(1,4), a=rNZ(-3,3), b=rI(-4,4); return arNum('Uma reta passa por ('+fI(x1)+', '+fI(a*x1+b)+') e ('+fI(x2)+', '+fI(a*x2+b)+'). Qual o coeficiente angular?',a,{d:0,neg:true,c:[-a,1/a,a+1],steps:['a = Δy/Δx = ('+fI(a*x2+b)+' − '+fI(a*x1+b)+') / ('+fI(x2)+' − '+fI(x1)+') = '+fI(a)]}); }]},
 {d:'Identifique a lei a partir do gráfico.',g:[()=>{ const a=rP([-2,-1,1,2,3]), b=rI(-3,3); return arCh('Qual é a lei da função do gráfico?','f(x) = '+fPoly([a,b],'x'),['f(x) = '+fPoly([-a,b],'x'),'f(x) = '+fPoly([a,-b||1],'x'),'f(x) = '+fPoly([b||1,a],'x'),'f(x) = '+fPoly([a*2,b],'x')],{fig:linFig(a,b),x:'Corta o eixo y em '+fI(b)+' (coeficiente linear) e sobe/desce '+fI(a)+' a cada unidade de x.'}); },()=>{ const a=rNZ(-3,3), b=rI(-4,4); return arCh('A função f(x) = '+fPoly([a,b],'x')+' é:',a>0?'Crescente':'Decrescente',[a>0?'Decrescente':'Crescente','Constante'],{x:'Coeficiente angular '+fI(a)+': '+(a>0?'positivo → crescente':'negativo → decrescente')+'.'}); }]},
 {d:'Quadrática: vértice, raízes, concavidade.',g:[()=>{ const h=rI(-3,3), k=rI(-4,3), a=rP([1,-1]); const b=-2*a*h, c=a*h*h+k; return arCh('Qual é o vértice de f(x) = '+fPoly([a,b,c],'x')+'?','('+fI(h)+', '+fI(k)+')',['('+fI(-h)+', '+fI(k)+')','('+fI(h)+', '+fI(c)+')','('+fI(k)+', '+fI(h)+')','('+fI(b)+', '+fI(c)+')'],{fig:fgPlot({xr:[-6,6],yr:[-8,8],sx:1,sy:2,fns:[{f:x=>a*x*x+b*x+c}],label:'Parábola'}),x:'xv = −b/2a = '+fI(h)+'; yv = f('+fI(h)+') = '+fI(k)+'.'}); },()=>{ const a=rP([1,2,-1,-2]); return arCh('Em f(x) = '+fPoly([a,rI(-4,4),rI(-5,5)],'x')+', a concavidade da parábola é voltada para:',a>0?'Cima':'Baixo',[a>0?'Baixo':'Cima','A direita','A esquerda'],{x:'a '+(a>0?'> 0: para cima (ponto de mínimo)':'< 0: para baixo (ponto de máximo)')+'.'}); }]},
 {d:'Máximo/mínimo em problemas, composta e inversa.',g:[()=>{ const P=rP([20,40,60,80,100,120]); return arNum('Com '+P+' m de corda, um bombeiro quer isolar uma área retangular. Qual a maior área possível?',Math.pow(P/4,2),{d:0,u:'m²',c:[P*P/8,P,Math.pow(P/2,2)],steps:['Retângulo de perímetro fixo: a maior área é a do quadrado.','Lado = '+P+'/4 = '+(P/4),'Área = '+Math.pow(P/4,2)]}); },()=>{ const a=rI(2,4), b=rI(-3,3), c=rI(1,3), k=rI(-2,3); return arNum('Sendo f(x) = '+fPoly([a,b],'x')+' e g(x) = '+fPoly([c,0],'x')+', quanto vale f(g('+fI(k)+'))?',a*c*k+b,{d:0,neg:true,c:[c*(a*k+b),a*k+b,a*c*k]}); },()=>{ const a=rP([2,3,4,5]), b=rI(-6,6); const y=rI(-5,8); return arNum('Sendo f(x) = '+fPoly([a,b],'x')+', qual é f⁻¹('+fI(a*y+b)+')?',y,{d:0,neg:true,c:[a*(a*y+b)+b,(a*y+b)/a,-y]}); }]}]);

/* ---------- exponencial e log ---------- */
mg('ar-mat-exp','mat-exp','Exponencial e logaritmo','log','Equações exponenciais, definição e propriedades do log, aplicações.',[
 {d:'Equação exponencial de mesma base.',g:[()=>{ const b=rP([2,3,5]), x=rI(2,6); return arNum('Resolva: '+b+'ˣ = '+Math.pow(b,x),x,{d:0,c:[Math.pow(b,x)/b,x+1,x-1],steps:[Math.pow(b,x)+' = '+b+sq(x),'Bases iguais → x = '+x]}); }]},
 {d:'Definição de logaritmo.',g:[()=>{ const b=rP([2,3,5,10]), e=rI(1,4); return arNum('Calcule log'+sb(b)+' '+Math.pow(b,e)+'.',e,{d:0,c:[Math.pow(b,e)/b,b*e,e+1],steps:['log'+sb(b)+' '+Math.pow(b,e)+' = x ⇔ '+b+'ˣ = '+Math.pow(b,e),'x = '+e]}); },()=>{ const e=rI(-3,5); return arNum('Quanto vale log '+(Math.pow(10,e)).toLocaleString('pt-BR',{maximumFractionDigits:5})+'? (base 10)',e,{d:0,neg:true,c:[e+1,-e,e*10]}); }]},
 {d:'Propriedades: log de produto, quociente e potência.',g:[()=>{ const a=rI(0,4), b=rI(0,3), c=rI(-1,1); if(!a&&!b) return arNum('Quanto vale log 100?',2,{d:0,c:[10,1,3]}); const v=Math.pow(2,a)*Math.pow(3,b)*Math.pow(10,c); const L=0.30*a+0.48*b+c; return arNum('Dados log 2 = 0,30 e log 3 = 0,48, calcule log '+fN(v,3)+'.',L,{d:2,neg:true,c:[0.30*b+0.48*a+c,L+0.3,0.30*a*0.48*b+c],steps:['Fatore em potências de 2, 3 e 10.','log = '+[a?a+'·0,30':'',b?b+'·0,48':'',c?fI(c):''].filter(Boolean).join(' + ')+' = '+fN(L,2)]}); },()=>{ const k=rI(0,3); const L2=0.30, L3=0.48; const opts=[['log 6',L2+L3,'log 6 = log 2 + log 3'],['log 12',2*L2+L3,'log 12 = 2·log 2 + log 3'],['log 18',L2+2*L3,'log 18 = log 2 + 2·log 3'],['log 1,5',L3-L2,'log 1,5 = log 3 − log 2'],['log 8',3*L2,'log 8 = 3·log 2'],['log 5',1-L2,'log 5 = log 10 − log 2']];
   const o=rP(opts); return arNum('Dados log 2 = 0,30 e log 3 = 0,48, calcule '+o[0]+'.',o[1],{d:2,c:[o[1]+0.3,L2*L3,o[1]*2],steps:[o[2]]}); }]},
 {d:'Exponenciais com mudança de base.',g:[()=>{ const b=rP([2,3]), a=rP([1,2,3]), x=rI(-2,5), c=rI(-3,3); const k=a*x+c; return arNum('Resolva: '+b+'^('+(a>1?a:'')+'x'+(c<0?' − '+(-c):c>0?' + '+c:'')+') = '+(k>=0?Math.pow(b,k):'1/'+Math.pow(b,-k))+'.',x,{d:0,neg:true,c:[k,x+1,-x],steps:['Escreva o lado direito como '+b+sq(k),'Iguale os expoentes e isole x: x = '+x]}); },()=>{ const x=rI(1,4), y=rI(1,3); return arNum('Resolva: 4ˣ = 8'+sq(y*2)+' (dica: escreva tudo em base 2).',3*y,{d:0,c:[y*2,6*y,y]}); },()=>{ const x=rI(1,4); return arNum('Resolva: 9ˣ = 27 · 3'+sq(2*x-3),Math.round(2*x/2),{d:0,c:[x+1,x*2,x-1]}); }]},
 {d:'Aplicações: crescimento e meia-vida.',g:[()=>{ const P=rP([1000,2000,5000]), t=rI(2,4); return arNum('Uma colônia de bactérias começa com '+fN(P,0)+' e dobra a cada hora. Quantas haverá após '+t+' horas?',P*Math.pow(2,t),{d:0,c:[P*2*t,P*Math.pow(2,t-1),P*t]}); },()=>{ const m=rP([80,160,320,640]), n=rI(2,4); return arNum('Uma substância tem meia-vida de 10 anos. De '+m+' g, quanto resta após '+(10*n)+' anos?',m/Math.pow(2,n),{d:0,u:'g',c:[m/(2*n),m-10*n,m/n]}); },()=>{ return arNum('Com log 2 = 0,30, em quantos anos um capital dobra a 10% ao ano (juros compostos)? Use log 1,1 = 0,04.',7.5,{d:1,u:'anos',c:[10,5,20],steps:['1,1ᵗ = 2 → t = log 2 / log 1,1 = 0,30 / 0,04 = 7,5']}); }]}]);

/* ---------- progressões ---------- */
mg('ar-mat-pa','mat-pa','Progressões','PA',"PA e PG: termo geral, somas, soma infinita e interpolação.",[
 {d:'Termo geral da PA.',g:[()=>{ const a1=rI(-5,20), r=rNZ(-6,9), n=rI(5,20); return arNum('Numa PA, a₁ = '+fI(a1)+' e a razão é '+fI(r)+'. Qual o '+n+'º termo?',a1+(n-1)*r,{d:0,neg:true,c:[a1+n*r,a1*n,a1+(n-1)*r+r]}); }]},
 {d:'Soma da PA.',g:[()=>{ const a1=rI(1,20), r=rI(1,9), n=rI(5,20), an=a1+(n-1)*r; return arNum('Qual a soma dos '+n+' primeiros termos da PA com a₁ = '+a1+' e razão '+r+'?',n*(a1+an)/2,{d:0,c:[n*(a1+an),(a1+an)/2,n*an],steps:['aₙ = '+an,'Sₙ = n(a₁ + aₙ)/2 = '+n+' × '+(a1+an)+'/2 = '+fN(n*(a1+an)/2,0)]}); },()=>{ const n=rP([50,100,200]); return arNum('Qual a soma dos números naturais de 1 a '+n+'?',n*(n+1)/2,{d:0,c:[n*n/2,n*(n-1)/2,n*(n+1)]}); }]},
 {d:'Termo geral da PG.',g:[()=>{ const a1=rP([1,2,3,5]), q=rP([2,3,-2]), n=rI(3,6); return arNum('Numa PG, a₁ = '+a1+' e a razão é '+fI(q)+'. Qual o '+n+'º termo?',a1*Math.pow(q,n-1),{d:0,neg:true,c:[a1*Math.pow(q,n),a1+(n-1)*q,a1*q*n]}); }]},
 {d:'Soma da PG finita e infinita.',g:[()=>{ const a1=rP([1,2,3]), q=rP([2,3]), n=rI(3,6); const Sn=a1*(Math.pow(q,n)-1)/(q-1); return arNum('Soma dos '+n+' primeiros termos da PG com a₁ = '+a1+' e razão '+q+'.',Sn,{d:0,c:[a1*Math.pow(q,n-1),a1*Math.pow(q,n),Sn+1]}); },()=>{ const a1=rP([3,6,9,12,20]), q=rP([[1,2],[1,3],[1,4],[2,3]]); const S=a1/(1-q[0]/q[1]); return arNum('Qual a soma infinita da PG com a₁ = '+a1+' e razão '+q[0]+'/'+q[1]+'?',S,{d:2,c:[a1*q[1]/q[0],a1/(q[0]/q[1]),a1*2]}); }]},
 {d:'Problemas: interpolação e três termos.',g:[()=>{ const a=rI(2,10), r=rI(2,8), k=rP([3,4,5]); return arNum('Interpolando '+k+' meios aritméticos entre '+a+' e '+(a+(k+1)*r)+', qual a razão?',r,{d:0,c:[r*2,(k+1)*r/k,r+1]}); },()=>{ const x=rI(3,10), r=rI(2,6); return arNum('Três números em PA somam '+(3*x)+' e o maior é '+(x+r)+'. Qual o menor?',x-r,{d:0,neg:true,c:[x,x+r,r]}); }]}]);

/* ---------- combinatória e probabilidade ---------- */
const fat=n=>n<=1?1:n*fat(n-1), Cnk=(n,k)=>fat(n)/(fat(k)*fat(n-k)), Ank=(n,k)=>fat(n)/fat(n-k);
mg('ar-mat-comb','mat-comb','Contagem e sorte','n!','Princípio multiplicativo, permutações, arranjos, combinações e probabilidade.',[
 {d:'Princípio fundamental da contagem.',g:[()=>{ const a=rI(2,6), b=rI(2,6), c=rI(2,5); return arNum('Um cadete tem '+a+' calças, '+b+' camisas e '+c+' pares de botas. De quantas formas pode se vestir?',a*b*c,{d:0,c:[a+b+c,a*b+c,a*b]}); }]},
 {d:'Permutações e anagramas.',g:[()=>{ const n=rI(4,7), f=rI(1,2); return arNum('Quantos anagramas de uma palavra com '+n+' letras distintas começam por uma letra fixa'+(f===2?' e terminam em outra letra fixa':'')+'?',fat(n-f),{d:0,c:[fat(n),fat(n-1)*2,n*(n-f)]}); },()=>{ const n=rI(3,6); return arNum('De quantas formas '+n+' bombeiros podem se organizar em fila?',fat(n),{d:0,c:[n*n,fat(n-1),n*2]}); },()=>{ const w=rP([['ARARA',5,[3,2]],['BANANA',6,[3,2]],['PARANÁ',6,[3]],['CASA',4,[2]],['OSSO',4,[2,2]]]); const v=fat(w[1])/w[2].reduce((p,k)=>p*fat(k),1); return arNum('Quantos anagramas tem a palavra '+w[0]+'?',v,{d:0,c:[fat(w[1]),v*2,fat(w[1]-1)]}); }]},
 {d:'Arranjo × combinação.',g:[()=>{ const n=rI(5,10), k=rI(2,3); return arNum('De quantas formas podemos escolher uma comissão de '+k+' pessoas entre '+n+'?',Cnk(n,k),{d:0,c:[Ank(n,k),n*k,Cnk(n,k)*2]}); },()=>{ const n=rI(5,10); return arNum(n+' candidatos disputam ouro, prata e bronze. Quantos pódios diferentes são possíveis?',Ank(n,3),{d:0,c:[Cnk(n,3),n*3,Math.pow(n,3)]}); },()=>arSort('A ordem importa?',['Arranjo (ordem importa)','Combinação (ordem não importa)'],rN([['Escolher presidente e vice',0],['Formar uma comissão de 3',1],['Senha de 4 dígitos distintos',0],['Escolher 2 sabores de sorvete',1],['Pódio de uma corrida',0],['Sortear 6 números da loteria',1]],4),{x:'Se trocar a ordem gera um resultado diferente, é arranjo.'})]},
 {d:'Probabilidade simples e complementar.',g:[()=>{ const ev=rP([['sair número par','1/2'],['sair número maior que 4','1/3'],['sair múltiplo de 3','1/3'],['sair o número 6','1/6'],['sair número menor que 6','5/6'],['sair número primo','1/2']]); return arCh('Num dado comum, qual a probabilidade de '+ev[0]+'?',ev[1],['1/2','1/3','1/6','2/3','5/6','1/4'].filter(x=>x!==ev[1]),{x:'Casos favoráveis ÷ casos possíveis (6).'}); },()=>{ const v=rI(2,6), a=rI(2,6), p=rI(1,4); const t=v+a+p; return arCh('Uma urna tem '+v+' bolas vermelhas, '+a+' azuis e '+p+' pretas. Qual a probabilidade de NÃO sair vermelha?',fFr(a+p,t),[fFr(v,t),fFr(a,t),fFr(p,t),fFr(1,t)],{x:'Não vermelha: ('+(a+p)+')/'+t+'.'}); }]},
 {d:'Eventos independentes, "pelo menos um", condicional.',g:[()=>{ const r=rI(2,6), a=rI(2,6), t=r+a; return arCh('Uma urna tem '+r+' bolas vermelhas e '+a+' azuis. Retirando duas, sem reposição, qual a probabilidade de as duas serem vermelhas?',fFr(r*(r-1),t*(t-1)),[fFr(r*r,t*t),fFr(r,t),fFr(r*(r-1),t*t),fFr(2*r,t*(t-1))],{x:'('+r+'/'+t+') × ('+(r-1)+'/'+(t-1)+') = '+fFr(r*(r-1),t*(t-1))+'.'}); },()=>{ const s=rI(3,11); const cases=[]; for(let i=1;i<=6;i++) for(let j=1;j<=6;j++) if(i+j===s) cases.push([i,j]); const k=rI(1,6); const fav=cases.filter(c=>c[0]===k||c[1]===k).length; if(!fav) return arCh('Dois dados: qual a probabilidade de a soma ser '+s+'?',fFr(cases.length,36),[fFr(1,6),fFr(cases.length+1,36),fFr(1,36)],{x:cases.length+' casos em 36.'}); return arCh('Dois dados são lançados. Sabendo que a soma foi '+s+', qual a probabilidade de aparecer pelo menos um '+k+'?',fFr(fav,cases.length),[fFr(fav,36),fFr(1,6),fFr(cases.length,36),fFr(fav+1,cases.length+1)],{x:'Soma '+s+': '+cases.length+' casos; com '+k+': '+fav+'.'}); },()=>{ const n=rP([2,3]); return arCh('Lançando uma moeda '+n+' vezes, qual a probabilidade de sair cara em todas?','1/'+Math.pow(2,n),['1/'+(2*n),n+'/'+Math.pow(2,n),'1/2','1/'+Math.pow(2,n+1)],{x:'Eventos independentes: multiplique (1/2)'+sq(n)+'.'}); },()=>{ const n=rP([2,3]); return arCh('Lançando uma moeda '+n+' vezes, qual a probabilidade de sair pelo menos uma cara?',(Math.pow(2,n)-1)+'/'+Math.pow(2,n),['1/'+Math.pow(2,n),'1/2',n+'/'+Math.pow(2,n),'1/'+n],{x:'Complementar: 1 − P(nenhuma cara) = 1 − 1/'+Math.pow(2,n)+'.'}); },()=>{ return arCh('Dois dados são lançados. Sabendo que a soma foi 8, qual a probabilidade de um dos dados ser 6?','2/5',['1/6','1/3','5/36','1/5'],{x:'Soma 8: (2,6),(3,5),(4,4),(5,3),(6,2) = 5 casos; com 6: 2 casos → 2/5.'}); }]}]);

/* ---------- estatística ---------- */
function statSet(n,a,b){ return Array.from({length:n},()=>rI(a,b)); }
mg('ar-mat-est','mat-est','Estatística de ocorrências','x̄','Média, mediana, moda, média ponderada, desvio padrão e gráficos.',[
 {d:'Média aritmética.',g:[()=>{ const xs=statSet(5,2,20); const s=xs.reduce((a,b)=>a+b,0); return arNum('Média de '+xs.join(', ')+'?',s/5,{d:1,c:[s,s/4,xs.slice().sort((a,b)=>a-b)[2]],steps:['Soma: '+s,'÷ 5 = '+fN(s/5,1)]}); }]},
 {d:'Mediana e moda.',g:[()=>{ const xs=statSet(rP([5,7]),1,30); const so=xs.slice().sort((a,b)=>a-b); return arNum('Mediana de '+xs.join(', ')+'?',so[(so.length-1)/2],{d:0,c:[xs[(xs.length-1)/2],so[0],so[so.length-1]],steps:['Ordene: '+so.join(', '),'Termo do meio: '+so[(so.length-1)/2]]}); },()=>{ const m=rI(3,9), xs=rS([m,m,m].concat(statSet(4,1,12).filter(x=>x!==m))); return arNum('Moda de '+xs.join(', ')+'?',m,{d:0,c:xs.filter(x=>x!==m).slice(0,3)}); },()=>{ const xs=statSet(6,1,20); const so=xs.slice().sort((a,b)=>a-b); return arNum('Mediana de '+xs.join(', ')+' (quantidade par)?',(so[2]+so[3])/2,{d:1,c:[so[2],so[3],xs.reduce((a,b)=>a+b)/6]}); }]},
 {d:'Média ponderada.',g:[()=>{ const n=[rI(4,10),rI(4,10),rI(4,10)], p=[rP([1,2]),rP([2,3]),rP([3,4])]; const v=(n[0]*p[0]+n[1]*p[1]+n[2]*p[2])/(p[0]+p[1]+p[2]); return arNum('Notas '+n.join(', ')+' com pesos '+p.join(', ')+'. Qual a média ponderada?',v,{d:2,c:[(n[0]+n[1]+n[2])/3,n[0]*p[0]+n[1]*p[1]+n[2]*p[2]],steps:['Σ(nota·peso) = '+(n[0]*p[0]+n[1]*p[1]+n[2]*p[2]),'÷ Σpesos '+(p[0]+p[1]+p[2])+' = '+fN(v,2)]}); }]},
 {d:'Variância e desvio padrão.',g:[()=>{ const m=rI(4,10), d=rP([[1,1,-1,-1],[2,2,-2,-2],[3,3,-3,-3],[2,-2,0,0]]); const xs=d.map(x=>m+x); const v=d.reduce((a,x)=>a+x*x,0)/4; return arNum('Variância (populacional) de '+xs.join(', ')+'?',v,{d:1,c:[Math.sqrt(v),v*4/3,m],steps:['Média: '+m,'Desvios²: '+d.map(x=>x*x).join(', '),'Média dos desvios² = '+fN(v,1)]}); },()=>{ const m=rI(5,10), k=rI(1,3); const xs=[m-k,m+k,m-k,m+k]; return arNum('Desvio padrão de '+xs.join(', ')+'?',k,{d:0,c:[k*k,2*k,m]}); }]},
 {d:'Gráficos e efeito de transformações.',g:[()=>{ const L=['Seg','Ter','Qua','Qui','Sex'], V=L.map(()=>rI(1,12)); const s=V.reduce((a,b)=>a+b); return arNum('O gráfico mostra ocorrências por dia. Qual a média diária?',s/5,{d:1,fig:fgBars(L,V,{yl:'ocorrências'}),c:[Math.max.apply(null,V),s,s/4]}); },()=>{ const k=rI(2,5), m=rI(5,10), dp=rI(1,4); return arCh('Um conjunto tem média '+m+' e desvio padrão '+dp+'. Somando '+k+' a todos os valores, média e desvio passam a ser:',(m+k)+' e '+dp,[(m+k)+' e '+(dp+k),m+' e '+dp,(m*k)+' e '+(dp*k)],{x:'Somar uma constante desloca a média, mas não muda a dispersão.'}); },()=>{ const k=rI(2,4), m=rI(3,8), dp=rI(1,3); return arCh('Multiplicando todos os valores por '+k+', média '+m+' e desvio '+dp+' passam a ser:',(m*k)+' e '+(dp*k),[(m*k)+' e '+dp,(m+k)+' e '+(dp*k),(m*k)+' e '+(dp*k*k)],{x:'Multiplicar por constante multiplica média e desvio padrão (a variância, pelo quadrado).'}); }]}]);

/* ---------- matrizes e sistemas ---------- */
const mS=m=>'['+m.map(r=>r.map(fI).join('  ')).join(' ; ')+']';
mg('ar-mat-mtz','mat-mtz','Matrizes e sistemas','[ ]','Elementos, operações, produto, determinantes e sistemas lineares.',[
 {d:'Elementos e lei de formação.',g:[()=>{ const i=rI(1,3), j=rI(1,3), a=rI(1,3), b=rI(1,3); return arNum('Na matriz A = (aᵢⱼ) com aᵢⱼ = '+a+'i + '+b+'j, quanto vale a'+sb(i)+sb(j)+'?',a*i+b*j,{d:0,c:[a*j+b*i,i+j,a*b*i*j]}); }]},
 {d:'Soma, produto por escalar e transposta.',g:[()=>{ const A=[[rI(-3,5),rI(-3,5)],[rI(-3,5),rI(-3,5)]], B=[[rI(-3,5),rI(-3,5)],[rI(-3,5),rI(-3,5)]], k=rI(2,3); const C=A.map((r,i)=>r.map((v,j)=>k*v+B[i][j])); return arCh('Sendo A = '+mS(A)+' e B = '+mS(B)+', calcule '+k+'A + B.',mS(C),[mS(A.map((r,i)=>r.map((v,j)=>v+B[i][j]))),mS(A.map((r,i)=>r.map((v,j)=>k*(v+B[i][j])))),mS(C.map((r,i)=>r.map((v,j)=>C[j][i])))],{x:'Multiplique cada elemento de A por '+k+' e some elemento a elemento com B.'}); }]},
 {d:'Produto de matrizes 2×2.',g:[()=>{ const A=[[rI(-2,4),rI(-2,4)],[rI(-2,4),rI(-2,4)]], B=[[rI(-2,4),rI(-2,4)],[rI(-2,4),rI(-2,4)]]; const P=[[A[0][0]*B[0][0]+A[0][1]*B[1][0],A[0][0]*B[0][1]+A[0][1]*B[1][1]],[A[1][0]*B[0][0]+A[1][1]*B[1][0],A[1][0]*B[0][1]+A[1][1]*B[1][1]]]; return arNum('Sendo A = '+mS(A)+' e B = '+mS(B)+', qual o elemento c₁₁ de C = A·B?',P[0][0],{d:0,neg:true,c:[A[0][0]*B[0][0],P[1][1],A[0][0]*B[0][0]+A[0][1]*B[0][1]],steps:['Linha 1 de A × coluna 1 de B: '+fI(A[0][0])+'·'+fI(B[0][0])+' + '+fI(A[0][1])+'·'+fI(B[1][0])+' = '+fI(P[0][0])]}); }]},
 {d:'Determinantes 2×2 e 3×3.',g:[()=>{ const a=rI(-4,9), b=rI(-4,9), c=rI(-4,9), d=rI(-4,9); return arNum('Determinante de '+mS([[a,b],[c,d]])+'?',a*d-b*c,{d:0,neg:true,c:[a*d+b*c,a+d,b*c-a*d]}); },()=>{ const m=[[rI(-2,3),rI(-2,3),rI(-2,3)],[rI(-2,3),rI(-2,3),rI(-2,3)],[rI(-2,3),rI(-2,3),rI(-2,3)]]; const D=m[0][0]*(m[1][1]*m[2][2]-m[1][2]*m[2][1])-m[0][1]*(m[1][0]*m[2][2]-m[1][2]*m[2][0])+m[0][2]*(m[1][0]*m[2][1]-m[1][1]*m[2][0]); return arNum('Determinante (Sarrus) de '+mS(m)+'?',D,{d:0,neg:true,c:[-D,D+1,m[0][0]*m[1][1]*m[2][2]]}); }]},
 {d:'Sistemas: Cramer e classificação.',g:[()=>{ const x=rI(-4,6), y=rI(-4,6), a=rNZ(-3,4), b=rNZ(-3,4), c=rNZ(-3,4), d=rNZ(-3,4); if(a*d-b*c===0) return arNum('Resolva: x + y = 5 e x − y = 1. Quanto vale x?',3,{d:0,c:[2,5,1]}); const ty=k=>(k<0?'− ':'+ ')+(Math.abs(k)===1?'':Math.abs(k))+'y'; return arNum('Resolva: '+fPoly([a,0],'x')+' '+ty(b)+' = '+fI(a*x+b*y)+' e '+fPoly([c,0],'x')+' '+ty(d)+' = '+fI(c*x+d*y)+'. Quanto vale y?',y,{d:0,neg:true,c:[x,-y,x+y]}); },()=>{ const k=rI(2,4), a=rI(1,4), b=rI(1,4), c=rI(1,9), t=rI(0,1); return arCh('O sistema '+a+'x + '+b+'y = '+c+' e '+(k*a)+'x + '+(k*b)+'y = '+(t?k*c:k*c+1)+' é:',t?'Possível e indeterminado':'Impossível',['Possível e determinado','Possível e indeterminado','Impossível'].filter(x=>x!==(t?'Possível e indeterminado':'Impossível')),{x:'A 2ª equação é a 1ª multiplicada por '+k+(t?', inclusive o termo independente: infinitas soluções (SPI).':', mas o termo independente não acompanha: nenhuma solução (SI).')}); }]}]);

/* ---------- trigonometria ---------- */
const TRIG={30:['1/2','√3/2','√3/3'],45:['√2/2','√2/2','1'],60:['√3/2','1/2','√3']};
mg('ar-mat-trig','mat-trig','Trigonometria','θ','Razões no triângulo, ângulos notáveis, círculo, leis dos senos e cossenos, identidades.',[
 {d:'Seno, cosseno e tangente no triângulo retângulo.',g:[()=>{ const [a,b,c]=rP([[3,4,5],[6,8,10],[5,12,13],[8,15,17],[7,24,25],[20,21,29],[9,40,41],[4,3,5],[12,5,13]]); const k=rI(0,2), nm=['sen θ','cos θ','tg θ'][k], v=[fFr(a,c),fFr(b,c),fFr(a,b)][k]; return arCh('No triângulo, qual é '+nm+'?',v,[fFr(a,c),fFr(b,c),fFr(a,b),fFr(b,a),fFr(c,a)].filter(x=>x!==v),{fig:fgTri({b:b+' (adjacente)',h:a+' (oposto)',c:String(c),ang:'θ'}),x:'sen = oposto/hipotenusa; cos = adjacente/hipotenusa; tg = oposto/adjacente.'}); }]},
 {d:'Ângulos notáveis e cálculo de lados.',g:[()=>{ const g=rP([30,45,60]), k=rI(0,2); const nm=['sen','cos','tg'][k]; return arCh('Quanto vale '+nm+' '+g+'°?',TRIG[g][k],['1/2','√2/2','√3/2','√3','√3/3','1'].filter(x=>x!==TRIG[g][k]),{x:'Tabela: sen 30 = 1/2, sen 45 = √2/2, sen 60 = √3/2; cos é o inverso da ordem; tg 30 = √3/3, tg 45 = 1, tg 60 = √3.'}); },()=>{ const h=rP([4,6,8,10,12,20]); return arNum('Uma escada de '+h+' m apoiada num prédio forma 30° com o chão. A que altura ela toca a parede?',h/2,{d:1,u:'m',c:[h*Math.sqrt(3)/2,h,h/3],steps:['altura = hipotenusa × sen 30° = '+h+' × 1/2 = '+fN(h/2,1)+' m']}); }]},
 {d:'Graus × radianos e círculo trigonométrico.',g:[()=>{ const g=rP([30,45,60,90,120,135,150,180,270,360]); const map={30:'π/6',45:'π/4',60:'π/3',90:'π/2',120:'2π/3',135:'3π/4',150:'5π/6',180:'π',270:'3π/2',360:'2π'}; return arCh('Quanto é '+g+'° em radianos?',map[g],Object.values(map).filter(x=>x!==map[g]),{x:'180° = π rad: '+g+'° = '+map[g]+'.'}); },()=>{ const g=rP([100,150,200,250,300,340]); const q=g<90?1:g<180?2:g<270?3:4; return arCh('Em que quadrante está o ângulo de '+g+'° e qual o sinal do seno?',q+'º quadrante, seno '+(q<=2?'positivo':'negativo'),['1º quadrante, seno positivo','2º quadrante, seno positivo','3º quadrante, seno negativo','4º quadrante, seno negativo','2º quadrante, seno negativo'].filter(x=>x!==q+'º quadrante, seno '+(q<=2?'positivo':'negativo')),{x:'Seno positivo no 1º e 2º quadrantes.'}); }]},
 {d:'Lei dos senos e lei dos cossenos.',g:[()=>{ const [b,c]=[rI(2,8),rI(2,8)]; return arCh('Num triângulo, dois lados medem '+b+' e '+c+' e formam 60°. Quanto mede o terceiro lado?','√'+(b*b+c*c-b*c),['√'+(b*b+c*c),'√'+(b*b+c*c+b*c),String(b+c),'√'+(b*b+c*c-2*b*c)],{x:'a² = b² + c² − 2bc·cos 60° = '+(b*b)+' + '+(c*c)+' − '+(b*c)+' = '+(b*b+c*c-b*c)+'.'}); },()=>{ const a=rP([4,6,8,10]); return arNum('Num triângulo, o lado oposto a 30° mede '+a+'. Quanto mede o lado oposto a 90°?',2*a,{d:0,c:[a/2,a*Math.sqrt(3),a]}); }]},
 {d:'Identidades e arcos côngruos.',g:[()=>{ const s=rP([[3,5],[5,13],[8,17]]); return arCh('Se sen x = '+s[0]+'/'+s[1]+' e x está no 1º quadrante, quanto vale cos x?',Math.sqrt(s[1]*s[1]-s[0]*s[0])+'/'+s[1],[s[0]+'/'+s[1],(s[1]-s[0])+'/'+s[1],s[1]+'/'+s[0]],{x:'sen² + cos² = 1 → cos = √(1 − '+(s[0]*s[0])+'/'+(s[1]*s[1])+').'}); },()=>{ const k=rI(1,4), g=rP([30,45,60,120,210,300]); const a=360*k+g; return arNum('Qual a primeira determinação positiva de '+a+'°?',g,{d:0,u:'°',c:[a-360,g+180,360-g]}); }]}]);

/* ---------- geometria plana ---------- */
mg('ar-mat-gp','mat-gp','Geometria plana','△','Áreas, perímetros, Pitágoras, ângulos, semelhança e figuras compostas.',[
 {d:'Área e perímetro de retângulo, quadrado e triângulo.',g:[()=>{ const b=rI(3,20), h=rI(2,15); return rC(.5)?arNum('Qual a área do retângulo?',b*h,{d:0,u:'m²',fig:fgShape('rect',{b:b+' m',h:h+' m'}),c:[2*(b+h),b+h,b*h/2]}):arNum('Qual o perímetro do retângulo?',2*(b+h),{d:0,u:'m',fig:fgShape('rect',{b:b+' m',h:h+' m'}),c:[b*h,b+h,4*b]}); },()=>{ const b=rI(2,10)*2, h=rI(3,14); return arNum('Qual a área do triângulo?',b*h/2,{d:0,u:'m²',fig:fgShape('tri',{b:b+' m',h:h+' m'}),c:[b*h,b+h,b*h/4]}); }]},
 {d:'Círculo, trapézio e losango.',g:[()=>{ const r=rI(1,10); return rC(.5)?arNum('Área do círculo de raio '+r+' m (use π = 3,14).',3.14*r*r,{d:2,u:'m²',fig:fgShape('circ',{r:r+' m'}),c:[2*3.14*r,3.14*r,3.14*2*r*r]}):arNum('Comprimento da circunferência de raio '+r+' m (π = 3,14).',2*3.14*r,{d:2,u:'m',c:[3.14*r*r,3.14*r,4*3.14*r]}); },()=>{ const B=rI(8,16), b=rI(3,7), h=rI(2,10); return arNum('Área do trapézio?',(B+b)*h/2,{d:1,u:'m²',fig:fgShape('trap',{B:B+' m',b:b+' m',h:h+' m'}),c:[(B+b)*h,B*b*h/2,(B-b)*h/2]}); },()=>{ const D=rI(4,16), d=rI(2,10); return arNum('Losango com diagonais '+D+' e '+d+' cm. Área?',D*d/2,{d:0,u:'cm²',c:[D*d,D+d,D*d/4]}); }]},
 {d:'Pitágoras e ângulos de polígonos.',g:[()=>{ const [a,b,c]=rP([[3,4,5],[6,8,10],[5,12,13],[8,15,17],[9,12,15],[12,16,20]]).map(v=>v); const k=rI(0,1); return k?arNum('Qual a hipotenusa?',c,{d:0,fig:fgTri({b:String(b),h:String(a),c:'?'}),c:[a+b,c+1,Math.round((a*a+b*b)/2)]}):arNum('Qual o cateto que falta?',a,{d:0,fig:fgTri({b:String(b),h:'?',c:String(c)}),c:[c-b,Math.round(Math.sqrt(c*c+b*b)),a+1]}); },()=>{ const n=rI(5,12); return arNum('Soma dos ângulos internos de um polígono de '+n+' lados?',(n-2)*180,{d:0,u:'°',c:[n*180,(n-1)*180,360]}); },()=>{ const n=rI(5,12); return arNum('Quantas diagonais tem um polígono de '+n+' lados?',n*(n-3)/2,{d:0,c:[n*(n-3),n*(n-1)/2,n]}); }]},
 {d:'Semelhança e Teorema de Tales.',g:[()=>{ const s=rI(2,4), h=rI(2,6)*2, k=rI(3,9); return arNum('Um poste projeta sombra de '+(s*k)+' m no mesmo instante em que uma estaca de '+h+' m projeta sombra de '+s+' m. Qual a altura do poste?',h*k,{d:0,u:'m',c:[s*k*s/h,h+k,h*s*k]}); },()=>{ const a=rI(2,6), b=rI(2,6), k=rP([2,3]); return arNum('Três paralelas cortam duas transversais. Na primeira, os segmentos medem '+a+' e '+b+'; na segunda, o primeiro mede '+(a*k)+'. Quanto mede o segundo?',b*k,{d:0,c:[a*k*k,a*b,b+k]}); }]},
 {d:'Figuras compostas e polígonos regulares.',g:[()=>{ const L=rP([4,6,8,10]); return arNum('Um quadrado de lado '+L+' m tem um círculo inscrito. Qual a área fora do círculo (π = 3,14)?',L*L-3.14*(L/2)*(L/2),{d:2,u:'m²',c:[L*L-3.14*L*L,3.14*L*L/4,L*L/2]}); },()=>{ const L=rP([2,4,6,8]); return arCh('Área de um hexágono regular de lado '+L+' cm?',(3*L*L/2)+'√3 cm²',[(L*L)+'√3 cm²',(6*L*L)+' cm²',(3*L*L/4)+'√3 cm²'],{x:'Hexágono = 6 triângulos equiláteros: 6 × L²√3/4 = 3L²√3/2.'}); },()=>{ const L=rP([4,6,8,10]); return arCh('Qual a diagonal de um quadrado de lado '+L+' m?',L+'√2 m',[L+'√3 m',(2*L)+' m',L*L+' m','√'+L+' m'],{x:'d = L√2.'}); }]}]);

/* ---------- geometria espacial ---------- */
mg('ar-mat-ge','mat-ge','Geometria espacial','⬡','Volumes e áreas de prismas, cilindros, cones, esferas e a relação de Euler.',[
 {d:'Cubo e paralelepípedo; m³ em litros.',g:[()=>{ const a=rI(2,8), b=rI(2,8), c=rI(1,5); return arNum('Volume da caixa d’água?',a*b*c,{d:0,u:'m³',fig:fgShape('caixa',{a:a+' m',b:b+' m',c:c+' m'}),c:[a+b+c,2*(a*b+a*c+b*c),a*b]}); },()=>{ const v=rI(2,40); return arNum('Quantos litros cabem em '+v+' m³?',v*1000,{d:0,u:'L',c:[v*100,v*10,v*10000]}); }]},
 {d:'Cilindro (tanques e mangueiras).',g:[()=>{ const r=rI(1,4), h=rI(2,8); return arNum('Volume do cilindro (π = 3)?',3*r*r*h,{d:0,u:'m³',fig:fgShape('cil',{r:r+' m',h:h+' m'}),c:[3*r*h,2*3*r*h,3*r*r]}); },()=>{ const r=rP([0.5,1,2]), h=rP([2,3,4]); return arNum('Um tanque cilíndrico de raio '+fN(r,1)+' m e altura '+h+' m. Quantos litros cabem (π = 3)?',3*r*r*h*1000,{d:0,u:'L',c:[3*r*r*h,3*r*h*1000,3*r*r*h*100]}); }]},
 {d:'Prismas, pirâmides e cones.',g:[()=>{ const r=rI(1,6), h=rI(2,9)*1; return arNum('Volume do cone (π = 3)?',r*r*h,{d:0,u:'m³',fig:fgShape('cone',{r:r+' m',h:h+' m'}),c:[3*r*r*h,r*r*h*3/2,3*r*h]}); },()=>{ const L=rI(2,8), h=rI(3,9); return arNum('Pirâmide de base quadrada de lado '+L+' m e altura '+h+' m. Volume?',L*L*h/3,{d:1,u:'m³',c:[L*L*h,L*L*h/2,L*h/3]}); }]},
 {d:'Esfera e áreas superficiais.',g:[()=>{ const r=rP([1,2,3,6]); return arNum('Volume da esfera de raio '+r+' m (π = 3)?',4*r*r*r,{d:0,u:'m³',fig:fgShape('esfera',{r:r+' m'}),c:[4*3*r*r,3*r*r*r,4*r*r]}); },()=>{ const r=rI(1,5); return arNum('Área da superfície de uma esfera de raio '+r+' m (π = 3)?',12*r*r,{d:0,u:'m²',c:[4*r*r*r,3*r*r,12*r]}); },()=>{ const a=rI(2,9); return arNum('Área total de um cubo de aresta '+a+' cm?',6*a*a,{d:0,u:'cm²',c:[a*a*a,4*a*a,12*a]}); }]},
 {d:'Problemas e relação de Euler.',g:[()=>{ const [V,A,F]=rP([[8,12,6],[6,12,8],[12,30,20],[20,30,12],[4,6,4],[10,15,7]]); const k=rI(0,2); const q=['V','A','F'][k]; return arNum('Um poliedro convexo tem '+(k===0?A+' arestas e '+F+' faces':k===1?V+' vértices e '+F+' faces':V+' vértices e '+A+' arestas')+'. Quantos '+(k===0?'vértices':k===1?'arestas':'faces')+' tem?',[V,A,F][k],{d:0,c:[[V,A,F][k]+2,[V,A,F][k]-2]}); },()=>{ const Q=rP([200,300,400,500]), a=rP([2,3,4]), b=rP([2,3]), c=rP([1,2]); const vol=a*b*c*1000; return arNum('Uma caixa de '+a+' m × '+b+' m × '+c+' m está vazia. Uma bomba enche '+Q+' L/min. Em quantos minutos enche?',vol/Q,{d:0,u:'min',c:[a*b*c*Q,vol/Q/60,vol/Q*10]}); }]}]);

/* ---------- geometria analítica ---------- */
mg('ar-mat-analit','mat-analit','Geometria analítica','(x,y)','Ponto médio, distância, retas, posições relativas e circunferência.',[
 {d:'Ponto médio e distância.',g:[()=>{ const x1=rI(-6,6), y1=rI(-6,6), x2=x1+2*rI(-4,4), y2=y1+2*rI(-4,4); return arCh('Ponto médio de A('+fI(x1)+', '+fI(y1)+') e B('+fI(x2)+', '+fI(y2)+')?','('+fI((x1+x2)/2)+', '+fI((y1+y2)/2)+')',['('+fI(x2-x1)+', '+fI(y2-y1)+')','('+fI(x1+x2)+', '+fI(y1+y2)+')','('+fI((y1+y2)/2)+', '+fI((x1+x2)/2)+')'],{x:'Média das coordenadas.'}); },()=>{ const [p,q,r]=rP([[3,4,5],[6,8,10],[5,12,13],[8,6,10]]); const x1=rI(-3,5), y1=rI(-3,5); return arNum('Distância entre A('+fI(x1)+', '+fI(y1)+') e B('+fI(x1+p)+', '+fI(y1+q)+')?',r,{d:0,c:[p+q,r*r,r+1]}); }]},
 {d:'Coeficiente angular e equação da reta.',g:[()=>{ const a=rNZ(-3,3), b=rI(-5,5), x1=rI(-3,1), x2=x1+rI(1,3); return arCh('Equação da reta que passa por ('+fI(x1)+', '+fI(a*x1+b)+') e ('+fI(x2)+', '+fI(a*x2+b)+')?','y = '+fPoly([a,b],'x'),['y = '+fPoly([-a,b],'x'),'y = '+fPoly([a,-b||2],'x'),'y = '+fPoly([b||2,a],'x')],{x:'m = '+fI(a)+'; substituindo um ponto, n = '+fI(b)+'.'}); }]},
 {d:'Paralelas e perpendiculares.',g:[()=>{ const m=rP([2,3,4,5,-2,-3,-4,1/2,1/4,-1/2,-1/3,1/5]); const perp=rC(.5); const mm=perp?-1/m:m, b1=rNZ(-6,6), b2=rNZ(-6,6); const L=(k,b)=>'y = '+fN(k,2)+'x '+(b<0?'− '+(-b):'+ '+b); return arCh('Qual reta é '+(perp?'perpendicular':'paralela')+' a '+L(m,b1)+'?',L(mm,b2),[L(perp?m:-1/m,b2),L(-m,b2),L(perp?1/m:m*2,b1)],{x:perp?'Perpendiculares: m₁·m₂ = −1.':'Paralelas: mesmo coeficiente angular.'}); }]},
 {d:'Distância de ponto a reta e circunferência.',g:[()=>{ const a=rI(-5,5), b=rI(-5,5), r=rI(1,6); return arCh('Centro e raio de (x '+(a<0?'+ '+(-a):'− '+a)+')² + (y '+(b<0?'+ '+(-b):'− '+b)+')² = '+r*r+'?','C('+fI(a)+', '+fI(b)+') e r = '+r,['C('+fI(-a)+', '+fI(-b)+') e r = '+r,'C('+fI(a)+', '+fI(b)+') e r = '+r*r,'C('+fI(b)+', '+fI(a)+') e r = '+r],{x:'(x − a)² + (y − b)² = r².'}); },()=>{ const [A,B,d]=rP([[3,4,5],[4,3,5],[6,8,10]]); const C=rP([0,5,10]).valueOf(); const x0=rI(-2,3), y0=rI(-2,3); const val=Math.abs(A*x0+B*y0+C)/d; return arNum('Distância do ponto ('+fI(x0)+', '+fI(y0)+') à reta '+A+'x + '+B+'y + '+C+' = 0?',val,{d:1,c:[Math.abs(A*x0+B*y0+C),val*2]}); }]},
 {d:'Área por determinante e interseção.',g:[()=>{ const x1=rI(0,4), y1=rI(0,4), b=rI(2,6), h=rI(2,6); return arNum('Área do triângulo de vértices ('+x1+', '+y1+'), ('+(x1+b)+', '+y1+') e ('+x1+', '+(y1+h)+')?',b*h/2,{d:1,c:[b*h,b+h,b*h/4]}); },()=>{ const x=rI(-3,4), y=rI(-3,4), a=rNZ(-2,3), c=rNZ(-2,3); if(a===c) return arNum('Interseção de y = 2x e y = x + 3: qual o x?',3,{d:0,c:[6,1,-3]}); return arCh('Ponto de interseção de y = '+fPoly([a,y-a*x],'x')+' e y = '+fPoly([c,y-c*x],'x')+'?','('+fI(x)+', '+fI(y)+')',['('+fI(y)+', '+fI(x)+')','('+fI(-x)+', '+fI(y)+')','('+fI(x)+', '+fI(-y)+')'],{x:'Iguale as expressões e resolva.'}); }]}]);

/* ---------- limites, derivadas e integrais ---------- */
mg('ar-mat-calc','mat-calc','Limites e derivadas','dy/dx','Limites por substituição e fatoração, derivadas, tangentes, máximos e integrais simples.',[
 {d:'Limite por substituição direta.',g:[()=>{ const a=rI(-3,3), b=rI(-5,5), k=rI(-3,4); return arNum('Calcule o limite de '+fPoly([1,a,b],'x')+' quando x → '+fI(k)+'.',k*k+a*k+b,{d:0,neg:true,c:[k*k+b,a*k+b,k*k-a*k+b]}); }]},
 {d:'Limite 0/0 por fatoração.',g:[()=>{ const b=rNZ(-7,7); return arNum('Calcule o limite de (x² '+(b<0?'− '+(-b):'+ '+b)+'x)/x quando x → 0.',b,{d:0,neg:true,c:[0,1,-b],steps:['Coloque x em evidência: x(x '+(b<0?'− '+(-b):'+ '+b)+')/x','Cancele e substitua x = 0: '+fI(b)]}); },()=>{ const a=rNZ(-4,5), c=rNZ(-4,5); if(a===c) return arNum('Limite de (x² − 9)/(x − 3) quando x → 3?',6,{d:0,c:[3,0,9]}); return arNum('Calcule o limite de ('+fPoly([1,-(a+c),a*c],'x')+')/(x '+(a<0?'+ '+(-a):'− '+a)+') quando x → '+fI(a)+'.',a-c,{d:0,neg:true,c:[a+c,a,-c],steps:['Fatore: (x '+(a<0?'+ '+(-a):'− '+a)+')(x '+(c<0?'+ '+(-c):'− '+c)+')','Cancele e substitua: '+fI(a)+' '+(c<0?'+ '+(-c):'− '+c)+' = '+fI(a-c)]}); },()=>{ const a=rNZ(-5,5); return arNum('Calcule o limite de (x² − '+(a*a)+')/(x '+(a<0?'+ '+(-a):'− '+a)+') quando x → '+fI(a)+'.',2*a,{d:0,neg:true,c:[a,0,a*a],steps:['x² − '+(a*a)+' = (x − '+fI(a)+')(x + '+fI(a)+')','Cancele: x + '+fI(a)+' → '+fI(2*a)]}); }]},
 {d:'Derivada de polinômio.',g:[()=>{ const a=rI(2,6), n=rI(2,4), k=rI(1,3); return arNum('Se f(x) = '+a+'x'+sq(n)+', quanto vale f′('+k+')?',n*a*Math.pow(k,n-1),{d:0,c:[a*Math.pow(k,n),n*a,n*a*Math.pow(k,n)],steps:['f′(x) = '+(n*a)+'x'+(n-1>1?sq(n-1):''),'f′('+k+') = '+(n*a*Math.pow(k,n-1))]}); },()=>{ const a=rI(1,4), b=rI(-5,5), c=rI(-5,5); return arCh('Derivada de f(x) = '+fPoly([a,b,c],'x')+'?','f′(x) = '+fPoly([2*a,b],'x'),['f′(x) = '+fPoly([a,b],'x'),'f′(x) = '+fPoly([2*a,b,c],'x'),'f′(x) = '+fPoly([2*a,0],'x')],{x:'Regra da potência termo a termo; a constante some.'}); }]},
 {d:'Reta tangente e regras de derivação.',g:[()=>{ const a=rI(1,3), k=rI(-2,3); return arNum('Coeficiente angular da reta tangente a y = '+a+'x² no ponto de abscissa '+fI(k)+'?',2*a*k,{d:0,neg:true,c:[a*k*k,a*k,2*k]}); },()=>{ const a=rI(2,5), b=rI(1,4); return arCh('Derivada de f(x) = ('+a+'x + '+b+')²?','f′(x) = '+(2*a)+'('+a+'x + '+b+')',['f′(x) = 2('+a+'x + '+b+')','f′(x) = '+a+'('+a+'x + '+b+')','f′(x) = ('+(2*a)+'x)²'],{x:'Regra da cadeia: 2(u)·u′, com u′ = '+a+'.'}); }]},
 {d:'Máximos e mínimos; integral simples.',g:[()=>{ const h=rI(-3,4), k=rI(-5,5); return arNum('A função f(x) = x² '+(h?(-2*h<0?'− '+(2*h):'+ '+(-2*h))+'x':'')+' + '+(h*h+k)+' tem mínimo em qual x?',h,{d:0,neg:true,c:[-h,k,2*h]}); },()=>{ const a=rI(1,3), b=rI(1,4); return arNum('Calcule a integral de '+(2*a)+'x de 0 a '+b+'.',a*b*b,{d:0,c:[2*a*b,a*b,2*a*b*b],steps:['Primitiva: '+a+'x²','De 0 a '+b+': '+a+' × '+(b*b)+' = '+(a*b*b)]}); }]}]);
