
/* ===================== ARENA: FÍSICA =====================
   Situações de bombeiro com números novos a cada rodada, conceitos com distratores
   plausíveis e gráficos para ler. g = 10 m/s² em todo o jogo. */
const fg=(id,t,nome,ic,desc,lv)=>arGame({id,s:'fis',t,nome,ic,desc,lv});

fg('ar-fis-unid','fis-unid','Unidades e ordens de grandeza','SI','Unidades do SI, conversões, prefixos, notação científica e análise dimensional.',[
 {d:'Grandeza e unidade no SI.',g:[cq([['Força','newton (N)'],['Energia','joule (J)'],['Potência','watt (W)'],['Pressão','pascal (Pa)'],['Carga elétrica','coulomb (C)'],['Corrente elétrica','ampère (A)'],['Resistência elétrica','ohm (Ω)'],['Tensão elétrica','volt (V)'],['Frequência','hertz (Hz)'],['Temperatura','kelvin (K)'],['Massa','quilograma (kg)'],['Quantidade de matéria','mol (mol)']],'Qual a unidade no SI de:')]},
 {d:'Conversões: km/h e m/s, cm, g, min.',g:[()=>{ const ms=rP([5,10,15,20,25,30]); return rC(.5)?arNum('Quanto é '+fN(ms*3.6,0)+' km/h em m/s?',ms,{d:0,u:'m/s',c:[ms*3.6*3.6,ms*36,ms*2]}):arNum('Quanto é '+ms+' m/s em km/h?',ms*3.6,{d:0,u:'km/h',c:[ms/3.6,ms*10,ms*36]}); },()=>{ const v=rI(2,90); const k=rI(0,2); return k===0?arNum(v+' cm equivalem a quantos metros?',v/100,{d:2,u:'m',c:[v/10,v/1000,v*100]}):k===1?arNum(v+' g equivalem a quantos kg?',v/1000,{d:3,u:'kg',c:[v/100,v/10,v*1000]}):arNum(v+' minutos equivalem a quantos segundos?',v*60,{d:0,u:'s',c:[v*100,v/60,v*3600]}); }]},
 {d:'Notação científica.',g:[()=>{ const m=rI(11,99)/10, e=rP([-6,-5,-4,-3,3,4,5,6,7]); const f=(a,b)=>fN(a,1)+' × 10'+sq(b); const dec=Number((m*Math.pow(10,e)).toPrecision(2)).toLocaleString('pt-BR',{maximumFractionDigits:10}); return arCh('Escreva '+dec+' em notação científica.',f(m,e),[f(m,e+1),f(m,e-1),f(m,-e),f(m*10,e-1)],{x:'Um algarismo antes da vírgula: '+f(m,e)+'.'}); }]},
 {d:'Prefixos: mili, micro, nano, quilo, mega, giga.',g:[()=>{ const P=rP([['k','10³','quilo'],['M','10⁶','mega'],['G','10⁹','giga'],['m','10⁻³','mili'],['μ','10⁻⁶','micro'],['n','10⁻⁹','nano']]); return arCh('O prefixo '+P[2]+' ('+P[0]+') equivale a:',P[1],['10³','10⁶','10⁹','10⁻³','10⁻⁶','10⁻⁹','10²','10⁻²'].filter(x=>x!==P[1]),{x:P[2]+' = '+P[1]+'.'}); },()=>{ const v=rI(2,90); const k=rI(0,2); return k===0?arNum(v+' mA equivalem a quantos A?',v/1000,{d:3,u:'A',c:[v/100,v*1000,v/10]}):k===1?arNum(v+' km equivalem a quantos metros?',v*1000,{d:0,u:'m',c:[v*100,v/1000,v*10000]}):arNum(v+' MW equivalem a quantos kW?',v*1000,{d:0,u:'kW',c:[v*1e6,v/1000,v*100]}); }]},
 {d:'Análise dimensional e ordem de grandeza.',g:[cq([['Unidade de energia (J) em unidades de base:','kg·m²/s²','kg·m/s²|kg·m²/s|kg·m/s'],['Unidade de força (N) em unidades de base:','kg·m/s²','kg·m²/s²|kg/s²|kg·m/s'],['Unidade de pressão (Pa) em unidades de base:','kg/(m·s²)','kg·m/s²|kg·m²/s²|N·m'],['Unidade de potência (W) em unidades de base:','kg·m²/s³','kg·m²/s²|kg·m/s|J·s'],['1 kWh equivale a:','3,6 × 10⁶ J','1.000 J|3.600 J|3,6 × 10³ J'],['Ordem de grandeza de segundos em um dia (86.400 s):','10⁵','10⁴|10³|10⁶'],['Unidade de carga elétrica (C) em unidades de base:','A·s','A/s|V·A|J/V·s'],['Unidade de trabalho equivalente ao joule:','N·m','N/m|W/s|kg·m/s'],['1 cal equivale a aproximadamente:','4,2 J','1 J|42 J|0,42 J'],['1 atm equivale a aproximadamente:','10⁵ Pa','10³ Pa|10⁷ Pa|760 Pa'],['1 cavalo-vapor (cv) equivale a cerca de:','735 W','100 W|1.000 J|7.350 W']]),()=>{ const e=rI(-6,9), m=rP([1.2,2,3.5,4.1,6,8.7]); const og=m<3.16?e:e+1; return arNum('Qual a ordem de grandeza (expoente de 10) de '+fN(m,1)+' × 10'+sq(e)+'?',og,{d:0,neg:true,c:[e,og+1,og-1],steps:['Compare a mantissa com √10 ≈ 3,16: '+(m<3.16?'menor → mantém '+e:'maior → sobe para '+(e+1))]}); }]}]);

fg('ar-fis-cin','fis-cin','Cinemática','v','Velocidade média, MU, MUV, queda livre, lançamentos e gráficos.',[
 {d:'Velocidade média.',g:[()=>{ const t=rI(2,6), v=rP([40,50,60,70,80,90,100]); return arNum('Uma viatura percorre '+(v*t)+' km em '+t+' h. Velocidade média?',v,{d:0,u:'km/h',c:[v*t*t,v+10,v*t/2]}); },()=>{ const d1=rP([60,120]), v1=rP([60,40]), d2=rP([60,120]), v2=rP([30,120]); const T=d1/v1+d2/v2, vm=(d1+d2)/T; return arNum('Uma viatura faz '+d1+' km a '+v1+' km/h e depois '+d2+' km a '+v2+' km/h. Velocidade média do trajeto todo?',vm,{d:1,u:'km/h',c:[(v1+v2)/2,d1+d2,vm+10]}); }]},
 {d:'MU: função horária e encontro.',g:[()=>{ const s0=rI(0,50), v=rI(2,20), t=rI(2,10); return arNum('s = '+s0+' + '+v+'t (SI). Posição em t = '+t+' s?',s0+v*t,{d:0,u:'m',c:[v*t,s0*v*t,s0+v]}); },()=>{ const d=rP([100,200,300,600]), va=rP([10,20,30]), vb=rP([10,20]); return arNum('Dois veículos, a '+d+' m um do outro, vão um ao encontro do outro a '+va+' m/s e '+vb+' m/s. Em quantos segundos se encontram?',d/(va+vb),{d:1,u:'s',c:[d/Math.abs(va-vb||1),d/va,d/(va+vb)*2]}); }]},
 {d:'MUV: velocidade, Torricelli.',g:[()=>{ const v0=rI(0,10), a=rI(1,5), t=rI(2,10); return arNum('v₀ = '+v0+' m/s, a = '+a+' m/s². Velocidade após '+t+' s?',v0+a*t,{d:0,u:'m/s',c:[a*t,v0*a*t,v0+a]}); },()=>{ const v0=rP([10,20,30]), a=rP([2,4,5]); return arNum('Uma viatura a '+v0+' m/s freia com '+a+' m/s². Distância até parar?',v0*v0/(2*a),{d:1,u:'m',c:[v0*v0/a,v0/a,v0*a],steps:['Torricelli: v² = v₀² − 2aΔs','0 = '+(v0*v0)+' − '+(2*a)+'·Δs → Δs = '+fN(v0*v0/(2*a),1)+' m']}); }]},
 {d:'Queda livre e lançamento vertical.',g:[()=>{ const t=rI(1,5); return rC(.5)?arNum('Um objeto cai do repouso. Velocidade após '+t+' s?',10*t,{d:0,u:'m/s',c:[5*t*t,10*t*t,t]}):arNum('Quantos metros um objeto cai do repouso em '+t+' s?',5*t*t,{d:0,u:'m',c:[10*t,10*t*t,5*t]}); },()=>{ const v=rP([10,20,30,40]); return arNum('Uma bola é lançada para cima a '+v+' m/s. Altura máxima?',v*v/20,{d:0,u:'m',c:[v*v/10,v/10,v*2]}); }]},
 {d:'Gráficos v × t e lançamento horizontal.',g:[()=>{ const v1=rI(2,10), t1=rI(2,5); return arNum('O gráfico mostra a velocidade de um móvel. Qual o deslocamento de 0 a '+t1+' s?',v1*t1/2,{d:1,u:'m',fig:fgPlot({xr:[0,6],yr:[0,12],sx:1,sy:2,xl:'t (s)',yl:'v (m/s)',segs:[[0,0,t1,v1],[t1,v1,6,v1]],label:'Gráfico v × t'}),c:[v1*t1,v1/t1,v1]}); },()=>{ const v=rI(2,12), t=rI(2,5); return arNum('Pelo gráfico, qual a aceleração no trecho inicial?',v/t,{d:2,u:'m/s²',fig:fgPlot({xr:[0,6],yr:[0,12],sx:1,sy:2,xl:'t (s)',yl:'v (m/s)',segs:[[0,0,t,v],[t,v,6,v]],label:'Gráfico v × t'}),c:[v*t,v*t/2,t/v]}); },()=>{ const h=rP([5,20,45,80]), v=rP([2,5,10]); const t=Math.sqrt(h/5); return arNum('Uma pedra é lançada horizontalmente a '+v+' m/s de uma altura de '+h+' m. Alcance horizontal?',v*t,{d:0,u:'m',c:[v*h/10,h,v*t*2]}); }]}]);

fg('ar-fis-din','fis-din','Leis de Newton','F=ma','As três leis, força resultante, atrito, plano inclinado, elevador e força centrípeta.',[
 {d:'Qual lei de Newton explica?',g:[cq([['O passageiro é lançado para a frente quando o ônibus freia.','1ª lei (inércia)'],['O bombeiro sente a mangueira empurrá-lo para trás ao lançar água.','3ª lei (ação e reação)'],['Quanto maior a força sobre o carrinho, maior a aceleração.','2ª lei (F = m·a)'],['Um foguete sobe expelindo gases para baixo.','3ª lei (ação e reação)'],['Um livro sobre a mesa permanece parado.','1ª lei (inércia)'],['Um caminhão carregado demora mais para acelerar que um vazio.','2ª lei (F = m·a)'],['O cinto de segurança segura o motorista numa freada brusca.','1ª lei (inércia)'],['Ao remar, o barco vai para a frente porque o remo empurra a água para trás.','3ª lei (ação e reação)'],['Um chute mais forte faz a bola sair mais rápido.','2ª lei (F = m·a)'],['Ao pular do barco para o cais, o barco se afasta.','3ª lei (ação e reação)'],['Puxar a toalha rapidamente sem derrubar os pratos.','1ª lei (inércia)'],['A arma recua quando dispara.','3ª lei (ação e reação)'],['Empurrar um carro vazio é mais fácil do que um cheio.','2ª lei (F = m·a)']],'Qual lei de Newton explica a situação?')]},
 {d:'F = m·a e peso.',g:[()=>{ const m=rI(2,50), a=rI(1,6); return arNum('Força resultante para acelerar '+m+' kg a '+a+' m/s²?',m*a,{d:0,u:'N',c:[m+a,m/a,m*a*10]}); },()=>{ const m=rI(2,120); return arNum('Peso de um corpo de '+m+' kg (g = 10)?',m*10,{d:0,u:'N',c:[m,m/10,m*100]}); }]},
 {d:'Força resultante e atrito.',g:[()=>{ const [a,b,c]=rP([[3,4,5],[6,8,10],[9,12,15],[30,40,50]]); return arNum('Duas forças perpendiculares de '+a+' N e '+b+' N atuam num corpo. Resultante?',c,{d:0,u:'N',c:[a+b,b-a,a*b]}); },()=>{ const m=rI(2,20), mu=rP([0.1,0.2,0.3,0.4,0.5]); return arNum('Um bloco de '+m+' kg desliza num piso com coeficiente de atrito '+fN(mu,1)+'. Força de atrito?',mu*m*10,{d:1,u:'N',c:[mu*m,m*10,mu*10]}); },()=>{ const F=rI(20,80), m=rI(2,10), fa=rI(5,15); return arNum('Uma força de '+F+' N puxa um bloco de '+m+' kg; o atrito vale '+fa+' N. Aceleração?',(F-fa)/m,{d:2,u:'m/s²',c:[F/m,(F+fa)/m,F-fa]}); }]},
 {d:'Plano inclinado e blocos ligados.',g:[()=>{ const m=rI(2,20); return arNum('Um bloco de '+m+' kg desce um plano inclinado a 30° sem atrito. Aceleração?',5,{d:0,u:'m/s²',c:[10,8.66,m*5]}); },()=>{ const ma=rI(2,8), mb=rI(2,8), F=rI(10,60); return arNum('Dois blocos ('+ma+' kg e '+mb+' kg) encostados são empurrados por '+F+' N num piso liso. Aceleração do conjunto?',F/(ma+mb),{d:2,u:'m/s²',c:[F/ma,F/mb,F]}); }]},
 {d:'Elevador (peso aparente) e força centrípeta.',g:[()=>{ const m=rP([50,60,70,80]), a=rI(1,3), up=rC(.5); return arNum('Uma pessoa de '+m+' kg está num elevador que '+(up?'acelera para cima':'acelera para baixo')+' a '+a+' m/s². Força normal do piso?',m*(10+(up?a:-a)),{d:0,u:'N',c:[m*10,m*(10+(up?-a:a)),m*a]}); },()=>{ const m=rI(500,1500), v=rP([10,20]), R=rP([50,100,200]); return arNum('Um carro de '+m+' kg faz uma curva de raio '+R+' m a '+v+' m/s. Força centrípeta?',m*v*v/R,{d:0,u:'N',c:[m*v/R,m*v*v,m*R/v]}); }]}]);

fg('ar-fis-ene','fis-ene','Energia em jogo','E','Energia cinética e potencial, trabalho, potência, conservação, energia elástica e rendimento.',[
 {d:'Energia cinética e potencial.',g:[()=>{ const m=rP([2,4,6,10,20,50,80]), v=rP([2,4,5,10,20]); return arNum('Energia cinética de '+m+' kg a '+v+' m/s?',m*v*v/2,{d:0,u:'J',c:[m*v,m*v*v,m*v/2]}); },()=>{ const m=rI(2,80), h=rI(1,20); return arNum('Energia potencial de '+m+' kg a '+h+' m (g = 10)?',m*10*h,{d:0,u:'J',c:[m*h,m*h*5,m*10*h*10]}); }]},
 {d:'Trabalho e potência.',g:[()=>{ const F=rI(1,20)*10, d=rI(2,20); return arNum('Trabalho de '+F+' N ao longo de '+d+' m (mesma direção)?',F*d,{d:0,u:'J',c:[F+d,F/d,F*d*2]}); },()=>{ const t=rI(2,10), P=rI(1,20)*10; return arNum('Um motor realiza '+(P*t)+' J em '+t+' s. Potência?',P,{d:0,u:'W',c:[P*t*t,P*t,P*2]}); }]},
 {d:'Conservação da energia mecânica.',g:[()=>{ const k=rI(1,6), h0=rI(0,1)?0:rP([5,20]); const H=5*k*k; return h0?arNum('Um objeto parte do repouso a '+(H+h0)+' m de altura. Qual sua velocidade ao passar a '+h0+' m do chão, sem atrito?',10*k,{d:0,u:'m/s',c:[Math.sqrt(20*(H+h0)),10*k*2,H]}):arNum('Um bombeiro deixa cair uma ferramenta de '+H+' m. Velocidade ao tocar o chão, sem atrito?',10*k,{d:0,u:'m/s',c:[20*H,10*H,5*k]}); },()=>{ const h=rP([5,20,45,80]); return arNum('Um objeto cai de '+h+' m, sem atrito. Velocidade ao chegar ao solo?',Math.sqrt(20*h),{d:0,u:'m/s',c:[10*h,20*h,Math.sqrt(10*h)]}); },()=>{ const v=rP([10,20,30]); return arNum('Uma bola sobe a partir de '+v+' m/s, sem atrito. Altura máxima?',v*v/20,{d:0,u:'m',c:[v*v/10,v/2,v*2]}); }]},
 {d:'Energia elástica, trabalho com ângulo e rendimento.',g:[()=>{ const k=rP([100,200,400,500]), x=rP([0.1,0.2,0.5]); return arNum('Mola de k = '+k+' N/m comprimida '+fN(x,1)+' m. Energia elástica?',k*x*x/2,{d:1,u:'J',c:[k*x,k*x*x,k*x/2]}); },()=>{ const F=rI(2,10)*10, d=rI(2,10); return arNum('Força de '+F+' N a 60° com o deslocamento de '+d+' m. Trabalho?',F*d/2,{d:0,u:'J',c:[F*d,F*d*0.87,F*d/4]}); },()=>{ const Pt=rP([1000,2000,4000,5000]), r=rP([60,75,80,90]); return arNum('Um motor recebe '+fN(Pt,0)+' W e tem rendimento de '+r+'%. Potência útil?',Pt*r/100,{d:0,u:'W',c:[Pt,Pt*(100-r)/100,Pt/r]}); }]},
 {d:'Bomba d’água e energia dissipada.',g:[()=>{ const V=rP([500,1000,2000]), h=rP([10,20,30]), t=rP([50,100,200]); return arNum('Uma bomba eleva '+fN(V,0)+' L de água ('+fN(V,0)+' kg) a '+h+' m em '+t+' s. Potência útil?',V*10*h/t,{d:0,u:'W',c:[V*h/t,V*10*h,V*10/t]}); },()=>{ const m=rP([2,4,5]), h=rP([5,10,20]), v=rP([6,8,10]); if(v*v/2>10*h) return arNum('Energia potencial de 2 kg a 5 m?',100,{d:0,u:'J',c:[10,50,200]}); return arNum('Um bloco de '+m+' kg desce de '+h+' m e chega embaixo a '+v+' m/s. Energia dissipada pelo atrito?',m*10*h-m*v*v/2,{d:0,u:'J',c:[m*10*h,m*v*v/2,m*h]}); }]}]);

fg('ar-fis-qm','fis-qm','Impulso e colisões','p','Quantidade de movimento, impulso, colisões, recuo e explosões.',[
 {d:'Quantidade de movimento Q = m·v.',g:[()=>{ const m=rI(2,80), v=rI(2,20); return arNum('Quantidade de movimento de '+m+' kg a '+v+' m/s?',m*v,{d:0,u:'kg·m/s',c:[m*v*v/2,m+v,m*v*2]}); }]},
 {d:'Impulso e teorema do impulso.',g:[()=>{ const F=rI(10,100), t=rP([0.1,0.2,0.5,1,2]); return arNum('Uma força de '+F+' N atua por '+fN(t,1)+' s. Impulso?',F*t,{d:1,u:'N·s',c:[F/t,F+t,F*t*10]}); },()=>{ const m=rP([0.5,1,2]), v=rP([10,20,30]); return arNum('Uma bola de '+fN(m,1)+' kg a '+v+' m/s é parada. Módulo do impulso recebido?',m*v,{d:1,u:'N·s',c:[m*v*v/2,2*m*v,v/m]}); }]},
 {d:'Colisão em que os corpos grudam.',g:[()=>{ const m1=rI(1,6)*100, v1=rI(5,20), m2=rI(1,6)*100; return arNum('Um carro de '+m1+' kg a '+v1+' m/s bate num de '+m2+' kg parado e seguem juntos. Velocidade após?',m1*v1/(m1+m2),{d:2,u:'m/s',c:[v1/2,m1*v1/m2,v1]}); }]},
 {d:'Recuo e explosão.',g:[()=>{ const M=rP([2,3,4,5]), m=rP([0.01,0.02,0.05]), v=rP([200,300,400]); return arNum('Uma arma de '+M+' kg dispara um projétil de '+fN(m,2)+' kg a '+v+' m/s. Velocidade de recuo?',m*v/M,{d:2,u:'m/s',c:[M*v/m,m*v,v/M]}); },()=>{ const m1=rI(1,4), m2=rI(1,4), v1=rI(2,8); return arNum('Um objeto parado explode em dois pedaços: '+m1+' kg sai a '+v1+' m/s. Velocidade do outro, de '+m2+' kg?',m1*v1/m2,{d:2,u:'m/s',c:[v1,m2*v1/m1,m1*v1]}); }]},
 {d:'Tipos de colisão e coeficiente de restituição.',g:[()=>{ const va=rI(4,20), e=rP([0.2,0.25,0.5,0.75,0.8,1]); const vd=va*e; return arNum('Numa colisão, a velocidade relativa de aproximação é '+va+' m/s e a de afastamento é '+fN(vd,1)+' m/s. Coeficiente de restituição?',e,{d:2,c:[1/e,va-vd,1-e]}); },()=>{ const m=rI(1,5), v=rI(2,10); return arCh('Uma bola de '+m+' kg a '+v+' m/s bate numa bola idêntica parada, em colisão elástica frontal. Depois do choque:','a primeira para e a segunda sai a '+v+' m/s',['as duas seguem juntas a '+fN(v/2,1)+' m/s','a primeira volta a '+v+' m/s e a segunda fica parada','as duas saem a '+v+' m/s'],{x:'Massas iguais em colisão elástica frontal trocam de velocidade.'}); },cq([['A energia cinética total se conserva.','Colisão elástica (e = 1)'],['Os corpos seguem grudados após o choque.','Colisão perfeitamente inelástica (e = 0)'],['Há perda parcial de energia cinética e os corpos se separam.','Colisão parcialmente elástica (0 < e < 1)'],['Grandeza que se conserva em toda colisão de sistema isolado.','Quantidade de movimento total']],'Classifique:')]}]);

fg('ar-fis-hid','fis-hid','Pressão e fluidos','P','Pressão, densidade, Stevin, Pascal, Arquimedes, vazão e continuidade no esguicho.',[
 {d:'Pressão e densidade.',g:[()=>{ const F=rP([100,200,500,1000,2000]), A=rP([0.5,1,2,4,5]); return arNum('Pressão de '+F+' N sobre '+fN(A,1)+' m²?',F/A,{d:1,u:'Pa',c:[F*A,F/A*2,F/A/10]}); },()=>{ const m=rI(2,50)*10, V=rP([0.5,1,2,4]); return arNum('Densidade de um corpo de '+m+' kg e '+fN(V,1)+' m³?',m/V,{d:1,u:'kg/m³',c:[m*V,V/m,m]}); }]},
 {d:'Pressão hidrostática (Stevin).',g:[()=>{ const h=rI(1,30); return arNum('Pressão da água (sem a atmosférica) a '+h+' m de profundidade?',1000*10*h,{d:0,u:'Pa',c:[1000*h,10*h,100000*h]}); },()=>{ const h=rP([10,20,30]); return arNum('Pressão absoluta a '+h+' m de profundidade na água, em atm (1 atm ≈ 10 m de água)?',1+h/10,{d:0,u:'atm',c:[h/10,h,2+h/10]}); }]},
 {d:'Princípio de Pascal (prensa hidráulica).',g:[()=>{ const a1=rP([2,5,10]), k=rP([5,10,20]), F=rP([20,50,100]); return arNum('Prensa hidráulica: êmbolos de '+a1+' cm² e '+(a1*k)+' cm². Força de '+F+' N no menor. Força no maior?',F*k,{d:0,u:'N',c:[F/k,F+k,F*a1]}); }]},
 {d:'Arquimedes: empuxo, flutuação, peso aparente.',g:[()=>{ const liq=rP([['água',1000],['óleo',800],['água do mar',1030],['álcool',790]]), V=rI(1,20); return arNum('Empuxo sobre um corpo de '+V+' L totalmente submerso em '+liq[0]+' (d = '+fN(liq[1],0)+' kg/m³)?',liq[1]*V/1000*10,{d:1,u:'N',c:[liq[1]*V/1000,liq[1]*V*10,V*10]}); },()=>{ const P=rI(5,20)*10, V=rI(1,4); return arNum('Um objeto pesa '+P+' N no ar e tem '+V+' L. Qual o peso aparente dentro da água?',P-V*10,{d:0,u:'N',neg:true,c:[P,P+V*10,V*10]}); },()=>{ const d=rP([200,400,500,600,800,900]), dl=1000; return arNum('Um bloco de densidade '+d+' kg/m³ flutua na água. Que fração do volume fica submersa (em %)?',d/dl*100,{d:0,u:'%',c:[100-d/10,d/10/2,100]}); },()=>{ const V=rP([0.001,0.002,0.005,0.01]); return arNum('Empuxo sobre um corpo de '+fN(V*1000,0)+' L totalmente submerso em água?',1000*V*10,{d:0,u:'N',c:[1000*V,V*10,1000*V*100]}); },cq([['Um corpo flutua quando sua densidade é…','menor que a do líquido','maior que a do líquido|igual a zero|maior que a da água sempre'],['O empuxo depende…','do volume submerso e da densidade do líquido','da massa do corpo|da profundidade|da forma do recipiente']])]},
 {d:'Vazão e continuidade (esguicho).',g:[()=>{ const A=rP([0.001,0.002,0.005]), v=rI(2,10); return arNum('Uma mangueira com seção de '+fN(A*10000,0)+' cm² tem água a '+v+' m/s. Vazão em L/s?',A*v*1000,{d:1,u:'L/s',c:[A*v,A*v*100,v]}); },()=>{ const v1=rI(2,5), k=rP([2,4,5]); return arNum('A água sai da mangueira a '+v1+' m/s. O esguicho tem área '+k+' vezes menor. Velocidade no esguicho?',v1*k,{d:0,u:'m/s',c:[v1/k,v1+k,v1*k*k]}); },()=>{ const Q=rP([100,200,300,400,600]); return arNum('Uma linha de ataque lança '+Q+' L/min. Quantos litros em '+rP([5,10,15])+' minutos?',Q*10,{d:0,u:'L',c:[Q,Q*60,Q/10]}); }]}]);

fg('ar-fis-term','fis-term','Calor e temperatura','°C','Escalas, calor sensível e latente, equilíbrio térmico e dilatação.',[
 {d:'Escalas termométricas.',g:[()=>{ const C=rI(-4,20)*5; return rC(.5)?arNum(C+' °C em kelvin?',C+273,{d:0,u:'K',c:[C-273,C+32,C*1.8+32]}):arNum(C+' °C em °F?',1.8*C+32,{d:0,u:'°F',c:[C+32,C*1.8,C+273]}); }]},
 {d:'Calor sensível Q = m·c·ΔT.',g:[()=>{ const m=rI(1,10)*50, dT=rI(1,12)*5; return arNum('Calor para aquecer '+m+' g de água em '+dT+' °C (c = 1 cal/g°C)?',m*dT,{d:0,u:'cal',c:[m+dT,m*dT/10,m*dT*4]}); }]},
 {d:'Calor latente e mudanças de estado.',g:[()=>{ const m=rP([10,50,100,200]); return arNum('Calor para derreter '+m+' g de gelo a 0 °C (L = 80 cal/g)?',m*80,{d:0,u:'cal',c:[m,m*540,m*80/10]}); },()=>{ const m=rP([10,20,50]); return arNum('Calor para vaporizar '+m+' g de água a 100 °C (L = 540 cal/g)?',m*540,{d:0,u:'cal',c:[m*80,m*100,m*54]}); },cq([['Sólido → gasoso sem passar pelo líquido','Sublimação'],['Líquido → gasoso','Vaporização'],['Gasoso → líquido','Condensação (liquefação)'],['Líquido → sólido','Solidificação'],['Sólido → líquido','Fusão']],'Nome da mudança:')]},
 {d:'Equilíbrio térmico (misturas).',g:[()=>{ const m1=rP([100,200,300]), t1=rP([20,30,40]), m2=rP([100,200,300]), t2=rP([60,80,90]); return arNum('Misturam-se '+m1+' g de água a '+t1+' °C com '+m2+' g a '+t2+' °C. Temperatura de equilíbrio?',(m1*t1+m2*t2)/(m1+m2),{d:1,u:'°C',c:[(t1+t2)/2,t2-t1,(m1*t2+m2*t1)/(m1+m2)]}); }]},
 {d:'Dilatação e capacidade térmica.',g:[()=>{ const L=rP([10,20,50,100]), a=rP([1.2e-5,2.4e-5]), dT=rP([50,100]); return arNum('Uma barra de '+L+' m (α = '+fN(a*1e5,1)+' × 10⁻⁵ /°C) aquece '+dT+' °C. Dilatação em mm?',L*a*dT*1000,{d:1,u:'mm',c:[L*a*dT,L*a*dT*100,L*dT/1000]}); },()=>{ const C=rP([50,100,200]), dT=rP([10,20,30]); return arNum('Um corpo de capacidade térmica '+C+' cal/°C varia '+dT+' °C. Calor trocado?',C*dT,{d:0,u:'cal',c:[C/dT,C+dT,C*dT/10]}); }]}]);

fg('ar-fis-tdin','fis-tdin','Máquinas térmicas','ΔU','Transformações gasosas, 1ª lei, trabalho, rendimento e Carnot.',[
 {d:'Tipos de transformação.',g:[cq([['Temperatura constante','Isotérmica'],['Pressão constante','Isobárica'],['Volume constante','Isocórica (isovolumétrica)'],['Sem troca de calor com o meio','Adiabática'],['Gás aquecido num botijão fechado e rígido','Isocórica (isovolumétrica)'],['Ar comprimido rapidamente numa bomba de bicicleta','Adiabática'],['Seringa tampada empurrada bem devagar, em equilíbrio térmico','Isotérmica'],['Gás num cilindro com êmbolo livre, aquecido ao sol','Isobárica'],['Spray que esfria ao ser liberado rapidamente','Adiabática'],['Gráfico p × V com reta horizontal','Isobárica'],['Gráfico p × V com reta vertical','Isocórica (isovolumétrica)'],['Gráfico p × V em forma de hipérbole','Isotérmica']],'Qual transformação:')]},
 {d:'Trabalho isobárico W = p·ΔV.',g:[()=>{ const p=rI(1,9)*1e5, dV=rI(1,9)/100; return arNum('Um gás a '+fN(p,0)+' Pa expande '+fN(dV,2)+' m³ a pressão constante. Trabalho?',p*dV,{d:0,u:'J',c:[p/dV,p*dV*10,p*dV/2]}); }]},
 {d:'1ª lei: Q = W + ΔU.',g:[()=>{ const Q=rI(2,20)*100, W=rI(1,10)*50; return arNum('Um gás recebe '+Q+' J de calor e realiza '+W+' J de trabalho. Variação da energia interna?',Q-W,{d:0,u:'J',neg:true,c:[Q+W,W-Q,Q]}); },cq([['Numa transformação isotérmica de gás ideal, ΔU é:','zero','máxima|igual ao calor|negativa sempre'],['Numa isocórica, o trabalho é:','zero','igual a Q|igual a ΔU e ao calor ao mesmo tempo|máximo']])]},
 {d:'Rendimento e Carnot.',g:[()=>{ const Q1=rP([1000,2000,5000]), r=rP([20,25,30,40]); return arNum('Uma máquina recebe '+fN(Q1,0)+' J da fonte quente e realiza '+(Q1*r/100)+' J de trabalho. Rendimento?',r,{d:0,u:'%',c:[100-r,r/2,r*2]}); },()=>{ const Tq=rP([400,500,600,800]), Tf=rP([200,300]); return arNum('Rendimento máximo (Carnot) entre '+Tq+' K e '+Tf+' K?',(1-Tf/Tq)*100,{d:0,u:'%',c:[Tf/Tq*100,(Tq-Tf)/Tf*100,50]}); }]},
 {d:'Gases ideais e gráfico p × V.',g:[()=>{ const n=rP([1,2]), T=rP([273,300]); return arCh('Qual o volume de '+n+' mol de gás ideal a '+T+' K e 1 atm (R = 0,082)?',fN(n*0.082*T,1)+' L',[fN(n*0.082*T/2,1)+' L',fN(n*22.4,1)+' L',fN(n*0.082*T*2,1)+' L'],{x:'V = nRT/p.'}); },()=>{ const p=rI(1,5), V1=rI(1,3), V2=V1+rI(1,4); return arNum('Pelo gráfico (p em 10⁵ Pa, V em m³), qual o trabalho na expansão isobárica, em 10⁵ J?',p*(V2-V1),{d:0,fig:fgPlot({xr:[0,8],yr:[0,6],sx:1,sy:1,xl:'V',yl:'p',segs:[[V1,p,V2,p]],area:[[[V1,0],[V1,p],[V2,p],[V2,0]]],label:'Gráfico p × V'}),c:[p*V2,V2-V1,p]}); }]}]);

fg('ar-fis-ond','fis-ond','Ondas e som','λ','v = λf, tipos de onda, fenômenos, som, eco e harmônicos.',[
 {d:'Equação fundamental v = λ·f.',g:[()=>{ const l=rP([0.5,1,2,3,4,5]), f=rP([10,20,50,100,170]); return arNum('Onda de comprimento '+fN(l,1)+' m e frequência '+f+' Hz. Velocidade?',l*f,{d:0,u:'m/s',c:[f/l,l+f,l*f*2]}); }]},
 {d:'Período, frequência e classificação.',g:[()=>{ const f=rP([2,4,5,10,20,25,50,100]); return arNum('Uma onda tem frequência de '+f+' Hz. Qual o período?',1/f,{d:3,u:'s',c:[f,f/10,2/f]}); },()=>{ const T=rP([0.1,0.2,0.5,0.02,0.04,0.25,0.01,0.05]); return arNum('Período de '+fN(T,2)+' s. Frequência?',1/T,{d:0,u:'Hz',c:[T,T*10,1/T/2]}); },cq([['Som no ar','Mecânica e longitudinal'],['Luz','Eletromagnética e transversal'],['Onda numa corda de violão','Mecânica e transversal'],['Ondas de rádio','Eletromagnética e transversal'],['Ultrassom','Mecânica e longitudinal']],'Classifique:')]},
 {d:'Fenômenos ondulatórios.',g:[cq([['Ouvir alguém atrás de um muro','Difração'],['Canudo parece quebrado dentro do copo','Refração'],['Eco numa caverna','Reflexão'],['Taça que se quebra com uma nota musical','Ressonância'],['Sirene fica mais aguda ao se aproximar','Efeito Doppler'],['Cores numa bolha de sabão','Interferência'],['Arco-íris após a chuva','Dispersão (refração)'],['Ondas do mar mudando de direção ao chegar na praia','Refração'],['Rádio AM captado atrás de montanhas','Difração'],['Ponte que oscila com o vento no ritmo certo','Ressonância'],['Radar de velocidade medindo carros','Efeito Doppler'],['Fone com cancelamento de ruído','Interferência destrutiva'],['Imagem no espelho','Reflexão'],['Luz polarizada em óculos de sol','Polarização']],'Qual fenômeno explica:')]},
 {d:'Qualidades do som e eco.',g:[cq([['Diferencia som grave de agudo','Altura (frequência)'],['Diferencia som forte de fraco','Intensidade (amplitude)'],['Diferencia um violão de um piano na mesma nota','Timbre (forma da onda)'],['Aumentar o volume do rádio altera','Intensidade (amplitude)'],['Uma voz fina tem maior','Altura (frequência)']],'Qual qualidade:'),()=>{ const t=rI(1,30)/10; return arNum('Um grito volta como eco após '+fN(t,1)+' s. Distância até o obstáculo (som a 340 m/s)?',340*t/2,{d:0,u:'m',c:[340*t,340/t,170*t*2]}); },()=>{ const d=rI(2,20)*34; return arNum('Um trovão é ouvido '+fN(d/340,1)+' s depois do relâmpago. A que distância caiu (som a 340 m/s)?',d,{d:0,u:'m',c:[d/2,340,d*2]}); }]},
 {d:'Harmônicos e nível sonoro.',g:[()=>{ const L=rP([0.5,1,2]), v=rP([200,340,400]), n=rI(1,3); return arNum('Corda de '+fN(L,1)+' m, v = '+v+' m/s. Frequência do '+n+'º harmônico?',n*v/(2*L),{d:0,u:'Hz',c:[v/(2*L),n*v/L,n*v*L]}); },cq([['Aumentar 10 dB significa multiplicar a intensidade por','10','2|20|100'],['Aumentar 20 dB significa multiplicar a intensidade por','100','20|2|40']])]}]);

fg('ar-fis-opt','fis-opt','Óptica','◐','Propagação da luz, espelhos, refração, lentes e defeitos da visão.',[
 {d:'Princípios e cores.',g:[cq([['Uma bandeira verde vista sob luz vermelha parece','preta','verde|vermelha|branca'],['A cor branca de um objeto indica que ele','reflete todas as cores','absorve todas as cores|emite luz própria|é transparente'],['Um eclipse é explicado pela','propagação retilínea da luz','refração da luz|difração|interferência'],['A câmara escura forma imagem','invertida','direita e maior|virtual|sem forma definida'],['Sombras bem definidas se explicam pela','propagação retilínea da luz'],['Um objeto é visto vermelho sob luz branca porque','reflete o vermelho e absorve as outras cores'],['Um objeto é visto preto porque','absorve praticamente todas as cores'],['Dois feixes que se cruzam seguem sem se alterar:','independência dos raios luminosos']],'')]},
 {d:'Espelho plano.',g:[cq([['A imagem num espelho plano é:','virtual, direita e do mesmo tamanho','real e invertida|virtual e maior|real e menor'],['No espelho plano, a imagem troca','esquerda e direita (é enantiomorfa)','cima e baixo|tamanho|cor']]),()=>{ const d=rI(1,8), v=rI(1,4); return rC(.5)?arNum('Uma pessoa está a '+d+' m de um espelho plano. Distância entre ela e sua imagem?',2*d,{d:0,u:'m',c:[d,d/2,4*d]}):arNum('Uma pessoa se aproxima de um espelho plano a '+v+' m/s. Com que velocidade se aproxima da própria imagem?',2*v,{d:0,u:'m/s',c:[v,v/2,4*v]}); },()=>{ const a=rP([30,45,60,72,90,120]); return arNum('Dois espelhos planos formam '+a+'°. Quantas imagens de um objeto entre eles?',360/a-1,{d:0,c:[360/a,360/a+1,a/10]}); }]},
 {d:'Espelhos esféricos (Gauss).',g:[()=>{ const f=rP([5,10,12,15,20,30,40]), p=f*rP([2,3,4,5,1.5]); const pl=f*p/(p-f); return arNum('Espelho côncavo de foco '+f+' cm; objeto a '+fN(p,1)+' cm. Distância da imagem?',pl,{d:1,u:'cm',c:[p-f,f*p/(p+f),p]}); },()=>{ const f=rP([10,20,30,40]), p=f*rP([2,3,4]); const pl=f*p/(p-f); return arNum('Nas mesmas condições (foco '+f+' cm, objeto a '+p+' cm), qual o aumento linear (|A| = p′/p)?',pl/p,{d:2,c:[p/pl,pl,f/p]}); },cq([['Espelho convexo forma imagem','sempre virtual, direita e menor','real e invertida|virtual e maior|real e maior'],['Retrovisor de moto e espelho de segurança de garagem são','convexos','côncavos|planos|parabólicos'],['Espelho de maquiagem que aumenta o rosto é','côncavo, com o rosto entre o foco e o espelho','convexo|plano|côncavo, com o rosto além do centro']])]},
 {d:'Refração: índice e Snell.',g:[()=>{ const n=rP([1.2,1.25,1.33,1.5,1.6,2,2.4,2.5]); return arNum('Num meio de índice '+fN(n,2)+', a velocidade da luz é (c = 3 × 10⁸ m/s) quantos × 10⁸ m/s?',3/n,{d:2,c:[3*n,n,3/n/2]}); },()=>{ const n2=rP([['√2','45°'],['√3','60°']]); return arCh('A luz passa do ar (n = 1) para um meio de índice '+n2[0]+', com incidência de '+n2[1]+'. Qual o ângulo de refração?','30°',['45°','60°','90°','15°'],{x:'Snell: 1 · sen '+n2[1]+' = '+n2[0]+' · sen r → sen r = 1/2 → r = 30°.'}); },cq([['Condição para reflexão total:','luz indo do meio mais refringente para o menos refringente, acima do ângulo limite','luz indo do ar para a água|qualquer ângulo de incidência|só acontece em espelhos']])]},
 {d:'Lentes e defeitos da visão.',g:[()=>{ const f=rP([0.1,0.2,0.25,0.4,0.5,1,2,-0.5,-0.25,-1]); if(f<0) return arNum('Uma lente divergente tem foco de '+fN(Math.abs(f)*100,0)+' cm. Vergência em dioptrias?',1/f,{d:1,u:'di',neg:true,c:[-1/f,f,f*100]}); return arNum('Uma lente tem foco de '+fN(f*100,0)+' cm. Vergência em dioptrias?',1/f,{d:1,u:'di',c:[f,f*100,1/f/10]}); },cq([['Miopia é corrigida com lente','divergente','convergente|cilíndrica|bifocal apenas'],['Hipermetropia é corrigida com lente','convergente','divergente|cilíndrica|plana'],['Astigmatismo é corrigido com lente','cilíndrica','divergente|convergente|plana'],['A lente divergente forma imagem','sempre virtual, direita e menor','real e invertida|real e maior|virtual e maior']])]}]);

fg('ar-fis-elst','fis-elst','Eletrostática','±','Cargas, eletrização, Coulomb, campo, potencial e contato entre esferas.',[
 {d:'Atração, repulsão, condutores e eletrização.',g:[()=>{ const t=rP([['Um corpo neutro tem número igual de prótons e elétrons.',true],['Na eletrização por contato, os corpos ficam com cargas de sinais opostos.',false],['O para-raios funciona pelo poder das pontas.',true],['Dentro de um condutor em equilíbrio, o campo elétrico é nulo.',true],['Prótons se movem de um corpo para outro na eletrização.',false],['A carga elétrica é quantizada: múltipla da carga do elétron.',true],['Água pura é ótima condutora de eletricidade.',false],['Cargas de mesmo sinal se repelem.',true],['Cargas de sinais opostos se repelem.',false],['Metais são bons condutores.',true],['Borracha é boa condutora.',false],['Um corpo positivo perdeu elétrons.',true],['Na eletrização por atrito, os corpos ficam com cargas de mesmo sinal.',false],['Na indução, o induzido não toca o indutor.',true]]); return arTF(t[0],t[1],{x:t[1]?'Correto.':'Incorreto.'}); }]},
 {d:'Quantização: Q = n·e.',g:[()=>{ const q=rP([1.6,3.2,4.8,8,16,32]), e=rP([-6,-9,-12]); return arCh('Um corpo tem carga de '+fN(q,1)+' × 10'+sq(e)+' C. Quantos elétrons em excesso (e = 1,6 × 10⁻¹⁹ C)?',fN(q/1.6,0)+' × 10'+sq(e+19),[fN(q/1.6,0)+' × 10'+sq(e-19),fN(q*1.6,1)+' × 10'+sq(e+19),fN(q/1.6,0)+' × 10'+sq(e+18)],{x:'n = Q/e.'}); },()=>{ const n=rP([1,2,5,3,4])*Math.pow(10,rP([12,13,14,15])); const ex=Math.round(Math.log10(n)); const m=n/Math.pow(10,ex); return arCh('Carga de '+fN(m,0)+' × 10'+sq(ex)+' elétrons (e = 1,6 × 10⁻¹⁹ C)?',fN(m*1.6,1)+' × 10'+sq(ex-19)+' C',[fN(m*1.6,1)+' × 10'+sq(ex+19)+' C',fN(m/1.6,2)+' × 10'+sq(ex-19)+' C',fN(m*1.6,1)+' × 10'+sq(ex-18)+' C'],{x:'Q = n·e.'}); }]},
 {d:'Lei de Coulomb: proporções.',g:[()=>{ const q=rP([2,3,4]), d=rP([2,3,4]); const f=q/(d*d); return arCh('Multiplicando uma das cargas por '+q+' e a distância por '+d+', a força fica multiplicada por:',fFr(q,d*d),[fFr(q,d),fFr(q*d,1),fFr(d*d,q),fFr(q*q,d*d)],{x:'F ∝ Q/d²: '+q+'/'+(d*d)+'.'}); },()=>{ const k=rP([2,3,4]), mode=rI(0,2); const r=mode===0?['Dobrando/triplicando a distância',1/(k*k)]:mode===1?['Multiplicando uma das cargas por '+k,k]:['Multiplicando as duas cargas por '+k,k*k]; const txt=mode===0?'Multiplicando a distância por '+k:r[0]; return arCh(txt+', a força elétrica fica multiplicada por:',fFr(mode===0?1:r[1],mode===0?k*k:1),[fFr(1,k),String(k),String(k*k),fFr(1,k*k),String(2*k)].filter(x=>x!==fFr(mode===0?1:r[1],mode===0?k*k:1)),{x:'F = k·Q·q/d²: proporcional às cargas e inversamente ao quadrado da distância.'}); }]},
 {d:'Campo elétrico.',g:[()=>{ const Q=rP([1,2,3,4,5]), d=rP([0.1,0.2,0.3,0.5,1]); return arNum('Campo elétrico a '+fN(d,1)+' m de uma carga de '+Q+' μC (k = 9 × 10⁹), em 10⁵ N/C?',9e9*Q*1e-6/(d*d)/1e5,{d:1,c:[9e9*Q*1e-6/d/1e5,9e9*Q*1e-6/(d*d)/1e4,9*Q/d]}); },()=>{ const F=rI(1,9)*1e-3, q=rP([1,2,4,5])*1e-6; return arNum('Uma carga de '+fN(q*1e6,0)+' μC sofre força de '+fN(F*1e3,0)+' mN. Intensidade do campo, em N/C?',F/q,{d:0,u:'N/C',c:[F*q,q/F,F/q/10]}); }]},
 {d:'Contato entre esferas e trabalho elétrico.',g:[()=>{ const a=rI(-6,10), b=rI(-6,10); return arNum('Duas esferas iguais com '+fI(a)+' μC e '+fI(b)+' μC se tocam e se separam. Carga final de cada uma, em μC?',(a+b)/2,{d:1,neg:true,c:[a+b,a-b,(a-b)/2]}); },()=>{ const q=rP([2,4,5])*1e-6, U=rP([100,200,500]); return arNum('Trabalho para levar '+fN(q*1e6,0)+' μC por uma ddp de '+U+' V, em mJ?',q*U*1000,{d:1,u:'mJ',c:[q*U,U/q/1e6,q*U*1e6]}); }]}]);

fg('ar-fis-eldin','fis-eldin','Circuitos elétricos','Ω','Ohm, potência, consumo, associações, circuitos mistos e geradores.',[
 {d:'Lei de Ohm U = R·i.',g:[()=>{ const R=rP([2,4,5,10,20,50]), i=rI(1,5); const k=rI(0,1); return k?arNum('Tensão num resistor de '+R+' Ω com '+i+' A?',R*i,{d:0,u:'V',c:[R/i,R+i,R*i*2]}):arNum('Corrente num resistor de '+R+' Ω ligado a '+(R*i)+' V?',i,{d:0,u:'A',c:[R*R*i,R/(R*i),i+1]}); }]},
 {d:'Potência e consumo em kWh.',g:[()=>{ const U=rP([110,127,220]), i=rP([5,10,20,25]); return arNum('Aparelho em '+U+' V com '+i+' A. Potência?',U*i,{d:0,u:'W',c:[U/i,U+i,U*i/2]}); },()=>{ const P=rP([1000,2000,4000,5500]), h=rP([0.5,1,2]), d=30, pr=rP([0.8,1]); return arNum('Um chuveiro de '+fN(P,0)+' W fica ligado '+fN(h,1)+' h por dia durante 30 dias. Consumo em kWh?',P/1000*h*d,{d:0,u:'kWh',c:[P*h*d,P/1000*h,P/1000*d]}); }]},
 {d:'Associação em série e em paralelo.',g:[()=>{ const rs=[rP([2,4,6]),rP([3,5,10]),rP([2,4,8])]; return arNum('Resistência equivalente do circuito em série?',rs[0]+rs[1]+rs[2],{d:0,u:'Ω',fig:fgCirc('serie',rs.map((r,i)=>'R'+sb(i+1)+' = '+r+' Ω')),c:[rs[0]*rs[1]*rs[2],1/(1/rs[0]+1/rs[1]+1/rs[2]),rs[0]+rs[1]]}); },()=>{ const [a,b]=rP([[6,3],[12,6],[4,4],[10,10],[20,5],[12,4]]); return arNum('Resistência equivalente em paralelo?',a*b/(a+b),{d:1,u:'Ω',fig:fgCirc('paralelo',['R₁ = '+a+' Ω','R₂ = '+b+' Ω']),c:[a+b,a*b,(a+b)/2]}); }]},
 {d:'Circuitos com fonte: corrente total.',g:[()=>{ const [a,b]=rP([[6,3],[12,6],[4,4],[10,10],[12,4]]), U=rP([12,24,36]); const Req=a*b/(a+b); return arNum('Corrente total fornecida pela fonte de '+U+' V?',U/Req,{d:1,u:'A',fig:fgCirc('paralelo',['R₁ = '+a+' Ω','R₂ = '+b+' Ω'],U),c:[U/(a+b),U/a,U*Req]}); },()=>{ const rs=[rP([2,4]),rP([4,6]),rP([2,6])], U=rP([12,24,36]); const R=rs[0]+rs[1]+rs[2]; return arNum('Corrente no circuito em série ligado a '+U+' V?',U/R,{d:2,u:'A',fig:fgCirc('serie',rs.map((r,i)=>'R'+sb(i+1)+' = '+r+' Ω'),U),c:[U*R,U/rs[0],R/U]}); }]},
 {d:'Gerador real, P = U²/R e o chuveiro.',g:[()=>{ const E=rP([12,24]), r=rP([1,2]), R=rP([4,5,10]); return arNum('Gerador de fem '+E+' V e resistência interna '+r+' Ω alimenta um resistor de '+R+' Ω. Corrente?',E/(R+r),{d:2,u:'A',c:[E/R,E/r,E*(R+r)]}); },cq([['Chuveiro: na posição "inverno", a resistência é','menor, e a potência maior','maior, e a potência maior|igual, só muda a tensão|menor, e a potência menor'],['Fusível e disjuntor servem para','interromper a corrente quando ela passa do limite','aumentar a tensão|armazenar carga|reduzir o consumo mensal'],['Lâmpadas de uma casa são ligadas em','paralelo, com a mesma tensão','série, com a mesma corrente|série, com a mesma tensão|misto obrigatório']])]}]);

fg('ar-fis-msolid','fis-msolid','Alavancas, polias e gravitação','⚖','Hooke, alavancas, torque, equilíbrio, polias de resgate e gravitação.',[
 {d:'Lei de Hooke e tipos de alavanca.',g:[()=>{ const k=rP([100,200,500]), x=rP([0.02,0.05,0.1,0.2]); return arNum('Mola de k = '+k+' N/m deformada '+fN(x*100,0)+' cm. Força elástica?',k*x,{d:0,u:'N',c:[k*x*100,k/x,k*x*x/2]}); },cq([['Tesoura','Interfixa'],['Gangorra','Interfixa'],['Carrinho de mão','Inter-resistente'],['Quebra-nozes','Inter-resistente'],['Pinça','Interpotente'],['Antebraço levantando peso','Interpotente']],'Tipo de alavanca:')]},
 {d:'Momento de força (torque).',g:[()=>{ const F=rI(2,20)*10, d=rP([0.2,0.5,1,2]); return arNum('Força de '+F+' N aplicada a '+fN(d,1)+' m do eixo, perpendicular. Momento?',F*d,{d:0,u:'N·m',c:[F/d,F+d,F*d*2]}); }]},
 {d:'Equilíbrio da alavanca.',g:[()=>{ const P=rP([200,400,600,800]), d1=rP([0.5,1]), d2=rP([2,4]); return arNum('Uma barra de ferro levanta uma pedra de '+P+' N a '+fN(d1,1)+' m do apoio, com a força a '+d2+' m do outro lado. Força necessária?',P*d1/d2,{d:0,u:'N',c:[P*d2/d1,P,P/2]}); }]},
 {d:'Polias móveis (vantagem mecânica no resgate).',g:[()=>{ const P=rP([400,800,1200,1600]), n=rI(1,3); return arNum('Para içar uma vítima de '+P+' N com '+n+' polia(s) móvel(is), qual a força mínima?',P/Math.pow(2,n),{d:0,u:'N',c:[P/n,P,P/(2*n+1)]}); },cq([['Uma polia fixa','só muda a direção da força','divide a força por 2|multiplica a força|elimina o peso']])]},
 {d:'Gravitação e leis de Kepler.',g:[()=>{ const k=rP([2,3,4]), mode=rI(0,1); return mode?arCh('Se a distância entre dois corpos for multiplicada por '+k+', a força gravitacional fica multiplicada por:','1/'+(k*k),['1/'+k,String(k),String(k*k)],{x:'F = G·M·m/d²'}):arCh('Se a massa de um dos corpos for multiplicada por '+k+', a força gravitacional:','fica multiplicada por '+k,['fica dividida por '+k,'fica multiplicada por '+(k*k),'não se altera'],{x:'Proporcional às massas.'}); },cq([['As órbitas dos planetas são elipses, com o Sol num dos focos.','1ª lei de Kepler'],['O raio vetor varre áreas iguais em tempos iguais.','2ª lei de Kepler'],['T² é proporcional ao cubo do raio médio da órbita.','3ª lei de Kepler'],['O planeta é mais rápido quando está mais perto do Sol.','2ª lei de Kepler'],['Planetas mais distantes do Sol têm ano mais longo.','3ª lei de Kepler']],'Qual lei:'),()=>{ const m=rP([2,3,4]), r=rP([2,3,4]); return arCh('Um planeta tem '+m+' vezes a massa da Terra e '+r+' vezes o raio. A gravidade na superfície é quantas vezes a da Terra?',fFr(m,r*r),[fFr(m,r),fFr(m*r*r,1),fFr(r*r,m)],{x:'g = GM/R²: '+m+'/'+(r*r)+'.'}); },()=>{ const P=rP([600,700,800]), g=rP([1.6,3.7,24.8]); return arNum('Um astronauta com massa de '+(P/10)+' kg vai a um astro onde g = '+fN(g,1)+' m/s². Seu peso lá?',P/10*g,{d:0,u:'N',c:[P,P/10,P/g]}); }]}]);
