
/* ===================== ARENA: QUÍMICA =====================
   Nomenclatura gerada a partir de tabelas de íons e de cadeias carbônicas, tabela periódica
   interativa, balanceamento com coeficientes, cálculos com números novos a cada rodada. */
const qg=(id,t,nome,ic,desc,lv)=>arGame({id,s:'qui',t,nome,ic,desc,lv});
const AR_EL=('H,Hidrogênio,1,1,1,1.0|He,Hélio,2,1,18,4|Li,Lítio,3,2,1,7|Be,Berílio,4,2,2,9|B,Boro,5,2,13,11|C,Carbono,6,2,14,12|N,Nitrogênio,7,2,15,14|O,Oxigênio,8,2,16,16|F,Flúor,9,2,17,19|Ne,Neônio,10,2,18,20|'+
 'Na,Sódio,11,3,1,23|Mg,Magnésio,12,3,2,24|Al,Alumínio,13,3,13,27|Si,Silício,14,3,14,28|P,Fósforo,15,3,15,31|S,Enxofre,16,3,16,32|Cl,Cloro,17,3,17,35.5|Ar,Argônio,18,3,18,40|'+
 'K,Potássio,19,4,1,39|Ca,Cálcio,20,4,2,40|Sc,Escândio,21,4,3,45|Ti,Titânio,22,4,4,48|V,Vanádio,23,4,5,51|Cr,Cromo,24,4,6,52|Mn,Manganês,25,4,7,55|Fe,Ferro,26,4,8,56|Co,Cobalto,27,4,9,59|Ni,Níquel,28,4,10,59|Cu,Cobre,29,4,11,63.5|Zn,Zinco,30,4,12,65|'+
 'Ga,Gálio,31,4,13,70|Ge,Germânio,32,4,14,73|As,Arsênio,33,4,15,75|Se,Selênio,34,4,16,79|Br,Bromo,35,4,17,80|Kr,Criptônio,36,4,18,84').split('|').map(r=>{ const a=r.split(','); return {s:a[0],n:a[1],z:+a[2],p:+a[3],g:+a[4],m:+a[5]}; });
const EL=Object.fromEntries(AR_EL.map(e=>[e.s,e]));
const FAM={1:'Metais alcalinos',2:'Metais alcalino-terrosos',13:'Família do boro',14:'Família do carbono',15:'Família do nitrogênio',16:'Calcogênios',17:'Halogênios',18:'Gases nobres'};
const famOf=e=>e.s==='H'?'Hidrogênio (não pertence a família)':e.g>=3&&e.g<=12?'Metais de transição':FAM[e.g];
const METAL=e=>(e.g<=2&&e.s!=='H')||(e.g>=3&&e.g<=12)||['Al','Ga'].indexOf(e.s)>=0;
/* classe de cor para o mapa de cores da tabela (dupla codificação: cor + posição) */
const famClass=e=>e.s==='H'?'h':e.g===1?'alk':e.g===2?'alkt':(e.g>=3&&e.g<=12)?'trans':e.g===13?'boro':e.g===14?'carbono':e.g===15?'nitro':e.g===16?'calc':e.g===17?'halo':'nobre';
const FAM_LEGEND=[['h','Hidrogênio'],['alk','Metais alcalinos'],['alkt','Metais alcalino-terrosos'],['trans','Metais de transição'],['boro','Família do boro'],['carbono','Família do carbono'],['nitro','Família do nitrogênio'],['calc','Calcogênios'],['halo','Halogênios'],['nobre','Gases nobres']];
const famSyms=k=>AR_EL.filter(e=>famClass(e)===k).map(e=>e.s);
function sheetQuiTabela(){
  const cells={}; AR_EL.forEach(e=>{ cells[e.p+'-'+e.g]=e; });
  let grid='<div class="ptwrap"><div class="ptgrid ptatlas">';
  for(let p=1;p<=4;p++) for(let g=1;g<=18;g++){ const e=cells[p+'-'+g]; grid+=e?'<span class="ptcell fam-'+famClass(e)+'" title="'+esc(e.n)+' · Z='+e.z+'"><b>'+e.s+'</b><em>'+e.z+'</em></span>':'<span class="ptcell empty"></span>'; }
  grid+='</div></div>';
  const leg='<div class="ptleg">'+FAM_LEGEND.map(([k,n])=>'<span><i style="background:color-mix(in srgb,var(--fam-'+k+') 55%,var(--surface))"></i>'+esc(n)+'</span>').join('')+'</div>';
  let h='<h2 id="sheetTitle">Atlas da tabela periódica</h2><p class="small muted">Os 36 elementos dos 4 primeiros períodos, coloridos por família — a mesma cor do jogo Mapa dos elementos. Cor + posição juntas fixam muito mais rápido do que decorar em lista.</p>'+grid+leg;
  h+=FAM_LEGEND.map(([k,n])=>{ const els=AR_EL.filter(e=>famClass(e)===k); return '<h3 style="margin-top:16px">'+esc(n)+'</h3><p class="small muted" style="margin-top:-6px">'+els.map(e=>e.n+' ('+e.s+')').join(', ')+'</p>'; }).join('');
  openSheet(h,{key:'quiTabela'});
}
/* distribuição de Linus Pauling (sem as exceções Cr e Cu) */
const SUBN=[['1s',2],['2s',2],['2p',6],['3s',2],['3p',6],['4s',2],['3d',10],['4p',6]];
function pauling(z){ const out=[]; let r=z; for(const [n,c] of SUBN){ if(r<=0) break; const k=Math.min(c,r); out.push([n,k]); r-=k; } return out; }
const fPaul=d=>d.map(([n,k])=>n+sq(k)).join(' ');
function valence(z){ const d=pauling(z); const maxN=Math.max.apply(null,d.map(x=>+x[0][0])); return {n:maxN,e:d.filter(x=>+x[0][0]===maxN).reduce((a,x)=>a+x[1],0),last:d[d.length-1]}; }

/* ---------- íons para nomenclatura inorgânica ---------- */
const CAT=[['Na','sódio',1,1],['K','potássio',1,1],['Li','lítio',1,1],['Ag','prata',1,0],['NH₄','amônio',1,0],['Ca','cálcio',2,1],['Mg','magnésio',2,0],['Ba','bário',2,1],['Zn','zinco',2,0],['Fe','ferro II',2,0],['Cu','cobre II',2,0],['Al','alumínio',3,0],['Fe','ferro III',3,0]];
const ANI=[['Cl','cloreto',1,'clorídrico',1],['Br','brometo',1,'bromídrico',1],['I','iodeto',1,'iodídrico',1],['F','fluoreto',1,'fluorídrico',0],['S','sulfeto',2,'sulfídrico',0],['NO₃','nitrato',1,'nítrico',1],['NO₂','nitrito',1,'nitroso',0],['SO₄','sulfato',2,'sulfúrico',1],['SO₃','sulfito',2,'sulfuroso',0],['CO₃','carbonato',2,'carbônico',0],['PO₄','fosfato',3,'fosfórico',0],['ClO','hipoclorito',1,'hipocloroso',0],['ClO₄','perclorato',1,'perclórico',1]];
const poly=s=>/[A-Z].*[A-Z]|₄|₃|₂/.test(s)&&s.length>2;
function grp(s,n){ if(n===1) return s; return (poly(s)||s==='NH₄'?'('+s+')':s)+sb(n); }
function saltF(c,a){ const g=gcd(c[2],a[2]); return grp(c[0],a[2]/g)+grp(a[0],c[2]/g); }
const saltN=(c,a)=>a[1]+' de '+c[1];
const acidF=a=>'H'+(a[2]>1?sb(a[2]):'')+a[0];
const baseF=c=>c[0]==='NH₄'?'NH₄OH':grp(c[0],1)+(c[2]>1?'(OH)'+sb(c[2]):'OH');

/* ---------- compostos com massa molar ---------- */
const COMP=[['H₂O',{H:2,O:1}],['CO₂',{C:1,O:2}],['NH₃',{N:1,H:3}],['CH₄',{C:1,H:4}],['NaCl',{Na:1,Cl:1}],['CaCO₃',{Ca:1,C:1,O:3}],['H₂SO₄',{H:2,S:1,O:4}],['NaOH',{Na:1,O:1,H:1}],['C₆H₁₂O₆',{C:6,H:12,O:6}],['C₂H₆O',{C:2,H:6,O:1}],['O₂',{O:2}],['HCl',{H:1,Cl:1}],['MgO',{Mg:1,O:1}],['Al₂O₃',{Al:2,O:3}],['KOH',{K:1,O:1,H:1}],['Ca(OH)₂',{Ca:1,O:2,H:2}],['Fe₂O₃',{Fe:2,O:3}],['HNO₃',{H:1,N:1,O:3}],['C₃H₈',{C:3,H:8}],['CaO',{Ca:1,O:1}],['Na₂CO₃',{Na:2,C:1,O:3}]];
const mm=c=>Object.keys(c[1]).reduce((a,k)=>a+EL[k].m*c[1][k],0);
const mmSteps=c=>Object.keys(c[1]).map(k=>c[1][k]+' × '+fN(EL[k].m,1)+' ('+k+')').join(' + ')+' = '+fN(mm(c),1)+' g/mol';

/* ---------- equações balanceadas ---------- */
const EQ=[[['H₂','O₂'],['H₂O'],[2,1,2],'Síntese'],[['N₂','H₂'],['NH₃'],[1,3,2],'Síntese'],[['CH₄','O₂'],['CO₂','H₂O'],[1,2,1,2],'Combustão'],[['C₃H₈','O₂'],['CO₂','H₂O'],[1,5,3,4],'Combustão'],[['Fe','O₂'],['Fe₂O₃'],[4,3,2],'Síntese'],[['Al','O₂'],['Al₂O₃'],[4,3,2],'Síntese'],
 [['Na','Cl₂'],['NaCl'],[2,1,2],'Síntese'],[['H₂O₂'],['H₂O','O₂'],[2,2,1],'Decomposição'],[['KClO₃'],['KCl','O₂'],[2,2,3],'Decomposição'],[['CaCO₃'],['CaO','CO₂'],[1,1,1],'Decomposição'],[['Mg','HCl'],['MgCl₂','H₂'],[1,2,1,1],'Simples troca'],[['Zn','HCl'],['ZnCl₂','H₂'],[1,2,1,1],'Simples troca'],
 [['HCl','NaOH'],['NaCl','H₂O'],[1,1,1,1],'Dupla troca'],[['H₂SO₄','NaOH'],['Na₂SO₄','H₂O'],[1,2,1,2],'Dupla troca'],[['C₂H₆O','O₂'],['CO₂','H₂O'],[1,3,2,3],'Combustão'],[['C₂H₂','O₂'],['CO₂','H₂O'],[2,5,4,2],'Combustão'],[['SO₂','O₂'],['SO₃'],[2,1,2],'Síntese'],
 [['Fe₂O₃','CO'],['Fe','CO₂'],[1,3,2,3],'Simples troca'],[['Al','HCl'],['AlCl₃','H₂'],[2,6,2,3],'Simples troca'],[['P','O₂'],['P₂O₅'],[4,5,2],'Síntese'],[['C₆H₁₂O₆','O₂'],['CO₂','H₂O'],[1,6,6,6],'Combustão'],[['NH₃','O₂'],['NO','H₂O'],[4,5,4,6],'Combustão'],
 [['C₄H₁₀','O₂'],['CO₂','H₂O'],[2,13,8,10],'Combustão'],[['Ca(OH)₂','HCl'],['CaCl₂','H₂O'],[1,2,1,2],'Dupla troca'],[['H₃PO₄','NaOH'],['Na₃PO₄','H₂O'],[1,3,1,3],'Dupla troca'],[['K','H₂O'],['KOH','H₂'],[2,2,2,1],'Simples troca'],[['AgNO₃','NaCl'],['AgCl','NaNO₃'],[1,1,1,1],'Dupla troca']];
const eqT=e=>arEqText(e[0],e[1],e[2]);

qg('ar-qui-mat','qui-mat','Matéria e separação','⚗','Substâncias e misturas, fenômenos, separação, estados físicos e curvas de aquecimento.',[
 {d:'Substância pura × mistura; homogênea × heterogênea.',g:[()=>arSort('Classifique:',['Substância pura','Mistura homogênea','Mistura heterogênea'],rN([['Água destilada',0],['Gás oxigênio',0],['Ouro 24 quilates',0],['Água e sal dissolvido',1],['Ar filtrado',1],['Álcool 70%',1],['Água e óleo',2],['Granito',2],['Água e areia',2],['Sangue (ao microscópio)',2]],5),{x:'Mistura homogênea: uma fase. Heterogênea: mais de uma fase.'})]},
 {d:'Fenômeno físico × químico.',g:[cq([['Queima do papel','Químico'],['Derretimento do gelo','Físico'],['Formação de ferrugem','Químico'],['Evaporação da água','Físico'],['Digestão dos alimentos','Químico'],['Dissolução do açúcar na água','Físico'],['Cozimento do ovo','Químico'],['Quebra de um vidro','Físico'],['Combustão da gasolina','Químico'],['Sublimação da naftalina','Físico'],['Leite azedando','Químico'],['Moer café','Físico']],'O fenômeno é:')]},
 {d:'Métodos de separação.',g:[cq([['Separar a borra do café','Filtração'],['Água e óleo','Decantação (funil de separação)'],['Obter sal nas salinas','Evaporação'],['Água pura a partir de água salgada','Destilação simples'],['Frações do petróleo','Destilação fracionada'],['Limalha de ferro e areia','Separação magnética'],['Água e álcool','Destilação fracionada'],['Separar os componentes de uma tinta','Cromatografia'],['Separar arroz de feijão à mão','Catação'],['Separar partículas do sangue','Centrifugação'],['Separar o nitrogênio e o oxigênio do ar','Liquefação e destilação fracionada'],['Tirar a poeira do ar num aspirador','Filtração'],['Separar a gordura do leite','Centrifugação'],['Obter água potável na estação de tratamento (retirar partículas que afundam)','Decantação'],['Separar areia e serragem com água','Flotação'],['Extrair o sal de uma mistura com areia usando água','Dissolução fracionada']],'Método adequado:')]},
 {d:'Estados físicos a partir de PF e PE.',g:[()=>{ const pf=rI(-120,60), pe=pf+rI(20,200), T=rP([-50,0,25,80,150]); const st=T<pf?'Sólido':T<pe?'Líquido':'Gasoso'; return arCh('Uma substância tem PF = '+pf+' °C e PE = '+pe+' °C. A '+T+' °C ela está no estado:',st,['Sólido','Líquido','Gasoso'].filter(x=>x!==st),{x:'Abaixo do PF: sólido; entre PF e PE: líquido; acima do PE: gasoso.'}); },()=>{ const pura=rC(.5); return arCh('No gráfico de aquecimento, a amostra é:',pura?'Substância pura (patamares de temperatura constante)':'Mistura (sem patamares definidos)',[pura?'Mistura (sem patamares definidos)':'Substância pura (patamares de temperatura constante)','Mistura azeotrópica','Mistura eutética'],{fig:fgPlot({xr:[0,10],yr:[-20,120],sx:2,sy:20,xl:'tempo',yl:'T (°C)',segs:pura?[[0,-20,2,0],[2,0,4,0],[4,0,6,100],[6,100,8,100],[8,100,10,120]]:[[0,-20,2,-2],[2,-2,4,8],[4,8,6,90],[6,90,8,106],[8,106,10,120]],label:'Curva de aquecimento'}),x:'Substância pura funde e ferve a temperatura constante.'}); }]},
 {d:'Densidade e misturas especiais.',g:[()=>{ const m=rP([20,40,60,80,100]), v=rP([10,20,25,50]); return arNum('Densidade de '+m+' g ocupando '+v+' mL?',m/v,{d:2,u:'g/mL',c:[v/m,m*v,m/v*10]}); },cq([['Mistura que ferve a temperatura constante','Azeotrópica'],['Mistura que funde a temperatura constante','Eutética'],['Sistema com água, gelo e óleo','Trifásico'],['Número de componentes de água + sal + areia','3 componentes']],'')]}]);

qg('ar-qui-atom','qui-atom','Átomo e tabela periódica','Z','Partículas, íons, isótopos, distribuição eletrônica, famílias e propriedades periódicas.',[
 {d:'Prótons, nêutrons e elétrons.',g:[()=>{ const e=rP(AR_EL.filter(x=>x.z>2)); const A=Math.round(e.m); return arNum('Quantos nêutrons tem o '+e.s+' (Z = '+e.z+', A = '+A+')?',A-e.z,{d:0,c:[A,e.z,A+e.z]}); }]},
 {d:'Elétrons em íons.',g:[()=>{ const e=rP(AR_EL.filter(x=>[1,2,13,15,16,17].indexOf(x.g)>=0&&x.z>2&&x.s!=='B'&&x.s!=='C'&&x.s!=='Si'&&x.s!=='Ge'&&x.s!=='As'&&x.s!=='Ga')); const c={1:1,2:2,13:3,15:-3,16:-2,17:-1}[e.g]; const ion=e.s+(Math.abs(c)>1?sq(Math.abs(c)):'')+(c>0?'⁺':'⁻'); return arNum('Quantos elétrons tem o íon '+ion+' (Z = '+e.z+')?',e.z-c,{d:0,c:[e.z,e.z+c,e.z-c+1],steps:['Cátion perde elétrons; ânion ganha.','e = '+e.z+' − ('+fI(c)+') = '+(e.z-c)]}); },()=>{ const [ion,z,c]=rP([['Ca²⁺',20,2],['Na⁺',11,1],['Cl⁻',17,-1],['Al³⁺',13,3],['O²⁻',8,-2],['K⁺',19,1],['S²⁻',16,-2],['Mg²⁺',12,2],['F⁻',9,-1],['Fe³⁺',26,3]]); return arNum('Quantos elétrons tem o íon '+ion+' (Z = '+z+')?',z-c,{d:0,c:[z,z+c,z-c+1]}); }]},
 {d:'Isótopos, isóbaros e isótonos; ache na tabela.',g:[()=>{ const Z=rI(6,30), A=Z*2+rI(0,6), t=rI(0,2); const B=t===0?[Z,A+rI(1,3)]:t===1?[Z+rI(1,3),A]:(()=>{ const dz=rI(1,3); return [Z+dz,A+dz]; })(); const nm=['Isótopos','Isóbaros','Isótonos'][t]; return arCh('Os átomos ᴬX com Z = '+Z+', A = '+A+' e Y com Z = '+B[0]+', A = '+B[1]+' são:',nm,['Isótopos','Isóbaros','Isótonos','Isoeletrônicos'].filter(x=>x!==nm),{x:'Isótopos: mesmo Z. Isóbaros: mesmo A. Isótonos: mesmo número de nêutrons.'}); },()=>{ const e=rP(AR_EL); return arPT('Toque no elemento: **'+e.n+'** (Z = '+e.z+').',e.s,{x:e.n+' ('+e.s+'): período '+e.p+', grupo '+e.g+'.'}); }]},
 {d:'Distribuição eletrônica (Linus Pauling).',g:[()=>{ const z=rP(AR_EL.filter(x=>x.z>=5&&[24,29].indexOf(x.z)<0)).z; const v=valence(z); return arNum('Quantos elétrons há na camada de valência do elemento de Z = '+z+'?',v.e,{d:0,c:[v.e+2,z%8,v.n],steps:['Distribuição: '+fPaul(pauling(z)),'Camada '+v.n+': '+v.e+' elétrons']}); },()=>{ const z=rP(AR_EL.filter(x=>x.z>=5&&[24,29].indexOf(x.z)<0)).z; const d=pauling(z), last=d[d.length-1]; const R=last[0]+sq(last[1]); const ws=SUBN.map(([n,c])=>n+sq(Math.min(c,rI(1,c)))).filter(x=>x!==R); return arCh('Subnível mais energético do elemento de Z = '+z+'?',R,ws,{x:fPaul(d)}); }]},
 {d:'Família, período e propriedades periódicas.',g:[()=>{ const e=rP(AR_EL.filter(x=>x.s!=='H')); return arCh(e.n+' ('+e.s+') pertence a:',famOf(e),['Metais alcalinos','Metais alcalino-terrosos','Metais de transição','Calcogênios','Halogênios','Gases nobres','Família do carbono'].filter(x=>x!==famOf(e)),{x:'Grupo '+e.g+', período '+e.p+'.'}); },()=>{ const [a,b]=rN(AR_EL.filter(x=>x.g!==18&&x.s!=='H'),2); const prop=rP(['maior raio atômico','maior eletronegatividade','maior energia de ionização']); const score=e=>prop==='maior raio atômico'?(e.p*20-e.g):(e.g*1-e.p*3); const win=score(a)>score(b)?a:b; if(score(a)===score(b)) return arPT('Toque no elemento: **'+a.n+'**.',a.s,{x:a.n}); return arCh('Entre '+a.n+' ('+a.s+') e '+b.n+' ('+b.s+'), qual tem '+prop+'?',win.n,[win===a?b.n:a.n],{x:prop==='maior raio atômico'?'O raio cresce para baixo e para a esquerda.':'Eletronegatividade e energia de ionização crescem para cima e para a direita.'}); }]}]);

/* ---------- Mapa dos elementos: intimidade brutal com a tabela periódica ----------
   Memória espacial (onde mora), recuperação bidirecional símbolo↔nome, reconhecimento
   de família por cor+posição (dupla codificação) e, no nível 5, tudo interleaved sem aviso. */
const elAt=(p,g)=>AR_EL.find(e=>e.p===p&&e.g===g);
const ptG1=()=>{ const e=rP(AR_EL); return arPT('Toque no elemento: **'+e.n+'**.',e.s,{x:e.n+' ('+e.s+'): período '+e.p+', grupo '+e.g+'.'}); };
const ptG1z=()=>{ const e=rP(AR_EL); return arPT('Toque no elemento de número atômico **Z = '+e.z+'**.',e.s,{x:e.s+' ('+e.n+'), período '+e.p+', grupo '+e.g+'.'}); };
const ptG2sym=()=>{ const e=rP(AR_EL); return arCh('Qual é o símbolo de **'+e.n+'**?',e.s,rN(AR_EL.filter(x=>x!==e),5).map(x=>x.s),{x:e.n+' → '+e.s+'.'}); };
const ptG2nome=()=>{ const e=rP(AR_EL); return arCh('Qual elemento tem o símbolo **'+e.s+'**?',e.n,rN(AR_EL.filter(x=>x!==e),5).map(x=>x.n),{x:e.s+' → '+e.n+'.'}); };
const ptG3fam=()=>{ const fk=rP(FAM_LEGEND.filter(([k])=>k!=='h')); const syms=famSyms(fk[0]); return arPT('Toque em QUALQUER elemento da família: **'+fk[1]+'**.',syms,{x:'Também são dessa família: '+syms.map(s=>EL[s].n).join(', ')+'.'}); };
const ptG3classif=()=>{ const e=rP(AR_EL.filter(x=>x.s!=='H')); return arCh(e.n+' ('+e.s+') pertence a:',famOf(e),FAM_LEGEND.map(([,n])=>n).filter(x=>x!==famOf(e)).slice(0,5),{x:'Grupo '+e.g+', período '+e.p+'.'}); };
const ptG4metal=()=>{ const e=rP(AR_EL.filter(x=>x.g!==18)); const t=METAL(e)?'Metal':'Ametal'; return arCh(e.n+' ('+e.s+') é:',t,['Metal','Ametal'].filter(x=>x!==t).concat('Gás nobre'),{x:'Metais ficam à esquerda e no centro da tabela; ametais, à direita; gases nobres, no grupo 18.'}); };
const ptG4viz=()=>{ const cand=AR_EL.filter(e=>elAt(e.p,e.g+1)); const e=rP(cand), nb=elAt(e.p,e.g+1); return arPT('Qual elemento fica imediatamente à direita de **'+e.n+'** ('+e.s+') no período '+e.p+'?',nb.s,{x:nb.n+' ('+nb.s+') vem logo depois de '+e.s+' no período '+e.p+'.'}); };
const ptG4trend=()=>{ const p=rP([1,2,3,4]); const row=AR_EL.filter(e=>e.p===p); const [a,b]=rN(row,2); const winA=a.g<b.g; return arCh('No período '+p+', qual fica mais à esquerda (em geral, mais metálico)?',winA?a.n:b.n,[winA?b.n:a.n],{x:'Na tabela, o caráter metálico cai da esquerda para a direita, no mesmo período.'}); };
qg('ar-qui-tabela','qui-atom','Mapa dos elementos','PT','Onde cada elemento mora, símbolo, família por cor e vizinhança na tabela — treino intenso e focado só na tabela periódica.',[
 {d:'Ache o elemento pelo nome ou pelo número atômico — fixe onde cada um mora.',g:[ptG1,ptG1z]},
 {d:'Símbolo relâmpago: vá e volte entre símbolo e nome, sem consultar a tabela.',g:[ptG2sym,ptG2nome]},
 {d:'Família em foco: toque em QUALQUER elemento da família pedida — o que importa é reconhecer o grupo pela cor e pela posição.',g:[ptG3fam,ptG3classif]},
 {d:'Vizinhança e tendências: metal ou ametal, e quem fica ao lado de quem.',g:[ptG4metal,ptG4viz,ptG4trend]},
 {d:'Domínio brutal: tudo misturado, sem aviso do que vem — o teste final de intimidade com a tabela.',g:[ptG1,ptG1z,ptG2sym,ptG2nome,ptG3fam,ptG3classif,ptG4metal,ptG4viz,ptG4trend]}
]);

qg('ar-qui-radio','qui-radio','Radioatividade','☢','Partículas α, β e γ, emissões, séries radioativas, meia-vida e aplicações.',[
 {d:'Características de α, β e γ.',g:[cq([['Formada por 2 prótons e 2 nêutrons','Partícula alfa (α)'],['É um elétron emitido do núcleo','Partícula beta (β)'],['Onda eletromagnética, sem carga e sem massa','Radiação gama (γ)'],['Maior poder de penetração','Radiação gama (γ)'],['Menor poder de penetração (barrada por uma folha de papel)','Partícula alfa (α)'],['Carga +2','Partícula alfa (α)'],['Carga −1','Partícula beta (β)'],['Barrada por alguns milímetros de alumínio','Partícula beta (β)'],['Exige chumbo ou concreto espesso para blindagem','Radiação gama (γ)'],['Equivale ao núcleo do hélio','Partícula alfa (α)'],['Não altera Z nem A do núcleo','Radiação gama (γ)'],['Aumenta o número atômico em uma unidade','Partícula beta (β)'],['Diminui o número de massa em 4','Partícula alfa (α)']],'')]},
 {d:'Nuclídeo após uma emissão.',g:[()=>{ const Z=rI(82,92), A=Z*2+rI(40,60), a=rC(.5); return arCh('Um núcleo com Z = '+Z+' e A = '+A+' emite uma partícula '+(a?'alfa':'beta')+'. O novo núcleo tem:',a?'Z = '+(Z-2)+' e A = '+(A-4):'Z = '+(Z+1)+' e A = '+A,['Z = '+(Z-2)+' e A = '+(A-4),'Z = '+(Z+1)+' e A = '+A,'Z = '+(Z-1)+' e A = '+A,'Z = '+(Z+2)+' e A = '+(A+4),'Z = '+(Z-4)+' e A = '+(A-2)].filter(x=>x!==(a?'Z = '+(Z-2)+' e A = '+(A-4):'Z = '+(Z+1)+' e A = '+A)),{x:'Alfa: Z − 2 e A − 4. Beta: Z + 1 e A igual.'}); }]},
 {d:'Séries: quantas α e β.',g:[()=>{ const Z0=rI(86,92), A0=Z0*2+rI(46,56), na=rI(2,8), nb=rI(0,Math.min(6,2*na)); const Z1=Z0-2*na+nb, A1=A0-4*na; return arCh('Um nuclídeo (Z = '+Z0+', A = '+A0+') se transforma em outro (Z = '+Z1+', A = '+A1+'). Quantas partículas α e β foram emitidas?',na+' α e '+nb+' β',[(na+1)+' α e '+nb+' β',na+' α e '+(nb+2)+' β',nb+' α e '+na+' β',(na-1)+' α e '+(nb+1)+' β'],{x:'α = ΔA/4 = '+(4*na)+'/4 = '+na+'. Z: '+Z0+' − 2·'+na+' + β = '+Z1+' → β = '+nb+'.'}); }]},
 {d:'Meia-vida.',g:[()=>{ const m0=rP([80,160,200,400,640]), T=rP([2,5,8,10]), k=rI(1,4); return arNum('Meia-vida de '+T+' anos. De '+m0+' g, quanto resta após '+(k*T)+' anos?',m0/Math.pow(2,k),{d:1,u:'g',c:[m0/(2*k),m0-k*T,m0/Math.pow(2,k)*2]}); },()=>{ const T=rP([5,8,30]), k=rI(2,5); return arNum('Uma amostra caiu a 1/'+Math.pow(2,k)+' da atividade inicial. Meia-vida de '+T+' dias. Quantos dias se passaram?',k*T,{d:0,u:'dias',c:[Math.pow(2,k)*T,T*k*2,T]}); }]},
 {d:'Fissão, fusão e aplicações.',g:[cq([['Núcleo pesado se divide em núcleos menores','Fissão nuclear'],['Núcleos leves se unem formando um mais pesado','Fusão nuclear'],['Energia do Sol','Fusão nuclear'],['Usinas de Angra dos Reis','Fissão nuclear'],['Datação de fósseis','Carbono-14'],['Acidente radiológico de Goiânia (1987)','Césio-137'],['Exames da tireoide','Iodo-131'],['Bomba de Hiroshima (1945)','Fissão nuclear'],['Acidente de Chernobyl (1986)','Fissão nuclear (usina)'],['Esterilização de alimentos e materiais cirúrgicos','Radiação gama'],['Radioterapia contra o câncer','Cobalto-60'],['Detector de fumaça residencial','Amerício-241']],'')]}]);

qg('ar-qui-lig','qui-lig','Ligações e forças','⌬','Tipo de ligação, fórmulas iônicas, geometria, polaridade e forças intermoleculares.',[
 {d:'Iônica, covalente ou metálica?',g:[()=>{ const pool=AR_EL.filter(e=>e.g!==18&&e.z<=20); const a=rP(pool), b=rP(pool); const ma=METAL(a), mb=METAL(b); const t=ma&&mb?'Metálica':(ma||mb)?'Iônica':'Covalente'; if(a===b&&!ma) return arCh('Ligação entre átomos de '+a.n+':','Covalente',['Iônica','Metálica'],{x:'Ametal com ametal: covalente.'}); return arCh('Ligação entre '+a.n+' e '+b.n+':',t,['Iônica','Covalente','Metálica'].filter(x=>x!==t),{x:'Metal + ametal: iônica; ametal + ametal (ou H): covalente; metal + metal: metálica.'}); }]},
 {d:'Fórmula do composto iônico.',g:[()=>{ const c=rP(CAT.filter(x=>x[0]!=='NH₄')), a=rP(ANI.filter(x=>x[0].length<=2)); const R=saltF(c,a); const ws=[grp(c[0],c[2])+grp(a[0],a[2]),c[0]+a[0],grp(c[0],a[2]+1)+a[0],c[0]+grp(a[0],c[2]+1)]; return arCh('Fórmula do composto formado por '+c[0]+(c[2]>1?sq(c[2]):'')+'⁺ e '+a[0]+(a[2]>1?sq(a[2]):'')+'⁻?',R,ws,{x:'Cargas cruzadas e simplificadas: '+R+'.'}); }]},
 {d:'Geometria molecular.',g:[cq([['CO₂','Linear'],['H₂O','Angular'],['NH₃','Piramidal'],['CH₄','Tetraédrica'],['BF₃','Trigonal plana'],['HCl','Linear'],['SO₂','Angular'],['CCl₄','Tetraédrica'],['PH₃','Piramidal'],['SiH₄','Tetraédrica'],['H₂S','Angular'],['BeH₂','Linear'],['SO₃','Trigonal plana'],['HCN','Linear'],['CH₂O','Trigonal plana'],['O₃','Angular']],'Geometria da molécula:')]},
 {d:'Polaridade e forças intermoleculares.',g:[cq([['H₂O','Ligação de hidrogênio'],['NH₃','Ligação de hidrogênio'],['HF','Ligação de hidrogênio'],['HCl','Dipolo-dipolo'],['CH₄','Dipolo induzido (London)'],['CO₂','Dipolo induzido (London)'],['O₂','Dipolo induzido (London)'],['H₂S','Dipolo-dipolo']],'Força intermolecular predominante:'),cq([['CO₂','Apolar'],['H₂O','Polar'],['CH₄','Apolar'],['NH₃','Polar'],['CCl₄','Apolar'],['HCl','Polar'],['O₂','Apolar']],'A molécula é:')]},
 {d:'Ebulição, solubilidade e octeto.',g:[cq([['Por que a água ferve a 100 °C e o H₂S (mais pesado) a −60 °C?','A água faz ligações de hidrogênio','O H₂S é iônico|A água é apolar|O H₂S tem mais átomos'],['Por que o óleo não se mistura com a água?','Óleo é apolar e água é polar','Óleo é mais denso|Água é apolar|Óleo é iônico'],['Quantas ligações covalentes o carbono faz (octeto)?','4','2|3|1'],['Quantas ligações covalentes o oxigênio faz (octeto)?','2','1|3|4'],['Quantas ligações covalentes o nitrogênio faz (octeto)?','3','1|2|4'],['Quantas ligações covalentes o hidrogênio faz?','1','2|3|4'],['Por que o gelo boia na água?','As ligações de hidrogênio deixam o gelo menos denso','O gelo tem mais massa|O gelo é apolar|A água líquida é iônica'],['Sal de cozinha se dissolve bem em água porque','compostos iônicos interagem com a água polar','o sal é apolar|a água é apolar|o sal é metálico'],['Entre éter (C₄H₁₀O) e butan-1-ol, qual ferve a temperatura maior?','O butan-1-ol, por fazer ligações de hidrogênio','O éter, por ser mais volátil|Os dois, igualmente|O éter, por ter mais oxigênio'],['Metais conduzem eletricidade porque','têm elétrons livres (mar de elétrons)','são iônicos|são polares|têm prótons livres']],'')]}]);

qg('ar-qui-gas','qui-gas','Gases em ação','PV','Transformações, Boyle, Charles, equação geral e Clapeyron.',[
 {d:'Qual transformação?',g:[cq([['Temperatura constante','Isotérmica (Boyle)'],['Pressão constante','Isobárica (Charles)'],['Volume constante','Isocórica (Gay-Lussac)'],['Botijão de gás exposto ao sol (recipiente rígido)','Isocórica (Gay-Lussac)'],['Balão de festa murcha na geladeira (pressão ambiente)','Isobárica (Charles)'],['Seringa tampada empurrada devagar','Isotérmica (Boyle)'],['Pneu aquece e a pressão sobe (volume quase fixo)','Isocórica (Gay-Lussac)'],['Bolha de ar que cresce ao subir do fundo do lago (temperatura constante)','Isotérmica (Boyle)'],['P e V inversamente proporcionais','Isotérmica (Boyle)'],['V diretamente proporcional a T','Isobárica (Charles)'],['P diretamente proporcional a T','Isocórica (Gay-Lussac)']],'Qual transformação:')]},
 {d:'Lei de Boyle.',g:[()=>{ const P1=rP([1,2,3,4]), V1=rP([6,8,12,24]), P2=rP([2,3,4,6]); const V2=P1*V1/P2; return arNum('Um gás ocupa '+V1+' L a '+P1+' atm. A temperatura constante, qual o volume a '+P2+' atm?',V2,{d:1,u:'L',c:[V1*P2/P1,V1+P2-P1,V2*2]}); }]},
 {d:'Charles e Gay-Lussac (em kelvin!).',g:[()=>{ const T1=rP([27,127,227]), V1=rP([2,4,6,10]), k=rP([2,1.5]); const T1K=T1+273, T2K=T1K*k, T2=T2K-273; return arNum('Um gás ocupa '+V1+' L a '+T1+' °C. A pressão constante, qual o volume a '+T2+' °C?',V1*k,{d:1,u:'L',c:[V1*T2/T1,V1*2,V1]}); },()=>{ const P1=rP([1,2,3]), T1=rP([300,400]), T2=rP([600,800,900]); return arNum('Um gás a '+P1+' atm e '+T1+' K é aquecido a '+T2+' K em volume constante. Nova pressão?',P1*T2/T1,{d:1,u:'atm',c:[P1*T1/T2,P1+T2/100,P1*2]}); }]},
 {d:'Equação geral dos gases.',g:[()=>{ const P1=rP([1,2]), V1=rP([4,6,10]), T1=rP([200,300]), P2=rP([2,4]), T2=rP([300,400,600]); return arNum('P₁ = '+P1+' atm, V₁ = '+V1+' L, T₁ = '+T1+' K → P₂ = '+P2+' atm, T₂ = '+T2+' K. Qual V₂?',P1*V1*T2/(T1*P2),{d:1,u:'L',c:[P1*V1*T1/(T2*P2),V1*P2/P1,V1]}); }]},
 {d:'Clapeyron e volume molar.',g:[()=>{ const n=rP([0.5,1,2]), T=rP([273,300,400]), P=rP([1,2]); return arNum('Volume de '+fN(n,1)+' mol de gás a '+T+' K e '+P+' atm (R = 0,082)?',n*0.082*T/P,{d:1,u:'L',c:[n*22.4,n*0.082*T*P,n*T/P]}); },()=>{ const c=rP([['CO₂',44],['O₂',32],['CH₄',16],['NH₃',17]]), m=c[1]*rP([0.5,1,2,3]); return arNum('Volume de '+fN(m,0)+' g de '+c[0]+' nas CNTP (22,4 L/mol)?',m/c[1]*22.4,{d:1,u:'L',c:[m*22.4,22.4,m/c[1]]}); }]}]);

qg('ar-qui-inorg','qui-inorg','Funções inorgânicas','H⁺','Ácidos, bases, sais e óxidos: classificação, nomes, fórmulas, força e neutralização.',[
 {d:'Ácido, base, sal ou óxido?',g:[()=>{ const k=rI(0,3); let f,t; if(k===0){ f=acidF(rP(ANI)); t='Ácido'; } else if(k===1){ f=baseF(rP(CAT.filter(c=>c[0]!=='Ag'))); t='Base'; } else if(k===2){ f=saltF(rP(CAT),rP(ANI)); t='Sal'; } else { f=rP(['CO₂','SO₃','Na₂O','CaO','Fe₂O₃','MgO','SO₂','N₂O₅','CO','ZnO','Al₂O₃','K₂O']); t='Óxido'; } return arCh('**'+f+'** é:',t,['Ácido','Base','Sal','Óxido'].filter(x=>x!==t),{x:'Ácido: começa com H. Base: termina em OH. Óxido: binário com oxigênio. Sal: cátion + ânion (não H⁺ nem OH⁻).'}); }]},
 {d:'Nomes dos ácidos (-ídrico, -ico, -oso).',g:[()=>{ const a=rP(ANI); return arCh('Nome do ácido **'+acidF(a)+'**?','ácido '+a[3],ANI.filter(x=>x!==a).map(x=>'ácido '+x[3]),{x:'Ânion -eto → ácido -ídrico; -ato → -ico; -ito → -oso. '+a[1]+' → ácido '+a[3]+'.'}); }]},
 {d:'Nomes e fórmulas de bases e sais.',g:[()=>{ const c=rP(CAT), a=rP(ANI); return arCh('Nome do sal **'+saltF(c,a)+'**?',saltN(c,a),[saltN(rP(CAT.filter(x=>x!==c)),a),saltN(c,rP(ANI.filter(x=>x!==a))),a[3]+' de '+c[1]],{x:'Nome do ânion + de + nome do cátion.'}); },()=>{ const c=rP(CAT), a=rP(ANI); return arCh('Fórmula do '+saltN(c,a)+'?',saltF(c,a),[c[0]+a[0],grp(c[0],c[2])+grp(a[0],a[2]),grp(c[0],a[2]+1)+a[0]],{x:'Cargas: '+c[0]+' ('+c[2]+'+) e '+a[0]+' ('+a[2]+'−).'}); },()=>{ const c=rP(CAT.filter(x=>x[0]!=='Ag')); return arCh('Nome de **'+baseF(c)+'**?','hidróxido de '+c[1],CAT.filter(x=>x!==c).map(x=>'hidróxido de '+x[1]),{x:'Base: hidróxido de + cátion.'}); }]},
 {d:'Força de ácidos e tipos de óxido.',g:[()=>{ const a=rP(ANI); const s=a[4]?'Forte':'Fraco ou moderado'; return arCh('O ácido **'+acidF(a)+'** é:',s,['Forte','Fraco ou moderado'].filter(x=>x!==s),{x:'Hidrácidos fortes: HCl, HBr, HI. Oxiácidos: (O − H) ≥ 2 é forte (HNO₃, H₂SO₄, HClO₄). H₂CO₃ é fraco.'}); },cq([['CO₂','Óxido ácido'],['SO₃','Óxido ácido'],['Na₂O','Óxido básico'],['CaO','Óxido básico'],['CO','Óxido neutro'],['NO','Óxido neutro'],['ZnO','Óxido anfótero'],['Al₂O₃','Óxido anfótero']],'Classifique o óxido:')]},
 {d:'Neutralização e caráter do sal.',g:[()=>{ const c=rP(CAT.filter(x=>x[3])), a=rP(ANI.filter(x=>x[0]!=='ClO')); return arCh('Qual sal se forma em '+acidF(a)+' + '+baseF(c)+'?',saltF(c,a)+' ('+saltN(c,a)+')',[c[0]+a[0]+' ('+saltN(c,a)+')',saltF(rP(CAT.filter(x=>x!==c)),a),saltF(c,rP(ANI.filter(x=>x!==a)))],{x:'Ácido + base → sal + água: o cátion vem da base e o ânion vem do ácido.'}); },cq([['NaCl','Neutro'],['KNO₃','Neutro'],['NH₄Cl','Ácido'],['Na₂CO₃','Básico'],['CH₃COONa','Básico'],['NaHCO₃','Básico'],['(NH₄)₂SO₄','Ácido']],'Em água, a solução deste sal tem caráter:')]}]);

qg('ar-qui-reac','qui-reac','Reações e balanceamento','⇌','Tipos de reação, balanceamento com coeficientes, NOX e oxirredução.',[
 {d:'Tipo de reação.',g:[()=>{ const e=rP(EQ); return arCh(eqT(e)+'\nEssa reação é de:',e[3],['Síntese','Decomposição','Simples troca','Dupla troca','Combustão'].filter(x=>x!==e[3]),{x:'Síntese: A + B → AB. Decomposição: AB → A + B. Simples troca: A + BC → AC + B. Dupla troca: AB + CD → AD + CB. Combustão: com O₂ gerando CO₂ e H₂O.'}); }]},
 {d:'Coeficientes corretos.',g:[()=>{ const e=rP(EQ); return arAsChoice(arBal('Balanceie a equação.',e[0],e[1],e[2],{x:'Balanceada: '+eqT(e)+'.'})); }]},
 {d:'Balanceie você mesmo.',g:[()=>{ const e=rP(EQ.filter(x=>x[2].length>=3&&x[2].some(v=>v>1))); return arBal('Ajuste os coeficientes para balancear (menores inteiros).',e[0],e[1],e[2],{x:'Balanceada: '+eqT(e)+'.'}); }]},
 {d:'Número de oxidação (NOX).',g:[()=>{ const it=rP([['S','H₂SO₄',6],['S','SO₂',4],['S','H₂S',-2],['S','SO₃',6],['N','HNO₃',5],['N','NH₃',-3],['N','NO₂',4],['N','HNO₂',3],['N','N₂',0],['Mn','KMnO₄',7],['Mn','MnO₂',4],['Cr','K₂Cr₂O₇',6],['O','H₂O₂',-1],['C','CO₂',4],['C','CH₄',-4],['C','CO',2],['Cl','HClO',1],['Cl','HClO₄',7],['Cl','NaCl',-1],['Fe','Fe₂O₃',3],['Fe','FeO',2],['P','H₃PO₄',5]]); return arNum('Qual o NOX do '+it[0]+' em '+it[1]+'?',it[2],{d:0,neg:true,c:[-it[2],it[2]+2,it[2]-1],x:'Soma dos NOX = 0; H = +1, O = −2 (exceto peróxidos), metais alcalinos = +1.'}); }]},
 {d:'Oxidante, redutor, quem oxida.',g:[()=>{ const r=rP([['Zn + CuSO₄ → ZnSO₄ + Cu','Zn','Cu²⁺ (CuSO₄)'],['Fe + 2HCl → FeCl₂ + H₂','Fe','H⁺ (HCl)'],['Mg + 2AgNO₃ → Mg(NO₃)₂ + 2Ag','Mg','Ag⁺ (AgNO₃)'],['2Na + Cl₂ → 2NaCl','Na','Cl₂'],['CuO + H₂ → Cu + H₂O','H₂','CuO'],['Fe₂O₃ + 3CO → 2Fe + 3CO₂','CO','Fe₂O₃'],['2Al + 3CuSO₄ → Al₂(SO₄)₃ + 3Cu','Al','Cu²⁺ (CuSO₄)'],['Cl₂ + 2NaBr → 2NaCl + Br₂','Br⁻ (NaBr)','Cl₂'],['2H₂ + O₂ → 2H₂O','H₂','O₂'],['C + O₂ → CO₂','C','O₂'],['Zn + 2HCl → ZnCl₂ + H₂','Zn','H⁺ (HCl)']]); const ask=rI(0,1); return arCh(r[0]+'\nQual é o agente '+(ask?'oxidante':'redutor')+'?',ask?r[2]:r[1],[ask?r[1]:r[2],'Não há oxirredução','A água'],{x:'O redutor sofre oxidação (perde elétrons, NOX aumenta): '+r[1]+'. O oxidante sofre redução: '+r[2]+'.'}); }]}]);

qg('ar-qui-esteq','qui-esteq','Estequiometria','mol','Massa molar, mol, proporções, reagente limitante, pureza e rendimento.',[
 {d:'Massa molar.',g:[()=>{ const c=rP(COMP); return arNum('Massa molar de '+c[0]+'? (H 1, C 12, N 14, O 16, Na 23, Mg 24, Al 27, S 32, Cl 35,5, K 39, Ca 40, Fe 56)',mm(c),{d:1,u:'g/mol',c:[mm(c)+16,mm(c)-1,mm(c)*2],steps:[mmSteps(c)]}); }]},
 {d:'Mol, massa e número de moléculas.',g:[()=>{ const c=rP(COMP), n=rP([0.5,1,2,3,4]); return rC(.5)?arNum('Quantos mols há em '+fN(n*mm(c),1)+' g de '+c[0]+' (M = '+fN(mm(c),1)+' g/mol)?',n,{d:1,u:'mol',c:[n*mm(c),mm(c)/n,n*2]}):arNum('Massa de '+fN(n,1)+' mol de '+c[0]+' (M = '+fN(mm(c),1)+')?',n*mm(c),{d:1,u:'g',c:[mm(c)/n,n+mm(c),n*mm(c)*2]}); },()=>{ const n=rP([0.5,1,2,3]); return arCh('Quantas moléculas há em '+fN(n,1)+' mol (Avogadro = 6 × 10²³)?',fN(n*6,1)+' × 10²³',[fN(n*6,1)+' × 10²²','6 × 10²³',fN(n*12,1)+' × 10²³'],{x:'n × 6 × 10²³.'}); }]},
 {d:'Proporção estequiométrica.',g:[()=>{ const e=rP(EQ.filter(x=>x[2].length>=3)); const all=e[0].concat(e[1]); const i=rI(0,all.length-1); let j=rI(0,all.length-1); if(j===i) j=(i+1)%all.length; const k=rP([1,2,3,4]); return arNum('Em '+eqT(e)+', quantos mols de '+all[j]+' correspondem a '+(k*e[2][i])+' mol de '+all[i]+'?',k*e[2][j],{d:1,u:'mol',c:[k*e[2][i],k,e[2][j]]}); }]},
 {d:'Massa a partir de massa; reagente limitante.',g:[()=>{ const k=rP([1,2,3,4]); return arNum('Na síntese 2H₂ + O₂ → 2H₂O, qual a massa de água formada a partir de '+(4*k)+' g de H₂ (H 1, O 16)?',36*k,{d:0,u:'g',c:[18*k,4*k,72*k]}); },()=>{ const a=rP([2,4,6]), b=rP([1,2,4]); const lim=a/2<b?'H₂':'O₂'; return arCh('Misturam-se '+a+' mol de H₂ e '+b+' mol de O₂ (2H₂ + O₂ → 2H₂O). Qual o reagente limitante?',a/2===b?'Nenhum: estão em proporção exata':lim,['H₂','O₂','Nenhum: estão em proporção exata'].filter(x=>x!==(a/2===b?'Nenhum: estão em proporção exata':lim)),{x:'Proporção 2:1. '+a+' mol de H₂ exigem '+(a/2)+' mol de O₂.'}); }]},
 {d:'Pureza, rendimento e volume de gás.',g:[()=>{ const m=rP([100,200,500]), p=rP([60,75,80,90]); return arNum('Uma amostra de '+m+' g de calcário tem '+p+'% de CaCO₃. Quantos mols de CaCO₃ (100 g/mol)?',m*p/100/100,{d:2,u:'mol',c:[m/100,m*p/100,m*p/10000*2]}); },()=>{ const t=rP([40,50,80,100]), r=rP([60,75,80,90]); return arNum('Teoricamente se formariam '+t+' g de produto; o rendimento foi '+r+'%. Massa obtida?',t*r/100,{d:0,u:'g',c:[t,t*(100-r)/100,t/r*100]}); },()=>{ const k=rP([1,2,3]); return arNum('Queimando '+(16*k)+' g de CH₄ (CH₄ + 2O₂ → CO₂ + 2H₂O), qual o volume de CO₂ nas CNTP?',22.4*k,{d:1,u:'L',c:[44*k,22.4*2*k,11.2*k]}); }]}]);

qg('ar-qui-sol','qui-sol','Soluções','g/L','Concentração comum, molaridade, diluição, mistura, título e solubilidade.',[
 {d:'Concentração comum (g/L).',g:[()=>{ const V=rP([250,500,1000,2000]), C=rP([2,4,5,8,10,20,40]); return arNum('Dissolvem-se '+fN(C*V/1000,1)+' g de soluto em '+V+' mL de solução. Concentração?',C,{d:1,u:'g/L',c:[C*V/1000*V,C/1000,C*10]}); }]},
 {d:'Molaridade (mol/L).',g:[()=>{ const c=rP(COMP.filter(x=>['NaCl','NaOH','KOH','HCl','H₂SO₄','C₆H₁₂O₆'].indexOf(x[0])>=0)), n=rP([0.1,0.2,0.5,1]), V=rP([0.5,1,2]); return arNum('Dissolvem-se '+fN(n*mm(c),2)+' g de '+c[0]+' (M = '+fN(mm(c),1)+') em água até '+fN(V,1)+' L. Molaridade?',n/V,{d:2,u:'mol/L',c:[n,n*V,n*mm(c)/V]}); }]},
 {d:'Diluição.',g:[()=>{ const C1=rP([10,20,30,40,60]), V1=rP([100,200,300]), k=rP([2,3,4,5]); return arNum(V1+' mL a '+C1+' g/L são diluídos até '+(V1*k)+' mL. Nova concentração?',C1/k,{d:1,u:'g/L',c:[C1*k,C1-k,C1/k*2]}); },()=>{ const C1=rP([2,4,5]), C2=rP([0.5,1]), V2=rP([200,500,1000]); return arNum('Que volume de solução '+C1+' mol/L é preciso para preparar '+V2+' mL de solução '+fN(C2,1)+' mol/L?',C2*V2/C1,{d:0,u:'mL',c:[C1*V2/C2,V2/C1,V2-C2*V2/C1]}); }]},
 {d:'Mistura de soluções do mesmo soluto.',g:[()=>{ const C1=rP([1,2,4]), V1=rP([100,200,300]), C2=rP([2,3,5]), V2=rP([100,200]); return arNum('Misturam-se '+V1+' mL de solução '+C1+' mol/L com '+V2+' mL de solução '+C2+' mol/L. Concentração final?',(C1*V1+C2*V2)/(V1+V2),{d:2,u:'mol/L',c:[(C1+C2)/2,C1+C2,(C1*V2+C2*V1)/(V1+V2)]}); }]},
 {d:'Título, ppm e solubilidade.',g:[()=>{ const m=rP([200,400,500]), t=rP([10,20,25,40]); return arNum('Em '+m+' g de solução com título '+t+'%, quantos gramas de soluto?',m*t/100,{d:0,u:'g',c:[m*t,m/t,m*(100-t)/100]}); },()=>{ const S=rP([36,40,60,80]), W=rP([50,100,200]), m=rP([S*W/100-10,S*W/100,S*W/100+15]); const st=m<S*W/100?'Insaturada':m===S*W/100?'Saturada':'Saturada com corpo de fundo'; return arCh('A solubilidade de um sal é '+S+' g/100 g de água. Dissolvendo '+m+' g em '+W+' g de água, a mistura fica:',st,['Insaturada','Saturada','Saturada com corpo de fundo'].filter(x=>x!==st),{x:'Com '+W+' g de água, dissolvem-se no máximo '+(S*W/100)+' g.'}); }]}]);

qg('ar-qui-termo','qui-termo','Termoquímica e fogo','ΔH','Exo e endotérmicas, gráficos de entalpia, Hess, energia de ligação e combustão.',[
 {d:'Exotérmica ou endotérmica?',g:[cq([['Combustão da madeira','Exotérmica'],['Fotossíntese','Endotérmica'],['Evaporação da água','Endotérmica'],['Condensação do vapor','Exotérmica'],['Fusão do gelo','Endotérmica'],['Respiração celular','Exotérmica'],['Neutralização ácido-base','Exotérmica'],['Decomposição do calcário','Endotérmica'],['Sublimação do gelo-seco','Endotérmica'],['Solidificação da água','Exotérmica'],['Explosão de pólvora','Exotérmica'],['Cozinhar um alimento','Endotérmica'],['Bolsa de gelo instantâneo (dissolução de sal)','Endotérmica'],['Cal virgem reagindo com água','Exotérmica'],['Eletrólise da água','Endotérmica']],'O processo é:')]},
 {d:'Sinal de ΔH no gráfico de entalpia.',g:[()=>{ const hr=rI(2,9)*10, hp=rI(1,9)*10; if(hr===hp) return arNum('Reagentes com H = 80 kJ e produtos com H = 30 kJ. ΔH?',-50,{d:0,u:'kJ',neg:true,c:[50,110]}); const ea=Math.max(hr,hp)+rI(2,5)*10, askH=rC(.5), v=askH?hp-hr:ea-hr; return arNum('Pelo diagrama, os reagentes estão em '+hr+' kJ, os produtos em '+hp+' kJ e o pico em '+ea+' kJ. '+(askH?'Qual o ΔH da reação?':'Qual a energia de ativação da reação direta?'),v,{d:0,u:'kJ',neg:true,fig:fgEnergy({hr:hr/1.5,hp:hp/1.5,ea:ea/1.5}),c:askH?[hr-hp,ea-hp,ea-hr]:[ea,ea-hp,hp-hr],x:askH?'ΔH = H(produtos) − H(reagentes) = '+hp+' − '+hr+' = '+(hp-hr)+' kJ.':'Ea = H(pico) − H(reagentes) = '+ea+' − '+hr+' = '+(ea-hr)+' kJ.'}); },()=>{ const exo=rC(.5), hr=exo?rI(50,70):rI(15,35), hp=exo?rI(10,30):rI(55,75); return arCh('Pelo diagrama, a reação é:',exo?'Exotérmica, ΔH < 0':'Endotérmica, ΔH > 0',[exo?'Endotérmica, ΔH > 0':'Exotérmica, ΔH < 0','Exotérmica, ΔH > 0','Endotérmica, ΔH < 0'],{fig:fgEnergy({hr,hp,ea:Math.max(hr,hp)+20}),x:'Produtos abaixo dos reagentes: liberou energia (ΔH negativo).'}); }]},
 {d:'Lei de Hess.',g:[()=>{ const h1=-rI(35,40)*10, h2=-rI(25,29)*10; return arNum('C + O₂ → CO₂ (ΔH = '+fI(h1)+' kJ) e CO + ½O₂ → CO₂ (ΔH = '+fI(h2)+' kJ). Qual o ΔH de C + ½O₂ → CO?',h1-h2,{d:0,u:'kJ',neg:true,c:[h1+h2,h2-h1,h1]}); }]},
 {d:'Energia de ligação.',g:[()=>{ const HH=rI(430,440), ClCl=rI(240,246), HCl=rI(428,434); return arNum('H₂ + Cl₂ → 2HCl. Energias de ligação (kJ/mol): H–H '+HH+', Cl–Cl '+ClCl+', H–Cl '+HCl+'. ΔH?',HH+ClCl-2*HCl,{d:0,u:'kJ',neg:true,c:[HH+ClCl-HCl,2*HCl-HH-ClCl,HH+ClCl]}); }]},
 {d:'Combustão completa e incompleta; calor liberado.',g:[()=>{ const c=rP([['metano (CH₄)',16,890],['etanol (C₂H₆O)',46,1370],['propano (C₃H₈)',44,2220],['hidrogênio (H₂)',2,286],['butano (C₄H₁₀)',58,2880]]), k=rP([0.5,1,2,3,4,5]); return arNum('A combustão do '+c[0]+' libera '+fN(c[2],0)+' kJ/mol (M = '+c[1]+' g/mol). Quanto calor liberam '+fN(c[1]*k,0)+' g?',c[2]*k,{d:0,u:'kJ',c:[c[2]*c[1]*k,c[2]/k,c[2]]}); },cq([['Combustão completa do carbono gera','CO₂','CO|C (fuligem)|O₂'],['Combustão incompleta pode gerar','CO e fuligem','somente CO₂|O₂|H₂'],['O CO é perigoso porque','se liga à hemoglobina e impede o transporte de O₂','é inflamável só a 1.000 °C|é mais pesado que o ar e sufoca|forma ácido no pulmão']])]}]);

qg('ar-qui-cin','qui-cin','Cinética química','v','Fatores de velocidade, velocidade média, energia de ativação, catalisador e lei de velocidade.',[
 {d:'Fatores que alteram a velocidade.',g:[cq([['Aumentar a temperatura','Aumenta a velocidade'],['Usar catalisador','Aumenta a velocidade'],['Triturar o sólido','Aumenta a velocidade'],['Diluir os reagentes','Diminui a velocidade'],['Resfriar o sistema','Diminui a velocidade'],['Aumentar a concentração','Aumenta a velocidade'],['Usar inibidor','Diminui a velocidade'],['Guardar alimento na geladeira','Diminui a velocidade'],['Usar lenha picada em vez de toras','Aumenta a velocidade'],['Soprar brasa (mais oxigênio)','Aumenta a velocidade'],['Usar comprimido efervescente inteiro em vez de triturado','Diminui a velocidade'],['Enzimas na digestão','Aumenta a velocidade']],'Efeito na velocidade da reação:')]},
 {d:'Velocidade média.',g:[()=>{ const c1=rP([2,4,6,8]), c2=rP([0.5,1,1.5]), t=rP([2,4,5,10]); return arNum('A concentração de um reagente caiu de '+c1+' para '+fN(c2,1)+' mol/L em '+t+' min. Velocidade média?',(c1-c2)/t,{d:2,u:'mol/L·min',c:[c1/t,(c1+c2)/t,(c1-c2)*t]}); }]},
 {d:'Energia de ativação e catalisador.',g:[()=>{ const hr=rI(3,6)*10, hp=rI(1,3)*10, ea=hr+rI(2,5)*10, eac=hr+rI(1,Math.floor((ea-hr)/10)-1||1)*10; const k=rI(0,2); const q=['a energia de ativação sem catalisador','a energia de ativação com catalisador','o ΔH da reação'][k], v=[ea-hr,eac-hr,hp-hr][k]; return arNum('Reagentes em '+hr+' kJ, produtos em '+hp+' kJ; o complexo ativado fica em '+ea+' kJ sem catalisador e em '+eac+' kJ com catalisador. Calcule '+q+'.',v,{d:0,u:'kJ',neg:true,c:[ea,eac,hr-hp,ea-hp]}); },()=>{ return arCh('No gráfico, a curva tracejada representa a reação com catalisador. O catalisador:','diminui a energia de ativação sem alterar o ΔH',['aumenta o ΔH','diminui o ΔH','aumenta a energia de ativação','desloca o equilíbrio'],{fig:fgEnergy({hr:55,hp:25,ea:90,eac:70}),x:'O catalisador cria um caminho de menor energia de ativação; reagentes e produtos não mudam.'}); }]},
 {d:'Lei de velocidade: efeito de dobrar concentrações.',g:[()=>{ const a=rI(0,2), b=rI(0,2), k=rP([2,3]); return arNum('Para v = k[A]'+(a===1?'':sq(a))+'[B]'+(b===1?'':sq(b))+', multiplicando [A] e [B] por '+k+', a velocidade fica multiplicada por:',Math.pow(k,a+b),{d:0,c:[k,Math.pow(k,a),k*(a+b)]}); }]},
 {d:'Ordem a partir da tabela de experimentos.',g:[()=>{ const a=rI(0,2), b=rI(1,2), v0=rP([1,2,4]); const tab='Exp. 1: [A] = 0,1; [B] = 0,1; v = '+v0+'\nExp. 2: [A] = 0,2; [B] = 0,1; v = '+(v0*Math.pow(2,a))+'\nExp. 3: [A] = 0,1; [B] = 0,2; v = '+(v0*Math.pow(2,b)); const lei='v = k'+(a?'[A]'+(a>1?sq(a):''):'')+'[B]'+(b>1?sq(b):''); return arCh('Pelos experimentos:\n'+tab+'\nQual é a lei de velocidade?',lei,['v = k[A][B]','v = k[A]²[B]','v = k[B]²','v = k[A][B]²','v = k[A]²[B]²','v = k[B]'].filter(x=>x!==lei),{x:'Dobrar [A] multiplicou v por '+Math.pow(2,a)+' → ordem '+a+' em A. Dobrar [B] multiplicou por '+Math.pow(2,b)+' → ordem '+b+' em B.'}); }]}]);

const LECH=[['N₂(g) + 3H₂(g) ⇌ 2NH₃(g), ΔH < 0',4,2,-1],['2SO₂(g) + O₂(g) ⇌ 2SO₃(g), ΔH < 0',3,2,-1],['N₂O₄(g) ⇌ 2NO₂(g), ΔH > 0',1,2,1],['CO(g) + 2H₂(g) ⇌ CH₃OH(g), ΔH < 0',3,1,-1],['CaCO₃(s) ⇌ CaO(s) + CO₂(g), ΔH > 0',0,1,1]];
function lech(){ const r=rP(LECH), p=rP(['adicionar reagente','retirar produto','adicionar produto','aumentar a pressão','diminuir a pressão','aumentar a temperatura','diminuir a temperatura','adicionar catalisador']);
  let d; if(p==='adicionar reagente'||p==='retirar produto') d=1; else if(p==='adicionar produto') d=-1; else if(p==='adicionar catalisador') d=0;
  else if(p.indexOf('pressão')>=0){ const up=p.startsWith('aumentar'); d=r[1]===r[2]?0:((r[2]<r[1])===up?1:-1); } else { const up=p.startsWith('aumentar'); d=(r[3]>0)===up?1:-1; }
  const L={1:'Para os produtos (direita)',[-1]:'Para os reagentes (esquerda)',0:'Não se desloca'}[d];
  return arCh(r[0]+'\nAo '+p+', o equilíbrio se desloca:',L,['Para os produtos (direita)','Para os reagentes (esquerda)','Não se desloca'].filter(x=>x!==L),{x:'Le Chatelier: o sistema reage contra a perturbação. Pressão favorece o lado com menos mols de gás; aquecimento favorece o sentido endotérmico; catalisador não desloca.'}); }
qg('ar-qui-eq','qui-eq','Equilíbrio e pH','pH','pH e pOH, Kc, Le Chatelier, ácidos e bases fortes e hidrólise.',[
 {d:'pH a partir de [H⁺]; ácido, neutro ou básico.',g:[()=>{ const n=rI(1,13); return arNum('[H⁺] = 10'+sq(-n)+' mol/L. Qual o pH?',n,{d:0,c:[14-n,n+1,n*10]}); },()=>{ const n=rI(1,13); const t=n<7?'Ácida':n===7?'Neutra':'Básica'; return arCh('Uma solução de pH '+n+' é:',t,['Ácida','Neutra','Básica'].filter(x=>x!==t),{x:'pH < 7 ácido, 7 neutro, > 7 básico (25 °C).'}); }]},
 {d:'pH + pOH = 14 e [OH⁻].',g:[()=>{ const n=rI(1,13); return arNum('pH = '+n+'. Qual o pOH?',14-n,{d:0,c:[n,7-n+7,14+n]}); },()=>{ const n=rI(1,13); return arCh('pH = '+n+'. Qual a [OH⁻]?','10'+sq(n-14)+' mol/L',['10'+sq(-n)+' mol/L','10'+sq(n)+' mol/L','10'+sq(14-n)+' mol/L'],{x:'pOH = '+(14-n)+' → [OH⁻] = 10^−'+(14-n)+'.'}); }]},
 {d:'Constante de equilíbrio Kc.',g:[()=>{ const h=rP([0.1,0.2,0.5]), i=rP([0.1,0.2,0.4]), hi=rP([0.2,0.4,0.8,1]); return arNum('H₂ + I₂ ⇌ 2HI. No equilíbrio: [H₂] = '+fN(h,1)+', [I₂] = '+fN(i,1)+', [HI] = '+fN(hi,1)+' mol/L. Kc?',hi*hi/(h*i),{d:1,c:[hi/(h*i),h*i/(hi*hi),2*hi/(h*i)]}); }]},
 {d:'Deslocamento de equilíbrio (Le Chatelier).',g:[lech]},
 {d:'pH de ácidos e bases fortes; hidrólise.',g:[()=>{ const n=rI(1,4), base=rC(.5); return arNum('Qual o pH de uma solução '+fN(Math.pow(10,-n),4)+' mol/L de '+(base?'NaOH':'HCl')+'?',base?14-n:n,{d:0,c:[base?n:14-n,base?7+n:7-n]}); },cq([['NaCl','Neutro'],['NH₄Cl','Ácido'],['Na₂CO₃','Básico'],['KNO₃','Neutro'],['CH₃COONa','Básico']],'Caráter da solução aquosa do sal:')]}]);

const EPOT=[['Li','Li⁺/Li',-3.04],['K','K⁺/K',-2.93],['Mg','Mg²⁺/Mg',-2.37],['Al','Al³⁺/Al',-1.66],['Zn','Zn²⁺/Zn',-0.76],['Fe','Fe²⁺/Fe',-0.44],['Ni','Ni²⁺/Ni',-0.25],['Pb','Pb²⁺/Pb',-0.13],['Cu','Cu²⁺/Cu',0.34],['Ag','Ag⁺/Ag',0.80]];
qg('ar-qui-ele','qui-ele','Pilhas e eletrólise','e⁻','Ânodo e cátodo, potenciais, ddp, corrosão, metal de sacrifício e eletrólise.',[
 {d:'Ânodo, cátodo, oxidação e redução.',g:[cq([['Ocorre oxidação','Ânodo'],['Ocorre redução','Cátodo'],['Polo negativo da pilha','Ânodo'],['Polo positivo da pilha','Cátodo'],['Eletrodo que se desgasta','Ânodo'],['Eletrodo onde o metal se deposita','Cátodo'],['Para onde os elétrons vão pelo fio externo','Cátodo'],['De onde saem os elétrons','Ânodo'],['Eletrodo cuja solução fica mais concentrada em íons metálicos','Ânodo'],['Eletrodo em que a massa aumenta','Cátodo']],'Na pilha:')]},
 {d:'Quem oxida pela variação do NOX.',g:[()=>{ const [a,b]=rN(EPOT,2); const an=a[2]<b[2]?a:b; return arCh('Numa pilha de '+a[0]+' e '+b[0]+' (E° '+a[1]+' = '+fN(a[2],2)+' V; '+b[1]+' = '+fN(b[2],2)+' V), qual metal se oxida?',an[0],[a===an?b[0]:a[0],'Os dois','Nenhum'],{x:'Oxida quem tem menor potencial de redução: '+an[0]+'.'}); }]},
 {d:'ddp da pilha.',g:[()=>{ const [a,b]=rN(EPOT,2); const d=Math.abs(a[2]-b[2]); return arNum('ddp da pilha com '+a[1]+' (E° = '+fN(a[2],2)+' V) e '+b[1]+' (E° = '+fN(b[2],2)+' V)?',d,{d:2,u:'V',c:[a[2]+b[2],Math.abs(a[2]+b[2]),d*2]}); }]},
 {d:'Corrosão e metal de sacrifício.',g:[()=>{ const [a,b]=rN(EPOT,2); const hi=a[2]>b[2]?a:b, lo=a===hi?b:a; return arCh('Numa placa de '+hi[0]+' em contato com '+lo[0]+', qual metal sofre corrosão primeiro?',lo[0],[hi[0],'Os dois ao mesmo tempo','Nenhum'],{x:'Oxida primeiro o de menor potencial de redução: '+lo[0]+' ('+fN(lo[2],2)+' V).'}); },()=>{ const good=rP(['Mg','Zn','Al']), bad=rP(['Cu','Ag','Pb']); return arCh('Qual metal pode proteger um casco de ferro como metal de sacrifício?',good,[bad,'Ni','Nenhum metal protege o ferro'],{x:'O metal de sacrifício tem menor potencial de redução que o ferro (oxida no lugar dele): Mg, Zn, Al.'}); },cq([['A ferrugem é','óxido de ferro hidratado formado por oxidação','um sal de cobre|ferro reduzido|um processo físico'],['Galvanização é','revestir o ferro com zinco','revestir com cobre|pintar com tinta comum|mergulhar em ácido']])]},
 {d:'Eletrólise e Faraday.',g:[()=>{ const m=rP([['Cu²⁺','cobre',63.5,2],['Ag⁺','prata',108,1],['Zn²⁺','zinco',65,2],['Ni²⁺','níquel',59,2],['Al³⁺','alumínio',27,3]]), k=rP([1,2,3,4,5,6]); const mass=m[2]*k/10/m[3]; return arNum('Uma carga de '+fN(9650*k,0)+' C atravessa uma solução de '+m[0]+' (M = '+fN(m[2],1)+' g/mol; F = 96.500 C). Massa de '+m[1]+' depositada?',mass,{d:2,u:'g',c:[m[2]*k/10,mass*2,m[2]*k]}); },()=>{ const i=rP([2,4,5,10]), t=rP([965,1930,4825,9650]); return arNum('Uma corrente de '+i+' A passa por '+t+' s. Quantos mols de elétrons circularam (F = 96.500 C)?',i*t/96500,{d:2,u:'mol',c:[i*t,i*t/9650,i*t/965]}); },cq([['Eletrólise ígnea do NaCl produz','sódio metálico e gás cloro','hidrogênio e oxigênio|soda cáustica e sal|cloro e hidrogênio'],['Na eletrólise, o cátodo é o polo','negativo (redução)','positivo (oxidação)|neutro|positivo (redução)']])]}]);

/* ---------- orgânica: cadeias geradas ---------- */
const PREF=['met','et','prop','but','pent','hex','hept','oct'];
function chain(n,end){ const parts=[]; for(let i=0;i<n;i++) parts.push(i===0?(n===1?'CH₄':'CH₃'):'CH₂'); if(n>1) parts[n-1]='CH₃'; return parts; }
function orgGen(fn){ let n, name, f, C, H, O=0, N=0;
  if(fn==='alcano'){ n=rI(1,8); C=n; H=2*n+2; name=PREF[n-1]+'ano'; f=n===1?'CH₄':chain(n).join('–'); }
  else if(fn==='alceno'){ n=rI(2,6); C=n; H=2*n; name=n===2?'eteno':n===3?'propeno':PREF[n-1]+'-1-eno'; f='CH₂='+(n===2?'CH₂':'CH'+(n>3?'–'+Array(n-3).fill('CH₂').join('–'):'')+'–CH₃'); if(n>3) name=PREF[n-1]+'-1-eno'; }
  else if(fn==='alcino'){ n=rI(2,6); C=n; H=2*n-2; name=n===2?'etino':n===3?'propino':PREF[n-1]+'-1-ino'; f='CH≡'+(n===2?'CH':'C'+(n>3?'–'+Array(n-3).fill('CH₂').join('–'):'')+'–CH₃'); }
  else if(fn==='álcool'){ n=rI(1,6); C=n; H=2*n+2; O=1; name=n<=2?PREF[n-1]+'anol':PREF[n-1]+'an-1-ol'; f=n===1?'CH₃–OH':'CH₃–'+Array(n-2).fill('CH₂').concat(['CH₂–OH']).join('–'); }
  else if(fn==='aldeído'){ n=rI(1,6); C=n; H=2*n; O=1; name=PREF[n-1]+'anal'; f=n===1?'H–CHO':'CH₃–'+Array(n-2).fill('CH₂').concat(['CHO']).join('–'); }
  else if(fn==='cetona'){ n=rI(3,6); C=n; H=2*n; O=1; name=n<=4?PREF[n-1]+'anona':PREF[n-1]+'an-2-ona'; f='CH₃–CO–'+(n===3?'CH₃':Array(n-3).fill('CH₂').join('–')+'–CH₃'); }
  else if(fn==='ácido carboxílico'){ n=rI(1,6); C=n; H=2*n; O=2; name='ácido '+PREF[n-1]+'anoico'; f=n===1?'H–COOH':'CH₃–'+Array(n-2).fill('CH₂').concat(['COOH']).join('–'); }
  else if(fn==='amina'){ n=rI(1,4); C=n; H=2*n+3; N=1; name=['metil','etil','propil','butil'][n-1]+'amina'; f=(n===1?'CH₃':'CH₃–'+Array(n-2).fill('CH₂').concat(['CH₂']).join('–'))+'–NH₂'; }
  else if(fn==='éster'){ const a=rI(1,3), b=rI(1,2); C=a+b; H=2*(a+b); O=2; name=PREF[a-1]+'anoato de '+['metila','etila'][b-1]; f=(a===1?'H':'CH₃'+(a>2?'–CH₂':''))+'–COO–'+(b===1?'CH₃':'CH₂–CH₃'); }
  else if(fn==='amida'){ n=rI(1,4); C=n; H=2*n+1; O=1; N=1; name=PREF[n-1]+'anamida'; f=n===1?'H–CONH₂':'CH₃–'+Array(n-2).fill('CH₂').concat(['CONH₂']).join('–'); }
  else { const a=rI(1,2), b=rI(1,2); C=a+b; H=2*(a+b)+2; O=1; name=['metoxi','etoxi'][Math.min(a,b)-1]+['metano','etano'][Math.max(a,b)-1]; f=(a===1?'CH₃':'CH₃–CH₂')+'–O–'+(b===1?'CH₃':'CH₂–CH₃'); fn='éter'; }
  const mf='C'+(C>1?sb(C):'')+'H'+sb(H)+(N?'N':'')+(O?'O'+(O>1?sb(O):''):'');
  return {fn,name,f,mf,C,H,O,N}; }
const FUNCS=['alcano','alceno','alcino','álcool','aldeído','cetona','ácido carboxílico','amina','éster','éter','amida'];
qg('ar-qui-org','qui-org','Química orgânica','C–C','Cadeias, nomenclatura gerada, funções, isomeria e reações orgânicas.',[
 {d:'Classificação de cadeias.',g:[cq([['CH₃–CH₂–CH₃','Aberta, saturada, homogênea, normal'],['CH₂=CH–CH₃','Aberta, insaturada, homogênea, normal'],['CH₃–O–CH₃','Aberta, saturada, heterogênea, normal'],['CH₃–CH(CH₃)–CH₃','Aberta, saturada, homogênea, ramificada'],['Benzeno (C₆H₆)','Fechada, aromática']],'Classifique a cadeia:'),()=>{ const o=orgGen(rP(['alcano','alceno','alcino'])); const sat=o.fn==='alcano'?'Saturada':'Insaturada'; return arCh(o.f+'\nA cadeia é:',sat,['Saturada','Insaturada'].filter(x=>x!==sat),{x:'Saturada: só ligações simples entre carbonos.'}); }]},
 {d:'Nomenclatura de hidrocarbonetos.',g:[()=>{ const o=orgGen(rP(['alcano','alceno','alcino'])); const ws=[orgGen(o.fn).name,orgGen(rP(['alcano','alceno','alcino'])).name,orgGen(rP(['alcano','alceno','alcino'])).name,orgGen(rP(['alcano','alceno','alcino'])).name]; return arCh('Nome do composto **'+o.f+'**?',o.name,ws,{x:'Prefixo (nº de C) + infixo (an, en, in) + o. '+o.name+'.'}); }]},
 {d:'Grupo funcional e função orgânica.',g:[()=>{ const o=orgGen(rP(FUNCS.slice(3))); return arCh('**'+o.f+'** pertence à função:',o.fn[0].toUpperCase()+o.fn.slice(1),FUNCS.filter(x=>x!==o.fn).map(x=>x[0].toUpperCase()+x.slice(1)),{x:'Nome: '+o.name+'.'}); },()=>{ const o=orgGen(rP(FUNCS)); return arCh('Nome de **'+o.f+'**?',o.name,[orgGen(o.fn).name,orgGen(rP(FUNCS)).name,orgGen(rP(FUNCS)).name,orgGen(rP(FUNCS)).name],{x:'Função '+o.fn+': '+o.name+'.'}); }]},
 {d:'Fórmula molecular e isomeria.',g:[()=>{ const o=orgGen(rP(FUNCS)); const alt=[o.mf.replace(/H(\S)/,'H'+sb(o.H+2)),o.mf.replace(/H(\S+?)(?=[NO]|$)/,'H'+sb(Math.max(2,o.H-2))),'C'+sb(o.C+1)+'H'+sb(o.H)]; return arCh('Fórmula molecular de '+o.name+' ('+o.f+')?',o.mf,alt,{x:o.C+' C, '+o.H+' H'+(o.O?', '+o.O+' O':'')+(o.N?', '+o.N+' N':'')+'.'}); },cq([['Propan-1-ol e propan-2-ol','Isomeria de posição'],['Etanol e metoximetano','Isomeria de função'],['Butano e metilpropano','Isomeria de cadeia'],['Propanal e propanona','Isomeria de função'],['Ácido propanoico e etanoato de metila','Isomeria de função'],['cis-but-2-eno e trans-but-2-eno','Isomeria geométrica'],['But-1-eno e but-2-eno','Isomeria de posição']],'Tipo de isomeria:')]},
 {d:'Reações orgânicas.',g:[cq([['Ácido carboxílico + álcool → éster + água','Esterificação'],['Éster + base forte → sabão + álcool','Saponificação'],['CH₄ + Cl₂ → CH₃Cl + HCl (luz)','Substituição'],['CH₂=CH₂ + H₂ → CH₃–CH₃','Adição (hidrogenação)'],['C₂H₆O + 3O₂ → 2CO₂ + 3H₂O','Combustão'],['Muitos monômeros se unem formando uma cadeia longa','Polimerização'],['Óleo vegetal + H₂ → margarina','Adição (hidrogenação)'],['Benzeno + HNO₃ → nitrobenzeno + H₂O','Substituição (nitração)'],['Etanol → eteno + H₂O (aquecimento com ácido)','Eliminação (desidratação)'],['CH₂=CH₂ + Br₂ → CH₂Br–CH₂Br','Adição (halogenação)'],['Éster + água → ácido + álcool','Hidrólise'],['Álcool primário + oxidante → aldeído','Oxidação']],'Tipo de reação:')]}]);
