/* ===================== JORNADA DO PARANÁ: GLOSSÁRIO =====================
   Termos específicos da história e da geografia do Paraná viram botões com pontilhado embaixo,
   dentro do texto da Jornada. Tocar (ou passar o mouse, no computador) abre uma explicação curta
   e didática, sem precisar sair da cena. JN_GTERMS mapeia cada forma exata do termo no texto
   (respeitando maiúsculas e o singular/plural realmente usados) para a chave em JN_GLOSS. */
const JN_GLOSS={
  guaira:{n:'Guairá',d:'Território sob domínio espanhol entre os rios Paranapanema, Paraná, Iguaçu e Tibagi, no atual oeste e norte do Paraná. Teve cidades e reduções jesuíticas até ser destruído por bandeirantes paulistas entre 1628 e 1632.'},
  uti_possidetis:{n:'Uti possidetis',d:'Princípio de direito internacional pelo qual a posse de fato de um território vale mais do que um tratado antigo dizia no papel. Foi usado no Tratado de Madri (1750) para reconhecer como portuguesas terras que Tordesilhas dava à Espanha.'},
  tordesilhas:{n:'Tratado de Tordesilhas',d:'Acordo de 1494 entre Portugal e Espanha que dividiu as terras do Novo Mundo por uma linha imaginária: a leste, Portugal; a oeste, Espanha. Por essa linha, quase todo o atual Paraná ficaria espanhol.'},
  madri:{n:'Tratado de Madri',d:'Tratado de 1750 entre Portugal e Espanha que substituiu Tordesilhas pelo princípio do uti possidetis, reconhecendo como portuguesas as terras que Portugal já ocupava de fato — entre elas, o atual Paraná.'},
  bandeirante:{n:'Bandeirante',d:'Colono paulista que organizava expedições armadas (bandeiras) para o interior do Brasil, quase sempre para caçar e escravizar indígenas ou procurar metais preciosos. Foram bandeirantes que destruíram as reduções jesuíticas do Guairá.'},
  reducao:{n:'Redução jesuítica',d:'Aldeia organizada por padres jesuítas para reunir, catequizar e proteger indígenas guarani, com agricultura e trabalho coletivos. As do Guairá foram destruídas por bandeirantes entre 1628 e 1632.'},
  sesmaria:{n:'Sesmaria',d:'Lote de terra que a Coroa portuguesa doava a um colono, com a obrigação de ocupá-lo e produzir nele. Foi assim que surgiram as primeiras fazendas de gado dos Campos Gerais, no século XVIII.'},
  tropeiro:{n:'Tropeiro',d:'Condutor de tropas de mulas e gado que viajava por meses entre o Rio Grande do Sul e a feira de Sorocaba (SP), atravessando o Paraná. Deixou como herança o chimarrão, o feijão tropeiro e boa parte das cidades dos Campos Gerais.'},
  invernada:{n:'Invernada',d:'Pasto onde as tropas de mulas e gado descansavam e engordavam durante a longa viagem entre o Rio Grande do Sul e São Paulo, antes de seguir viagem.'},
  pouso:{n:'Pouso',d:'Ponto de parada das tropas de mulas ao longo do Caminho de Viamão, onde surgiam capelas, vendas e casas. Muitos pousos viraram cidades atuais dos Campos Gerais, como Castro e Lapa.'},
  erva_mate:{n:'Erva-mate',d:'Planta nativa da mata de araucária cujas folhas tostadas e moídas viraram o principal produto de exportação do Paraná no século XIX, vendido sobretudo à Argentina, ao Uruguai e ao Chile.'},
  engenho:{n:'Engenho (de erva-mate)',d:'Instalação onde a erva-mate colhida era socada, moída e preparada para exportação. No Paraná do século XIX, os principais engenhos ficavam em Curitiba, Morretes, Antonina e Paranaguá.'},
  ervateiro:{n:'Ervateiro',d:'Pessoa que colhia e beneficiava a erva-mate nos ervais nativos do Paraná, no auge da economia da erva no século XIX.'},
  faiscacao:{n:'Faiscação',d:'Garimpo manual de ouro em leitos de rio, com bateia, sem minas profundas. Foi assim que se buscou o primeiro ouro do Paraná, no litoral e no Primeiro Planalto, no século XVII.'},
  ouro_aluviao:{n:'Ouro de aluvião',d:'Ouro encontrado em pequenos grãos e pepitas nos leitos de rios, e não em minas profundas. Foi esse ouro, e não uma grande jazida, que atraiu os primeiros povoadores de Paranaguá e Curitiba.'},
  planalto1:{n:'Primeiro Planalto',d:'Faixa de planalto logo depois da Serra do Mar, a cerca de 900 m de altitude, onde fica Curitiba. É o mais próximo do litoral entre os três planaltos do Paraná.'},
  planalto2:{n:'Segundo Planalto',d:'Planalto de campos naturais — os Campos Gerais — entre a Escarpa Devoniana e a Serra Geral, onde ficam Ponta Grossa, Castro e Lapa.'},
  planalto3:{n:'Terceiro Planalto',d:'O maior planalto do Paraná, a oeste da Serra Geral, onde ficam Guarapuava, o Norte, o Oeste e o Sudoeste do estado.'},
  escarpa:{n:'Escarpa Devoniana',d:'Degrau de relevo que separa o Primeiro do Segundo Planalto, com rochas de cerca de 400 milhões de anos, do período Devoniano. Fica entre Curitiba e os Campos Gerais.'},
  serrageral:{n:'Serra Geral',d:'Também chamada de Serra da Esperança: o degrau de relevo que separa o Segundo do Terceiro Planalto do Paraná, entre os Campos Gerais e Guarapuava.'},
  araucaria:{n:'Araucária',d:'O pinheiro-do-paraná, símbolo do estado. Cobria, junto com campos naturais, boa parte do centro e do leste do Paraná antes da ocupação, e ainda dá o pinhão, colhido entre março e julho.'},
  terraroxa:{n:'Terra roxa',d:'Solo avermelhado e muito fértil, formado pela decomposição do basalto, encontrado no Norte e no Oeste do Paraná. Foi decisivo para atrair a lavoura de café para essas regiões.'},
  sambaqui:{n:'Sambaqui',d:'Monte de conchas, ossos e ferramentas deixado por antigos povos pescadores e coletores do litoral, muitos com milhares de anos. Há centenas deles no litoral paranaense.'},
  peabiru:{n:'Caminho do Peabiru',d:'Rede de trilhas indígenas que ligava o litoral atlântico ao Paraguai e aos Andes, atravessando o Paraná de leste a oeste. Foi por ela que os primeiros europeus, como Cabeza de Vaca, entraram no interior.'},
  kaingang:{n:'Kaingang',d:'Povo indígena de língua Jê que ocupava os campos do planalto paranaense, entre eles Guarapuava e Palmas, e resistiu à conquista portuguesa desses territórios nos séculos XVIII e XIX.'},
  guarani:{n:'Guarani',d:'Povo indígena de língua tupi-guarani que ocupava o oeste e os vales dos grandes rios do Paraná. Foi reunido pelos jesuítas espanhóis nas reduções do Guairá, no século XVII.'},
  carijo:{n:'Carijós',d:'Grupo indígena guarani que ocupava o litoral do Paraná e de Santa Catarina antes da chegada dos europeus.'},
  xeta:{n:'Xetá',d:'Povo indígena da Serra dos Dourados, no noroeste do Paraná. Foi o último a ser contatado no estado, só nas décadas de 1940 e 1950, e quase desapareceu com a chegada da colonização.'},
  realexp:{n:'Real Expedição',d:'Expedição militar e colonizadora enviada por D. João em 1809 para conquistar os Campos de Guarapuava, terra dos Kaingang, e nela instalar povoadores portugueses.'},
  colmilitar:{n:'Colônia militar',d:'Povoado fundado pelo governo, com soldados e famílias, para marcar presença numa área de fronteira. Foi assim que nasceram Foz do Iguaçu (1889) e a colônia do Chopim (1882).'},
  comarca:{n:'Comarca',d:'Divisão administrativa e judiciária de uma província. Antes de 1853, o território do Paraná era a Comarca de Curitiba e Paranaguá, a 5ª comarca da Província de São Paulo.'},
  provincia:{n:'Província',d:'Divisão administrativa do Império do Brasil, equivalente a um estado de hoje, governada por um presidente nomeado pelo Imperador. O Paraná virou província em 1853.'},
  lei704:{n:'Lei nº 704',d:'Lei sancionada por D. Pedro II em 29 de agosto de 1853 que criou a Província do Paraná, desmembrada da Província de São Paulo.'},
  graciosa:{n:'Estrada da Graciosa',d:'Estrada aberta em 1873 ligando o planalto de Curitiba ao porto de Antonina, pela Serra do Mar, para escoar a erva-mate antes de existir a ferrovia.'},
  ctnp:{n:'Companhia de Terras Norte do Paraná',d:'Empresa colonizadora de capital inglês, fundada em 1925, que planejou e vendeu em lotes pequenos as terras do Norte do Paraná, fundando cidades como Londrina (1929) e Maringá (1947).'},
  geadanegra:{n:'Geada negra',d:'Geada excepcionalmente forte que atingiu o Paraná em 18 de julho de 1975 e destruiu praticamente todos os cafezais do estado numa só noite, encerrando o ciclo do café.'},
  contestado:{n:'Contestado',d:'Área de mata de araucária entre o Paraná e Santa Catarina, disputada pelos dois estados até 1916, e palco da Guerra do Contestado (1912–1916), um dos maiores conflitos internos da história republicana do Brasil.'},
  monge:{n:'Monge (do Contestado)',d:'Líder religioso leigo que pregava o retorno a uma vida comunitária e simples, atraindo multidões de caboclos pobres. O monge José Maria foi um dos estopins da Guerra do Contestado.'},
  caboclo:{n:'Caboclo',d:'Morador do interior, geralmente de ascendência indígena e europeia misturada, que vivia da terra sem título de propriedade. Muitos caboclos do Contestado foram expulsos de suas terras pela ferrovia e pela madeireira Lumber.'},
  maragato:{n:'Maragato',d:'Apelido dos federalistas que lutaram na Revolução Federalista (1893–1895), contrários ao governo do presidente Floriano Peixoto.'},
  picapau:{n:'Pica-pau',d:'Apelido dos republicanos fiéis ao presidente Floriano Peixoto na Revolução Federalista (1893–1895), em oposição aos federalistas maragatos.'},
  revfederalista:{n:'Revolução Federalista',d:'Guerra civil de 1893 a 1895, iniciada no Rio Grande do Sul, entre federalistas (maragatos) e republicanos fiéis ao governo (pica-paus). Chegou ao Paraná com o Cerco da Lapa, em 1894.'},
  cercolapa:{n:'Cerco da Lapa',d:'Resistência de 26 dias, em 1894, dos republicanos comandados pelo general Gomes Carneiro contra os maragatos invasores, na cidade da Lapa, durante a Revolução Federalista.'},
  revfarroupilha:{n:'Revolução Farroupilha',d:'Revolta separatista do Rio Grande do Sul contra o Império, entre 1835 e 1845. O Paraná, no caminho entre o Rio Grande e São Paulo, precisou se manter fiel ao Império durante o conflito.'},
  revliberal:{n:'Revolução Liberal',d:'Revolta de 1842 em São Paulo e Minas Gerais contra o governo imperial. A comarca de Curitiba e Paranaguá não aderiu a ela, o que ajudou a garantir, anos depois, a promessa de emancipação do Paraná.'},
  questaopalmas:{n:'Questão de Palmas',d:'Disputa de fronteira entre Brasil e Argentina pela região de Palmas, resolvida em 1895 por arbitragem do presidente dos Estados Unidos, a favor do Brasil.'},
  posseiro:{n:'Posseiro',d:'Morador que ocupa e trabalha uma terra sem ter o título de propriedade dela. A expulsão de posseiros por empresas de terra provocou tanto o Contestado (1912) quanto a Revolta dos Posseiros no Sudoeste (1957).'},
  cango:{n:'CANGO',d:'Colônia Agrícola Nacional General Osório, criada por Getúlio Vargas em 1943 no Sudoeste do Paraná para assentar colonos. Deu origem à cidade de Francisco Beltrão.'},
  getsop:{n:'GETSOP',d:'Grupo Executivo para as Terras do Sudoeste do Paraná, criado pelo governo federal em 1962 para regularizar os títulos de terra da região, depois da Revolta dos Posseiros.'},
  maripa:{n:'MARIPÁ',d:'Colonizadora particular que, a partir de 1946, vendeu lotes de terra a gaúchos e catarinenses no Oeste do Paraná, fundando a cidade de Toledo.'},
  territiguacu:{n:'Território Federal do Iguaçu',d:'Território administrado diretamente pelo governo federal entre 1943 e 1946, formado com terras tiradas do Paraná e de Santa Catarina, com capital em Laranjeiras do Sul.'},
  obrage:{n:'Obrage',d:'Empresa de capital argentino ou inglês que explorava erva-mate e madeira no Oeste do Paraná no fim do século XIX, usando trabalhadores paraguaios chamados mensus.'},
  mensu:{n:'Mensu',d:'Trabalhador paraguaio contratado, muitas vezes em condições de servidão por dívida, para extrair erva-mate e madeira nas obrages do Oeste do Paraná.'},
  picoparana:{n:'Pico Paraná',d:'Montanha de 1.877 m na Serra do Mar, o ponto mais alto do Sul do Brasil.'},
  seteQuedas:{n:'Sete Quedas',d:'Conjunto de quedas d’água no rio Paraná, em Guaíra, descrito por viajantes da época como ainda maior que as Cataratas do Iguaçu. Foi coberto pelo lago da usina de Itaipu em 1982.'},
  serroazul:{n:'Barão do Serro Azul',d:'Ildefonso Pereira Correia, o maior industrial e exportador de erva-mate do Paraná no século XIX. Negociou com os maragatos em 1894 para proteger Curitiba e foi fuzilado sem julgamento, acusado de traição; hoje é reconhecido como herói da pátria.'}
};
const JN_GTERMS={
  'Guairá':'guaira','Província del Guairá':'guaira',
  'uti possidetis':'uti_possidetis',
  'Tratado de Tordesilhas':'tordesilhas','Tordesilhas':'tordesilhas',
  'Tratado de Madri':'madri',
  'bandeirantes':'bandeirante','bandeirante':'bandeirante',
  'reduções jesuíticas':'reducao','redução jesuítica':'reducao',
  'sesmarias':'sesmaria','sesmaria':'sesmaria',
  'tropeiros':'tropeiro','tropeiro':'tropeiro',
  'invernadas':'invernada','invernada':'invernada',
  'pousos':'pouso',
  'erva-mate':'erva_mate',
  'engenhos':'engenho',
  'ervateiros':'ervateiro',
  'faiscação':'faiscacao',
  'ouro de aluvião':'ouro_aluviao',
  'Primeiro Planalto':'planalto1',
  'Segundo Planalto':'planalto2',
  'Terceiro Planalto':'planalto3',
  'Escarpa Devoniana':'escarpa',
  'Serra Geral':'serrageral',
  'araucária':'araucaria','araucárias':'araucaria',
  'terra roxa':'terraroxa',
  'sambaquis':'sambaqui','sambaqui':'sambaqui',
  'Caminho do Peabiru':'peabiru',
  'Kaingang':'kaingang',
  'Guarani':'guarani',
  'Carijós':'carijo',
  'Xetá':'xeta',
  'Real Expedição':'realexp',
  'colônia militar':'colmilitar','colônias militares':'colmilitar',
  'comarca':'comarca',
  'província':'provincia',
  'Lei nº 704':'lei704',
  'Estrada da Graciosa':'graciosa',
  'Companhia de Terras Norte do Paraná':'ctnp',
  'geada negra':'geadanegra',
  'Contestado':'contestado',
  'monge':'monge',
  'caboclos':'caboclo','caboclo':'caboclo',
  'maragatos':'maragato','maragato':'maragato',
  'pica-paus':'picapau',
  'Revolução Federalista':'revfederalista',
  'Cerco da Lapa':'cercolapa',
  'Revolução Farroupilha':'revfarroupilha',
  'Revolução Liberal':'revliberal',
  'Questão de Palmas':'questaopalmas',
  'posseiros':'posseiro','posseiro':'posseiro',
  'CANGO':'cango',
  'GETSOP':'getsop',
  'MARIPÁ':'maripa',
  'Território Federal do Iguaçu':'territiguacu',
  'obrages':'obrage','obrage':'obrage',
  'mensus':'mensu','mensu':'mensu',
  'Pico Paraná':'picoparana',
  'Sete Quedas':'seteQuedas','Salto de Sete Quedas':'seteQuedas',
  'Barão do Serro Azul':'serroazul'
};
