/* ===================== JORNADA DO PARANÁ: ROTEIRO =====================
   Capítulos em ordem cronológica. Cada cena: y (época), t (texto), m (mudanças no mapa em relação à
   cena anterior: z enquadramento, l camadas, r/r2 regiões pintadas, c cidades, rt caminhos, a áreas,
   rv rios em destaque, lg legenda das cores). Perguntas: q + o (a primeira opção é a certa; o app
   embaralha) + x (explicação); qm = tocar a região r no mapa; qo = pôr os itens de o em ordem.
   lb marca pergunta de relembrar capítulo anterior. Datas e nomes conferidos em fontes oficiais e
   acadêmicas (prefeituras, Assembleia Legislativa, Arquivo Público, Itaipu, IBGE). */
const JN_CAP=[];
const JN_ALL=['litoral','curitiba','camposgerais','sudeste','guarapuava','palmas','sudoeste','oeste','nortepioneiro','nortenovo','noroeste','centro'];

JN_CAP.push({id:'c0',n:'O palco',t:'Conhecendo o mapa antes da história',era:'Hoje',tp:'geo-reg',reg:['curitiba'],
sc:[
{y:'Hoje',m:{z:'wide',l:['rios','nb'],c:['Curitiba']},t:'Antes de contar a história, você precisa enxergar o palco. Toda vez que eu falar de um lugar, ele vai acender neste mapa.\nEste é o **Paraná**, no sul do Brasil. A capital, **Curitiba**, fica no leste, perto do mar.'},
{m:{c:[]},t:'Repare nos vizinhos, escritos em cinza. Ao **norte**, **São Paulo**. Ao **sul**, **Santa Catarina**. A **oeste**, o **Mato Grosso do Sul** e o **Paraguai**. A **sudoeste**, a **Argentina**. A **leste**, o **Oceano Atlântico**.\nGuarde: o Paraná faz fronteira com **dois países**.'},
{q:'Com quais países o Paraná faz fronteira?',o:['Paraguai e Argentina','Paraguai e Uruguai','Argentina e Uruguai','Bolívia e Paraguai'],x:'Paraguai a oeste, pelo rio Paraná; Argentina a sudoeste, pelo rio Iguaçu. O Uruguai faz fronteira com o Rio Grande do Sul.'},
{m:{z:'pr',rv:['paranapanema','parana','iguacu'],c:['Foz do Iguaçu','Cataratas do Iguaçu','Itaipu']},t:'Três rios desenham as bordas do estado (estão mais grossos no mapa).\nNo **norte**, o **Paranapanema** separa o Paraná de São Paulo. No **oeste**, o **rio Paraná** separa do Mato Grosso do Sul e do Paraguai; é nele que fica **Itaipu**. No **sul**, o **Iguaçu** atravessa o estado de leste a oeste e termina nas **Cataratas**, em **Foz do Iguaçu**.'},
{q:'Qual rio forma a divisa norte do Paraná com São Paulo?',o:['Paranapanema','Iguaçu','Tibagi','Ivaí'],x:'O Paranapanema corre no norte, de leste para oeste, até desaguar no rio Paraná.'},
{m:{rv:[],c:[],l:['rios','relevo'],r:['litoral'],z:'leste'},t:'Agora o relevo, que explica quase tudo o que vem depois. Saindo do mar, você encontra uma faixa baixa: o **Litoral** (pintado).\nLogo atrás, uma muralha de montanhas: a **Serra do Mar**. Nela fica o **Pico Paraná**, com 1.877 m, o ponto mais alto do Sul do Brasil.'},
{m:{r:['curitiba'],c:['Curitiba','Pico Paraná']},t:'Subindo a serra, você chega a um planalto de campos e pinheirais: o **Primeiro Planalto**, onde fica **Curitiba**, a cerca de 900 m de altitude.\nPor isso a viagem de Curitiba ao litoral é uma descida forte: são poucas dezenas de quilômetros e quase mil metros de desnível.'},
{m:{z:'pr',r:['camposgerais'],c:['Ponta Grossa','Castro','Lapa']},t:'Indo para o oeste, outro degrau: a **Escarpa Devoniana**. Em cima dela está o **Segundo Planalto**, com os **Campos Gerais**: Ponta Grossa, Castro, Lapa. São campos naturais, ótimos para criar gado.\nDepois, mais um degrau, a **Serra Geral** (ou da Esperança), e começa o **Terceiro Planalto**, o maior de todos: Guarapuava, o Norte, o Oeste e o Sudoeste.'},
{qo:'Coloque em ordem, do mar para o interior:',o:['Litoral','Serra do Mar','Primeiro Planalto (Curitiba)','Segundo Planalto (Campos Gerais)','Terceiro Planalto (Guarapuava, Norte, Oeste)'],x:'Mar → Litoral → Serra do Mar → 1º Planalto → Escarpa Devoniana → 2º Planalto → Serra Geral → 3º Planalto.'},
{qm:'Toque nos **Campos Gerais**, o Segundo Planalto.',r:'camposgerais',x:'Os Campos Gerais ficam entre Curitiba e Guarapuava: Ponta Grossa, Castro, Palmeira, Lapa, Jaguariaíva.'},
{m:{l:['rios'],r:['nortepioneiro','nortenovo','noroeste'],c:['Jacarezinho','Londrina','Maringá','Umuarama'],lg:['O Norte, em três ondas']},t:'Vou usar nomes de regiões a história inteira, então já vá se acostumando.\nNo alto do mapa fica o **Norte**, ocupado em ondas: o **Norte Pioneiro** (ou Norte Velho), colado em São Paulo; o **Norte Novo**, de Londrina e Maringá; e o **Noroeste** (Norte Novíssimo), de Umuarama e Paranavaí.'},
{m:{r:['guarapuava','palmas','sudoeste','oeste'],c:['Guarapuava','Palmas','Francisco Beltrão','Cascavel','Foz do Iguaçu'],lg:null},t:'No centro e no sul, os **Campos de Guarapuava** e os **Campos de Palmas**. No canto de baixo, à esquerda, o **Sudoeste** (Francisco Beltrão, Pato Branco) e o **Oeste** (Cascavel, Toledo, Foz do Iguaçu).\nO Oeste e o Sudoeste foram as últimas áreas colonizadas, já no século XX.'},
{qm:'Toque no **Oeste**, a região de Cascavel, Toledo e Foz do Iguaçu.',r:'oeste',x:'O Oeste faz fronteira com o Paraguai (rio Paraná) e com a Argentina (rio Iguaçu).'},
{m:{r:['curitiba','camposgerais','sudeste','guarapuava','palmas'],r2:['nortepioneiro','nortenovo','noroeste','centro','oeste','sudoeste'],c:[],lg:['Mata de Araucárias e campos naturais','Florestas sobre a terra roxa']},t:'Por fim, a paisagem original. O leste e o centro tinham a **Mata de Araucárias** (o pinheiro-do-paraná, símbolo do estado) misturada a **campos naturais**. Na serra e no litoral, **Mata Atlântica**.\nNo Norte e no Oeste, florestas densas sobre a **terra roxa**: um solo avermelhado e muito fértil, que vem da decomposição do **basalto**. É ela que vai atrair o café.'},
{q:'A terra roxa, solo fértil do Norte e do Oeste, vem da decomposição de qual rocha?',o:['Basalto','Granito','Calcário','Mármore'],x:'O Terceiro Planalto é coberto por derrames de basalto. Decomposto, ele forma a terra roxa.'},
{q:'Onde fica Curitiba?',o:['No Primeiro Planalto','No Segundo Planalto','No Litoral','No Terceiro Planalto'],x:'Curitiba está no Primeiro Planalto, logo depois da Serra do Mar.'},
{m:{r:[],r2:[],lg:null,z:'pr',l:['rios']},t:'Pronto: você já tem o palco. Quando se perder, toque no ícone de **mapa**, no alto, para abrir o **Atlas**, com camadas de rios, relevo, caminhos e cidades.\nAgora sim: vamos voltar alguns milhares de anos.'}
],
res:['Vizinhos: **SP** (norte), **SC** (sul), **MS** e **Paraguai** (oeste), **Argentina** (sudoeste), **Atlântico** (leste).','Rios de fronteira: **Paranapanema** (norte), **Paraná** (oeste, Itaipu), **Iguaçu** (sul e sudoeste, Cataratas).','Relevo do mar para o interior: Litoral → **Serra do Mar** (Pico Paraná, 1.877 m) → **1º Planalto** (Curitiba) → Escarpa Devoniana → **2º Planalto** (Campos Gerais) → Serra Geral → **3º Planalto**.','**Campos Gerais**: Ponta Grossa, Castro, Palmeira, Lapa, Jaguariaíva.','**Terra roxa** (do basalto) no Norte e no Oeste; **Mata de Araucárias** e campos no centro-leste.'],
tl:[],
pers:[]});

JN_CAP.push({id:'c1',n:'Os primeiros donos da terra',t:'Povos indígenas e o Caminho do Peabiru',era:'Antes de 1500',tp:'hist-ocup',reg:['litoral'],
sc:[
{y:'Há milhares de anos',m:{z:'litoral',r:['litoral'],c:['Paranaguá','Guaraqueçaba','Ilha do Mel']},t:'Muito antes de qualquer europeu, o litoral já era habitado. Os **povos dos sambaquis** viviam da pesca e da coleta de mariscos.\nEles deixaram montes enormes de conchas, ossos, ferramentas e até sepulturas: os **sambaquis**. Só no litoral paranaense há centenas deles, alguns com milhares de anos.'},
{q:'O que são sambaquis?',o:['Montes de conchas e restos deixados por antigos povos do litoral','Aldeias jesuíticas do século XVII','Fortes portugueses na baía de Paranaguá','Pinturas indígenas nas cavernas dos Campos Gerais'],x:'Sambaquis são sítios arqueológicos feitos de conchas acumuladas por povos pescadores e coletores.'},
{y:'Século XVI',m:{z:'pr',r:['litoral','oeste','noroeste','centro','nortenovo'],c:[],lg:['Terras guarani (Tupi-Guarani)']},t:'Quando os europeus chegaram, dois grandes grupos dividiam o território.\nOs **Tupi-Guarani**: os **Guarani**, no oeste e nos vales dos grandes rios, e os **Carijós**, um grupo guarani, no litoral. Plantavam milho e mandioca e viviam em aldeias.'},
{m:{r:['curitiba','camposgerais','guarapuava','palmas','sudeste','sudoeste'],lg:['Terras dos povos Jê (Kaingang e Xokleng)']},t:'No planalto viviam os povos **Jê**: os **Kaingang**, nos campos de Guarapuava e Palmas, e os **Xokleng**, nas matas do sul e da serra.\nOs Kaingang vão aparecer muito nesta história, porque os campos onde moravam eram exatamente os que os criadores de gado queriam.'},
{q:'Kaingang e Xokleng pertencem a qual grupo?',o:['Jê','Tupi-Guarani','Aruaque','Karib'],x:'Kaingang e Xokleng são Jê, povos do planalto. Guarani e Carijós são Tupi-Guarani.'},
{m:{z:'norte',r:['noroeste'],c:['Umuarama','Paranavaí'],lg:['Serra dos Dourados, terra dos Xetá']},t:'Havia ainda os **Xetá**, na **Serra dos Dourados**, no noroeste. Foram o último povo do Sul a ser contatado, só nas décadas de **1940 e 1950**, quando a colonização chegou lá.\nEm poucos anos quase desapareceram. Hoje restam poucos descendentes, que lutam pela memória do seu povo.'},
{q:'Qual povo indígena do Paraná só foi contatado em meados do século XX e quase foi extinto?',o:['Xetá','Kaingang','Carijó','Guarani'],x:'Os Xetá, da Serra dos Dourados, foram contatados nos anos 1940 e 1950 e quase exterminados na expansão da fronteira agrícola.'},
{y:'Antes de 1500',m:{z:'wide',r:[],lg:null,rt:['peabiru'],c:['Paranaguá','Curitiba','Tibagi','Peabiru','Guaíra']},t:'Esses povos se deslocavam por uma rede de trilhas enormes. A mais famosa é o **Caminho do Peabiru**, que ligava o **litoral atlântico** ao **Paraguai** e até aos **Andes**, atravessando o Paraná de leste a oeste.\nA linha no mapa é um traçado aproximado: na verdade eram vários ramais.'},
{m:{c:['Peabiru','Campo Mourão']},t:'Guarde este caminho: foi por ele que os primeiros europeus entraram no interior.\nUma cidade do centro-oeste do Paraná se chama **Peabiru**, em homenagem à trilha.'},
{q:'O Caminho do Peabiru ligava:',o:['O litoral atlântico ao Paraguai e aos Andes','Curitiba a Sorocaba, para levar gado','Paranaguá a Curitiba, pela Serra do Mar','Foz do Iguaçu a Guarapuava, para levar erva-mate'],x:'O Peabiru era uma rede de trilhas indígenas de milhares de quilômetros entre o Atlântico e o interior do continente.'},
{m:{z:'pr',rt:[],c:[],rv:['parana']},t:'E o nome **Paraná**? Vem do tupi-guarani e costuma ser traduzido como **“semelhante ao mar”**: era o nome do grande rio do oeste, largo como um mar. O estado herdou o nome do rio.'},
{q:'O nome “Paraná” vem do tupi-guarani e significa algo como:',o:['Semelhante ao mar','Terra dos pinheiros','Campo alto','Rio de pedras'],x:'Pará (mar) + nã (semelhante): semelhante ao mar, o grande rio.'},
{m:{rv:[]},t:'Esses povos não saem da história: vão reaparecer como guias, aliados, trabalhadores forçados e resistentes em quase todos os capítulos.\nNo próximo capítulo chegam os primeiros europeus. E quem chega primeiro ao interior não são os portugueses.'}
],
res:['**Sambaquis**: montes de conchas de antigos povos pescadores do litoral.','**Tupi-Guarani**: Guarani (oeste e vales) e **Carijós** (litoral).','**Jê**: **Kaingang** (campos de Guarapuava e Palmas) e **Xokleng** (matas do sul e da serra).','**Xetá**: Serra dos Dourados (noroeste), contatados só nos anos 1940–1950, quase extintos.','**Caminho do Peabiru**: rede de trilhas indígenas do Atlântico ao Paraguai e aos Andes.','**Paraná** = “semelhante ao mar”, nome do grande rio.'],
tl:[['Milhares de anos atrás','Povos dos sambaquis no litoral'],['Antes de 1500','Caminho do Peabiru liga o Atlântico ao interior'],['Anos 1940–1950','Contato com os Xetá, na Serra dos Dourados']],
pers:[['Kaingang','Povo Jê dos campos de Guarapuava e Palmas'],['Carijós','Grupo guarani do litoral'],['Xetá','Povo da Serra dos Dourados, contatado no século XX']]});

JN_CAP.push({id:'c2',n:'O Paraná espanhol',t:'Tordesilhas, Guairá, jesuítas e bandeirantes',era:'1494–1750',tp:'hist-ocup',reg:['noroeste','centro'],
sc:[
{lb:1,q:'Lembra? Qual rio forma a divisa norte com São Paulo?',o:['Paranapanema','Iguaçu','Ivaí','Ribeira'],x:'O Paranapanema é a divisa norte; o Paraná, a oeste; o Iguaçu, no sul.'},
{y:'1494',m:{z:'wide',l:['rios','nb','tord'],c:['Curitiba','Paranaguá']},t:'Em **1494**, Portugal e Espanha assinaram o **Tratado de Tordesilhas**: uma linha imaginária dividia as terras do Novo Mundo. A leste da linha, Portugal; a oeste, Espanha.\nOlhe a linha tracejada: ela passa perto do litoral paranaense. Resultado: **quase todo o Paraná seria espanhol**. Curitiba ficava do lado da Espanha.'},
{q:'Pelo Tratado de Tordesilhas (1494), a maior parte do atual Paraná pertenceria:',o:['À Espanha','A Portugal','Aos jesuítas','À França'],x:'A linha passava perto do litoral; o interior paranaense ficava do lado espanhol.'},
{y:'1541–1542',m:{l:['rios','nb'],c:['Cataratas do Iguaçu'],rt:['cabeza']},t:'Em **1541**, o espanhol **Álvar Núñez Cabeza de Vaca** desembarcou no litoral de Santa Catarina com uma missão: chegar a **Assunção**, no Paraguai, por terra.\nGuiado por indígenas, cruzou o Paraná pelas trilhas do Peabiru. Em **janeiro de 1542**, foi o **primeiro europeu a ver as Cataratas do Iguaçu**.'},
{q:'Quem foi o primeiro europeu a ver as Cataratas do Iguaçu?',o:['Álvar Núñez Cabeza de Vaca','Antônio Raposo Tavares','Gabriel de Lara','Pedro Álvares Cabral'],x:'Cabeza de Vaca, em janeiro de 1542, a caminho de Assunção.'},
{y:'1554–1570',m:{z:'pr',rt:[],a:['guaira'],c:['Ciudad Real del Guairá','Villa Rica del Espíritu Santo']},t:'Os espanhóis criaram aqui a **Província del Guairá**: o oeste e o norte do atual Paraná, entre os rios Paranapanema, Paraná, Iguaçu e Tibagi (área hachurada).\nFundaram cidades: **Ontiveros** (1554), **Ciudad Real del Guairá** (1557), perto do rio Paraná, e **Villa Rica del Espíritu Santo** (1570), depois levada para a beira do rio **Ivaí**.'},
{q:'Como se chamava a província espanhola no oeste e no norte do atual Paraná?',o:['Guairá','Iguaçu','Missões','Prata'],x:'Província del Guairá, com Ontiveros, Ciudad Real e Villa Rica.'},
{y:'1610',m:{c:['Loreto e Santo Inácio (reduções)']},t:'Em **1610**, padres **jesuítas** espanhóis fundaram as primeiras **reduções** do Guairá: **Loreto** e **Santo Inácio**, no vale do Paranapanema.\nReduções eram aldeias onde os jesuítas reuniam os **Guarani** para catequizar e organizar o trabalho. Com o padre **Antonio Ruiz de Montoya**, surgiram mais de uma dezena delas.'},
{q:'O que eram as reduções jesuíticas do Guairá?',o:['Aldeias onde jesuítas reuniam e catequizavam os Guarani','Fortes militares portugueses na fronteira','Fazendas de gado dos Campos Gerais','Vilas de mineradores de ouro no litoral'],x:'As reduções concentravam milhares de Guarani sob a direção dos jesuítas.'},
{y:'1628–1632',m:{l:['rios','nb'],rt:['bandeiras']},t:'Só que as reduções reuniam milhares de indígenas num lugar só, e isso atraiu os **bandeirantes paulistas**, que caçavam indígenas para vender como escravos.\nEntre **1628 e 1632**, bandeiras de **Antônio Raposo Tavares** e **Manuel Preto** atacaram e destruíram as reduções.'},
{m:{rt:[],rv:['parana']},t:'Em **1631**, Montoya comandou uma fuga desesperada de milhares de Guarani rio abaixo, para o sul, onde depois surgiriam as Missões do Rio Grande do Sul, da Argentina e do Paraguai.\nAs cidades espanholas também foram abandonadas. O **Guairá espanhol acabou**.'},
{q:'Quem destruiu as reduções jesuíticas do Guairá, entre 1628 e 1632?',o:['Bandeirantes paulistas, como Raposo Tavares','Soldados espanhóis vindos de Assunção','Os Kaingang dos campos de Guarapuava','Tropeiros vindos do Rio Grande do Sul'],x:'As bandeiras paulistas buscavam indígenas para escravizar.'},
{y:'1750',m:{a:[],rv:[],c:[],l:['rios','nb']},t:'Com os espanhóis fora, o território ficou, na prática, com Portugal. Em **1750**, o **Tratado de Madri** reconheceu isso pelo princípio do **uti possidetis**: a terra fica com quem de fato a ocupa.\nTordesilhas estava superado.'},
{q:'Qual tratado, de 1750, reconheceu a posse portuguesa sobre terras que antes seriam espanholas?',o:['Tratado de Madri','Tratado de Tordesilhas','Tratado de Petrópolis','Tratado de Itaipu'],x:'O Tratado de Madri aplicou o uti possidetis: vale quem ocupa.'},
{qm:'Toque na região onde ficava **Villa Rica del Espíritu Santo**, às margens do rio Ivaí (a região de Campo Mourão).',r:'centro',x:'Villa Rica foi transferida para a margem do Ivaí, na região de Campo Mourão e Fênix.'},
{m:{l:['rios']},t:'Resumo do capítulo: o Paraná quase foi espanhol. Os espanhóis e os jesuítas vieram pelo oeste; os bandeirantes paulistas acabaram com isso.\nNo próximo capítulo, os portugueses chegam pelo lado oposto: o mar. E atrás de ouro.'}
],
res:['**Tordesilhas (1494)**: quase todo o Paraná ficava do lado **espanhol**.','**Cabeza de Vaca**: cruzou o Paraná em 1541–1542; primeiro europeu a ver as **Cataratas** (jan. 1542).','**Guairá** (espanhol): Ontiveros (1554), **Ciudad Real** (1557), **Villa Rica** (1570, depois no Ivaí).','**Reduções jesuíticas** desde **1610** (Loreto, Santo Inácio), com o padre **Montoya**.','**Bandeirantes paulistas** (Raposo Tavares, Manuel Preto) destruíram as reduções entre **1628 e 1632**.','**Tratado de Madri (1750)**: uti possidetis, posse portuguesa reconhecida.'],
tl:[['1494','Tratado de Tordesilhas'],['1541–1542','Cabeza de Vaca cruza o Paraná e vê as Cataratas'],['1554','Fundação de Ontiveros'],['1557','Fundação de Ciudad Real del Guairá'],['1570','Fundação de Villa Rica del Espíritu Santo'],['1610','Primeiras reduções jesuíticas (Loreto e Santo Inácio)'],['1628–1632','Bandeiras destroem as reduções do Guairá'],['1750','Tratado de Madri (uti possidetis)']],
pers:[['Álvar Núñez Cabeza de Vaca','Espanhol, primeiro europeu a ver as Cataratas (1542)'],['Antonio Ruiz de Montoya','Jesuíta das reduções do Guairá; liderou a fuga de 1631'],['Antônio Raposo Tavares','Bandeirante que atacou as reduções'],['Manuel Preto','Bandeirante que atacou as reduções']]});

JN_CAP.push({id:'c3',n:'Ouro e as primeiras vilas',t:'Paranaguá, a Serra do Mar e Curitiba',era:'Séculos XVI e XVII',tp:'hist-ocup',reg:['litoral','curitiba'],
sc:[
{lb:1,q:'Lembra? Quais povos Jê viviam no planalto paranaense?',o:['Kaingang e Xokleng','Guarani e Carijós','Xetá e Tupinambá','Carijós e Kaingang'],x:'Kaingang e Xokleng são Jê; Guarani e Carijós, Tupi-Guarani.'},
{y:'1550–1560',m:{z:'litoral',l:['rios','relevo'],r:['litoral'],c:['Ilha da Cotinga','Paranaguá']},t:'Enquanto os espanhóis estavam no oeste, os portugueses subiam o litoral a partir de **São Vicente** e **Cananéia**, em São Paulo.\nPor volta de **1550–1560**, os primeiros moradores se instalaram na **Ilha da Cotinga**, dentro da baía de Paranaguá, com medo dos Carijós do continente.'},
{y:'Século XVII',t:'O que trouxe gente de verdade foi o **ouro**. Não ouro de mina funda: **ouro de aluvião**, pepitas e pó nos leitos dos rios, garimpados com bateia (a chamada **faiscação**).\nO ouro apareceu nos rios do litoral e, depois, no planalto.'},
{y:'1648',m:{c:['Paranaguá']},t:'O nome desta fase é **Gabriel de Lara**, o capitão-povoador. Ele levou provas do ouro às autoridades de São Paulo e, em **29 de julho de 1648**, o povoado virou **Vila de Nossa Senhora do Rosário de Paranaguá**.\nFoi a **primeira vila** do atual Paraná.'},
{q:'Qual foi a primeira vila do atual Paraná, criada em 1648?',o:['Paranaguá','Curitiba','Antonina','Castro'],x:'Paranaguá virou vila em 29 de julho de 1648.'},
{q:'O ouro que atraiu os primeiros povoadores era:',o:['Ouro de aluvião, garimpado nos rios','Ouro de minas profundas, como em Minas Gerais','Ouro trazido pelos espanhóis do Guairá','Ouro comprado dos Kaingang'],x:'Ouro de aluvião: pequenas quantidades nos leitos dos rios, garimpadas com bateia.'},
{y:'Século XVII',m:{z:'leste',r:['litoral','curitiba'],rt:['itupava'],c:['Paranaguá','Morretes','Curitiba']},t:'Atrás de mais ouro, os mineradores **subiram a Serra do Mar** por trilhas indígenas. A mais famosa virou o **Caminho do Itupava**, entre o planalto e Morretes, depois calçado com pedras por pessoas escravizadas.\nLá em cima, no **Primeiro Planalto**, encontraram campos, pinheirais e mais ouro nos rios.'},
{y:'1668',m:{r:['curitiba'],rt:['itupava'],c:['Curitiba']},t:'No planalto surgiu um povoado. Em **1668**, o mesmo **Gabriel de Lara** mandou erguer ali o **pelourinho**, a coluna que simbolizava a justiça do rei e o começo da vida oficial.\nEsse povoado é **Curitiba**.'},
{y:'1693',t:'Em **29 de março de 1693**, com a liderança de **Mateus Martins Leme**, Curitiba virou **Vila de Nossa Senhora da Luz dos Pinhais de Curitiba**.\nRepare no nome: **pinhais**, por causa das araucárias. O próprio nome Curitiba vem do tupi e costuma ser ligado a “muitos pinheiros”.'},
{q:'Em que ano Curitiba foi elevada a vila?',o:['1693','1648','1853','1668'],x:'1668 é o pelourinho; 1693, a vila. Paranaguá já era vila desde 1648.'},
{qm:'Toque na região onde fica **Curitiba**.',r:'curitiba',x:'Curitiba fica no Primeiro Planalto, logo atrás da Serra do Mar.'},
{m:{rt:[],c:['Antonina','Morretes','Paranaguá'],z:'litoral',r:['litoral']},t:'No fundo da baía, no pé da serra, cresceram outros povoados que serviam de porto para quem descia do planalto: **Antonina** e **Morretes**.\nO litoral virou a porta de entrada e de saída do Paraná, e continua sendo, com o porto de Paranaguá.'},
{y:'Fim do século XVII',m:{z:'pr',r:[],c:[],l:['rios','nb']},t:'O ouro paranaense era pouco. No fim do século XVII, os paulistas descobriram ouro em enorme quantidade em **Minas Gerais**, e muita gente foi embora para lá.\nQuem ficou no planalto passou a viver de **agricultura de subsistência** e, principalmente, de **gado**. É o começo do próximo capítulo.'},
{q:'Por que a mineração no Paraná perdeu força no fim do século XVII?',o:['Descobriram muito mais ouro em Minas Gerais','Os espanhóis tomaram as minas','Os jesuítas proibiram a mineração','Uma geada destruiu as lavras'],x:'As grandes jazidas de Minas Gerais atraíram os mineradores.'},
{qo:'Coloque em ordem:',o:['Moradores na Ilha da Cotinga (1550–1560)','Paranaguá vira vila (1648)','Pelourinho de Curitiba (1668)','Curitiba vira vila (1693)'],x:'Cotinga → Paranaguá (1648) → pelourinho de Curitiba (1668) → vila de Curitiba (1693).'}
],
res:['Primeiros moradores na **Ilha da Cotinga** (1550–1560), vindos de São Vicente e Cananéia.','**Ouro de aluvião** (faiscação): primeiro ciclo econômico, no século XVII.','**Gabriel de Lara**: capitão-povoador; **Paranaguá** vira vila em **29/07/1648** (primeira vila).','**Caminho do Itupava**: trilha pela Serra do Mar entre o planalto e Morretes.','**Curitiba**: pelourinho em **1668**; vila em **29/03/1693** (Mateus Martins Leme).','Fim do ouro: as minas de **Minas Gerais** esvaziaram a mineração; o planalto passa a viver de gado.'],
tl:[['1550–1560','Moradores na Ilha da Cotinga'],['29/07/1648','Paranaguá, primeira vila'],['1668','Pelourinho de Curitiba'],['29/03/1693','Curitiba vira vila'],['Fim do séc. XVII','Ouro de Minas Gerais esvazia a mineração paranaense']],
pers:[['Gabriel de Lara','Capitão-povoador de Paranaguá; ergueu o pelourinho de Curitiba (1668)'],['Mateus Martins Leme','Liderou a elevação de Curitiba a vila (1693)']]});

JN_CAP.push({id:'c4',n:'Gado, tropas e tropeiros',t:'Os Campos Gerais e o Caminho de Viamão',era:'Século XVIII',tp:'hist-ciclos',reg:['camposgerais'],
sc:[
{lb:1,q:'Lembra? Quem mandou erguer o pelourinho de Curitiba, em 1668?',o:['Gabriel de Lara','Mateus Martins Leme','Cabeza de Vaca','Raposo Tavares'],x:'Gabriel de Lara, o capitão-povoador. Mateus Martins Leme liderou a elevação a vila, em 1693.'},
{y:'Século XVIII',m:{z:'cg',l:['rios','relevo'],r:['camposgerais'],c:['Ponta Grossa','Castro','Lapa']},t:'Lembra dos **Campos Gerais**, no Segundo Planalto? São campos naturais, com capim e capões de mata. Para quem quer criar gado, é um paraíso.\nNo século XVIII, a Coroa distribuiu **sesmarias** (grandes lotes de terra) e surgiram ali as **fazendas de gado**.'},
{y:'Por volta de 1730',m:{z:'wide',l:['rios','nb'],rt:['tropas'],c:['Viamão (RS) ↓','Sorocaba (SP) →']},t:'Ao mesmo tempo, **Minas Gerais** vivia a febre do ouro e precisava de **animais de carga** e de carne. No sul, no Rio Grande, havia rebanhos imensos de **mulas** e **gado**.\nFaltava ligar as duas pontas. Por volta de **1730**, abriu-se o **Caminho de Viamão**, também chamado de Estrada das Tropas, com nomes como **Francisco de Sousa Faria** e **Cristóvão Pereira de Abreu**.'},
{m:{z:'pr',c:['Rio Negro','Lapa','Palmeira','Ponta Grossa','Castro','Jaguariaíva','Sengés']},t:'O caminho saía de **Viamão**, no Rio Grande do Sul, e ia até a grande **feira de Sorocaba**, em São Paulo, onde os animais eram vendidos para Minas.\nE passava pelo meio do Paraná: **Rio Negro, Lapa, Palmeira, Ponta Grossa, Castro, Piraí do Sul, Jaguariaíva e Sengés**.'},
{q:'O Caminho de Viamão levava tropas de mulas e gado:',o:['Do Rio Grande do Sul até a feira de Sorocaba (SP)','De Curitiba até o porto de Paranaguá','De Foz do Iguaçu até Guarapuava','De São Paulo até Assunção, no Paraguai'],x:'Sul → Sorocaba, atravessando os Campos Gerais; de Sorocaba, os animais seguiam para Minas.'},
{y:'1730–1900',m:{z:'cg',r:['camposgerais']},t:'Os homens que conduziam as tropas eram os **tropeiros**. A viagem levava meses.\nNos Campos Gerais, os animais paravam nas **invernadas**, pastos onde descansavam e engordavam antes de seguir. Nos pontos de parada, os **pousos**, nasciam capelas, vendas e casas.'},
{t:'Muitos pousos viraram cidades. **Castro** foi freguesia (Sant’Ana do Iapó) em 1774 e **vila em 1789**. **Ponta Grossa** virou freguesia em **1823** e vila em **1855**. **Lapa**, **Palmeira** e **Jaguariaíva** também nasceram nesse caminho.\nPor isso se diz que o tropeirismo **criou as cidades dos Campos Gerais**.'},
{qm:'Toque na região onde ficavam as invernadas e os pousos dos tropeiros.',r:'camposgerais',x:'Os Campos Gerais, no Segundo Planalto: Castro, Ponta Grossa, Lapa, Palmeira.'},
{q:'Qual destas cidades **não** nasceu no caminho das tropas?',o:['Paranaguá','Castro','Lapa','Ponta Grossa'],x:'Paranaguá é do litoral e do ouro (1648). Castro, Lapa e Ponta Grossa são pousos do Caminho de Viamão.'},
{m:{z:'pr',c:[]},t:'O tropeirismo deixou marcas que você reconhece até hoje: o **chimarrão**, o **feijão tropeiro**, o **charque**, o gosto pelo gado e pelas festas campeiras.\nE fez do Paraná um **corredor** entre o Sul e o Sudeste. Guarde isso: vai pesar muito na emancipação.'},
{q:'Depois do ouro, qual foi a principal atividade econômica do Paraná no século XVIII?',o:['Criação e comércio de gado (tropeirismo)','Café','Madeira de araucária','Soja'],x:'Ouro (séc. XVII) → tropeirismo (séc. XVIII) → erva-mate (séc. XIX) → madeira → café.'},
{y:'1768–1774',m:{rt:[],r:['guarapuava'],c:['Tibagi','Guarapuava']},t:'Ainda no século XVIII, o governador de São Paulo, o **Morgado de Mateus**, mandou **Afonso Botelho** explorar os sertões do Tibagi, do Ivaí e do Iguaçu.\nEntre **1768 e 1774**, suas expedições chegaram aos **Campos de Guarapuava**, mas não conseguiram ficar: os Kaingang resistiram. A conquista ficou para o século seguinte.'},
{q:'Quem comandou as expedições de 1768 a 1774 que chegaram aos Campos de Guarapuava?',o:['Afonso Botelho','Diogo Pinto de Azevedo Portugal','Cabeza de Vaca','Gabriel de Lara'],x:'Afonso Botelho, a mando do Morgado de Mateus. A ocupação efetiva só veio em 1810.'},
{m:{r:['camposgerais'],r2:['litoral','curitiba'],c:[],lg:['Gado (século XVIII)','Ouro (século XVII)']},t:'Até aqui: **ouro** no litoral e em Curitiba; **gado** nos Campos Gerais.\nNo próximo capítulo, os portugueses vão atrás dos campos que faltam: **Guarapuava e Palmas**, terra dos Kaingang.'}
],
res:['**Campos Gerais** (2º Planalto): sesmarias e fazendas de gado no século XVIII.','**Caminho de Viamão** (c. 1730): de **Viamão (RS)** à **feira de Sorocaba (SP)**; os animais abasteciam Minas Gerais.','**Tropeiros**, **invernadas** (engorda) e **pousos** (paradas) que viraram cidades.','Cidades do caminho: **Castro** (vila em 1789), **Ponta Grossa** (freguesia 1823, vila 1855), Lapa, Palmeira, Jaguariaíva.','Heranças: chimarrão, feijão tropeiro, charque; o Paraná vira corredor entre Sul e Sudeste.','**Afonso Botelho** (1768–1774) chega a Guarapuava, sem ocupar.'],
tl:[['c. 1730','Abertura do Caminho de Viamão'],['1768–1774','Expedições de Afonso Botelho'],['1774','Freguesia de Sant’Ana do Iapó (Castro)'],['1789','Castro vira vila'],['1823','Ponta Grossa vira freguesia'],['1855','Ponta Grossa vira vila']],
pers:[['Cristóvão Pereira de Abreu','Abriu e usou o caminho das tropas (1731)'],['Francisco de Sousa Faria','Pioneiro da estrada do Sul (1728–1730)'],['Morgado de Mateus','Governador de São Paulo que mandou explorar os sertões'],['Afonso Botelho','Comandou as expedições de 1768–1774']]});

JN_CAP.push({id:'c5',n:'A conquista dos campos',t:'Guarapuava, Palmas e os Kaingang',era:'1808–1895',tp:'hist-ocup',reg:['guarapuava','palmas'],
sc:[
{lb:1,q:'Lembra? Qual era o destino final das tropas do Caminho de Viamão?',o:['A feira de Sorocaba (SP)','O porto de Paranaguá','Assunção, no Paraguai','Curitiba'],x:'De Viamão (RS) a Sorocaba (SP).'},
{y:'1808',m:{z:'pr',l:['rios'],r:['guarapuava']},t:'Em 1808, a família real portuguesa chegou ao Brasil. Naquele mesmo ano, em **5 de novembro de 1808**, **D. João** assinou uma **Carta Régia** mandando conquistar e povoar os **Campos de Guarapuava** e declarando guerra aos indígenas que resistissem, principalmente os **Kaingang**.'},
{y:'1809–1810',m:{rt:['guarapuava'],c:['Curitiba','Guarapuava']},t:'A **Real Expedição**, comandada por **Diogo Pinto de Azevedo Portugal**, saiu de Curitiba em 1809. Junto ia o padre **Francisco das Chagas Lima**.\nEm **1810** chegaram aos campos e ergueram o **Fortim Atalaia**, que abrigou soldados e cerca de 300 famílias. Daí nasceu **Guarapuava**.'},
{q:'Quem comandou a Real Expedição que ocupou os Campos de Guarapuava em 1810?',o:['Diogo Pinto de Azevedo Portugal','Afonso Botelho','Gabriel de Lara','Zacarias de Góes e Vasconcelos'],x:'Diogo Pinto de Azevedo Portugal, com o padre Chagas Lima.'},
{t:'A conquista foi violenta. Os Kaingang perderam suas terras: parte resistiu, parte foi aldeada pelo padre Chagas Lima, e alguns líderes fizeram alianças com os portugueses.\nGuarde o padrão: **ocupar os campos significou tirar os Kaingang dos campos**.'},
{qm:'Toque nos **Campos de Guarapuava**.',r:'guarapuava',x:'Guarapuava fica no Terceiro Planalto, a oeste dos Campos Gerais.'},
{y:'1839',m:{r:['guarapuava','palmas'],rt:['guarapuava','palmas'],c:['Guarapuava','Palmas']},t:'Ao sul de Guarapuava havia outros campos cobiçados: os **Campos de Palmas**. Em **1839**, duas expedições chegaram quase juntas: uma de **José Ferreira dos Santos** e outra de **Pedro de Siqueira Côrtes**.\nCada uma queria para si o direito de descoberta.'},
{y:'1840',t:'A briga foi resolvida por **arbitragem**, em **1840**, e os campos foram divididos entre os dois grupos. Surgiram dezenas de fazendas de gado.\nOs fazendeiros se aliaram a líderes **Kaingang**, como **Vitorino Condá** e **Viri**, que ajudaram a “pacificar” outros grupos indígenas.'},
{q:'Os Campos de Palmas foram ocupados por volta de:',o:['1839–1840','1648','1810','1957'],x:'1810 é Guarapuava; 1839–1840, Palmas.'},
{m:{rt:['guarapuava','palmas','missoes']},t:'De Palmas partia o **Caminho das Missões**, que ligava os campos do Paraná ao Rio Grande do Sul.\nAssim, Guarapuava e Palmas também entraram no circuito do gado e dos tropeiros.'},
{y:'1895',m:{rt:[],r:['palmas','sudoeste'],c:['Palmas','Clevelândia'],l:['rios','nb']},t:'Um salto no tempo para fechar o assunto. A **Argentina** reivindicava a área entre Palmas e o rio Peperi-Guaçu: a **Questão de Palmas** (ou das Missões).\nO caso foi à arbitragem do presidente dos Estados Unidos, **Grover Cleveland**, e o Brasil, defendido pelo **Barão do Rio Branco**, venceu em **1895**. A cidade de **Clevelândia** homenageia o árbitro.'},
{q:'A Questão de Palmas, disputa de fronteira com a Argentina, terminou em 1895 com:',o:['Arbitragem do presidente dos EUA, a favor do Brasil','Uma guerra vencida pela Argentina','A divisão igual da área entre os dois países','A criação do Território do Iguaçu'],x:'Grover Cleveland deu ganho de causa ao Brasil; o advogado brasileiro foi o Barão do Rio Branco.'},
{q:'Qual povo indígena mais perdeu terras com a ocupação de Guarapuava e Palmas?',o:['Kaingang','Guarani','Xetá','Carijó'],x:'Os campos de Guarapuava e Palmas eram território Kaingang.'},
{qo:'Coloque em ordem:',o:['Expedições de Afonso Botelho (1768–1774)','Carta Régia de D. João (1808)','Real Expedição funda o Fortim Atalaia (1810)','Ocupação dos Campos de Palmas (1839–1840)','Questão de Palmas vencida pelo Brasil (1895)'],x:'Botelho → Carta Régia → Atalaia/Guarapuava → Palmas → arbitragem de 1895.'}
],
res:['**Carta Régia de 5/11/1808** (D. João): conquista de Guarapuava e guerra aos Kaingang.','**Real Expedição**: **Diogo Pinto de Azevedo Portugal** e o padre **Chagas Lima**; **Fortim Atalaia** em **1810** → Guarapuava.','**Campos de Palmas** (1839–1840): **José Ferreira dos Santos** × **Pedro de Siqueira Côrtes**, resolvido por arbitragem.','Líderes Kaingang aliados: **Vitorino Condá** e **Viri**.','**Questão de Palmas** (1895): arbitragem de **Grover Cleveland**, vitória do Brasil com o **Barão do Rio Branco** → Clevelândia.'],
tl:[['05/11/1808','Carta Régia manda conquistar Guarapuava'],['1810','Real Expedição e Fortim Atalaia (Guarapuava)'],['1839–1840','Ocupação dos Campos de Palmas'],['1895','Questão de Palmas vencida pelo Brasil']],
pers:[['D. João','Príncipe regente; Carta Régia de 1808'],['Diogo Pinto de Azevedo Portugal','Comandante da Real Expedição a Guarapuava'],['Padre Francisco das Chagas Lima','Religioso da Real Expedição; aldeou os Kaingang'],['José Ferreira dos Santos','Chefe de uma das expedições a Palmas (1839)'],['Pedro de Siqueira Côrtes','Chefe da outra expedição a Palmas (1839)'],['Vitorino Condá','Líder Kaingang aliado aos fazendeiros de Palmas'],['Grover Cleveland','Presidente dos EUA, árbitro da Questão de Palmas'],['Barão do Rio Branco','Defendeu o Brasil na Questão de Palmas']]});

JN_CAP.push({id:'c6',n:'Nasce a Província',t:'De comarca de São Paulo à emancipação de 1853',era:'1811–1889',tp:'hist-emanc',reg:[],
sc:[
{lb:1,q:'Lembra? Em que ano Curitiba foi elevada a vila?',o:['1693','1648','1810','1853'],x:'Paranaguá em 1648; Curitiba em 1693.'},
{y:'1811–1812',m:{z:'wide',l:['rios','nb'],r2:JN_ALL,lg:[null,'5ª Comarca de São Paulo (território aproximado de hoje)'],c:['Paranaguá','Curitiba']},t:'No começo do século XIX, o atual Paraná não tinha governo próprio. Era parte da **Capitania de São Paulo** (depois Província).\nEm **1811**, criou-se a **Comarca de Paranaguá**. Em **1812**, a sede passou para Curitiba e ela virou a **Comarca de Curitiba e Paranaguá**, também chamada de **5ª Comarca de São Paulo**.'},
{q:'Antes de 1853, o território do Paraná era:',o:['A 5ª Comarca da Província de São Paulo','Uma capitania independente','Parte da Província de Santa Catarina','Um território espanhol'],x:'Era a Comarca de Curitiba e Paranaguá, a 5ª Comarca de São Paulo.'},
{t:'Os moradores reclamavam: pagavam impostos a São Paulo e recebiam pouco em troca. Estradas ruins, justiça longe, nenhuma voz nas decisões.\nFoi crescendo a ideia de **emancipação**: separar-se de São Paulo.'},
{y:'1821',m:{z:'litoral',r2:[],r:['litoral'],c:['Paranaguá']},t:'A primeira tentativa forte foi a **Conjura Separatista de 1821**, em **Paranaguá**. Em **15 de julho de 1821**, numa cerimônia na Câmara, o capitão **Floriano Bento Viana** pediu em público um governo separado da província.\nNão deu certo, mas a semente ficou.'},
{q:'Quem liderou a Conjura Separatista de 1821, em Paranaguá?',o:['Floriano Bento Viana','Zacarias de Góes e Vasconcelos','Barão do Serro Azul','Gabriel de Lara'],x:'O capitão Floriano Bento Viana, em 15 de julho de 1821.'},
{y:'1835–1845',m:{z:'wide',r:[],l:['rios','nb'],rt:['tropas'],c:['Viamão (RS) ↓','Sorocaba (SP) →']},t:'Agora olhe para o sul. Entre **1835 e 1845**, o Rio Grande do Sul viveu a **Revolução Farroupilha**, uma revolta contra o Império.\nO Paraná ficava bem no caminho entre o Rio Grande e São Paulo, com as tropas passando. Para o Império, era vital manter essa região **fiel**.'},
{y:'1842',m:{rt:[],z:'pr',r:['curitiba','camposgerais'],c:['Curitiba']},t:'Em **1842**, estourou a **Revolução Liberal** em São Paulo e Minas Gerais. O governo mandou **João da Silva Machado**, o futuro **Barão de Antonina**, pedir apoio em Curitiba.\nA promessa: se a comarca ficasse do lado do Império, ganharia **autonomia**. A comarca **não aderiu** à revolta, e a promessa, garantida pelo futuro **Duque de Caxias**, virou argumento.'},
{q:'Em 1842, a 5ª Comarca não aderiu à Revolução Liberal. O que isso trouxe?',o:['A promessa de autonomia, que fortaleceu o pedido de emancipação','A anexação da comarca ao Rio Grande do Sul','A mudança da capital para Paranaguá','O fim do tropeirismo'],x:'A fidelidade ao Império em 1842 foi trocada pela promessa de emancipação.'},
{y:'29/08/1853',m:{r:JN_ALL,c:[],lg:['A nova Província do Paraná (limites de hoje)']},t:'Mesmo assim, o projeto levou mais de dez anos no Parlamento. Finalmente, a **Lei nº 704, de 29 de agosto de 1853**, assinada por **D. Pedro II**, criou a **Província do Paraná**, desmembrada de São Paulo.\nO mapa inteiro acende: nasce o Paraná.'},
{q:'Qual lei criou a Província do Paraná?',o:['Lei nº 704, de 29 de agosto de 1853','Lei nº 1.853, de 19 de dezembro de 1704','Lei Áurea, de 1888','Carta Régia de 1808'],x:'Lei nº 704, de 29 de agosto de 1853, sancionada por D. Pedro II.'},
{y:'19/12/1853',m:{c:['Curitiba']},t:'Criar no papel é uma coisa; instalar é outra. O primeiro presidente da província foi o baiano **Zacarias de Góes e Vasconcelos**.\nNo Império, presidente de província **não era eleito**: era **nomeado pelo Imperador**. Zacarias, político de confiança do governo, tomou posse em **19 de dezembro de 1853**, e a província foi **instalada** nesse dia. Por isso **19 de dezembro** é a data da emancipação do Paraná.'},
{q:'Por que Zacarias de Góes e Vasconcelos foi o primeiro presidente da província?',o:['Foi nomeado pelo Imperador, como todo presidente de província','Venceu a primeira eleição direta do Paraná','Tinha liderado a Conjura Separatista de 1821','Era o maior produtor de erva-mate da comarca'],x:'Presidentes de província eram escolhidos pelo governo imperial. Zacarias, baiano, depois chefiou o gabinete de ministros do Império.'},
{q:'Qual data é comemorada como a da emancipação política do Paraná?',o:['19 de dezembro de 1853','29 de agosto de 1853','15 de novembro de 1889','29 de março de 1693'],x:'29/08 é a lei; 19/12, a instalação da província, a data comemorada.'},
{y:'1853–1855',m:{c:['Curitiba','Paranaguá','Guarapuava'],r:[],rt:['graciosa'],z:'pr'},t:'Zacarias governou até **1855** e montou a província do zero: instalou a **Assembleia Legislativa Provincial** (1854), defendeu **Curitiba como capital**, mesmo sendo a menor candidata (Paranaguá e Guarapuava também queriam), mandou abrir estradas como a da **Graciosa** e criou o **Arquivo Público**.\nA primeira lei provincial, de **26 de julho de 1854**, confirmou Curitiba como capital.'},
{q:'Quais cidades disputaram com Curitiba o posto de capital da nova província?',o:['Paranaguá e Guarapuava','Londrina e Maringá','Castro e Lapa','Foz do Iguaçu e Cascavel'],x:'Paranaguá e Guarapuava; Zacarias foi decisivo pela escolha de Curitiba.'},
{y:'1853–1889',m:{rt:[],c:[],r:['camposgerais','curitiba','sudeste'],lg:['Gado e erva-mate: a economia de 1853']},t:'A nova província tinha cerca de **62 mil habitantes** e vivia de duas coisas: o **gado** que passava pelos Campos Gerais e a **erva-mate**.\nEm **1889**, com a Proclamação da República, a Província virou o **Estado do Paraná**.'},
{qo:'Coloque em ordem:',o:['Conjura Separatista em Paranaguá (1821)','Revolução Liberal: a comarca fica fiel ao Império (1842)','Lei nº 704 cria a Província (29/08/1853)','Instalação da Província, com Zacarias (19/12/1853)','Proclamação da República: vira Estado (1889)'],x:'1821 → 1842 → 29/08/1853 → 19/12/1853 → 1889.'}
],
res:['Antes de 1853: **Comarca de Curitiba e Paranaguá**, a **5ª Comarca de São Paulo** (criada em 1811; sede em Curitiba desde 1812).','**Conjura Separatista (1821)**, em Paranaguá: **Floriano Bento Viana**.','**Farroupilha (1835–1845)** e **Revolução Liberal (1842)**: a comarca fica fiel ao Império e recebe a promessa de autonomia (João da Silva Machado, Caxias).','**Lei nº 704, de 29/08/1853** (D. Pedro II) cria a Província, desmembrada de **São Paulo**.','Instalação em **19/12/1853**, com **Zacarias de Góes e Vasconcelos** (baiano, **nomeado** pelo Imperador).','Capital: **Curitiba** (disputa com Paranaguá e Guarapuava; lei de 26/07/1854). Cerca de **62 mil** habitantes; economia de **gado e erva-mate**.','**1889**: a Província vira **Estado do Paraná**.'],
tl:[['1811','Criação da Comarca de Paranaguá'],['1812','Sede vai para Curitiba (5ª Comarca de SP)'],['15/07/1821','Conjura Separatista em Paranaguá'],['1835–1845','Revolução Farroupilha'],['1842','Revolução Liberal; a comarca fica fiel ao Império'],['29/08/1853','Lei nº 704 cria a Província do Paraná'],['19/12/1853','Instalação da Província (Zacarias)'],['26/07/1854','Primeira lei provincial confirma Curitiba como capital'],['1889','Província vira Estado do Paraná']],
pers:[['Floriano Bento Viana','Líder da Conjura Separatista de 1821, em Paranaguá'],['João da Silva Machado (Barão de Antonina)','Levou a Curitiba, em 1842, a promessa de autonomia'],['D. Pedro II','Imperador que sancionou a Lei nº 704 (1853)'],['Zacarias de Góes e Vasconcelos','Baiano, primeiro presidente da Província (1853–1855)']]});

JN_CAP.push({id:'c7',n:'O ouro verde',t:'Erva-mate, a Graciosa e a ferrovia da serra',era:'Século XIX',tp:'hist-ciclos',reg:['sudeste'],
sc:[
{lb:1,q:'Lembra? Qual data é comemorada como a emancipação do Paraná?',o:['19 de dezembro','29 de agosto','15 de novembro','7 de setembro'],x:'19 de dezembro de 1853, a instalação da Província.'},
{y:'Século XIX',m:{z:'pr',l:['rios'],r:['curitiba','camposgerais','sudeste','guarapuava','palmas'],lg:['Ervais nativos, na mata de araucária']},t:'Nas matas de araucária crescia, nativa, uma planta que os Guarani já usavam: a **erva-mate**.\nNo século XIX ela virou o **principal produto da economia paranaense**: o nosso “ouro verde”.'},
{m:{z:'leste',r:['curitiba','litoral'],lg:['Engenhos e portos do mate'],c:['Curitiba','Morretes','Antonina','Paranaguá']},t:'Funcionava assim: no interior, os **ervateiros** colhiam, sapecavam e secavam as folhas. Depois, a erva descia para os **engenhos** de beneficiamento em **Curitiba, Morretes, Antonina e Paranaguá**.\nE saía pelo porto para os grandes consumidores: **Argentina, Uruguai e Chile**.'},
{q:'No século XIX, qual era o principal produto de exportação do Paraná?',o:['Erva-mate','Café','Soja','Ouro'],x:'A erva-mate sustentou a economia paranaense no século XIX.'},
{q:'Para onde ia a maior parte da erva-mate exportada?',o:['Argentina, Uruguai e Chile','Estados Unidos e Inglaterra','Portugal e Espanha','Minas Gerais e Rio de Janeiro'],x:'Os países do Prata e o Chile eram os grandes consumidores de mate.'},
{y:'1873',m:{z:'litoral',l:['rios','relevo'],r:[],lg:null,rt:['graciosa'],c:['Curitiba','Antonina']},t:'O problema era a **Serra do Mar**: descer toneladas de erva por trilhas de mula era caro e lento.\nEm **1873** ficou pronta a **Estrada da Graciosa**, entre o planalto e **Antonina**, já boa para carroças.'},
{y:'1880–1885',m:{rt:['graciosa','ferrovia'],c:['Curitiba','Morretes','Paranaguá']},t:'A grande virada foi a **Estrada de Ferro Paranaguá–Curitiba**, construída entre **1880 e 1885** e inaugurada em **2 de fevereiro de 1885**.\nSão cerca de 110 km cruzando a Serra do Mar, com 14 túneis e dezenas de pontes e viadutos, uma obra famosa até hoje. Entre os engenheiros, **João Teixeira Soares**.'},
{q:'A ferrovia Paranaguá–Curitiba foi inaugurada em:',o:['1885','1853','1910','1648'],x:'Obras de 1880 a 1885; inauguração em 2 de fevereiro de 1885.'},
{qm:'Toque na região aonde a ferrovia chega depois de descer a serra, onde fica o porto.',r:'litoral',x:'A ferrovia desce de Curitiba até Paranaguá, no Litoral.'},
{y:'1894',m:{z:'pr',l:['rios'],rt:['ferrovia','ferropg'],c:['Curitiba','Ponta Grossa','Paranaguá']},t:'Os trilhos seguiram para o interior e, em **1894**, chegaram a **Ponta Grossa**.\nA ferrovia barateou o transporte e acelerou a economia do mate e, logo depois, a da **madeira**.'},
{y:'1845–1894',m:{rt:[],c:['Curitiba'],r:['curitiba']},t:'O maior nome do mate foi **Ildefonso Pereira Correia**, o **Barão do Serro Azul**: industrial ervateiro de Curitiba, o maior exportador de erva-mate do Paraná.\nGuarde esse nome: ele terá um final trágico no capítulo 9.'},
{q:'Quem foi o Barão do Serro Azul?',o:['O maior exportador de erva-mate do Paraná','O primeiro presidente da Província','O líder dos bandeirantes no Guairá','O engenheiro da Estrada da Graciosa'],x:'Ildefonso Pereira Correia, industrial do mate em Curitiba.'},
{y:'Início do século XX',m:{r:[],c:[]},t:'A erva-mate reinou até o começo do século XX. Depois perdeu força, principalmente porque a **Argentina** passou a plantar a própria erva e comprou cada vez menos.\nA economia do Paraná ia mudar de novo.'},
{qo:'Coloque em ordem:',o:['Ouro de aluvião em Paranaguá','Caminho de Viamão e os tropeiros','Instalação da Província do Paraná','Estrada da Graciosa','Ferrovia Paranaguá–Curitiba'],x:'Ouro (séc. XVII) → tropas (séc. XVIII) → Província (1853) → Graciosa (1873) → ferrovia (1885).'}
],
res:['**Erva-mate**: principal produto do Paraná no século XIX, nativa da mata de araucária.','Cadeia: ervais no interior → **engenhos** em Curitiba, Morretes, Antonina e Paranaguá → exportação para **Argentina, Uruguai e Chile**.','**Estrada da Graciosa** (1873): planalto → Antonina.','**Ferrovia Paranaguá–Curitiba**: 1880–1885, inaugurada em **2/2/1885**; ~110 km pela Serra do Mar; chega a **Ponta Grossa em 1894**.','**Barão do Serro Azul** (Ildefonso Pereira Correia): maior exportador de mate.','Declínio no início do século XX: a Argentina passa a produzir a própria erva.'],
tl:[['Século XIX','Erva-mate é o principal produto do Paraná'],['1873','Estrada da Graciosa'],['1880–1885','Construção da ferrovia Paranaguá–Curitiba'],['02/02/1885','Inauguração da ferrovia'],['1894','Trilhos chegam a Ponta Grossa']],
pers:[['Barão do Serro Azul (Ildefonso Pereira Correia)','Industrial e maior exportador de erva-mate'],['João Teixeira Soares','Engenheiro da ferrovia Paranaguá–Curitiba']]});

JN_CAP.push({id:'c8',n:'Gente do mundo inteiro',t:'A imigração que formou o Paraná',era:'1829–1951',tp:'hist-ocup',reg:[],
sc:[
{lb:1,q:'Lembra? Em que ano foi inaugurada a ferrovia Paranaguá–Curitiba?',o:['1885','1853','1873','1910'],x:'1873 é a Graciosa; 1885, a ferrovia.'},
{y:'Século XIX',m:{z:'pr',l:['rios'],r:['curitiba'],c:['Curitiba']},t:'Depois da emancipação, a província tinha muita terra e pouca gente. E Curitiba precisava de **alimentos**.\nA solução foi trazer **imigrantes europeus** e instalá-los em **colônias** de pequenos agricultores. Entre 1829 e 1911 surgiram mais de cem núcleos coloniais, com cerca de 100 mil imigrantes.'},
{y:'1829',m:{z:'leste',c:['Rio Negro','Curitiba']},t:'Os primeiros foram **alemães**. Em **1829**, famílias alemãs se fixaram às margens do rio Negro e formaram a colônia de **Rio Negro**, a mais antiga colônia alemã do Paraná, com apoio de João da Silva Machado, o Barão de Antonina.'},
{q:'A mais antiga colônia alemã do Paraná, de 1829, fica em:',o:['Rio Negro','Santa Felicidade','Carambeí','Prudentópolis'],x:'Rio Negro, no sul, na divisa com Santa Catarina.'},
{y:'1847–1852',m:{z:'pr',r:['centro','litoral'],c:['Guaraqueçaba'],lg:['Colônias experimentais']},t:'Houve também experiências curiosas. Em **1847**, o médico **Jean-Maurice Faivre** criou a **Colônia Tereza**, com imigrantes franceses, às margens do rio **Ivaí**.\nEm **1852** surgiu a colônia de **Superagui**, no litoral de Guaraqueçaba, com suíços, alemães e franceses.'},
{y:'1871',m:{r:['curitiba','sudeste'],lg:['Colônias polonesas'],c:['Curitiba','São Mateus do Sul','Mallet','Irati']},t:'A partir de **1871** chegaram os **poloneses**. Formaram colônias ao redor de Curitiba e se espalharam pelo sul do estado: São Mateus do Sul, Mallet, Irati, Cruz Machado.\nO Paraná tem uma das maiores comunidades de origem polonesa do Brasil.'},
{y:'1878',m:{z:'leste',r:['curitiba','camposgerais'],lg:['Italianos'],c:['Curitiba','Palmeira']},t:'Os **italianos** chegaram em peso nos anos 1870. Em **1878** nasceu **Santa Felicidade**, em Curitiba, famosa até hoje pelos restaurantes.\nE em **1890**, em **Palmeira**, anarquistas italianos liderados por **Giovanni Rossi** criaram a **Colônia Cecília**: vida comunitária, sem governo nem propriedade privada. Durou poucos anos.'},
{q:'O que foi a Colônia Cecília, em Palmeira (1890)?',o:['Uma experiência anarquista de imigrantes italianos','A primeira colônia alemã do Paraná','Uma redução jesuítica do Guairá','Uma cooperativa holandesa de leite'],x:'Giovanni Rossi e anarquistas italianos tentaram viver sem Estado e sem propriedade privada.'},
{y:'1895–1896',m:{z:'pr',r:['sudeste'],lg:['Colônias ucranianas'],c:['Prudentópolis','Mallet','União da Vitória']},t:'Nos anos **1890** veio uma grande leva de **ucranianos**, da Galícia. Em **1895–1896**, milhares de famílias foram para **Prudentópolis** e arredores.\nPrudentópolis virou a maior colônia ucraniana do Brasil, a “pequena Ucrânia”, com igrejas de cúpulas e a tradição das **pêssankas**, os ovos pintados.'},
{qm:'Toque na região de **Prudentópolis**, a “pequena Ucrânia”.',r:'sudeste',x:'Prudentópolis fica no Sudeste, no Vale do Iguaçu, perto de Irati.'},
{q:'A imigração ucraniana se concentrou principalmente em:',o:['Prudentópolis','Carambeí','Rio Negro','Assaí'],x:'Prudentópolis e arredores (Mallet, União da Vitória).'},
{y:'1911',m:{z:'cg',r:['camposgerais'],lg:['Colônias holandesas'],c:['Carambeí','Castro','Arapoti']},t:'Em **1911**, os **holandeses** chegaram a **Carambeí**, nos Campos Gerais, numa área aberta pela companhia da ferrovia. Depois vieram **Castrolanda** (em Castro, 1951) e **Arapoti**.\nEles criaram **cooperativas** de leite que fizeram da região uma das maiores bacias leiteiras do país.'},
{q:'Os holandeses no Paraná são associados a:',o:['Carambeí e as cooperativas de leite','Santa Felicidade e os restaurantes','Prudentópolis e as igrejas de cúpulas','Rio Negro, a primeira colônia'],x:'Carambeí (1911), Castrolanda e Arapoti: cooperativas de leite.'},
{y:'Século XX',m:{z:'pr',r:['nortenovo','nortepioneiro'],lg:['Japoneses e alemães no Norte'],c:['Assaí','Rolândia','Londrina']},t:'No século XX, o **Norte** recebeu **japoneses**, como em **Assaí**, nos anos 1930, e **alemães**, como em Rolândia.\nNos Campos Gerais, **menonitas** fundaram **Witmarsum** (1951). E vieram **sírios e libaneses**, muitos como comerciantes. O Paraná virou um mosaico de povos.'},
{qo:'Coloque as chegadas em ordem:',o:['Alemães em Rio Negro (1829)','Poloneses a partir de 1871','Italianos em Santa Felicidade (1878)','Ucranianos em Prudentópolis (1895–1896)','Holandeses em Carambeí (1911)'],x:'1829 → 1871 → 1878 → 1895 → 1911.'},
{m:{r:[],c:[],lg:null},t:'Guarde a lógica: **colônias perto de Curitiba** para abastecer a capital; **eslavos** (poloneses e ucranianos) no sul, na mata de araucária e da erva-mate; **holandeses** nos Campos Gerais; **japoneses** no Norte do café.\nNo próximo capítulo, o Paraná entra em guerra. Duas vezes.'}
],
res:['Política de **colônias** de pequenos agricultores para povoar e abastecer Curitiba; mais de 100 núcleos e cerca de 100 mil imigrantes (1829–1911).','**Alemães**: Rio Negro (**1829**), a colônia mais antiga.','**Colônia Tereza** (1847, Faivre, franceses, rio Ivaí) e **Superagui** (1852).','**Poloneses** desde **1871** (Curitiba, São Mateus do Sul, Mallet, Irati).','**Italianos**: **Santa Felicidade** (1878); **Colônia Cecília** anarquista em Palmeira (1890, Giovanni Rossi).','**Ucranianos**: **Prudentópolis** (1895–1896), a “pequena Ucrânia”.','**Holandeses**: **Carambeí** (1911), Castrolanda (1951), cooperativas de leite. **Japoneses** no Norte (Assaí). **Menonitas** em Witmarsum (1951).'],
tl:[['1829','Colônia alemã de Rio Negro'],['1847','Colônia Tereza, no rio Ivaí'],['1852','Colônia de Superagui'],['1871','Início da imigração polonesa'],['1878','Santa Felicidade (italianos)'],['1890','Colônia Cecília, em Palmeira'],['1895–1896','Ucranianos em Prudentópolis'],['1911','Holandeses em Carambeí'],['1951','Castrolanda e Witmarsum']],
pers:[['Jean-Maurice Faivre','Médico que fundou a Colônia Tereza (1847)'],['Giovanni Rossi','Anarquista italiano da Colônia Cecília (1890)']]});

JN_CAP.push({id:'c9',n:'Tempos de guerra',t:'Revolução Federalista, Contestado e a madeira',era:'1893–1916',tp:'hist-ocup',reg:[],
sc:[
{lb:1,q:'Lembra? Quem foi o maior exportador de erva-mate do Paraná?',o:['O Barão do Serro Azul','Zacarias de Góes e Vasconcelos','Gabriel de Lara','Floriano Bento Viana'],x:'Ildefonso Pereira Correia, o Barão do Serro Azul.'},
{y:'1893',m:{z:'wide',l:['rios','nb'],r:[],c:[]},t:'Com a República (1889), o Brasil viveu anos turbulentos. Em **1893**, no Rio Grande do Sul, começou a **Revolução Federalista**.\nDe um lado, os **federalistas**, chamados de **maragatos**, que queriam mais autonomia para os estados. Do outro, os republicanos fiéis ao presidente **Floriano Peixoto**, os **pica-paus**.'},
{y:'Janeiro de 1894',m:{z:'leste',r:['camposgerais','curitiba','litoral'],lg:['Avanço maragato no Paraná'],c:['Lapa','Curitiba','Paranaguá']},t:'No começo de **1894**, os maragatos, com **Gumercindo Saraiva**, subiram por Santa Catarina e invadiram o Paraná. Paranaguá e Curitiba caíram.\nMas uma cidade resistiu: a **Lapa**, no velho caminho das tropas.'},
{y:'14/01–fev. 1894',m:{r:['camposgerais'],lg:null,c:['Lapa']},t:'O **Cerco da Lapa** começou em **14 de janeiro de 1894**. Os republicanos, comandados pelo general **Antônio Ernesto Gomes Carneiro**, resistiram **26 dias**, com pouca munição e comida.\nGomes Carneiro morreu em combate em **9 de fevereiro**, e a cidade se rendeu. Mas o atraso deu tempo para o governo de Floriano se reorganizar.'},
{q:'Quem comandou a resistência no Cerco da Lapa (1894)?',o:['O general Gomes Carneiro','Gumercindo Saraiva','O Barão do Serro Azul','Floriano Bento Viana'],x:'Gomes Carneiro, morto em combate em 9 de fevereiro de 1894.'},
{q:'Quanto tempo durou o Cerco da Lapa?',o:['26 dias','3 meses','1 semana','2 anos'],x:'De 14 de janeiro a meados de fevereiro de 1894: 26 dias.'},
{y:'20/05/1894',m:{r:['curitiba','litoral'],rt:['ferrovia'],c:['Curitiba','Morretes']},t:'Com os maragatos em Curitiba, o **Barão do Serro Azul** negociou com eles para evitar saques e violência, arrecadando dinheiro entre os comerciantes.\nQuando os republicanos retomaram o Paraná, ele foi acusado de **traição**. Em **20 de maio de 1894**, foi levado de trem e **fuzilado no km 65 da ferrovia**, na Serra do Mar, sem julgamento. Mais de um século depois, foi declarado **herói da pátria**.'},
{q:'O que aconteceu com o Barão do Serro Azul em 1894?',o:['Foi fuzilado na Serra do Mar, acusado de traição','Foi eleito presidente do estado','Fugiu para a Argentina com os maragatos','Morreu defendendo a Lapa'],x:'Fuzilado no km 65 da ferrovia Paranaguá–Curitiba, em 20 de maio de 1894.'},
{y:'1910',m:{z:'sul',l:['rios','nb'],r:['sudeste','palmas'],lg:['Lado paranaense da fronteira'],rt:['sprg'],a:['contestado'],c:['União da Vitória','Porto União (SC)','Três Barras (SC)']},t:'Agora a segunda guerra. Paraná e Santa Catarina brigavam havia décadas por uma região de araucárias e erva-mate ao sul dos rios Negro e Iguaçu: a área do **Contestado** (hachurada).\nEm **1910** ficou pronta a **Estrada de Ferro São Paulo–Rio Grande**, do empresário americano **Percival Farquhar**, cortando a região.'},
{t:'A companhia recebeu uma faixa de terra ao longo dos trilhos e **expulsou** milhares de **posseiros**, caboclos que viviam ali sem título.\nOutra empresa do mesmo grupo, a **Lumber**, montou em **Três Barras** (1911) a maior serraria da América Latina e passou a derrubar a floresta de araucária. Muita gente ficou sem terra e sem trabalho.'},
{y:'22/10/1912',m:{c:['Irani (SC)','União da Vitória']},t:'Nesse clima surgiu um líder religioso, o **monge José Maria**, que reunia seguidores numa vida comunitária.\nEm **22 de outubro de 1912**, a polícia do Paraná atacou o grupo no **Irani**. Morreram o monge José Maria e o comandante paranaense, **coronel João Gualberto**. Começava a **Guerra do Contestado** (1912–1916).'},
{q:'Qual foi a principal causa social da Guerra do Contestado?',o:['A expulsão de posseiros pela ferrovia e pela Lumber','A cobrança de impostos sobre a erva-mate pela Argentina','A invasão dos maragatos vindos do Rio Grande','A geada que destruiu os cafezais'],x:'Posseiros expulsos pela estrada de ferro e pela madeireira, somados ao messianismo e à disputa de limites.'},
{y:'1916',t:'A guerra durou até **1916**, com milhares de mortos. O Exército chegou a usar **aviões** em combate pela primeira vez no Brasil.\nEm **20 de outubro de 1916**, os governadores **Afonso Camargo** (PR) e **Felipe Schmidt** (SC), com mediação do presidente **Venceslau Brás**, assinaram o **acordo de limites**. Dos cerca de 48 mil km² disputados, **Santa Catarina ficou com a maior parte**, uns 28 mil.'},
{q:'O acordo de limites de 1916, que encerrou a disputa do Contestado, foi assinado entre:',o:['Paraná e Santa Catarina','Paraná e São Paulo','Brasil e Argentina','Paraná e Mato Grosso'],x:'Afonso Camargo (PR) e Felipe Schmidt (SC), mediados por Venceslau Brás.'},
{qm:'Toque na região paranaense colada à antiga área do Contestado, onde fica **União da Vitória**.',r:['sudeste','palmas'],x:'União da Vitória, no Sudeste, faz divisa com Porto União (SC); os Campos de Palmas também encostam na área contestada.'},
{y:'1900–1960',m:{z:'pr',a:[],rt:['sprg','ferropg'],r:['sudeste','palmas','curitiba','camposgerais','guarapuava'],lg:['Ciclo da madeira (araucária)'],c:['União da Vitória','Ponta Grossa']},t:'Este capítulo também marca um ciclo econômico: a **madeira**. A araucária foi derrubada em escala industrial do começo do século XX até os anos 1960, junto com as ferrovias que chegavam ao interior.\nHoje resta só uma pequena parte da floresta original.'},
{q:'Qual ciclo econômico acompanhou as ferrovias no início do século XX, no sul do Paraná?',o:['Madeira (araucária)','Ouro de aluvião','Café','Soja'],x:'Serrarias ao longo dos trilhos derrubaram a mata de araucária.'}
],
res:['**Revolução Federalista (1893–1895)**: **maragatos** (federalistas, Gumercindo Saraiva) × **pica-paus** (Floriano Peixoto).','**Cerco da Lapa**: começou em **14/01/1894**, durou **26 dias**; general **Gomes Carneiro** morto em **9/2/1894**.','**Barão do Serro Azul** negociou com os maragatos e foi **fuzilado no km 65** da ferrovia (**20/5/1894**).','**Contestado (1912–1916)**: disputa PR × SC + posseiros expulsos pela **Estrada de Ferro São Paulo–Rio Grande** (Farquhar) e pela **Lumber** (Três Barras).','**Irani (22/10/1912)**: mortes do monge **José Maria** e do coronel **João Gualberto**.','**Acordo de 20/10/1916**: Afonso Camargo × Felipe Schmidt, mediação de **Venceslau Brás**; SC fica com a maior parte.','**Ciclo da madeira** (araucária): início do século XX até os anos 1960.'],
tl:[['1893','Começa a Revolução Federalista'],['14/01/1894','Começa o Cerco da Lapa'],['09/02/1894','Morte de Gomes Carneiro'],['20/05/1894','Fuzilamento do Barão do Serro Azul'],['1910','Estrada de Ferro São Paulo–Rio Grande'],['1911','Lumber em Três Barras'],['22/10/1912','Combate do Irani: começa o Contestado'],['20/10/1916','Acordo de limites PR–SC']],
pers:[['Floriano Peixoto','Presidente da República; os pica-paus eram seus aliados'],['Gumercindo Saraiva','Líder maragato que invadiu o Paraná'],['Gomes Carneiro','General que defendeu a Lapa em 1894'],['Barão do Serro Azul','Fuzilado em 1894; hoje herói da pátria'],['Percival Farquhar','Empresário da ferrovia São Paulo–Rio Grande e da Lumber'],['Monge José Maria','Líder religioso do Contestado, morto no Irani'],['Coronel João Gualberto','Comandante paranaense morto no Irani'],['Afonso Camargo','Governador do Paraná no acordo de 1916'],['Felipe Schmidt','Governador de Santa Catarina no acordo de 1916'],['Venceslau Brás','Presidente que mediou o acordo de 1916']]});

JN_CAP.push({id:'c10',n:'O Norte do café',t:'Terra roxa, cidades planejadas e a geada negra',era:'1860–1975',tp:'hist-ciclos',reg:['nortepioneiro','nortenovo','noroeste'],
sc:[
{lb:1,q:'Lembra? Em que ano começou a Guerra do Contestado?',o:['1912','1894','1853','1932'],x:'Com o combate do Irani, em 22 de outubro de 1912.'},
{y:'1860–1920',m:{z:'norte',l:['rios','nb'],r:['nortepioneiro'],rt:['paulistas_norte','mineiros_norte'],c:['Jacarezinho','Tomazina','Santo Antônio da Platina','Cambará']},t:'Enquanto o sul vivia de mate, gado e madeira, o **Norte** era mata fechada sobre **terra roxa**.\nA partir da segunda metade do século XIX, **mineiros e paulistas** cruzaram o Paranapanema e ocuparam o **Norte Pioneiro** (Norte Velho): Tomazina, Jacarezinho, Santo Antônio da Platina, Cambará. Trouxeram o **café**, já a riqueza de São Paulo.'},
{q:'De onde vieram os primeiros ocupantes do Norte Pioneiro?',o:['De Minas Gerais e São Paulo','Do Rio Grande do Sul e Santa Catarina','Da Europa, direto para Curitiba','Do Paraguai e da Argentina'],x:'Mineiros e paulistas, com o café vindo de São Paulo.'},
{y:'1925',m:{rt:[],r:['nortepioneiro','nortenovo'],c:[]},t:'Nos anos 1920 começou a grande onda. Em **1925** foi fundada a **Companhia de Terras Norte do Paraná (CTNP)**, com capital **inglês**: a principal acionista era a Paraná Plantations, de Londres.\nEla comprou uma área enorme e fez algo diferente: dividiu tudo em **lotes pequenos e médios**, vendidos a prazo, com estradas e uma ferrovia.'},
{y:'1929',m:{c:['Londrina']},t:'Em **21 de agosto de 1929**, a primeira expedição da companhia chegou ao lugar onde nasceria **Londrina**, a “pequena Londres”, em homenagem aos ingleses.\nO município foi criado em **1934**.'},
{q:'A Companhia de Terras Norte do Paraná, que fundou Londrina, tinha capital:',o:['Inglês','Norte-americano','Japonês','Alemão'],x:'Paraná Plantations Ltd., de Londres; daí o nome Londrina.'},
{y:'1930–1950',m:{r:['nortenovo','noroeste'],rt:['cafe'],c:['Londrina','Apucarana','Maringá','Cianorte','Umuarama']},t:'O projeto era planejado: cidades maiores a cada cerca de 100 km, como **Londrina, Maringá, Cianorte e Umuarama**, e núcleos menores entre elas. A ferrovia avançava junto, levando o café para São Paulo e o porto de Santos.\nEm **1944** a companhia foi comprada por brasileiros e depois virou a **Companhia Melhoramentos Norte do Paraná**.'},
{y:'1947',m:{c:['Maringá']},t:'**Maringá** nasceu em **1947**, também planejada, com ruas largas e muito verde.\nO Norte Novo e o Noroeste se encheram de gente de todo o Brasil e de imigrantes, como os japoneses.'},
{qm:'Toque no **Norte Novo**, a região de Londrina e Maringá.',r:'nortenovo',x:'O Norte Novo fica no centro-norte, entre o Norte Pioneiro (leste) e o Noroeste (oeste).'},
{q:'Qual destas cidades foi planejada pela companhia colonizadora do Norte e fundada em 1947?',o:['Maringá','Curitiba','Ponta Grossa','Guarapuava'],x:'Maringá (1947). Londrina é de 1929.'},
{y:'Anos 1960',m:{rt:[],r:['nortepioneiro','nortenovo','noroeste'],c:[],lg:['O Paraná do café']},t:'O resultado impressiona: nos anos **1960**, o Paraná se tornou o **maior produtor de café do Brasil**.\nO café fez do Norte a região mais dinâmica do estado e puxou o peso da economia para lá.'},
{y:'1948–1951',m:{c:['Porecatu']},t:'Nem tudo foi pacífico. Em **Porecatu**, entre **1948 e 1951**, posseiros enfrentaram grileiros e fazendeiros numa luta armada pela terra, a **Guerra de Porecatu**, reprimida pela polícia.'},
{y:'18/07/1975',m:{c:[],lg:['Cafezais destruídos pela geada']},t:'Em **18 de julho de 1975**, uma massa de ar polar trouxe a **geada negra**. Numa só noite, os cafezais do Paraná foram praticamente destruídos.\nMuitos fazendeiros trocaram o café por **soja e trigo**, com máquinas que empregam pouca gente. Nos anos seguintes, milhões de pessoas deixaram o campo: o **êxodo rural**.'},
{q:'Qual acontecimento de 1975 derrubou o ciclo do café no Paraná?',o:['A geada negra','A Guerra de Porecatu','A construção de Itaipu','A crise de 1929'],x:'A geada negra de 18 de julho de 1975.'},
{q:'Depois da geada de 1975, o Norte trocou o café principalmente por:',o:['Soja e trigo mecanizados','Erva-mate','Criação de mulas','Mineração de ouro'],x:'A mecanização da soja e do trigo acelerou o êxodo rural.'},
{qo:'Coloque em ordem:',o:['Mineiros e paulistas no Norte Pioneiro (séc. XIX)','Fundação da Companhia de Terras Norte do Paraná (1925)','Chegada da expedição a Londrina (1929)','Fundação de Maringá (1947)','Geada negra (1975)'],x:'Norte Pioneiro → CTNP (1925) → Londrina (1929) → Maringá (1947) → geada (1975).'}
],
res:['**Norte Pioneiro** (Norte Velho): ocupado por **mineiros e paulistas** desde o século XIX (Jacarezinho, Tomazina, Santo Antônio da Platina, Cambará).','**CTNP (1925)**, capital **inglês** (Paraná Plantations): lotes pequenos, estradas e ferrovia; depois **Companhia Melhoramentos Norte do Paraná**.','**Londrina**: expedição em **21/8/1929**, município em **1934**. **Maringá**: **1947**. Cidades-polo a cada ~100 km (Cianorte, Umuarama).','Anos **1960**: Paraná, **maior produtor de café** do Brasil.','**Guerra de Porecatu** (1948–1951): conflito de posseiros.','**Geada negra (18/7/1975)**: fim do ciclo do café → soja e trigo mecanizados → **êxodo rural**.'],
tl:[['Séc. XIX','Mineiros e paulistas no Norte Pioneiro'],['1925','Fundação da Companhia de Terras Norte do Paraná'],['21/08/1929','Expedição chega ao local de Londrina'],['1934','Criação do município de Londrina'],['1947','Fundação de Maringá'],['1948–1951','Guerra de Porecatu'],['Anos 1960','Paraná, maior produtor de café do Brasil'],['18/07/1975','Geada negra']],
pers:[['Companhia de Terras Norte do Paraná','Colonizadora de capital inglês (1925) que fundou Londrina e Maringá']]});

JN_CAP.push({id:'c11',n:'A última fronteira',t:'Oeste e Sudoeste: obrages, colonos e Itaipu',era:'1882–1984',tp:'hist-ocup',reg:['oeste','sudoeste'],
sc:[
{lb:1,q:'Lembra? Quando foi a geada negra que destruiu os cafezais?',o:['1975','1929','1957','1916'],x:'18 de julho de 1975.'},
{y:'Fim do século XIX',m:{z:'oeste',l:['rios','nb'],r:['oeste'],c:['Foz do Iguaçu','Guaíra']},t:'No fim do século XIX, o **Oeste** quase não tinha presença do governo brasileiro. Quem mandava ali eram as **obrages**: empresas de capital **argentino** ou inglês que extraíam **erva-mate e madeira** com trabalhadores **paraguaios**, os mensus.\nTudo descia pelo rio Paraná rumo à Argentina.'},
{q:'O que eram as obrages do oeste paranaense?',o:['Empresas estrangeiras que exploravam erva-mate e madeira','Reduções jesuíticas espanholas','Colônias de imigrantes holandeses','Fortes do Exército brasileiro'],x:'Empresas de capital argentino ou inglês, com mão de obra paraguaia.'},
{y:'1882–1889',m:{r:['oeste','sudoeste'],c:['Foz do Iguaçu','Chopinzinho','Guarapuava'],z:'pr'},t:'Para marcar presença na fronteira, o governo criou **colônias militares**: a do **Chopim**, instalada em **1882**, na região de Chopinzinho, e a de **Foz do Iguaçu**, em **1889**, com uma expedição saída de Guarapuava.\nFoz do Iguaçu nasceu assim: como posto militar na fronteira.'},
{y:'1943',m:{a:['iguacu'],r:[],c:['Laranjeiras do Sul','Foz do Iguaçu'],z:'wide'},t:'Na **Marcha para o Oeste** do presidente **Getúlio Vargas**, em **1943**, o governo federal tirou do Paraná e de Santa Catarina uma grande faixa e criou o **Território Federal do Iguaçu** (área tracejada), com capital em **Laranjeiras do Sul**.\nDurou pouco: a Constituição de **1946** o extinguiu e as terras voltaram aos estados.'},
{q:'O Território Federal do Iguaçu existiu entre:',o:['1943 e 1946','1853 e 1889','1912 e 1916','1975 e 1985'],x:'Criado no Estado Novo (1943) e extinto pela Constituição de 1946.'},
{y:'1943',m:{a:[],z:'oeste',r:['sudoeste'],c:['Francisco Beltrão','Pato Branco']},t:'Também em **1943**, Vargas criou a **CANGO**, a Colônia Agrícola Nacional General Osório, no **Sudoeste**, para dar terras a colonos. A sede da colônia virou **Francisco Beltrão**.'},
{y:'1940–1960',m:{r:['sudoeste','oeste'],rt:['sulistas_sudoeste','sulistas_oeste'],c:['Francisco Beltrão','Pato Branco','Cascavel','Toledo']},t:'Então veio a grande migração: **gaúchos e catarinenses**, muitos descendentes de italianos e alemães, subiram para o **Sudoeste** e o **Oeste** atrás de terra fértil e barata.\nNo Oeste, colonizadoras particulares venderam os lotes; a mais famosa, a **MARIPÁ**, começou a colonizar **Toledo** em **1946**. **Cascavel** cresceu como encruzilhada de estradas.'},
{q:'O Oeste e o Sudoeste foram colonizados principalmente por migrantes vindos de:',o:['Rio Grande do Sul e Santa Catarina','São Paulo e Minas Gerais','Nordeste','Japão e Alemanha'],x:'A frente sulista: gaúchos e catarinenses. O Norte, ao contrário, recebeu paulistas e mineiros.'},
{y:'Outubro de 1957',m:{rt:[],r:['sudoeste'],c:['Francisco Beltrão','Pato Branco','Santo Antônio do Sudoeste']},t:'No Sudoeste, companhias de terras, como a **CITLA**, passaram a cobrar dos colonos por terras que eles já ocupavam, com jagunços e violência.\nEm **outubro de 1957**, os colonos se revoltaram, tomaram cidades como **Francisco Beltrão** e **Pato Branco** e expulsaram as companhias: a **Revolta dos Posseiros**. Em **1962**, o governo federal criou o **GETSOP** para regularizar os títulos das terras.'},
{qm:'Toque no **Sudoeste**, onde aconteceu a Revolta dos Posseiros.',r:'sudoeste',x:'Francisco Beltrão, Pato Branco e Santo Antônio do Sudoeste ficam no Sudoeste.'},
{q:'O que foi o GETSOP, criado em 1962?',o:['Um órgão federal para regularizar as terras do Sudoeste','A companhia que colonizou Londrina','A usina construída em Foz do Iguaçu','Uma colônia militar da fronteira'],x:'O Grupo Executivo para as Terras do Sudoeste do Paraná titulou dezenas de milhares de lotes.'},
{y:'1973–1984',m:{z:'oeste',r:['oeste'],l:['rios','nb'],c:['Itaipu','Foz do Iguaçu','Sete Quedas (submersa)','Guaíra','Cataratas do Iguaçu']},t:'Para fechar, uma obra gigante no rio Paraná. Em **26 de abril de 1973**, Brasil e Paraguai assinaram o **Tratado de Itaipu**.\nAs obras começaram em 1974. Em **1982** o lago se formou e cobriu para sempre o **Salto de Sete Quedas**, em Guaíra. Em **5 de maio de 1984**, a usina começou a gerar energia.'},
{q:'Qual cachoeira famosa foi coberta pelo lago de Itaipu em 1982?',o:['Salto de Sete Quedas','Cataratas do Iguaçu','Salto Santiago','Salto São João'],x:'Sete Quedas, em Guaíra. As Cataratas do Iguaçu ficam em outro rio, o Iguaçu.'},
{qo:'Coloque em ordem:',o:['Colônia Militar de Foz do Iguaçu (1889)','Território Federal do Iguaçu e CANGO (1943)','MARIPÁ começa a colonizar Toledo (1946)','Revolta dos Posseiros (1957)','Itaipu começa a gerar energia (1984)'],x:'1889 → 1943 → 1946 → 1957 → 1984.'},
{m:{z:'pr',r:JN_ALL,c:[],lg:['O Paraná ocupado de ponta a ponta'],l:['rios']},t:'Com isso, o mapa está completo: litoral e Curitiba pelo ouro, Campos Gerais pelo gado, Guarapuava e Palmas pelos campos, o sul pela erva e pela madeira, o Norte pelo café, o Oeste e o Sudoeste pelos colonos do Sul.\nFalta só uma coisa: juntar tudo para a prova.'}
],
res:['**Obrages**: empresas argentinas ou inglesas de erva-mate e madeira no Oeste, com trabalhadores paraguaios (mensus).','Colônias militares: **Chopim (1882)** e **Foz do Iguaçu (1889)**.','**Território Federal do Iguaçu (1943–1946)**, capital **Laranjeiras do Sul**; Marcha para o Oeste de **Vargas**.','**CANGO (1943)** no Sudoeste → Francisco Beltrão. **MARIPÁ** coloniza **Toledo (1946)**.','Migrantes **gaúchos e catarinenses** no Oeste e Sudoeste (o Norte recebeu paulistas e mineiros).','**Revolta dos Posseiros (out. 1957)**: Francisco Beltrão, Pato Branco; **GETSOP (1962)** regulariza as terras.','**Itaipu**: tratado em **26/4/1973**; lago em **1982** cobre **Sete Quedas**; energia desde **5/5/1984**.'],
tl:[['1882','Colônia Militar do Chopim'],['1889','Colônia Militar de Foz do Iguaçu'],['1943','Território Federal do Iguaçu e CANGO'],['1946','MARIPÁ começa a colonizar Toledo; fim do Território do Iguaçu'],['Out. 1957','Revolta dos Posseiros'],['1962','Criação do GETSOP'],['26/04/1973','Tratado de Itaipu'],['1982','Lago de Itaipu cobre Sete Quedas'],['05/05/1984','Itaipu começa a gerar energia']],
pers:[['Getúlio Vargas','Presidente da Marcha para o Oeste, do Território do Iguaçu e da CANGO']]});

JN_CAP.push({id:'c12',n:'A prova final',t:'Tudo em ordem, tudo no mapa, no estilo da banca',era:'Revisão geral',tp:'hist-ocup',reg:JN_ALL,
sc:[
{y:'Revisão',m:{z:'pr',l:['rios'],r:[]},t:'Última etapa. Vamos amarrar tudo com o que mais derruba candidato: a **ordem dos fatos**, o **lugar** de cada fato e as **pegadinhas** de banca.\nSe errar, leia a explicação com calma: é aqui que o conteúdo gruda.'},
{qo:'Os ciclos econômicos do Paraná, em ordem:',tp:'hist-ciclos',o:['Ouro de aluvião (séc. XVII)','Tropeirismo e gado (séc. XVIII)','Erva-mate (séc. XIX)','Madeira de araucária (início do séc. XX)','Café (meados do séc. XX)'],x:'Ouro → tropeirismo → erva-mate → madeira → café (e depois soja).'},
{qo:'A ocupação do território, em ordem:',o:['Paranaguá vira vila (1648)','Curitiba vira vila (1693)','Real Expedição a Guarapuava (1810)','Ocupação dos Campos de Palmas (1839–1840)','Fundação de Londrina (1929)'],x:'1648 → 1693 → 1810 → 1839 → 1929.'},
{qm:'Toque na região da **primeira vila** do Paraná.',r:'litoral',x:'Paranaguá, 1648, no Litoral.'},
{qm:'Toque na região dos **pousos dos tropeiros**.',r:'camposgerais',x:'Campos Gerais: Castro, Ponta Grossa, Lapa, Palmeira.'},
{qm:'Toque na região colonizada pela **Companhia de Terras Norte do Paraná**, onde ficam Londrina e Maringá.',r:'nortenovo',x:'Norte Novo.'},
{qm:'Toque na região das **obrages** e da **Colônia Militar de Foz do Iguaçu**.',r:'oeste',x:'Oeste, na fronteira com o Paraguai e a Argentina.'},
{q:'Sobre a emancipação política do Paraná, assinale a alternativa **correta**.',tp:'hist-emanc',o:['A Lei nº 704/1853 criou a província, instalada em 19 de dezembro de 1853.','A emancipação ocorreu em 1889, com a Proclamação da República.','O primeiro presidente da província foi eleito pela população de Curitiba.','A província foi desmembrada de Santa Catarina.'],x:'Lei nº 704 (29/08/1853); instalação em 19/12/1853; presidente nomeado; desmembrada de São Paulo.'},
{q:'Sobre o tropeirismo, assinale a alternativa **incorreta**.',tp:'hist-ciclos',o:['As tropas levavam os animais de Sorocaba até Viamão, rumo ao sul.','O Caminho de Viamão atravessava os Campos Gerais.','Pousos e invernadas deram origem a cidades como Castro e Lapa.','Os animais abasteciam a região das minas de ouro.'],x:'O sentido era o contrário: do Rio Grande do Sul (Viamão) para a feira de Sorocaba (SP).'},
{q:'Sobre a ocupação do Norte do Paraná, é **correto** afirmar:',o:['A Companhia de Terras Norte do Paraná, de capital inglês, vendeu lotes pequenos e planejou cidades como Londrina.','O Norte foi ocupado principalmente por gaúchos e catarinenses nos anos 1940.','A erva-mate foi o produto que motivou a ocupação do Norte Novo.','Londrina foi fundada por jesuítas espanhóis no século XVII.'],x:'Norte = paulistas, mineiros e a CTNP (inglesa), com o café. Gaúchos e catarinenses foram para o Oeste e o Sudoeste.'},
{q:'Sobre os povos indígenas do Paraná, assinale a **correta**.',o:['Os Kaingang, do grupo Jê, ocupavam os campos de Guarapuava e Palmas.','Os Xetá foram os primeiros indígenas contatados, ainda no século XVI.','Os Carijós eram um povo Jê do planalto.','Os sambaquis são ruínas das reduções jesuíticas.'],x:'Kaingang = Jê, campos do planalto. Xetá: contatados no século XX. Carijós: guarani do litoral. Sambaquis: montes de conchas.'},
{q:'Sobre a Guerra do Contestado (1912–1916), assinale a **correta**.',o:['Envolveu a expulsão de posseiros pela ferrovia São Paulo–Rio Grande e a disputa de limites entre PR e SC.','Foi uma guerra entre Brasil e Argentina pela região de Palmas.','Terminou com Santa Catarina anexada ao Paraná.','Começou com o Cerco da Lapa, em 1894.'],x:'Palmas × Argentina é a Questão de Palmas (1895). A Lapa é da Revolução Federalista. O acordo de 1916 deu a maior parte da área a SC.'},
{q:'Sobre a erva-mate no século XIX, assinale a **correta**.',tp:'hist-ciclos',o:['Era beneficiada em engenhos de Curitiba e do litoral e exportada para os países do Prata e o Chile.','Era plantada em grandes fazendas do Norte Novo, na terra roxa.','Foi introduzida no Paraná pelos imigrantes holandeses.','Perdeu importância por causa da geada negra de 1975.'],x:'Erva nativa das matas de araucária; engenhos em Curitiba, Morretes, Antonina e Paranaguá; exportada a Argentina, Uruguai e Chile.'},
{q:'Relacione: “a terra fica com quem de fato a ocupa” é o princípio que embasou:',o:['O Tratado de Madri (1750)','O Tratado de Tordesilhas (1494)','A Lei nº 704 (1853)','O acordo de limites de 1916'],x:'Uti possidetis, no Tratado de Madri.'},
{q:'Qual alternativa relaciona **corretamente** a região e sua principal frente de ocupação?',o:['Oeste e Sudoeste: gaúchos e catarinenses no século XX','Norte Novo: tropeiros vindos de Viamão','Campos Gerais: colonizadora inglesa CTNP','Litoral: bandeirantes caçando reduções'],x:'Litoral: ouro; Campos Gerais: gado e tropeiros; Norte: paulistas, mineiros e CTNP; Oeste/Sudoeste: sulistas.'},
{y:'Fim da Jornada',m:{r:JN_ALL,lg:['Você conhece o Paraná de ponta a ponta']},t:'Você chegou ao fim da Jornada. Agora você sabe **onde** cada coisa aconteceu, **quando** e **por quê**.\nPara manter vivo: jogue a **Arena de História** (os jogos puxam exatamente esses fatos), refaça capítulos para ganhar 3 estrelas e consulte o **Atlas** e a **Linha do tempo** sempre que bater dúvida.'}
],
res:['Ciclos: **ouro → tropeirismo → erva-mate → madeira → café** (depois soja).','Ocupação: **Paranaguá 1648 → Curitiba 1693 → Guarapuava 1810 → Palmas 1839–40 → Norte (Londrina 1929, Maringá 1947) → Oeste e Sudoeste (anos 1940–60)**.','Emancipação: **Lei nº 704 (29/8/1853)**, instalação **19/12/1853**, **Zacarias** (nomeado), desmembrada de **São Paulo**.','Frentes do século XX: **Norte** = paulistas, mineiros e CTNP; **Oeste/Sudoeste** = gaúchos e catarinenses.','Conflitos: **Lapa (1894)**, **Contestado (1912–1916)**, **Porecatu (1948–1951)**, **Posseiros (1957)**.'],
tl:[],
pers:[]});
